package dz.gov.mesrs.sii.commons.data.model.fve.offreformation;

// Generated 15 juil. 2014 16:41:51 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Niveau generated by hbm2java
 */
@Entity
@Table(name = "niveau", schema = "lmd", uniqueConstraints = {
		@UniqueConstraint(columnNames = "libelle_long_lt"),
		@UniqueConstraint(columnNames = "code") })
public class Niveau implements java.io.Serializable {

	/**
	 * serialVersionUID 
	 * @author rlaib  on : 16 juil. 2014  09:48:11
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private Cycle cycle;
	private String code;
	private String libelleLongLt;
	private String libelleLongAr;
	private String libelleCourtLt;
	private String libelleCourtAr;
	private int rang;
	private Set<Periode> periodes = new HashSet<Periode>(0);

	public Niveau() {
	}

	public Niveau(int id, Cycle cycle, String code, String libelleLongLt,
			int rang) {
		this.id = id;
		this.cycle = cycle;
		this.code = code;
		this.libelleLongLt = libelleLongLt;
		this.rang = rang;
	}

	public Niveau(int id, Cycle cycle, String code, String libelleLongLt,
			String libelleLongAr, String libelleCourtLt, String libelleCourtAr,
			int rang, Set<Periode> periodes) {
		this.id = id;
		this.cycle = cycle;
		this.code = code;
		this.libelleLongLt = libelleLongLt;
		this.libelleLongAr = libelleLongAr;
		this.libelleCourtLt = libelleCourtLt;
		this.libelleCourtAr = libelleCourtAr;
		this.rang = rang;
		this.periodes = periodes;
	}

	@SequenceGenerator(name="niveau_id_seq_gen", sequenceName="lmd.niveau_id_seq")
	@Id @GeneratedValue(generator="niveau_id_seq_gen")
	@Column(name = "id")
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_cycle", nullable = false)
	public Cycle getCycle() {
		return this.cycle;
	}

	public void setCycle(Cycle cycle) {
		this.cycle = cycle;
	}

	@Column(name = "code", unique = true, nullable = false, length = 2)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "libelle_long_lt", unique = true, nullable = false, length = 150)
	public String getLibelleLongLt() {
		return this.libelleLongLt;
	}

	public void setLibelleLongLt(String libelleLongLt) {
		this.libelleLongLt = libelleLongLt;
	}

	@Column(name = "libelle_long_ar", length = 150)
	public String getLibelleLongAr() {
		return this.libelleLongAr;
	}

	public void setLibelleLongAr(String libelleLongAr) {
		this.libelleLongAr = libelleLongAr;
	}

	@Column(name = "libelle_court_lt", length = 50)
	public String getLibelleCourtLt() {
		return this.libelleCourtLt;
	}

	public void setLibelleCourtLt(String libelleCourtLt) {
		this.libelleCourtLt = libelleCourtLt;
	}

	@Column(name = "libelle_court_ar", length = 50)
	public String getLibelleCourtAr() {
		return this.libelleCourtAr;
	}

	public void setLibelleCourtAr(String libelleCourtAr) {
		this.libelleCourtAr = libelleCourtAr;
	}

	@Column(name = "rang", nullable = false)
	public int getRang() {
		return this.rang;
	}

	public void setRang(int rang) {
		this.rang = rang;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "niveau")
	public Set<Periode> getPeriodes() {
		return this.periodes;
	}

	public void setPeriodes(Set<Periode> periodes) {
		this.periodes = periodes;
	}

}
