package dz.gov.mesrs.sii.commons.data.model.fve.offreformation;

// Generated 7 janv. 2014 14:52:44 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * OffreFormationDomaineCompetence generated by hbm2java
 */
@Entity
@Table(name = "offre_formation_domaine_competence", schema = "lmd")
public class OffreFormationDomaineCompetence implements java.io.Serializable {

	/**
	 * serialVersionUID 
	 * @author  Rafik LAIB  on : 22 avr. 2014  11:15:47
	 */
	private static final long serialVersionUID = -2805115139027573510L;
	private int id;
	private OffreFormation offreFormation;
	private String refCodeDomaineCompetence;

	public OffreFormationDomaineCompetence() {
	}

	public OffreFormationDomaineCompetence(int id,
			OffreFormation offreFormation, String refCodeDomaineCompetence) {
		this.id = id;
		this.offreFormation = offreFormation;
		this.refCodeDomaineCompetence = refCodeDomaineCompetence;
	}

	
	@SequenceGenerator(name="offre_formation_domaine_competence_id_seq_gen", sequenceName="lmd.offre_formation_domaine_competence_id_seq")
	@Id @GeneratedValue(generator="offre_formation_domaine_competence_id_seq_gen")
	@Column(name = "id")
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_offre_formation", nullable = false)
	public OffreFormation getOffreFormation() {
		return this.offreFormation;
	}

	public void setOffreFormation(OffreFormation offreFormation) {
		this.offreFormation = offreFormation;
	}

	@Column(name = "ref_code_domaine_competence", nullable = false)
	public String getRefCodeDomaineCompetence() {
		return this.refCodeDomaineCompetence;
	}

	public void setRefCodeDomaineCompetence(String refCodeDomaineCompetence) {
		this.refCodeDomaineCompetence = refCodeDomaineCompetence;
	}

}
