package dz.gov.mesrs.sii.commons.data.model.fve.offreformation;

// Generated 7 janv. 2014 14:52:44 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import dz.gov.mesrs.sii.commons.data.model.bpm.SituationEntite;
import dz.gov.mesrs.sii.commons.data.model.referentiel.Nomenclature;
import dz.gov.mesrs.sii.commons.data.model.referentiel.RefDomaineLMD;
import dz.gov.mesrs.sii.commons.data.model.referentiel.RefEtablissement;
import dz.gov.mesrs.sii.commons.data.model.referentiel.RefFiliereLmd;
import dz.gov.mesrs.sii.commons.data.model.referentiel.RefSpecialiteLmd;
import dz.gov.mesrs.sii.commons.data.model.referentiel.RefStructure;


/**
 * OffreFormation generated by hbm2java
 */
@Entity
@Table(name = "offre_formation", schema = "lmd")

public class OffreFormation implements java.io.Serializable {

	/**
	 * serialVersionUID 
	 * @author  Rafik LAIB  on : 18 avr. 2014  14:45:40
	 */
	private static final long serialVersionUID = -6185093698645946527L;
	private int id;
	private String code;
	private String codeInt;
	private String numeroArrete;
	private Boolean estValidee = false;
	private Boolean estHabilitee= false;
	private Boolean estArchivee= false;
	private Boolean estAmendee= false;
	private Boolean estSupprimee= false;
	private Boolean estPubliee= false;
	private Boolean estOuverte= false;
	private Date dateArrete;
	private Date dateCreation;
	private Date dateModification;
	private Date dateDebutHabilitation;
	private Date dateFinHabilitation;
	private OffreFormation offreFormationOriginale;
	private Set<ParcoursType> parcoursTypes = new HashSet<ParcoursType>(0);
	private Set<OffreFormationDetailContent> offreFormationDetailContents = new HashSet<OffreFormationDetailContent>(0);
	private Set<OffreFormationEquipe> offreFormationEquipes = new HashSet<OffreFormationEquipe>(0);
	private Set<OffreFormationContrat> offreFormationContrats = new HashSet<OffreFormationContrat>(0);
	private SituationEntite situationEntite;
	private Boolean estCompletee= false;
	private Cycle cycle;
	private RefEtablissement  refEtablissement;
	private RefStructure  refStructure;
	private String libelleLongFr;
	private String libelleCourtFr;
	private String abrevFr;
	private String libelleLongAr;
	private String libelleCourtAr;
	private String abrevAr;
	private String description;
	private RefDomaineLMD refDomaineLMD;
	private RefFiliereLmd refFiliereLmd;
	private RefSpecialiteLmd refSpecialiteLmd;
	private Nomenclature typeFormation;
	private Nomenclature vocationFormation;
	
	public OffreFormation() {
	}
	
	@SequenceGenerator(name="offre_formation_id_seq_gen", sequenceName="lmd.offre_formation_id_seq")
	@Id @GeneratedValue(generator="offre_formation_id_seq_gen")
	@Column(name = "id")
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	/**
	 * [OffreFormation.code] Getter 
	 * @author  Rafik LAIB on : 18 avr. 2014  13:53:28
	 * @return the code
	 */
	@Column(name = "code", nullable = false,length=50)
	public String getCode() {
		return code;
	}

	/**
	 * [OffreFormation.code] Setter 
	 * @author  Rafik LAIB on : 18 avr. 2014  13:53:28
	 * @param code the code to set
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * [OffreFormation.codeInt] Getter 
	 * @author  Rafik LAIB on : 18 avr. 2014  13:53:28
	 * @return the codeInt
	 */
	@Column(name = "code_int", length=50)
	public String getCodeInt() {
		return codeInt;
	}

	/**
	 * [OffreFormation.codeInt] Setter 
	 * @author  Rafik LAIB on : 18 avr. 2014  13:53:28
	 * @param codeInt the codeInt to set
	 */
	public void setCodeInt(String codeInt) {
		this.codeInt = codeInt;
	}

	/**
	 * [OffreFormation.numeroArrete] Getter 
	 * @author  Rafik LAIB on : 18 avr. 2014  13:53:28
	 * @return the numeroArrete
	 */
	@Column(name = "numero_arrete",length=50)
	public String getNumeroArrete() {
		return numeroArrete;
	}

	/**
	 * [OffreFormation.numeroArrete] Setter 
	 * @author  Rafik LAIB on : 18 avr. 2014  13:53:28
	 * @param numeroArrete the numeroArrete to set
	 */
	public void setNumeroArrete(String numeroArrete) {
		this.numeroArrete = numeroArrete;
	}

	/**
	 * [OffreFormation.estValidee] Getter 
	 * @author  Rafik LAIB on : 18 avr. 2014  13:53:28
	 * @return the estValidee
	 */
	@Column(name = "est_validee")
	public Boolean getEstValidee() {
		
		 return (this.estValidee == null) ?  false  : estValidee;
	}

	/**
	 * [OffreFormation.estValidee] Setter 
	 * @author  Rafik LAIB on : 18 avr. 2014  13:53:28
	 * @param estValidee the estValidee to set
	 */
	public void setEstValidee(Boolean estValidee) {

		this.estValidee = estValidee;
	}

	/**
	 * [OffreFormation.estHabilitee] Getter 
	 * @author  Rafik LAIB on : 18 avr. 2014  13:53:28
	 * @return the estHabilitee
	 */
	@Column(name = "est_habilitee")
	public Boolean getEstHabilitee() {
		
		 return (this.estHabilitee == null) ?  false  : estHabilitee;
	}

	/**
	 * [OffreFormation.estHabilitee] Setter 
	 * @author  Rafik LAIB on : 18 avr. 2014  13:53:28
	 * @param estHabilitee the estHabilitee to set
	 */
	public void setEstHabilitee(Boolean estHabilitee) {
		this.estHabilitee = estHabilitee;
	}

	/**
	 * [OffreFormation.estArchivee] Getter 
	 * @author  Rafik LAIB on : 18 avr. 2014  13:53:28
	 * @return the estArchivee
	 */
	@Column(name = "est_archivee")
	public Boolean getEstArchivee() {
		
		 return (this.estArchivee == null) ?  false  : estArchivee;

	}

	/**
	 * [OffreFormation.estArchivee] Setter 
	 * @author  Rafik LAIB on : 18 avr. 2014  13:53:28
	 * @param estArchivee the estArchivee to set
	 */
	public void setEstArchivee(Boolean estArchivee) {
		this.estArchivee = estArchivee;
	}

	/**
	 * [OffreFormation.estAmendee] Getter 
	 * @author  Rafik LAIB on : 18 avr. 2014  13:53:28
	 * @return the estAmendee
	 */
	@Column(name = "est_amendee")
	public Boolean getEstAmendee() {
		
		 return (this.estAmendee == null) ?  false  : estAmendee;

	}

	/**
	 * [OffreFormation.estAmendee] Setter 
	 * @author  Rafik LAIB on : 18 avr. 2014  13:53:28
	 * @param estAmendee the estAmendee to set
	 */
	public void setEstAmendee(Boolean estAmendee) {
		this.estAmendee = estAmendee;
	}

	/**
	 * [OffreFormation.estSupprimee] Getter 
	 * @author  Rafik LAIB on : 18 avr. 2014  13:53:28
	 * @return the estSupprimee
	 */
	@Column(name = "est_supprimee")
	public Boolean getEstSupprimee() {
		
		 return (this.estSupprimee == null) ?  false  : estSupprimee;
	}

	/**
	 * [OffreFormation.estSupprimee] Setter 
	 * @author  Rafik LAIB on : 18 avr. 2014  13:53:28
	 * @param estSupprimee the estSupprimee to set
	 */
	public void setEstSupprimee(Boolean estSupprimee) {
		this.estSupprimee = estSupprimee;
	}

	/**
	 * [OffreFormation.estPubliee] Getter 
	 * @author  Rafik LAIB on : 18 avr. 2014  13:53:28
	 * @return the estPubliee
	 */
	@Column(name = "est_publiee")
	public Boolean getEstPubliee() {
		
		 return (this.estPubliee == null) ?  false  : estPubliee;

	}

	/**
	 * [OffreFormation.estPubliee] Setter 
	 * @author  Rafik LAIB on : 18 avr. 2014  13:53:28
	 * @param estPubliee the estPubliee to set
	 */
	public void setEstPubliee(Boolean estPubliee) {
		this.estPubliee = estPubliee;
	}

	/**
	 * [OffreFormation.estOuverte] Getter 
	 * @author  Rafik LAIB on : 18 avr. 2014  13:53:28
	 * @return the estOuverte
	 */
	@Column(name = "est_ouverte")
	public Boolean getEstOuverte() {
		
		 return (this.estOuverte == null) ?  false  : estOuverte;

	}

	/**
	 * [OffreFormation.estOuverte] Setter 
	 * @author  Rafik LAIB on : 18 avr. 2014  13:53:28
	 * @param estOuverte the estOuverte to set
	 */
	public void setEstOuverte(Boolean estOuverte) {
		this.estOuverte = estOuverte;
	}

	/**
	 * [OffreFormation.dateArrete] Getter 
	 * @author  Rafik LAIB on : 18 avr. 2014  13:53:28
	 * @return the dateArrete
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_arrete", length = 29)
	public Date getDateArrete() {
		return dateArrete;
	}

	/**
	 * [OffreFormation.dateArrete] Setter 
	 * @author  Rafik LAIB on : 18 avr. 2014  13:53:28
	 * @param dateArrete the dateArrete to set
	 */
	public void setDateArrete(Date dateArrete) {
		this.dateArrete = dateArrete;
	}

	/**
	 * [OffreFormation.dateCreation] Getter 
	 * @author  Rafik LAIB on : 18 avr. 2014  13:53:28
	 * @return the dateCreation
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_creation", length = 29)
	public Date getDateCreation() {
		return dateCreation;
	}

	/**
	 * [OffreFormation.dateCreation] Setter 
	 * @author  Rafik LAIB on : 18 avr. 2014  13:53:28
	 * @param dateCreation the dateCreation to set
	 */
	public void setDateCreation(Date dateCreation) {
		this.dateCreation = dateCreation;
	}

	/**
	 * [OffreFormation.dateModification] Getter 
	 * @author  Rafik LAIB on : 18 avr. 2014  13:53:28
	 * @return the dateModification
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_modification", length = 29)
	public Date getDateModification() {
		return dateModification;
	}

	/**
	 * [OffreFormation.dateModification] Setter 
	 * @author  Rafik LAIB on : 18 avr. 2014  13:53:28
	 * @param dateModification the dateModification to set
	 */
	public void setDateModification(Date dateModification) {
		this.dateModification = dateModification;
	}

	/**
	 * [OffreFormation.dateDebutHabilitation] Getter 
	 * @author  Rafik LAIB on : 18 avr. 2014  13:53:28
	 * @return the dateDebutHabilitation
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_debut_habilitation", length = 29)
	public Date getDateDebutHabilitation() {
		return dateDebutHabilitation;
	}

	/**
	 * [OffreFormation.dateDebutHabilitation] Setter 
	 * @author  Rafik LAIB on : 18 avr. 2014  13:53:28
	 * @param dateDebutHabilitation the dateDebutHabilitation to set
	 */
	public void setDateDebutHabilitation(Date dateDebutHabilitation) {
		this.dateDebutHabilitation = dateDebutHabilitation;
	}

	/**
	 * [OffreFormation.dateFinHabilitation] Getter 
	 * @author  Rafik LAIB on : 18 avr. 2014  13:53:28
	 * @return the dateFinHabilitation
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_fin_habilitation", length = 29)
	public Date getDateFinHabilitation() {
		return dateFinHabilitation;
	}

	/**
	 * [OffreFormation.dateFinHabilitation] Setter 
	 * @author  Rafik LAIB on : 18 avr. 2014  13:53:28
	 * @param dateFinHabilitation the dateFinHabilitation to set
	 */
	public void setDateFinHabilitation(Date dateFinHabilitation) {
		this.dateFinHabilitation = dateFinHabilitation;
	}

	
	/**
	 * [OffreFormation.offreFormationOriginale] Getter 
	 * @author  Rafik LAIB on : 18 avr. 2014  14:56:08
	 * @return the offreFormationOriginale
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_offre_originale",nullable=true)
	public OffreFormation getOffreFormationOriginale() {
		return offreFormationOriginale;
	}

	
	/**
	 * [OffreFormation.offreFormationOriginale] Setter 
	 * @author  Rafik LAIB on : 18 avr. 2014  14:56:08
	 * @param offreFormationOriginale the offreFormationOriginale to set
	 */
	public void setOffreFormationOriginale(OffreFormation offreFormationOriginale) {
		this.offreFormationOriginale = offreFormationOriginale;
	}

	/**
	 * [OffreFormation.parcoursTypes] Getter 
	 * @author  Rafik LAIB on : 18 avr. 2014  14:52:30
	 * @return the parcoursTypes
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "offreFormation", targetEntity= ParcoursType.class)
	public Set<ParcoursType> getParcoursTypes() {
		return parcoursTypes;
	}
	

	/**
	 * [OffreFormation.parcoursTypes] Setter 
	 * @author  Rafik LAIB on : 18 avr. 2014  14:52:30
	 * @param parcoursTypes the parcoursTypes to set
	 */
	public void setParcoursTypes(Set<ParcoursType> parcoursTypes) {
		this.parcoursTypes = parcoursTypes;
	}
	

	/**
	 * [OffreFormation.offreFormationDetailContents] Getter 
	 * @author  Rafik LAIB on : 18 avr. 2014  14:52:30
	 * @return the offreFormationDetailContents
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "offreFormation", targetEntity= OffreFormationDetailContent.class)
	public Set<OffreFormationDetailContent> getOffreFormationDetailContents() {
		return offreFormationDetailContents;
	}
	

	/**
	 * [OffreFormation.offreFormationDetailContents] Setter 
	 * @author  Rafik LAIB on : 18 avr. 2014  14:52:30
	 * @param offreFormationDetailContents the offreFormationDetailContents to set
	 */
	public void setOffreFormationDetailContents(
			Set<OffreFormationDetailContent> offreFormationDetailContents) {
		this.offreFormationDetailContents = offreFormationDetailContents;
	}
	

	/**
	 * [OffreFormation.offreFormationEquipes] Getter 
	 * @author  Rafik LAIB on : 18 avr. 2014  14:52:30
	 * @return the offreFormationEquipes
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "offreFormation", targetEntity= OffreFormationEquipe.class)
	public Set<OffreFormationEquipe> getOffreFormationEquipes() {
		return this.offreFormationEquipes;
	}
	

	/**
	 * [OffreFormation.offreFormationEquipes] Setter 
	 * @author  Rafik LAIB on : 18 avr. 2014  14:52:30
	 * @param offreFormationEquipes the offreFormationEquipes to set
	 */
	public void setOffreFormationEquipes(
			Set<OffreFormationEquipe> offreFormationEquipes) {
		this.offreFormationEquipes = offreFormationEquipes;
	}
	

	/**
	 * [OffreFormation.offreFormationContrats] Getter 
	 * @author  Rafik LAIB on : 18 avr. 2014  14:52:30
	 * @return the offreFormationContrats
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "offreFormation", targetEntity= OffreFormationContrat.class)
	public Set<OffreFormationContrat> getOffreFormationContrats() {
		return offreFormationContrats;
	}
	

	/**
	 * [OffreFormation.offreFormationContrats] Setter 
	 * @author  Rafik LAIB on : 18 avr. 2014  14:52:30
	 * @param offreFormationContrats the offreFormationContrats to set
	 */
	public void setOffreFormationContrats(
			Set<OffreFormationContrat> offreFormationContrats) {
		this.offreFormationContrats = offreFormationContrats;
	}

	
	
	/**
	 * [OffreFormation.estCompletee] Getter 
	 * @author rlaib on : 4 mai 2014  11:29:48
	 * @return the estCompletee
	 */
	@Column(name = "est_completee")
	public Boolean getEstCompletee() {
		return estCompletee;
	}

	/**
	 * [OffreFormation.estCompletee] Setter 
	 * @author rlaib on : 4 mai 2014  11:29:48
	 * @param estCompletee the estCompletee to set
	 */
	public void setEstCompletee(Boolean estCompletee) {
		this.estCompletee = estCompletee;
	}

	/**
	 * [OffreFormation.situationEntite] Getter 
	 * @author  Rafik LAIB on : 2 mai 2014  17:42:54
	 * @return the situationEntite
	 */
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_situation", nullable = false)
	public SituationEntite getSituationEntite() {
		return situationEntite;
	}

	/**
	 * [OffreFormation.situationEntite] Setter 
	 * @author  Rafik LAIB on : 2 mai 2014  17:42:54
	 * @param situationEntite the situationEntite to set
	 */
	public void setSituationEntite(SituationEntite situationEntite) {
		this.situationEntite = situationEntite;
	}

	/**
	 * [dz.gov.mesrs.sii.fve.business.model.bo.offreformation.OffreFormation.hashCode] Method 
	 * overridden By :  @author  Rafik LAIB  
	 * On : 19 avr. 2014  15:56:29
	 * @return
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((code == null) ? 0 : code.hashCode());
		return result;
	}
	

	/**
	 * [dz.gov.mesrs.sii.fve.business.model.bo.offreformation.OffreFormation.equals] Method 
	 * overridden By :  @author  Rafik LAIB  
	 * On : 19 avr. 2014  15:56:29
	 * @param obj
	 * @return
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		OffreFormation other = (OffreFormation) obj;
		if (code == null) {
			if (other.code != null)
				return false;
		} else if (!code.equals(other.code))
			return false;
		return true;
	}

	/**
	 * [OffreFormation.cycle] Getter 
	 * @author rlaib on : 9 sept. 2014  13:56:59
	 * @return the cycle
	 */
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_cycle")
	public Cycle getCycle() {
		return cycle;
	}

	/**
	 * [OffreFormation.cycle] Setter 
	 * @author rlaib on : 9 sept. 2014  13:56:59
	 * @param cycle the cycle to set
	 */
	public void setCycle(Cycle cycle) {
		this.cycle = cycle;
	}

	/**
	 * [OffreFormation.refEtablissement] Getter 
	 * @author rlaib on : 11 oct. 2014  17:54:24
	 * @return the refEtablissement
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_etablissement")
	public RefEtablissement getRefEtablissement() {
		return refEtablissement;
	}

	/**
	 * [OffreFormation.refEtablissement] Setter 
	 * @author rlaib on : 11 oct. 2014  17:54:24
	 * @param refEtablissement the refEtablissement to set
	 */
	public void setRefEtablissement(RefEtablissement refEtablissement) {
		this.refEtablissement = refEtablissement;
	}

	/**
	 * [OffreFormation.refStructure] Getter 
	 * @author rlaib on : 11 oct. 2014  14:19:43
	 * @return the refStructure
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_structure")
	public RefStructure getRefStructure() {
		return refStructure;
	}

	/**
	 * [OffreFormation.refStructure] Setter 
	 * @author rlaib on : 11 oct. 2014  14:19:43
	 * @param refStructure the refStructure to set
	 */
	public void setRefStructure(RefStructure refStructure) {
		this.refStructure = refStructure;
	}

	/**
	 * [OffreFormation.libelleLongFr] Getter 
	 * @author rlaib on : 11 oct. 2014  14:56:24
	 * @return the libelleLongFr
	 */
	@Column(name = "libelle_long_fr")
	public String getLibelleLongFr() {
		return libelleLongFr;
	}

	/**
	 * [OffreFormation.libelleLongFr] Setter 
	 * @author rlaib on : 11 oct. 2014  14:56:24
	 * @param libelleLongFr the libelleLongFr to set
	 */
	public void setLibelleLongFr(String libelleLongFr) {
		this.libelleLongFr = libelleLongFr;
	}

	/**
	 * [OffreFormation.libelleCourtFr] Getter 
	 * @author rlaib on : 11 oct. 2014  14:56:24
	 * @return the libelleCourtFr
	 */
	@Column(name = "libelle_court_fr")
	public String getLibelleCourtFr() {
		return libelleCourtFr;
	}

	/**
	 * [OffreFormation.libelleCourtFr] Setter 
	 * @author rlaib on : 11 oct. 2014  14:56:24
	 * @param libelleCourtFr the libelleCourtFr to set
	 */
	public void setLibelleCourtFr(String libelleCourtFr) {
		this.libelleCourtFr = libelleCourtFr;
	}

	/**
	 * [OffreFormation.abrevFr] Getter 
	 * @author rlaib on : 11 oct. 2014  14:56:24
	 * @return the abrevFr
	 */
	@Column(name = "abrev_fr")
	public String getAbrevFr() {
		return abrevFr;
	}

	/**
	 * [OffreFormation.abrevFr] Setter 
	 * @author rlaib on : 11 oct. 2014  14:56:24
	 * @param abrevFr the abrevFr to set
	 */
	public void setAbrevFr(String abrevFr) {
		this.abrevFr = abrevFr;
	}

	/**
	 * [OffreFormation.libelleLongAr] Getter 
	 * @author rlaib on : 11 oct. 2014  14:56:24
	 * @return the libelleLongAr
	 */
	@Column(name = "libelle_long_ar")
	public String getLibelleLongAr() {
		return libelleLongAr;
	}

	/**
	 * [OffreFormation.libelleLongAr] Setter 
	 * @author rlaib on : 11 oct. 2014  14:56:24
	 * @param libelleLongAr the libelleLongAr to set
	 */
	public void setLibelleLongAr(String libelleLongAr) {
		this.libelleLongAr = libelleLongAr;
	}

	/**
	 * [OffreFormation.libelleCourtAr] Getter 
	 * @author rlaib on : 11 oct. 2014  14:56:24
	 * @return the libelleCourtAr
	 */
	@Column(name = "libelle_court_ar")
	public String getLibelleCourtAr() {
		return libelleCourtAr;
	}

	/**
	 * [OffreFormation.libelleCourtAr] Setter 
	 * @author rlaib on : 11 oct. 2014  14:56:24
	 * @param libelleCourtAr the libelleCourtAr to set
	 */
	public void setLibelleCourtAr(String libelleCourtAr) {
		this.libelleCourtAr = libelleCourtAr;
	}

	/**
	 * [OffreFormation.abrevAr] Getter 
	 * @author rlaib on : 11 oct. 2014  14:56:24
	 * @return the abrevAr
	 */
	@Column(name = "abrev_ar")
	public String getAbrevAr() {
		return abrevAr;
	}

	/**
	 * [OffreFormation.abrevAr] Setter 
	 * @author rlaib on : 11 oct. 2014  14:56:24
	 * @param abrevAr the abrevAr to set
	 */
	public void setAbrevAr(String abrevAr) {
		this.abrevAr = abrevAr;
	}

	/**
	 * [OffreFormation.description] Getter 
	 * @author rlaib on : 11 oct. 2014  14:58:46
	 * @return the description
	 */
	@Column(name = "description")
	public String getDescription() {
		return description;
	}

	/**
	 * [OffreFormation.description] Setter 
	 * @author rlaib on : 11 oct. 2014  14:58:46
	 * @param description the description to set
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * [OffreFormation.refDomaineLMD] Getter 
	 * @author rlaib on : 17 nov. 2014  10:51:24
	 * @return the refDomaineLMD
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_domaine", nullable = false)
	public RefDomaineLMD getRefDomaineLMD() {
		return refDomaineLMD;
	}

	/**
	 * [OffreFormation.refDomaineLMD] Setter 
	 * @author rlaib on : 17 nov. 2014  10:51:24
	 * @param refDomaineLMD the refDomaineLMD to set
	 */
	public void setRefDomaineLMD(RefDomaineLMD refDomaineLMD) {
		this.refDomaineLMD = refDomaineLMD;
	}

	/**
	 * [OffreFormation.refFiliereLmd] Getter 
	 * @author rlaib on : 17 nov. 2014  10:51:24
	 * @return the refFiliereLmd
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_filiere", nullable = false)
	public RefFiliereLmd getRefFiliereLmd() {
		return refFiliereLmd;
	}

	/**
	 * [OffreFormation.refFiliereLmd] Setter 
	 * @author rlaib on : 17 nov. 2014  10:51:24
	 * @param refFiliereLmd the refFiliereLmd to set
	 */
	public void setRefFiliereLmd(RefFiliereLmd refFiliereLmd) {
		this.refFiliereLmd = refFiliereLmd;
	}

	/**
	 * [OffreFormation.refSpecialiteLmd] Getter 
	 * @author rlaib on : 17 nov. 2014  10:51:24
	 * @return the refSpecialiteLmd
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_specialite", nullable = false)
	public RefSpecialiteLmd getRefSpecialiteLmd() {
		return refSpecialiteLmd;
	}

	/**
	 * [OffreFormation.refSpecialiteLmd] Setter 
	 * @author rlaib on : 17 nov. 2014  10:51:24
	 * @param refSpecialiteLmd the refSpecialiteLmd to set
	 */
	public void setRefSpecialiteLmd(RefSpecialiteLmd refSpecialiteLmd) {
		this.refSpecialiteLmd = refSpecialiteLmd;
	}

	/**
	 * [dz.gov.mesrs.sii.fve.business.model.bo.offreformation.OffreFormation.toString] Method 
	 * @author rlaib  on : 17 nov. 2014  18:14:05
	 * @return
	 */
	@Override
	public String toString() {
		return "OffreFormation [code=" + code + ", libelleLongFr="
				+ libelleLongFr + ", refDomaineLMD=" + refDomaineLMD + "]";
	}

	/**
	 * [OffreFormation.typeFormation] Getter 
	 * @author rlaib on : 2 déc. 2014  09:54:20
	 * @return the typeFormation
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_type_formation", nullable = false)
	public Nomenclature getTypeFormation() {
		return typeFormation;
	}

	/**
	 * [OffreFormation.typeFormation] Setter 
	 * @author rlaib on : 2 déc. 2014  09:54:20
	 * @param typeFormation the typeFormation to set
	 */
	public void setTypeFormation(Nomenclature typeFormation) {
		this.typeFormation = typeFormation;
	}

	/**
	 * [OffreFormation.vocationFormation] Getter 
	 * @author rlaib on : 2 déc. 2014  09:54:20
	 * @return the vocationFormation
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_vocation", nullable = false)
	public Nomenclature getVocationFormation() {
		return vocationFormation;
	}

	/**
	 * [OffreFormation.vocationFormation] Setter 
	 * @author rlaib on : 2 déc. 2014  09:54:20
	 * @param vocationFormation the vocationFormation to set
	 */
	public void setVocationFormation(Nomenclature vocationFormation) {
		this.vocationFormation = vocationFormation;
	}
	
	
	
}
