package dz.gov.mesrs.sii.commons.data.model.fve.offreformation;

// Generated 15 juil. 2014 16:41:51 by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import dz.gov.mesrs.sii.commons.data.model.referentiel.Nomenclature;

/**
 * Periode generated by hbm2java
 */
@Entity
@Table(name = "periode", schema = "lmd", uniqueConstraints = {
		@UniqueConstraint(columnNames = "libelle_long_lt"),
		@UniqueConstraint(columnNames = "code") })
public class Periode implements java.io.Serializable {

	/**
	 * serialVersionUID 
	 * @author rlaib  on : 16 juil. 2014  09:48:03
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private Niveau niveau;
	private String code;
	private String libelleLongLt;
	private String libelleLongAr;
	private String libelleCourtLt;
	private String libelleCourtAr;
	private int rang;
	private int credit;
	private String refCodePeriodicite;
	private String refCodePeriode;
	private Nomenclature ncPeriode;


	public Periode() {
	}

	public Periode(int id, Niveau niveau, String code, String libelleLongLt,
			int rang, int credit) {
		this.id = id;
		this.niveau = niveau;
		this.code = code;
		this.libelleLongLt = libelleLongLt;
		this.rang = rang;
		this.credit = credit;
	}

	public Periode(int id, Niveau niveau, String code, String libelleLongLt,
			String libelleLongAr, String libelleCourtLt, String libelleCourtAr,
			int rang, int credit) {
		this.id = id;
		this.niveau = niveau;
		this.code = code;
		this.libelleLongLt = libelleLongLt;
		this.libelleLongAr = libelleLongAr;
		this.libelleCourtLt = libelleCourtLt;
		this.libelleCourtAr = libelleCourtAr;
		this.rang = rang;
		this.credit = credit;
	}

	@SequenceGenerator(name="periode_id_seq_gen", sequenceName="lmd.periode_id_seq")
	@Id @GeneratedValue(generator="periode_id_seq_gen")
	@Column(name = "id")
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_niveau", nullable = false)
	public Niveau getNiveau() {
		return this.niveau;
	}

	public void setNiveau(Niveau niveau) {
		this.niveau = niveau;
	}

	@Column(name = "code", unique = true, nullable = false, length = 5)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "libelle_long_lt", unique = true, nullable = false, length = 150)
	public String getLibelleLongLt() {
		return this.libelleLongLt;
	}

	public void setLibelleLongLt(String libelleLongLt) {
		this.libelleLongLt = libelleLongLt;
	}

	@Column(name = "libelle_long_ar", length = 150)
	public String getLibelleLongAr() {
		return this.libelleLongAr;
	}

	public void setLibelleLongAr(String libelleLongAr) {
		this.libelleLongAr = libelleLongAr;
	}

	@Column(name = "libelle_court_lt", length = 50)
	public String getLibelleCourtLt() {
		return this.libelleCourtLt;
	}

	public void setLibelleCourtLt(String libelleCourtLt) {
		this.libelleCourtLt = libelleCourtLt;
	}

	@Column(name = "libelle_court_ar", length = 50)
	public String getLibelleCourtAr() {
		return this.libelleCourtAr;
	}

	public void setLibelleCourtAr(String libelleCourtAr) {
		this.libelleCourtAr = libelleCourtAr;
	}

	@Column(name = "rang", nullable = false)
	public int getRang() {
		return this.rang;
	}

	public void setRang(int rang) {
		this.rang = rang;
	}

	@Column(name = "credit", nullable = false)
	public int getCredit() {
		return this.credit;
	}

	public void setCredit(int credit) {
		this.credit = credit;
	}

	/**
	 * [Periode.refCodePeriodicite] Getter 
	 * @author rlaib on : 22 juil. 2014  12:42:31
	 * @return the refCodePeriodicite
	 */
	@Column(name = "ref_code_periodicite", nullable = false)
	public String getRefCodePeriodicite() {
		return refCodePeriodicite;
	}

	/**
	 * [Periode.refCodePeriodicite] Setter 
	 * @author rlaib on : 22 juil. 2014  12:42:31
	 * @param refCodePeriodicite the refCodePeriodicite to set
	 */
	public void setRefCodePeriodicite(String refCodePeriodicite) {
		this.refCodePeriodicite = refCodePeriodicite;
	}

	/**
	 * [Periode.refCodePeriode] Getter 
	 * @author rlaib on : 2 nov. 2014  09:43:51
	 * @return the refCodePeriode
	 */
	 @Column(name = "ref_code_periode", nullable = false)
	public String getRefCodePeriode() {
		return refCodePeriode;
	}

	/**
	 * [Periode.refCodePeriode] Setter 
	 * @author rlaib on : 2 nov. 2014  09:43:51
	 * @param refCodePeriode the refCodePeriode to set
	 */
	public void setRefCodePeriode(String refCodePeriode) {
		this.refCodePeriode = refCodePeriode;
	}

	
	/**
	 * [Periode.ncPeriode] Getter 
	 * @author rlaib on : 7 déc. 2014  13:23:49
	 * @return the ncPeriode
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_nc_periode", nullable = false)
	public Nomenclature getNcPeriode() {
		return ncPeriode;
	}

	/**
	 * [Periode.ncPeriode] Setter 
	 * @author rlaib on : 7 déc. 2014  13:23:49
	 * @param ncPeriode the ncPeriode to set
	 */
	public void setNcPeriode(Nomenclature ncPeriode) {
		this.ncPeriode = ncPeriode;
	}
	
	

}
