package dz.gov.mesrs.sii.commons.data.model.fve.scolarite;

// Generated 22 oct. 2014 12:07:17 by Hibernate Tools 3.6.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import dz.gov.mesrs.sii.commons.data.model.fve.offreformation.AnneeAcademique;
import dz.gov.mesrs.sii.commons.data.model.fve.offreformation.Niveau;
import dz.gov.mesrs.sii.commons.data.model.fve.offreformation.OuvertureOffreFormation;
import dz.gov.mesrs.sii.commons.data.model.referentiel.Nomenclature;

/**
 * Emploi generated by hbm2java
 */
@Entity
@Table(name = "emploi", schema = "fve_scolarite")
public class Emploi implements java.io.Serializable {

	/**
	 * serialVersionUID 
	 * @author BELDI Jamel  on : 22 oct. 2014  12:11:27
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private Nomenclature nomenclatureByIdNcPeriodicite;
	private Nomenclature nomenclatureByIdNcPeriode;
	private OuvertureOffreFormation ouvertureOffreFormation;
	private AnneeAcademique anneeAcademique;
	private Niveau niveau;
	private boolean estVerrouille;
	private Date dateVerrouillage;
	private Set<SeanceEmploi> seanceEmplois = new HashSet<SeanceEmploi>(0);

	public Emploi() {
	}

	public Emploi(int id, Nomenclature nomenclatureByIdNcPeriodicite,
			Nomenclature nomenclatureByIdNcPeriode,
			OuvertureOffreFormation ouvertureOffreFormation,
			AnneeAcademique anneeAcademique, boolean estVerrouille) {
		this.id = id;
		this.nomenclatureByIdNcPeriodicite = nomenclatureByIdNcPeriodicite;
		this.nomenclatureByIdNcPeriode = nomenclatureByIdNcPeriode;
		this.ouvertureOffreFormation = ouvertureOffreFormation;
		this.anneeAcademique = anneeAcademique;
		this.estVerrouille = estVerrouille;
	}

	public Emploi(int id, Nomenclature nomenclatureByIdNcPeriodicite,
			Nomenclature nomenclatureByIdNcPeriode,
			OuvertureOffreFormation ouvertureOffreFormation,
			AnneeAcademique anneeAcademique, Niveau niveau,
			boolean estVerrouille, Date dateVerrouillage,
			Set<SeanceEmploi> seanceEmplois) {
		this.id = id;
		this.nomenclatureByIdNcPeriodicite = nomenclatureByIdNcPeriodicite;
		this.nomenclatureByIdNcPeriode = nomenclatureByIdNcPeriode;
		this.ouvertureOffreFormation = ouvertureOffreFormation;
		this.anneeAcademique = anneeAcademique;
		this.niveau = niveau;
		this.estVerrouille = estVerrouille;
		this.dateVerrouillage = dateVerrouillage;
		this.seanceEmplois = seanceEmplois;
	}

	@Id
	@SequenceGenerator(name="emploi_id_seq_gen", sequenceName="fve_scolarite.emploi_id_seq")
	@GeneratedValue(generator="emploi_id_seq_gen")
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_nc_periodicite", nullable = false)
	public Nomenclature getNomenclatureByIdNcPeriodicite() {
		return this.nomenclatureByIdNcPeriodicite;
	}

	public void setNomenclatureByIdNcPeriodicite(
			Nomenclature nomenclatureByIdNcPeriodicite) {
		this.nomenclatureByIdNcPeriodicite = nomenclatureByIdNcPeriodicite;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_nc_periode", nullable = false)
	public Nomenclature getNomenclatureByIdNcPeriode() {
		return this.nomenclatureByIdNcPeriode;
	}

	public void setNomenclatureByIdNcPeriode(
			Nomenclature nomenclatureByIdNcPeriode) {
		this.nomenclatureByIdNcPeriode = nomenclatureByIdNcPeriode;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_ouverture_of", nullable = false)
	public OuvertureOffreFormation getOuvertureOffreFormation() {
		return this.ouvertureOffreFormation;
	}

	public void setOuvertureOffreFormation(
			OuvertureOffreFormation ouvertureOffreFormation) {
		this.ouvertureOffreFormation = ouvertureOffreFormation;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_annee_academique", nullable = false)
	public AnneeAcademique getAnneeAcademique() {
		return this.anneeAcademique;
	}

	public void setAnneeAcademique(AnneeAcademique anneeAcademique) {
		this.anneeAcademique = anneeAcademique;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_niveau")
	public Niveau getNiveau() {
		return this.niveau;
	}

	public void setNiveau(Niveau niveau) {
		this.niveau = niveau;
	}

	@Column(name = "est_verrouille", nullable = false)
	public boolean isEstVerrouille() {
		return this.estVerrouille;
	}

	public void setEstVerrouille(boolean estVerrouille) {
		this.estVerrouille = estVerrouille;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_verrouillage", length = 35)
	public Date getDateVerrouillage() {
		return this.dateVerrouillage;
	}

	public void setDateVerrouillage(Date dateVerrouillage) {
		this.dateVerrouillage = dateVerrouillage;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "emploi")
	public Set<SeanceEmploi> getSeanceEmplois() {
		return this.seanceEmplois;
	}

	public void setSeanceEmplois(Set<SeanceEmploi> seanceEmplois) {
		this.seanceEmplois = seanceEmplois;
	}

	
	
}
