package dz.gov.mesrs.sii.commons.data.model.fve.scolarite;

// Generated 22 oct. 2014 12:07:17 by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import dz.gov.mesrs.sii.commons.data.model.fve.cursus.AssociationGroupePedagogique;

/**
 * SeanceEmploi generated by hbm2java
 */
@Entity
@Table(name = "seance_emploi", schema = "fve_scolarite")
public class SeanceEmploi implements java.io.Serializable {

	/**
	 * serialVersionUID 
	 * @author BELDI Jamel  on : 22 oct. 2014  12:11:50
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private AssociationGroupePedagogique associationGroupePedagogique;
	private Emploi emploi;
	private AffectationLieuStructure affectationLieuStructure;

	public SeanceEmploi() {
	}

	public SeanceEmploi(int id,
			AssociationGroupePedagogique associationGroupePedagogique,
			Emploi emploi, AffectationLieuStructure affectationLieuStructure) {
		this.id = id;
		this.associationGroupePedagogique = associationGroupePedagogique;
		this.emploi = emploi;
		this.affectationLieuStructure = affectationLieuStructure;
	}

	@Id
	@SequenceGenerator(name="seance_emploi_id_seq_gen", sequenceName="fve_scolarite.seance_emploi_id_seq")
	@GeneratedValue(generator="seance_emploi_id_seq_gen")
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_association_groupe_pedagogique", nullable = false)
	public AssociationGroupePedagogique getAssociationGroupePedagogique() {
		return this.associationGroupePedagogique;
	}

	public void setAssociationGroupePedagogique(
			AssociationGroupePedagogique associationGroupePedagogique) {
		this.associationGroupePedagogique = associationGroupePedagogique;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_emploi", nullable = false)
	public Emploi getEmploi() {
		return this.emploi;
	}

	public void setEmploi(Emploi emploi) {
		this.emploi = emploi;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_affectation_lieu", nullable = false)
	public AffectationLieuStructure getAffectationLieuStructure() {
		return this.affectationLieuStructure;
	}

	public void setAffectationLieuStructure(
			AffectationLieuStructure affectationLieuStructure) {
		this.affectationLieuStructure = affectationLieuStructure;
	}

}
