package dz.gov.mesrs.sii.fve.business.model.dto.offreformation;

// Generated 7 janv. 2014 14:52:53 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * OffreFormationDto generated by hbm2java
 */
public class OffreFormationDto implements java.io.Serializable {

	/**
	 * serialVersionUID 
	 * @author  Rafik LAIB  on : 26 avr. 2014  19:32:05
	 */
	private static final long serialVersionUID = -5467261719100730696L;
	private int id;
	private String code;
	private String codeInt;
	private String numeroArrete;
	private Boolean estValidee;
	private Boolean estHabilitee;
	private Boolean estArchivee;
	private Boolean estAmendee;
	private Boolean estSupprimee;
	private Boolean estPubliee;
	private Boolean estOuverte;
	private String refCodeDomaine;
	private String refCodeFiliere;
	private String refCodeSpecialite;
	private String refCodeCycle;
	private Date dateArrete;
	private Date dateCreation;
	private Date dateModification;
	private Date dateDebutHabilitation;
	private Date dateFinHabilitation;
	private Boolean estCompletee;
	private String libelleLongFr;
	private String libelleCourtFr;
	private String abrevFr;
	private String libelleLongAr;
	private String libelleCourtAr;
	private String abrevAr;
	private String description;
	private Integer nombreEtudiantImporte;
	private Integer nombreEtudiantInscrit;

	// Cycle
	private Integer idCycle;
	private String codeCycle;
	private String libelleCycle;
	
	// Type de formation
	private Integer idTypeFormation;
	private String codeTypeFormation;
	private String libelleTypeFormation;
	
	// Vocation de formation
	private Integer idVocation;
	private String codeVocation;
	private String libelleVocation;
	
	// Domaine - Filiere  - Specialite
	private Integer idDomaine;
	private String codeDomaine;
	private String libelleDomaine;
	private Integer idFiliere;
	private String codeFiliere;
	private String libelleFiliere;
	private Integer idSpecialite;
	private String codeSpecialite;
	private String libelleSpecialite;
	
	// Etablissement
	private Integer idEtablissement;
	private String codeEtablissement;
	private String libelleEtablissement;
	
	// Structure
	private Integer idStructure;
	private String codeStructure;
	private String libelleStructure;
	private Integer idStructureMere;
	private String codeStructureMere;
	private String libelleStructureMere;
	
	// Situation
	private int idSituation;
	private String codeSituation;
	private String libelleSituationFr;
	
	public OffreFormationDto() {
	
	}

	/**
	 * [OffreFormationDto.id] Getter 
	 * @author  Rafik LAIB on : 19 avr. 2014  16:09:08
	 * @return the id
	 */
	public int getId() {
		return id;
	}

	/**
	 * [OffreFormationDto.id] Setter 
	 * @author  Rafik LAIB on : 19 avr. 2014  16:09:08
	 * @param id the id to set
	 */
	public void setId(int id) {
		this.id = id;
	}

	/**
	 * [OffreFormationDto.code] Getter 
	 * @author  Rafik LAIB on : 19 avr. 2014  16:09:08
	 * @return the code
	 */
	public String getCode() {
		return code;
	}

	/**
	 * [OffreFormationDto.code] Setter 
	 * @author  Rafik LAIB on : 19 avr. 2014  16:09:08
	 * @param code the code to set
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * [OffreFormationDto.codeInt] Getter 
	 * @author  Rafik LAIB on : 19 avr. 2014  16:09:08
	 * @return the codeInt
	 */
	public String getCodeInt() {
		return codeInt;
	}

	/**
	 * [OffreFormationDto.codeInt] Setter 
	 * @author  Rafik LAIB on : 19 avr. 2014  16:09:08
	 * @param codeInt the codeInt to set
	 */
	public void setCodeInt(String codeInt) {
		this.codeInt = codeInt;
	}

	/**
	 * [OffreFormationDto.numeroArrete] Getter 
	 * @author  Rafik LAIB on : 19 avr. 2014  16:09:08
	 * @return the numeroArrete
	 */
	public String getNumeroArrete() {
		return numeroArrete;
	}

	/**
	 * [OffreFormationDto.numeroArrete] Setter 
	 * @author  Rafik LAIB on : 19 avr. 2014  16:09:08
	 * @param numeroArrete the numeroArrete to set
	 */
	public void setNumeroArrete(String numeroArrete) {
		this.numeroArrete = numeroArrete;
	}

	/**
	 * [OffreFormationDto.estValidee] Getter 
	 * @author  Rafik LAIB on : 19 avr. 2014  16:09:08
	 * @return the estValidee
	 */
	public Boolean getEstValidee() {
		return estValidee;
	}

	/**
	 * [OffreFormationDto.estValidee] Setter 
	 * @author  Rafik LAIB on : 19 avr. 2014  16:09:08
	 * @param estValidee the estValidee to set
	 */
	public void setEstValidee(Boolean estValidee) {
		this.estValidee = estValidee;
	}

	/**
	 * [OffreFormationDto.estHabilitee] Getter 
	 * @author  Rafik LAIB on : 19 avr. 2014  16:09:08
	 * @return the estHabilitee
	 */
	public Boolean getEstHabilitee() {
		return estHabilitee;
	}

	/**
	 * [OffreFormationDto.estHabilitee] Setter 
	 * @author  Rafik LAIB on : 19 avr. 2014  16:09:08
	 * @param estHabilitee the estHabilitee to set
	 */
	public void setEstHabilitee(Boolean estHabilitee) {
		this.estHabilitee = estHabilitee;
	}

	/**
	 * [OffreFormationDto.estArchivee] Getter 
	 * @author  Rafik LAIB on : 19 avr. 2014  16:09:08
	 * @return the estArchivee
	 */
	public Boolean getEstArchivee() {
		return estArchivee;
	}

	/**
	 * [OffreFormationDto.estArchivee] Setter 
	 * @author  Rafik LAIB on : 19 avr. 2014  16:09:08
	 * @param estArchivee the estArchivee to set
	 */
	public void setEstArchivee(Boolean estArchivee) {
		this.estArchivee = estArchivee;
	}

	/**
	 * [OffreFormationDto.estAmendee] Getter 
	 * @author  Rafik LAIB on : 19 avr. 2014  16:09:08
	 * @return the estAmendee
	 */
	public Boolean getEstAmendee() {
		return estAmendee;
	}

	/**
	 * [OffreFormationDto.estAmendee] Setter 
	 * @author  Rafik LAIB on : 19 avr. 2014  16:09:08
	 * @param estAmendee the estAmendee to set
	 */
	public void setEstAmendee(Boolean estAmendee) {
		this.estAmendee = estAmendee;
	}

	/**
	 * [OffreFormationDto.estSupprimee] Getter 
	 * @author  Rafik LAIB on : 19 avr. 2014  16:09:08
	 * @return the estSupprimee
	 */
	public Boolean getEstSupprimee() {
		return estSupprimee;
	}

	/**
	 * [OffreFormationDto.estSupprimee] Setter 
	 * @author  Rafik LAIB on : 19 avr. 2014  16:09:08
	 * @param estSupprimee the estSupprimee to set
	 */
	public void setEstSupprimee(Boolean estSupprimee) {
		this.estSupprimee = estSupprimee;
	}

	/**
	 * [OffreFormationDto.estPubliee] Getter 
	 * @author  Rafik LAIB on : 19 avr. 2014  16:09:08
	 * @return the estPubliee
	 */
	public Boolean getEstPubliee() {
		return estPubliee;
	}

	/**
	 * [OffreFormationDto.estPubliee] Setter 
	 * @author  Rafik LAIB on : 19 avr. 2014  16:09:08
	 * @param estPubliee the estPubliee to set
	 */
	public void setEstPubliee(Boolean estPubliee) {
		this.estPubliee = estPubliee;
	}

	/**
	 * [OffreFormationDto.estOuverte] Getter 
	 * @author  Rafik LAIB on : 19 avr. 2014  16:09:08
	 * @return the estOuverte
	 */
	public Boolean getEstOuverte() {
		return estOuverte;
	}

	/**
	 * [OffreFormationDto.estOuverte] Setter 
	 * @author  Rafik LAIB on : 19 avr. 2014  16:09:08
	 * @param estOuverte the estOuverte to set
	 */
	public void setEstOuverte(Boolean estOuverte) {
		this.estOuverte = estOuverte;
	}

	/**
	 * [OffreFormationDto.refCodeDomaine] Getter 
	 * @author  Rafik LAIB on : 19 avr. 2014  16:09:08
	 * @return the refCodeDomaine
	 */
	public String getRefCodeDomaine() {
		return refCodeDomaine;
	}

	/**
	 * [OffreFormationDto.refCodeDomaine] Setter 
	 * @author  Rafik LAIB on : 19 avr. 2014  16:09:08
	 * @param refCodeDomaine the refCodeDomaine to set
	 */
	public void setRefCodeDomaine(String refCodeDomaine) {
		this.refCodeDomaine = refCodeDomaine;
	}

	/**
	 * [OffreFormationDto.refCodeFiliere] Getter 
	 * @author  Rafik LAIB on : 19 avr. 2014  16:09:08
	 * @return the refCodeFiliere
	 */
	public String getRefCodeFiliere() {
		return refCodeFiliere;
	}

	/**
	 * [OffreFormationDto.refCodeFiliere] Setter 
	 * @author  Rafik LAIB on : 19 avr. 2014  16:09:08
	 * @param refCodeFiliere the refCodeFiliere to set
	 */
	public void setRefCodeFiliere(String refCodeFiliere) {
		this.refCodeFiliere = refCodeFiliere;
	}

	/**
	 * [OffreFormationDto.refCodeSpecialite] Getter 
	 * @author  Rafik LAIB on : 19 avr. 2014  16:09:08
	 * @return the refCodeSpecialite
	 */
	public String getRefCodeSpecialite() {
		return refCodeSpecialite;
	}

	/**
	 * [OffreFormationDto.refCodeSpecialite] Setter 
	 * @author  Rafik LAIB on : 19 avr. 2014  16:09:08
	 * @param refCodeSpecialite the refCodeSpecialite to set
	 */
	public void setRefCodeSpecialite(String refCodeSpecialite) {
		this.refCodeSpecialite = refCodeSpecialite;
	}

	/**
	 * [OffreFormationDto.refCodeCycle] Getter 
	 * @author  Rafik LAIB on : 19 avr. 2014  16:09:08
	 * @return the refCodeCycle
	 */
	public String getRefCodeCycle() {
		return refCodeCycle;
	}

	/**
	 * [OffreFormationDto.refCodeCycle] Setter 
	 * @author  Rafik LAIB on : 19 avr. 2014  16:09:08
	 * @param refCodeCycle the refCodeCycle to set
	 */
	public void setRefCodeCycle(String refCodeCycle) {
		this.refCodeCycle = refCodeCycle;
	}

	
	/**
	 * [OffreFormationDto.dateArrete] Getter 
	 * @author  Rafik LAIB on : 19 avr. 2014  16:09:08
	 * @return the dateArrete
	 */
	public Date getDateArrete() {
		return dateArrete;
	}

	/**
	 * [OffreFormationDto.dateArrete] Setter 
	 * @author  Rafik LAIB on : 19 avr. 2014  16:09:08
	 * @param dateArrete the dateArrete to set
	 */
	public void setDateArrete(Date dateArrete) {
		this.dateArrete = dateArrete;
	}

	/**
	 * [OffreFormationDto.dateCreation] Getter 
	 * @author  Rafik LAIB on : 19 avr. 2014  16:09:08
	 * @return the dateCreation
	 */
	public Date getDateCreation() {
		return dateCreation;
	}

	/**
	 * [OffreFormationDto.dateCreation] Setter 
	 * @author  Rafik LAIB on : 19 avr. 2014  16:09:08
	 * @param dateCreation the dateCreation to set
	 */
	public void setDateCreation(Date dateCreation) {
		this.dateCreation = dateCreation;
	}

	/**
	 * [OffreFormationDto.dateModification] Getter 
	 * @author  Rafik LAIB on : 19 avr. 2014  16:09:08
	 * @return the dateModification
	 */
	public Date getDateModification() {
		return dateModification;
	}

	/**
	 * [OffreFormationDto.dateModification] Setter 
	 * @author  Rafik LAIB on : 19 avr. 2014  16:09:08
	 * @param dateModification the dateModification to set
	 */
	public void setDateModification(Date dateModification) {
		this.dateModification = dateModification;
	}

	/**
	 * [OffreFormationDto.dateDebutHabilitation] Getter 
	 * @author  Rafik LAIB on : 19 avr. 2014  16:09:08
	 * @return the dateDebutHabilitation
	 */
	public Date getDateDebutHabilitation() {
		return dateDebutHabilitation;
	}

	/**
	 * [OffreFormationDto.dateDebutHabilitation] Setter 
	 * @author  Rafik LAIB on : 19 avr. 2014  16:09:08
	 * @param dateDebutHabilitation the dateDebutHabilitation to set
	 */
	public void setDateDebutHabilitation(Date dateDebutHabilitation) {
		this.dateDebutHabilitation = dateDebutHabilitation;
	}

	/**
	 * [OffreFormationDto.dateFinHabilitation] Getter 
	 * @author  Rafik LAIB on : 19 avr. 2014  16:09:08
	 * @return the dateFinHabilitation
	 */
	public Date getDateFinHabilitation() {
		return dateFinHabilitation;
	}

	/**
	 * [OffreFormationDto.dateFinHabilitation] Setter 
	 * @author  Rafik LAIB on : 19 avr. 2014  16:09:08
	 * @param dateFinHabilitation the dateFinHabilitation to set
	 */
	public void setDateFinHabilitation(Date dateFinHabilitation) {
		this.dateFinHabilitation = dateFinHabilitation;
	}
	
	/**
	 * [OffreFormationDto.idSituation] Getter 
	 * @author  Rafik LAIB on : 3 mai 2014  19:28:16
	 * @return the idSituation
	 */
	public int getIdSituation() {
		return idSituation;
	}

	/**
	 * [OffreFormationDto.idSituation] Setter 
	 * @author  Rafik LAIB on : 3 mai 2014  19:28:16
	 * @param idSituation the idSituation to set
	 */
	public void setIdSituation(int idSituation) {
		this.idSituation = idSituation;
	}

	/**
	 * [OffreFormationDto.estCompletee] Getter 
	 * @author rlaib on : 4 mai 2014  11:30:54
	 * @return the estCompletee
	 */
	public Boolean getEstCompletee() {
		return estCompletee;
	}

	/**
	 * [OffreFormationDto.estCompletee] Setter 
	 * @author rlaib on : 4 mai 2014  11:30:54
	 * @param estCompletee the estCompletee to set
	 */
	public void setEstCompletee(Boolean estCompletee) {
		this.estCompletee = estCompletee;
	}

	/**
	 * [OffreFormationDto.nombreEtudiantImporte] Getter 
	 * @author MAKERRI Sofiane on : 17 juin 2014  12:36:05
	 * @return the nombreEtudiantImporte
	 */
	public Integer getNombreEtudiantImporte() {
		return nombreEtudiantImporte;
	}

	/**
	 * [OffreFormationDto.nombreEtudiantImporte] Setter 
	 * @author MAKERRI Sofiane on : 17 juin 2014  12:36:05
	 * @param nombreEtudiantImporte the nombreEtudiantImporte to set
	 */
	public void setNombreEtudiantImporte(Integer nombreEtudiantImporte) {
		this.nombreEtudiantImporte = nombreEtudiantImporte;
	}

	/**
	 * [OffreFormationDto.nombreEtudiantInscrit] Getter 
	 * @author MAKERRI Sofiane on : 17 juin 2014  12:36:05
	 * @return the nombreEtudiantInscrit
	 */
	public Integer getNombreEtudiantInscrit() {
		return nombreEtudiantInscrit;
	}

	/**
	 * [OffreFormationDto.nombreEtudiantInscrit] Setter 
	 * @author MAKERRI Sofiane on : 17 juin 2014  12:36:05
	 * @param nombreEtudiantInscrit the nombreEtudiantInscrit to set
	 */
	public void setNombreEtudiantInscrit(Integer nombreEtudiantInscrit) {
		this.nombreEtudiantInscrit = nombreEtudiantInscrit;
	}

	/**
	 * [OffreFormationDto.idCycle] Getter 
	 * @author rlaib on : 9 sept. 2014  15:26:30
	 * @return the idCycle
	 */
	public Integer getIdCycle() {
		return idCycle;
	}

	/**
	 * [OffreFormationDto.idCycle] Setter 
	 * @author rlaib on : 9 sept. 2014  15:26:30
	 * @param idCycle the idCycle to set
	 */
	public void setIdCycle(Integer idCycle) {
		this.idCycle = idCycle;
	}

	/**
	 * [OffreFormationDto.codeCycle] Getter 
	 * @author rlaib on : 9 sept. 2014  15:26:30
	 * @return the codeCycle
	 */
	public String getCodeCycle() {
		return codeCycle;
	}

	/**
	 * [OffreFormationDto.codeCycle] Setter 
	 * @author rlaib on : 9 sept. 2014  15:26:30
	 * @param codeCycle the codeCycle to set
	 */
	public void setCodeCycle(String codeCycle) {
		this.codeCycle = codeCycle;
	}

	/**
	 * [OffreFormationDto.libelleCycle] Getter 
	 * @author rlaib on : 9 sept. 2014  15:26:30
	 * @return the libelleCycle
	 */
	public String getLibelleCycle() {
		return libelleCycle;
	}

	/**
	 * [OffreFormationDto.libelleCycle] Setter 
	 * @author rlaib on : 9 sept. 2014  15:26:30
	 * @param libelleCycle the libelleCycle to set
	 */
	public void setLibelleCycle(String libelleCycle) {
		this.libelleCycle = libelleCycle;
	}

	/**
	 * [OffreFormationDto.libelleDomaine] Getter 
	 * @author BELDI Jamel on : 10 sept. 2014  12:30:50
	 * @return the libelleDomaine
	 */
	public String getLibelleDomaine() {
		return libelleDomaine;
	}

	/**
	 * [OffreFormationDto.libelleDomaine] Setter 
	 * @author BELDI Jamel on : 10 sept. 2014  12:30:50
	 * @param libelleDomaine the libelleDomaine to set
	 */
	public void setLibelleDomaine(String libelleDomaine) {
		this.libelleDomaine = libelleDomaine;
	}

	/**
	 * [OffreFormationDto.libelleFiliere] Getter 
	 * @author BELDI Jamel on : 10 sept. 2014  12:30:50
	 * @return the libelleFiliere
	 */
	public String getLibelleFiliere() {
		return libelleFiliere;
	}

	/**
	 * [OffreFormationDto.libelleFiliere] Setter 
	 * @author BELDI Jamel on : 10 sept. 2014  12:30:50
	 * @param libelleFiliere the libelleFiliere to set
	 */
	public void setLibelleFiliere(String libelleFiliere) {
		this.libelleFiliere = libelleFiliere;
	}

	/**
	 * [OffreFormationDto.libelleSpecialite] Getter 
	 * @author BELDI Jamel on : 10 sept. 2014  12:30:50
	 * @return the libelleSpecialite
	 */
	public String getLibelleSpecialite() {
		return libelleSpecialite;
	}

	/**
	 * [OffreFormationDto.libelleSpecialite] Setter 
	 * @author BELDI Jamel on : 10 sept. 2014  12:30:50
	 * @param libelleSpecialite the libelleSpecialite to set
	 */
	public void setLibelleSpecialite(String libelleSpecialite) {
		this.libelleSpecialite = libelleSpecialite;
	}

	/**
	 * [OffreFormationDto.idEtablissement] Getter 
	 * @author rlaib on : 11 oct. 2014  14:31:40
	 * @return the idEtablissement
	 */
	public Integer getIdEtablissement() {
		return idEtablissement;
	}

	/**
	 * [OffreFormationDto.idEtablissement] Setter 
	 * @author rlaib on : 11 oct. 2014  14:31:40
	 * @param idEtablissement the idEtablissement to set
	 */
	public void setIdEtablissement(Integer idEtablissement) {
		this.idEtablissement = idEtablissement;
	}

	/**
	 * [OffreFormationDto.codeEtablissement] Getter 
	 * @author rlaib on : 11 oct. 2014  14:31:40
	 * @return the codeEtablissement
	 */
	public String getCodeEtablissement() {
		return codeEtablissement;
	}

	/**
	 * [OffreFormationDto.codeEtablissement] Setter 
	 * @author rlaib on : 11 oct. 2014  14:31:40
	 * @param codeEtablissement the codeEtablissement to set
	 */
	public void setCodeEtablissement(String codeEtablissement) {
		this.codeEtablissement = codeEtablissement;
	}

	/**
	 * [OffreFormationDto.libelleEtablissement] Getter 
	 * @author rlaib on : 11 oct. 2014  14:31:40
	 * @return the libelleEtablissement
	 */
	public String getLibelleEtablissement() {
		return libelleEtablissement;
	}

	/**
	 * [OffreFormationDto.libelleEtablissement] Setter 
	 * @author rlaib on : 11 oct. 2014  14:31:40
	 * @param libelleEtablissement the libelleEtablissement to set
	 */
	public void setLibelleEtablissement(String libelleEtablissement) {
		this.libelleEtablissement = libelleEtablissement;
	}

	/**
	 * [OffreFormationDto.idStructure] Getter 
	 * @author rlaib on : 11 oct. 2014  14:31:40
	 * @return the idStructure
	 */
	public Integer getIdStructure() {
		return idStructure;
	}

	/**
	 * [OffreFormationDto.idStructure] Setter 
	 * @author rlaib on : 11 oct. 2014  14:31:40
	 * @param idStructure the idStructure to set
	 */
	public void setIdStructure(Integer idStructure) {
		this.idStructure = idStructure;
	}

	/**
	 * [OffreFormationDto.codeStructure] Getter 
	 * @author rlaib on : 11 oct. 2014  14:31:40
	 * @return the codeStructure
	 */
	public String getCodeStructure() {
		return codeStructure;
	}

	/**
	 * [OffreFormationDto.codeStructure] Setter 
	 * @author rlaib on : 11 oct. 2014  14:31:40
	 * @param codeStructure the codeStructure to set
	 */
	public void setCodeStructure(String codeStructure) {
		this.codeStructure = codeStructure;
	}

	/**
	 * [OffreFormationDto.libelleStructure] Getter 
	 * @author rlaib on : 11 oct. 2014  14:31:40
	 * @return the libelleStructure
	 */
	public String getLibelleStructure() {
		return libelleStructure;
	}

	/**
	 * [OffreFormationDto.libelleStructure] Setter 
	 * @author rlaib on : 11 oct. 2014  14:31:40
	 * @param libelleStructure the libelleStructure to set
	 */
	public void setLibelleStructure(String libelleStructure) {
		this.libelleStructure = libelleStructure;
	}

	/**
	 * [OffreFormationDto.libelleLongFr] Getter 
	 * @author rlaib on : 11 oct. 2014  14:59:57
	 * @return the libelleLongFr
	 */
	public String getLibelleLongFr() {
		return libelleLongFr;
	}

	/**
	 * [OffreFormationDto.libelleLongFr] Setter 
	 * @author rlaib on : 11 oct. 2014  14:59:57
	 * @param libelleLongFr the libelleLongFr to set
	 */
	public void setLibelleLongFr(String libelleLongFr) {
		this.libelleLongFr = libelleLongFr;
	}

	/**
	 * [OffreFormationDto.libelleCourtFr] Getter 
	 * @author rlaib on : 11 oct. 2014  14:59:57
	 * @return the libelleCourtFr
	 */
	public String getLibelleCourtFr() {
		return libelleCourtFr;
	}

	/**
	 * [OffreFormationDto.libelleCourtFr] Setter 
	 * @author rlaib on : 11 oct. 2014  14:59:57
	 * @param libelleCourtFr the libelleCourtFr to set
	 */
	public void setLibelleCourtFr(String libelleCourtFr) {
		this.libelleCourtFr = libelleCourtFr;
	}

	/**
	 * [OffreFormationDto.abrevFr] Getter 
	 * @author rlaib on : 11 oct. 2014  14:59:57
	 * @return the abrevFr
	 */
	public String getAbrevFr() {
		return abrevFr;
	}

	/**
	 * [OffreFormationDto.abrevFr] Setter 
	 * @author rlaib on : 11 oct. 2014  14:59:57
	 * @param abrevFr the abrevFr to set
	 */
	public void setAbrevFr(String abrevFr) {
		this.abrevFr = abrevFr;
	}

	/**
	 * [OffreFormationDto.libelleLongAr] Getter 
	 * @author rlaib on : 11 oct. 2014  14:59:57
	 * @return the libelleLongAr
	 */
	public String getLibelleLongAr() {
		return libelleLongAr;
	}

	/**
	 * [OffreFormationDto.libelleLongAr] Setter 
	 * @author rlaib on : 11 oct. 2014  14:59:57
	 * @param libelleLongAr the libelleLongAr to set
	 */
	public void setLibelleLongAr(String libelleLongAr) {
		this.libelleLongAr = libelleLongAr;
	}

	/**
	 * [OffreFormationDto.libelleCourtAr] Getter 
	 * @author rlaib on : 11 oct. 2014  14:59:57
	 * @return the libelleCourtAr
	 */
	public String getLibelleCourtAr() {
		return libelleCourtAr;
	}

	/**
	 * [OffreFormationDto.libelleCourtAr] Setter 
	 * @author rlaib on : 11 oct. 2014  14:59:57
	 * @param libelleCourtAr the libelleCourtAr to set
	 */
	public void setLibelleCourtAr(String libelleCourtAr) {
		this.libelleCourtAr = libelleCourtAr;
	}

	/**
	 * [OffreFormationDto.abrevAr] Getter 
	 * @author rlaib on : 11 oct. 2014  14:59:57
	 * @return the abrevAr
	 */
	public String getAbrevAr() {
		return abrevAr;
	}

	/**
	 * [OffreFormationDto.abrevAr] Setter 
	 * @author rlaib on : 11 oct. 2014  14:59:57
	 * @param abrevAr the abrevAr to set
	 */
	public void setAbrevAr(String abrevAr) {
		this.abrevAr = abrevAr;
	}

	/**
	 * [OffreFormationDto.description] Getter 
	 * @author rlaib on : 11 oct. 2014  14:59:57
	 * @return the description
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * [OffreFormationDto.description] Setter 
	 * @author rlaib on : 11 oct. 2014  14:59:57
	 * @param description the description to set
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * [OffreFormationDto.codeSituation] Getter 
	 * @author rlaib on : 11 oct. 2014  15:02:02
	 * @return the codeSituation
	 */
	public String getCodeSituation() {
		return codeSituation;
	}

	/**
	 * [OffreFormationDto.codeSituation] Setter 
	 * @author rlaib on : 11 oct. 2014  15:02:02
	 * @param codeSituation the codeSituation to set
	 */
	public void setCodeSituation(String codeSituation) {
		this.codeSituation = codeSituation;
	}

	/**
	 * [OffreFormationDto.libelleSituationFr] Getter 
	 * @author rlaib on : 11 oct. 2014  15:02:02
	 * @return the libelleSituationFr
	 */
	public String getLibelleSituationFr() {
		return libelleSituationFr;
	}

	/**
	 * [OffreFormationDto.libelleSituationFr] Setter 
	 * @author rlaib on : 11 oct. 2014  15:02:02
	 * @param libelleSituationFr the libelleSituationFr to set
	 */
	public void setLibelleSituationFr(String libelleSituationFr) {
		this.libelleSituationFr = libelleSituationFr;
	}

	
	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((abrevAr == null) ? 0 : abrevAr.hashCode());
		result = prime * result + ((abrevFr == null) ? 0 : abrevFr.hashCode());
		result = prime * result + ((code == null) ? 0 : code.hashCode());
		result = prime * result
				+ ((codeCycle == null) ? 0 : codeCycle.hashCode());
		result = prime * result
				+ ((codeDomaine == null) ? 0 : codeDomaine.hashCode());
		result = prime
				* result
				+ ((codeEtablissement == null) ? 0 : codeEtablissement
						.hashCode());
		result = prime * result
				+ ((codeFiliere == null) ? 0 : codeFiliere.hashCode());
		result = prime * result + ((codeInt == null) ? 0 : codeInt.hashCode());
		result = prime * result
				+ ((codeSituation == null) ? 0 : codeSituation.hashCode());
		result = prime * result
				+ ((codeSpecialite == null) ? 0 : codeSpecialite.hashCode());
		result = prime * result
				+ ((codeStructure == null) ? 0 : codeStructure.hashCode());
		result = prime
				* result
				+ ((codeTypeFormation == null) ? 0 : codeTypeFormation
						.hashCode());
		result = prime * result
				+ ((codeVocation == null) ? 0 : codeVocation.hashCode());
		result = prime * result
				+ ((dateArrete == null) ? 0 : dateArrete.hashCode());
		result = prime * result
				+ ((dateCreation == null) ? 0 : dateCreation.hashCode());
		result = prime
				* result
				+ ((dateDebutHabilitation == null) ? 0 : dateDebutHabilitation
						.hashCode());
		result = prime
				* result
				+ ((dateFinHabilitation == null) ? 0 : dateFinHabilitation
						.hashCode());
		result = prime
				* result
				+ ((dateModification == null) ? 0 : dateModification.hashCode());
		result = prime * result
				+ ((description == null) ? 0 : description.hashCode());
		result = prime * result
				+ ((estAmendee == null) ? 0 : estAmendee.hashCode());
		result = prime * result
				+ ((estArchivee == null) ? 0 : estArchivee.hashCode());
		result = prime * result
				+ ((estCompletee == null) ? 0 : estCompletee.hashCode());
		result = prime * result
				+ ((estHabilitee == null) ? 0 : estHabilitee.hashCode());
		result = prime * result
				+ ((estOuverte == null) ? 0 : estOuverte.hashCode());
		result = prime * result
				+ ((estPubliee == null) ? 0 : estPubliee.hashCode());
		result = prime * result
				+ ((estSupprimee == null) ? 0 : estSupprimee.hashCode());
		result = prime * result
				+ ((estValidee == null) ? 0 : estValidee.hashCode());
		result = prime * result + id;
		result = prime * result + ((idCycle == null) ? 0 : idCycle.hashCode());
		result = prime * result
				+ ((idDomaine == null) ? 0 : idDomaine.hashCode());
		result = prime * result
				+ ((idEtablissement == null) ? 0 : idEtablissement.hashCode());
		result = prime * result
				+ ((idFiliere == null) ? 0 : idFiliere.hashCode());
		result = prime * result + idSituation;
		result = prime * result
				+ ((idSpecialite == null) ? 0 : idSpecialite.hashCode());
		result = prime * result
				+ ((idStructure == null) ? 0 : idStructure.hashCode());
		result = prime * result
				+ ((idTypeFormation == null) ? 0 : idTypeFormation.hashCode());
		result = prime * result
				+ ((idVocation == null) ? 0 : idVocation.hashCode());
		result = prime * result
				+ ((libelleCourtAr == null) ? 0 : libelleCourtAr.hashCode());
		result = prime * result
				+ ((libelleCourtFr == null) ? 0 : libelleCourtFr.hashCode());
		result = prime * result
				+ ((libelleCycle == null) ? 0 : libelleCycle.hashCode());
		result = prime * result
				+ ((libelleDomaine == null) ? 0 : libelleDomaine.hashCode());
		result = prime
				* result
				+ ((libelleEtablissement == null) ? 0 : libelleEtablissement
						.hashCode());
		result = prime * result
				+ ((libelleFiliere == null) ? 0 : libelleFiliere.hashCode());
		result = prime * result
				+ ((libelleLongAr == null) ? 0 : libelleLongAr.hashCode());
		result = prime * result
				+ ((libelleLongFr == null) ? 0 : libelleLongFr.hashCode());
		result = prime
				* result
				+ ((libelleSituationFr == null) ? 0 : libelleSituationFr
						.hashCode());
		result = prime
				* result
				+ ((libelleSpecialite == null) ? 0 : libelleSpecialite
						.hashCode());
		result = prime
				* result
				+ ((libelleStructure == null) ? 0 : libelleStructure.hashCode());
		result = prime
				* result
				+ ((libelleTypeFormation == null) ? 0 : libelleTypeFormation
						.hashCode());
		result = prime * result
				+ ((libelleVocation == null) ? 0 : libelleVocation.hashCode());
		result = prime
				* result
				+ ((nombreEtudiantImporte == null) ? 0 : nombreEtudiantImporte
						.hashCode());
		result = prime
				* result
				+ ((nombreEtudiantInscrit == null) ? 0 : nombreEtudiantInscrit
						.hashCode());
		result = prime * result
				+ ((numeroArrete == null) ? 0 : numeroArrete.hashCode());
		result = prime * result
				+ ((refCodeCycle == null) ? 0 : refCodeCycle.hashCode());
		result = prime * result
				+ ((refCodeDomaine == null) ? 0 : refCodeDomaine.hashCode());
		result = prime * result
				+ ((refCodeFiliere == null) ? 0 : refCodeFiliere.hashCode());
		result = prime
				* result
				+ ((refCodeSpecialite == null) ? 0 : refCodeSpecialite
						.hashCode());
		return result;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		OffreFormationDto other = (OffreFormationDto) obj;
		if (abrevAr == null) {
			if (other.abrevAr != null)
				return false;
		} else if (!abrevAr.equals(other.abrevAr))
			return false;
		if (abrevFr == null) {
			if (other.abrevFr != null)
				return false;
		} else if (!abrevFr.equals(other.abrevFr))
			return false;
		if (code == null) {
			if (other.code != null)
				return false;
		} else if (!code.equals(other.code))
			return false;
		if (codeCycle == null) {
			if (other.codeCycle != null)
				return false;
		} else if (!codeCycle.equals(other.codeCycle))
			return false;
		if (codeDomaine == null) {
			if (other.codeDomaine != null)
				return false;
		} else if (!codeDomaine.equals(other.codeDomaine))
			return false;
		if (codeEtablissement == null) {
			if (other.codeEtablissement != null)
				return false;
		} else if (!codeEtablissement.equals(other.codeEtablissement))
			return false;
		if (codeFiliere == null) {
			if (other.codeFiliere != null)
				return false;
		} else if (!codeFiliere.equals(other.codeFiliere))
			return false;
		if (codeInt == null) {
			if (other.codeInt != null)
				return false;
		} else if (!codeInt.equals(other.codeInt))
			return false;
		if (codeSituation == null) {
			if (other.codeSituation != null)
				return false;
		} else if (!codeSituation.equals(other.codeSituation))
			return false;
		if (codeSpecialite == null) {
			if (other.codeSpecialite != null)
				return false;
		} else if (!codeSpecialite.equals(other.codeSpecialite))
			return false;
		if (codeStructure == null) {
			if (other.codeStructure != null)
				return false;
		} else if (!codeStructure.equals(other.codeStructure))
			return false;
		if (codeTypeFormation == null) {
			if (other.codeTypeFormation != null)
				return false;
		} else if (!codeTypeFormation.equals(other.codeTypeFormation))
			return false;
		if (codeVocation == null) {
			if (other.codeVocation != null)
				return false;
		} else if (!codeVocation.equals(other.codeVocation))
			return false;
		if (dateArrete == null) {
			if (other.dateArrete != null)
				return false;
		} else if (!dateArrete.equals(other.dateArrete))
			return false;
		if (dateCreation == null) {
			if (other.dateCreation != null)
				return false;
		} else if (!dateCreation.equals(other.dateCreation))
			return false;
		if (dateDebutHabilitation == null) {
			if (other.dateDebutHabilitation != null)
				return false;
		} else if (!dateDebutHabilitation.equals(other.dateDebutHabilitation))
			return false;
		if (dateFinHabilitation == null) {
			if (other.dateFinHabilitation != null)
				return false;
		} else if (!dateFinHabilitation.equals(other.dateFinHabilitation))
			return false;
		if (dateModification == null) {
			if (other.dateModification != null)
				return false;
		} else if (!dateModification.equals(other.dateModification))
			return false;
		if (description == null) {
			if (other.description != null)
				return false;
		} else if (!description.equals(other.description))
			return false;
		if (estAmendee == null) {
			if (other.estAmendee != null)
				return false;
		} else if (!estAmendee.equals(other.estAmendee))
			return false;
		if (estArchivee == null) {
			if (other.estArchivee != null)
				return false;
		} else if (!estArchivee.equals(other.estArchivee))
			return false;
		if (estCompletee == null) {
			if (other.estCompletee != null)
				return false;
		} else if (!estCompletee.equals(other.estCompletee))
			return false;
		if (estHabilitee == null) {
			if (other.estHabilitee != null)
				return false;
		} else if (!estHabilitee.equals(other.estHabilitee))
			return false;
		if (estOuverte == null) {
			if (other.estOuverte != null)
				return false;
		} else if (!estOuverte.equals(other.estOuverte))
			return false;
		if (estPubliee == null) {
			if (other.estPubliee != null)
				return false;
		} else if (!estPubliee.equals(other.estPubliee))
			return false;
		if (estSupprimee == null) {
			if (other.estSupprimee != null)
				return false;
		} else if (!estSupprimee.equals(other.estSupprimee))
			return false;
		if (estValidee == null) {
			if (other.estValidee != null)
				return false;
		} else if (!estValidee.equals(other.estValidee))
			return false;
		if (id != other.id)
			return false;
		if (idCycle == null) {
			if (other.idCycle != null)
				return false;
		} else if (!idCycle.equals(other.idCycle))
			return false;
		if (idDomaine == null) {
			if (other.idDomaine != null)
				return false;
		} else if (!idDomaine.equals(other.idDomaine))
			return false;
		if (idEtablissement == null) {
			if (other.idEtablissement != null)
				return false;
		} else if (!idEtablissement.equals(other.idEtablissement))
			return false;
		if (idFiliere == null) {
			if (other.idFiliere != null)
				return false;
		} else if (!idFiliere.equals(other.idFiliere))
			return false;
		if (idSituation != other.idSituation)
			return false;
		if (idSpecialite == null) {
			if (other.idSpecialite != null)
				return false;
		} else if (!idSpecialite.equals(other.idSpecialite))
			return false;
		if (idStructure == null) {
			if (other.idStructure != null)
				return false;
		} else if (!idStructure.equals(other.idStructure))
			return false;
		if (idTypeFormation == null) {
			if (other.idTypeFormation != null)
				return false;
		} else if (!idTypeFormation.equals(other.idTypeFormation))
			return false;
		if (idVocation == null) {
			if (other.idVocation != null)
				return false;
		} else if (!idVocation.equals(other.idVocation))
			return false;
		if (libelleCourtAr == null) {
			if (other.libelleCourtAr != null)
				return false;
		} else if (!libelleCourtAr.equals(other.libelleCourtAr))
			return false;
		if (libelleCourtFr == null) {
			if (other.libelleCourtFr != null)
				return false;
		} else if (!libelleCourtFr.equals(other.libelleCourtFr))
			return false;
		if (libelleCycle == null) {
			if (other.libelleCycle != null)
				return false;
		} else if (!libelleCycle.equals(other.libelleCycle))
			return false;
		if (libelleDomaine == null) {
			if (other.libelleDomaine != null)
				return false;
		} else if (!libelleDomaine.equals(other.libelleDomaine))
			return false;
		if (libelleEtablissement == null) {
			if (other.libelleEtablissement != null)
				return false;
		} else if (!libelleEtablissement.equals(other.libelleEtablissement))
			return false;
		if (libelleFiliere == null) {
			if (other.libelleFiliere != null)
				return false;
		} else if (!libelleFiliere.equals(other.libelleFiliere))
			return false;
		if (libelleLongAr == null) {
			if (other.libelleLongAr != null)
				return false;
		} else if (!libelleLongAr.equals(other.libelleLongAr))
			return false;
		if (libelleLongFr == null) {
			if (other.libelleLongFr != null)
				return false;
		} else if (!libelleLongFr.equals(other.libelleLongFr))
			return false;
		if (libelleSituationFr == null) {
			if (other.libelleSituationFr != null)
				return false;
		} else if (!libelleSituationFr.equals(other.libelleSituationFr))
			return false;
		if (libelleSpecialite == null) {
			if (other.libelleSpecialite != null)
				return false;
		} else if (!libelleSpecialite.equals(other.libelleSpecialite))
			return false;
		if (libelleStructure == null) {
			if (other.libelleStructure != null)
				return false;
		} else if (!libelleStructure.equals(other.libelleStructure))
			return false;
		if (libelleTypeFormation == null) {
			if (other.libelleTypeFormation != null)
				return false;
		} else if (!libelleTypeFormation.equals(other.libelleTypeFormation))
			return false;
		if (libelleVocation == null) {
			if (other.libelleVocation != null)
				return false;
		} else if (!libelleVocation.equals(other.libelleVocation))
			return false;
		if (nombreEtudiantImporte == null) {
			if (other.nombreEtudiantImporte != null)
				return false;
		} else if (!nombreEtudiantImporte.equals(other.nombreEtudiantImporte))
			return false;
		if (nombreEtudiantInscrit == null) {
			if (other.nombreEtudiantInscrit != null)
				return false;
		} else if (!nombreEtudiantInscrit.equals(other.nombreEtudiantInscrit))
			return false;
		if (numeroArrete == null) {
			if (other.numeroArrete != null)
				return false;
		} else if (!numeroArrete.equals(other.numeroArrete))
			return false;
		if (refCodeCycle == null) {
			if (other.refCodeCycle != null)
				return false;
		} else if (!refCodeCycle.equals(other.refCodeCycle))
			return false;
		if (refCodeDomaine == null) {
			if (other.refCodeDomaine != null)
				return false;
		} else if (!refCodeDomaine.equals(other.refCodeDomaine))
			return false;
		if (refCodeFiliere == null) {
			if (other.refCodeFiliere != null)
				return false;
		} else if (!refCodeFiliere.equals(other.refCodeFiliere))
			return false;
		if (refCodeSpecialite == null) {
			if (other.refCodeSpecialite != null)
				return false;
		} else if (!refCodeSpecialite.equals(other.refCodeSpecialite))
			return false;
		return true;
	}

	/**
	 * [OffreFormationDto.idDomaine] Getter 
	 * @author rlaib on : 17 nov. 2014  16:29:59
	 * @return the idDomaine
	 */
	public Integer getIdDomaine() {
		return idDomaine;
	}

	/**
	 * [OffreFormationDto.idDomaine] Setter 
	 * @author rlaib on : 17 nov. 2014  16:29:59
	 * @param idDomaine the idDomaine to set
	 */
	public void setIdDomaine(Integer idDomaine) {
		this.idDomaine = idDomaine;
	}

	/**
	 * [OffreFormationDto.codeDomaine] Getter 
	 * @author rlaib on : 17 nov. 2014  16:29:59
	 * @return the codeDomaine
	 */
	public String getCodeDomaine() {
		return codeDomaine;
	}

	/**
	 * [OffreFormationDto.codeDomaine] Setter 
	 * @author rlaib on : 17 nov. 2014  16:29:59
	 * @param codeDomaine the codeDomaine to set
	 */
	public void setCodeDomaine(String codeDomaine) {
		this.codeDomaine = codeDomaine;
	}

	/**
	 * [OffreFormationDto.idFiliere] Getter 
	 * @author rlaib on : 17 nov. 2014  16:29:59
	 * @return the idFiliere
	 */
	public Integer getIdFiliere() {
		return idFiliere;
	}

	/**
	 * [OffreFormationDto.idFiliere] Setter 
	 * @author rlaib on : 17 nov. 2014  16:29:59
	 * @param idFiliere the idFiliere to set
	 */
	public void setIdFiliere(Integer idFiliere) {
		this.idFiliere = idFiliere;
	}

	/**
	 * [OffreFormationDto.codeFiliere] Getter 
	 * @author rlaib on : 17 nov. 2014  16:29:59
	 * @return the codeFiliere
	 */
	public String getCodeFiliere() {
		return codeFiliere;
	}

	/**
	 * [OffreFormationDto.codeFiliere] Setter 
	 * @author rlaib on : 17 nov. 2014  16:29:59
	 * @param codeFiliere the codeFiliere to set
	 */
	public void setCodeFiliere(String codeFiliere) {
		this.codeFiliere = codeFiliere;
	}

	/**
	 * [OffreFormationDto.idSpecialite] Getter 
	 * @author rlaib on : 17 nov. 2014  16:29:59
	 * @return the idSpecialite
	 */
	public Integer getIdSpecialite() {
		return idSpecialite;
	}

	/**
	 * [OffreFormationDto.idSpecialite] Setter 
	 * @author rlaib on : 17 nov. 2014  16:29:59
	 * @param idSpecialite the idSpecialite to set
	 */
	public void setIdSpecialite(Integer idSpecialite) {
		this.idSpecialite = idSpecialite;
	}

	/**
	 * [OffreFormationDto.codeSpecialite] Getter 
	 * @author rlaib on : 17 nov. 2014  16:29:59
	 * @return the codeSpecialite
	 */
	public String getCodeSpecialite() {
		return codeSpecialite;
	}

	/**
	 * [OffreFormationDto.codeSpecialite] Setter 
	 * @author rlaib on : 17 nov. 2014  16:29:59
	 * @param codeSpecialite the codeSpecialite to set
	 */
	public void setCodeSpecialite(String codeSpecialite) {
		this.codeSpecialite = codeSpecialite;
	}

	/**
	 * [OffreFormationDto.idTypeFormation] Getter 
	 * @author rlaib on : 2 d�c. 2014  10:43:32
	 * @return the idTypeFormation
	 */
	public Integer getIdTypeFormation() {
		return idTypeFormation;
	}

	/**
	 * [OffreFormationDto.idTypeFormation] Setter 
	 * @author rlaib on : 2 d�c. 2014  10:43:32
	 * @param idTypeFormation the idTypeFormation to set
	 */
	public void setIdTypeFormation(Integer idTypeFormation) {
		this.idTypeFormation = idTypeFormation;
	}

	/**
	 * [OffreFormationDto.codeTypeFormation] Getter 
	 * @author rlaib on : 2 d�c. 2014  10:43:32
	 * @return the codeTypeFormation
	 */
	public String getCodeTypeFormation() {
		return codeTypeFormation;
	}

	/**
	 * [OffreFormationDto.codeTypeFormation] Setter 
	 * @author rlaib on : 2 d�c. 2014  10:43:32
	 * @param codeTypeFormation the codeTypeFormation to set
	 */
	public void setCodeTypeFormation(String codeTypeFormation) {
		this.codeTypeFormation = codeTypeFormation;
	}

	/**
	 * [OffreFormationDto.libelleTypeFormation] Getter 
	 * @author rlaib on : 2 d�c. 2014  10:43:32
	 * @return the libelleTypeFormation
	 */
	public String getLibelleTypeFormation() {
		return libelleTypeFormation;
	}

	/**
	 * [OffreFormationDto.libelleTypeFormation] Setter 
	 * @author rlaib on : 2 d�c. 2014  10:43:32
	 * @param libelleTypeFormation the libelleTypeFormation to set
	 */
	public void setLibelleTypeFormation(String libelleTypeFormation) {
		this.libelleTypeFormation = libelleTypeFormation;
	}

	/**
	 * [OffreFormationDto.idVocation] Getter 
	 * @author rlaib on : 2 d�c. 2014  10:43:32
	 * @return the idVocation
	 */
	public Integer getIdVocation() {
		return idVocation;
	}

	/**
	 * [OffreFormationDto.idVocation] Setter 
	 * @author rlaib on : 2 d�c. 2014  10:43:32
	 * @param idVocation the idVocation to set
	 */
	public void setIdVocation(Integer idVocation) {
		this.idVocation = idVocation;
	}

	/**
	 * [OffreFormationDto.codeVocation] Getter 
	 * @author rlaib on : 2 d�c. 2014  10:43:32
	 * @return the codeVocation
	 */
	public String getCodeVocation() {
		return codeVocation;
	}

	/**
	 * [OffreFormationDto.codeVocation] Setter 
	 * @author rlaib on : 2 d�c. 2014  10:43:32
	 * @param codeVocation the codeVocation to set
	 */
	public void setCodeVocation(String codeVocation) {
		this.codeVocation = codeVocation;
	}

	/**
	 * [OffreFormationDto.libelleVocation] Getter 
	 * @author rlaib on : 2 d�c. 2014  10:43:32
	 * @return the libelleVocation
	 */
	public String getLibelleVocation() {
		return libelleVocation;
	}

	/**
	 * [OffreFormationDto.libelleVocation] Setter 
	 * @author rlaib on : 2 d�c. 2014  10:43:32
	 * @param libelleVocation the libelleVocation to set
	 */
	public void setLibelleVocation(String libelleVocation) {
		this.libelleVocation = libelleVocation;
	}

	/**
	 * [OffreFormationDto.idStructureMere] Getter 
	 * @author Rafik on : 5 déc. 2014  22:31:41
	 * @return the idStructureMere
	 */
	public Integer getIdStructureMere() {
		return idStructureMere;
	}

	/**
	 * [OffreFormationDto.idStructureMere] Setter 
	 * @author Rafik on : 5 déc. 2014  22:31:41
	 * @param idStructureMere the idStructureMere to set
	 */
	public void setIdStructureMere(Integer idStructureMere) {
		this.idStructureMere = idStructureMere;
	}

	/**
	 * [OffreFormationDto.codeStructureMere] Getter 
	 * @author Rafik on : 5 déc. 2014  22:31:41
	 * @return the codeStructureMere
	 */
	public String getCodeStructureMere() {
		return codeStructureMere;
	}

	/**
	 * [OffreFormationDto.codeStructureMere] Setter 
	 * @author Rafik on : 5 déc. 2014  22:31:41
	 * @param codeStructureMere the codeStructureMere to set
	 */
	public void setCodeStructureMere(String codeStructureMere) {
		this.codeStructureMere = codeStructureMere;
	}

	/**
	 * [OffreFormationDto.libelleStructureMere] Getter 
	 * @author Rafik on : 5 déc. 2014  22:31:41
	 * @return the libelleStructureMere
	 */
	public String getLibelleStructureMere() {
		return libelleStructureMere;
	}

	/**
	 * [OffreFormationDto.libelleStructureMere] Setter 
	 * @author Rafik on : 5 déc. 2014  22:31:41
	 * @param libelleStructureMere the libelleStructureMere to set
	 */
	public void setLibelleStructureMere(String libelleStructureMere) {
		this.libelleStructureMere = libelleStructureMere;
	}

	
}
