package dz.gov.mesrs.sii.commons.data.model.gfc;

// Generated 24 nov. 2014 16:52:54 by Hibernate Tools 3.6.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import dz.gov.mesrs.sii.commons.data.model.Identifiable;
import dz.gov.mesrs.sii.commons.data.model.referentiel.RefEtablissement;
import dz.gov.mesrs.sii.commons.data.model.referentiel.RefStructure;

/**
 * AffectationEtabStrAgentComptable generated by hbm2java
 */
@Entity
@Table(name = "affectation_etab_str_agent_comptable", schema = "gfc")
public class AffectationEtabStrAgentComptable implements java.io.Serializable, Identifiable<Integer> {

	/**
	 * @author Mounir.MESSAOUDI on : 24 nov. 2014 17:31:41
	 */
	private static final long serialVersionUID = 1L;

	private Integer id;
	private RefStructure refStructure;
	private AgentComptable agentComptable;
	private RefEtablissement refEtablissement;
	private Date dateAffectation;
	private String observation;
	private String decisionAffectation;
	private Date dateFinAffectation;

	public AffectationEtabStrAgentComptable() {
	}

	public AffectationEtabStrAgentComptable(Integer id, AgentComptable agentComptable,
			RefEtablissement refEtablissement, Date dateAffectation, String decisionAffectation) {
		this.id = id;
		this.agentComptable = agentComptable;
		this.refEtablissement = refEtablissement;
		this.dateAffectation = dateAffectation;
		this.decisionAffectation = decisionAffectation;
	}

	public AffectationEtabStrAgentComptable(Integer id, RefStructure refStructure, AgentComptable agentComptable,
			RefEtablissement refEtablissement, Date dateAffectation, String observation, String decisionAffectation,
			Date dateFinAffectation) {
		this.id = id;
		this.refStructure = refStructure;
		this.agentComptable = agentComptable;
		this.refEtablissement = refEtablissement;
		this.dateAffectation = dateAffectation;
		this.observation = observation;
		this.decisionAffectation = decisionAffectation;
		this.dateFinAffectation = dateFinAffectation;
	}

	@SequenceGenerator(name = "affectation_etab_str_agent_comptable_id_seq", sequenceName = "gfc.affectation_etab_str_agent_comptable_id_seq")
	@Id
	@GeneratedValue(generator = "affectation_etab_str_agent_comptable_id_seq")
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_structure")
	public RefStructure getRefStructure() {
		return this.refStructure;
	}

	public void setRefStructure(RefStructure refStructure) {
		this.refStructure = refStructure;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_agent_compatable", nullable = false)
	public AgentComptable getAgentComptable() {
		return this.agentComptable;
	}

	public void setAgentComptable(AgentComptable agentComptable) {
		this.agentComptable = agentComptable;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_etablissement", nullable = false)
	public RefEtablissement getRefEtablissement() {
		return this.refEtablissement;
	}

	public void setRefEtablissement(RefEtablissement refEtablissement) {
		this.refEtablissement = refEtablissement;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_affectation", nullable = false, length = 29)
	public Date getDateAffectation() {
		return this.dateAffectation;
	}

	public void setDateAffectation(Date dateAffectation) {
		this.dateAffectation = dateAffectation;
	}

	@Column(name = "observation", length = 200)
	public String getObservation() {
		return this.observation;
	}

	public void setObservation(String observation) {
		this.observation = observation;
	}

	@Column(name = "decision_affectation", nullable = false, length = 50)
	public String getDecisionAffectation() {
		return this.decisionAffectation;
	}

	public void setDecisionAffectation(String decisionAffectation) {
		this.decisionAffectation = decisionAffectation;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_fin_affectation", length = 29)
	public Date getDateFinAffectation() {
		return this.dateFinAffectation;
	}

	public void setDateFinAffectation(Date dateFinAffectation) {
		this.dateFinAffectation = dateFinAffectation;
	}

	@Transient
	@Override
	public Integer getIdenfiant() {
		return id;
	}

	@Transient
	@Override
	public String getIdentifiantName() {
		return "id";
	}

}
