package dz.gov.mesrs.sii.commons.data.model.gfc;

// Generated 25 nov. 2014 09:31:22 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;

import dz.gov.mesrs.sii.commons.data.model.Identifiable;

/**
 * AffectationRegieChapitreArticle generated by hbm2java
 */
@Entity
@Table(name = "affectation_regie_chapitre_article", schema = "gfc", uniqueConstraints = @UniqueConstraint(columnNames = {
		"id_regie", "id_affectation_etab_chapitre_article" }))
public class AffectationRegieChapitreArticle implements java.io.Serializable, Identifiable<Integer> {

	/**
	 * @author Mounir.MESSAOUDI on : 25 nov. 2014 09:30:19
	 */
	private static final long serialVersionUID = 1L;

	private Integer id;
	private AffectationEtabChapitreArticle affectationEtabChapitreArticle;
	private Regie regie;
	private double plafond;
	
	public AffectationRegieChapitreArticle() {
	}

	public AffectationRegieChapitreArticle(Integer id, AffectationEtabChapitreArticle affectationEtabChapitreArticle,
			Regie regie) {
		this.id = id;
		this.affectationEtabChapitreArticle = affectationEtabChapitreArticle;
		this.regie = regie;
	}

	@SequenceGenerator(name = "affectation_regie_chapitre_article_id_seq", sequenceName = "gfc.affectation_regie_chapitre_article_id_seq")
	@Id
	@GeneratedValue(generator = "affectation_regie_chapitre_article_id_seq")
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_affectation_etab_chapitre_article", nullable = false)
	public AffectationEtabChapitreArticle getAffectationEtabChapitreArticle() {
		return this.affectationEtabChapitreArticle;
	}

	public void setAffectationEtabChapitreArticle(AffectationEtabChapitreArticle affectationEtabChapitreArticle) {
		this.affectationEtabChapitreArticle = affectationEtabChapitreArticle;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_regie", nullable = false)
	public Regie getRegie() {
		return this.regie;
	}

	public void setRegie(Regie regie) {
		this.regie = regie;
	}

	@Transient
	@Override
	public Integer getIdenfiant() {
		return id;
	}

	@Transient
	@Override
	public String getIdentifiantName() {
		return "id";
	}

	/**
	 * @return the plafond
	 */

	@Column(name = "plafond", precision = 10)
	public double getPlafond() {
		return plafond;
	}

	/**
	 * @param plafond the plafond to set
	 */
	public void setPlafond(double plafond) {
		this.plafond = plafond;
	}

}
