package dz.gov.mesrs.sii.commons.data.model.gfc;

// Generated 24 nov. 2014 16:52:54 by Hibernate Tools 3.6.0

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;

import dz.gov.mesrs.sii.commons.data.model.Identifiable;
import dz.gov.mesrs.sii.commons.data.model.referentiel.RefEtablissement;

/**
 * AffectationEtabChapitreArticle generated by hbm2java
 */
@Entity
@Table(name = "affectation_etab_chapitre_article", schema = "gfc")
public class AffectationEtabChapitreArticle implements java.io.Serializable, Identifiable<Integer> {

	/**
	 * @author Mounir.MESSAOUDI on : 24 nov. 2014 17:31:32
	 */
	private static final long serialVersionUID = 1L;

	private Integer id;
	private Chapitre chapitre;
	private RefEtablissement refEtablissement;
	private Article article;
	private BigDecimal montantPlafond;
	private String observation;
	private List<Fonds> fondses = new ArrayList<Fonds>(0);
	private List<Regie> regies = new ArrayList<Regie>(0);

	public AffectationEtabChapitreArticle() {
	}

	public AffectationEtabChapitreArticle(Integer id, Chapitre chapitre, RefEtablissement refEtablissement) {
		this.id = id;
		this.chapitre = chapitre;
		this.refEtablissement = refEtablissement;
	}

	public AffectationEtabChapitreArticle(Integer id, Chapitre chapitre, RefEtablissement refEtablissement,
			Article article, BigDecimal montantPlafond, String observation, List<Fonds> fondses, List<Regie> regies) {
		this.id = id;
		this.chapitre = chapitre;
		this.refEtablissement = refEtablissement;
		this.article = article;
		this.montantPlafond = montantPlafond;
		this.observation = observation;
		this.fondses = fondses;
		this.regies = regies;
	}

	@SequenceGenerator(name = "affectation_etab_chapitre_article_id_seq", sequenceName = "gfc.affectation_etab_chapitre_article_id_seq")
	@Id
	@GeneratedValue(generator = "affectation_etab_chapitre_article_id_seq")
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_chapitre", nullable = false)
	public Chapitre getChapitre() {
		return this.chapitre;
	}

	public void setChapitre(Chapitre chapitre) {
		this.chapitre = chapitre;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_etablissement", nullable = false)
	public RefEtablissement getRefEtablissement() {
		return this.refEtablissement;
	}

	public void setRefEtablissement(RefEtablissement refEtablissement) {
		this.refEtablissement = refEtablissement;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_article", nullable = true)
	public Article getArticle() {
		return this.article;
	}

	public void setArticle(Article article) {
		this.article = article;
	}

	@Column(name = "montant_plafond", precision = 10)
	public BigDecimal getMontantPlafond() {
		return this.montantPlafond;
	}

	public void setMontantPlafond(BigDecimal montantPlafond) {
		this.montantPlafond = montantPlafond;
	}

	@Column(name = "observation", length = 200)
	public String getObservation() {
		return this.observation;
	}

	public void setObservation(String observation) {
		this.observation = observation;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "affectation_fonds_chapitre_article", schema = "gfc", joinColumns = { @JoinColumn(name = "id_affectation_etab_chapitre_article", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "id_fonds", nullable = false, updatable = false) })
	public List<Fonds> getFondses() {
		return this.fondses;
	}

	public void setFondses(List<Fonds> fondses) {
		this.fondses = fondses;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "affectation_regie_chapitre_article", schema = "gfc", joinColumns = { @JoinColumn(name = "id_affectation_etab_chapitre_article", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "id_regie", nullable = false, updatable = false) })
	public List<Regie> getRegies() {
		return this.regies;
	}

	public void setRegies(List<Regie> regies) {
		this.regies = regies;
	}

	@Transient
	@Override
	public Integer getIdenfiant() {
		return id;
	}

	@Transient
	@Override
	public String getIdentifiantName() {
		return "id";
	}

}
