package dz.gov.mesrs.sii.commons.data.model.gfc;

// Generated 24 nov. 2014 16:52:54 by Hibernate Tools 3.6.0

import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;

import dz.gov.mesrs.sii.commons.data.model.Identifiable;

/**
 * Chapitre generated by hbm2java
 */
@Entity
@Table(name = "chapitre", schema = "gfc")
public class Chapitre implements java.io.Serializable, Identifiable<Integer> {

	/**
	 * @author Mounir.MESSAOUDI on : 24 nov. 2014 17:32:03
	 */
	private static final long serialVersionUID = 1L;

	private Integer id;
	private Partie partie;
	private Titre titre;
	private Section idSection;
	private SousSection idSousSection;
	private String code;
	private String intituleFr;
	private String intituleAr;
	private String description;
	private String intituleFrCourt;
	private String intituleArCourt;
	private Boolean recetteType;

	private List<Article> articles = new ArrayList<Article>(0);

	List<AffectationEtabChapitreArticle> affectationsEtabChapitreArticle = new ArrayList<AffectationEtabChapitreArticle>();

	public Chapitre() {
	}

	public Chapitre(Integer id, Section idSection, String code, String intituleFr, String intituleAr) {
		this.id = id;
		this.idSection = idSection;
		this.code = code;
		this.intituleFr = intituleFr;
		this.intituleAr = intituleAr;
	}

	public Chapitre(Integer id, Partie partie, Titre titre, Section idSection, SousSection idSousSection, String code,
			String intituleFrCourt, String intituleArCourt, String intituleFr, String intituleAr, String description,
			List<Article> articles) {
		this.id = id;
		this.partie = partie;
		this.titre = titre;
		this.idSection = idSection;
		this.idSousSection = idSousSection;
		this.code = code;
		this.intituleFr = intituleFr;
		this.intituleAr = intituleAr;
		this.description = description;
		this.intituleFrCourt = intituleFrCourt;
		this.intituleArCourt = intituleArCourt;
		this.articles = articles;

	}

	@SequenceGenerator(name = "chapitre_id_seq", sequenceName = "gfc.chapitre_id_seq")
	@Id
	@GeneratedValue(generator = "chapitre_id_seq")
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_partie")
	public Partie getPartie() {
		return this.partie;
	}

	public void setPartie(Partie partie) {
		this.partie = partie;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_titre")
	public Titre getTitre() {
		return this.titre;
	}

	public void setTitre(Titre titre) {
		this.titre = titre;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_section", nullable = false)
	public Section getIdSection() {
		return this.idSection;
	}

	public void setIdSection(Section idSection) {
		this.idSection = idSection;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_sous_section")
	public SousSection getIdSousSection() {
		return this.idSousSection;
	}

	public void setIdSousSection(SousSection idSousSection) {
		this.idSousSection = idSousSection;
	}

	@Column(name = "code", nullable = false, length = 10)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "intitule_fr", nullable = false, length = 200)
	public String getIntituleFr() {
		return this.intituleFr;
	}

	public void setIntituleFr(String intituleFr) {
		this.intituleFr = intituleFr;
	}

	@Column(name = "intitule_ar", nullable = false, length = 200)
	public String getIntituleAr() {
		return this.intituleAr;
	}

	public void setIntituleAr(String intituleAr) {
		this.intituleAr = intituleAr;
	}

	@Column(name = "description", length = 200)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "chapitre")
	public List<Article> getArticles() {
		return this.articles;
	}

	public void setArticles(List<Article> articles) {
		this.articles = articles;
	}

	@Transient
	@Override
	public Integer getIdenfiant() {
		return id;
	}

	@Transient
	@Override
	public String getIdentifiantName() {
		return "id";
	}

	@OneToMany(targetEntity = AffectationEtabChapitreArticle.class, mappedBy = "chapitre", cascade = { CascadeType.ALL })
	public List<AffectationEtabChapitreArticle> getAffectationsEtabChapitreArticle() {
		return affectationsEtabChapitreArticle;
	}

	public void setAffectationsEtabChapitreArticle(List<AffectationEtabChapitreArticle> affectationsEtabChapitreArticle) {
		this.affectationsEtabChapitreArticle = affectationsEtabChapitreArticle;
	}

	/**
	 * @return the intituleFrCourt
	 */

	@Column(name = "intitule_fr_court", length = 200)
	public String getIntituleFrCourt() {
		return intituleFrCourt;
	}

	/**
	 * @param intituleFrCourt
	 *            the intituleFrCourt to set
	 */
	public void setIntituleFrCourt(String intituleFrCourt) {
		this.intituleFrCourt = intituleFrCourt;
	}

	/**
	 * @return the intituleArCourt
	 */

	@Column(name = "intitule_ar_court", length = 200)
	public String getIntituleArCourt() {
		return intituleArCourt;
	}

	/**
	 * @param intituleArCourt
	 *            the intituleArCourt to set
	 */
	public void setIntituleArCourt(String intituleArCourt) {
		this.intituleArCourt = intituleArCourt;
	}

	public Boolean isRecetteType() {
		return recetteType;
	}

	/**
	 * @return the recetteType
	 */
	@Column(name = "recette_type")
	public Boolean getRecetteType() {
		return recetteType;
	}

	/**
	 * @param recetteType
	 *            the recetteType to set
	 */
	public void setRecetteType(Boolean recetteType) {
		this.recetteType = recetteType;
	}

}
