package dz.gov.mesrs.sii.commons.data.model.gfc;

// Generated 24 nov. 2014 16:52:54 by Hibernate Tools 3.6.0

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import dz.gov.mesrs.sii.commons.data.model.Identifiable;
import dz.gov.mesrs.sii.commons.data.model.bpm.SituationEntite;
import dz.gov.mesrs.sii.commons.data.model.referentiel.Nomenclature;

/**
 * Compte generated by hbm2java
 */
@Entity
@Table(name = "compte", schema = "gfc")
public class Compte implements java.io.Serializable, Identifiable<Integer> {

	/**
	 * @author Mounir.MESSAOUDI on : 24 nov. 2014 17:32:10
	 */
	private static final long serialVersionUID = 1L;

	private Integer id;
	private AgentComptable agentComptable;
	private Nomenclature type;
	private SituationEntite situation;
	private String numero;
	private String intituleFr;
	private String intituleAr;
	private Date dateOuverture;
	private Date dateCloture;
	private Date dateCreation;
	private Date dateModification;
	private String observation;
	private List<Regie> regiesForIdCompteCcp = new ArrayList<Regie>(0);
	private List<Regie> regiesForIdCompteDepot = new ArrayList<Regie>(0);

	public Compte() {
	}

	public Compte(Integer id, Nomenclature type, SituationEntite situation, String numero, String intituleFr,
			String intituleAr, Date dateOuverture) {
		this.id = id;
		this.type = type;
		this.situation = situation;
		this.numero = numero;
		this.intituleFr = intituleFr;
		this.intituleAr = intituleAr;
		this.dateOuverture = dateOuverture;
	}

	public Compte(Integer id, AgentComptable agentComptable, Nomenclature type, SituationEntite situation,
			String numero, String intituleFr, String intituleAr, Date dateOuverture, Date dateCloture,
			Date dateCreation, Date dateModification, String observation, List<Regie> regiesForIdCompteCcp,
			List<Regie> regiesForIdCompteDepot) {
		this.id = id;
		this.agentComptable = agentComptable;
		this.type = type;
		this.situation = situation;
		this.numero = numero;
		this.intituleFr = intituleFr;
		this.intituleAr = intituleAr;
		this.dateOuverture = dateOuverture;
		this.dateCloture = dateCloture;
		this.dateCreation = dateCreation;
		this.dateModification = dateModification;
		this.observation = observation;
		this.regiesForIdCompteCcp = regiesForIdCompteCcp;
		this.regiesForIdCompteDepot = regiesForIdCompteDepot;
	}

	@SequenceGenerator(name = "compte_id_seq", sequenceName = "gfc.compte_id_seq")
	@Id
	@GeneratedValue(generator = "compte_id_seq")
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_agent_comptable")
	public AgentComptable getAgentComptable() {
		return this.agentComptable;
	}

	public void setAgentComptable(AgentComptable agentComptable) {
		this.agentComptable = agentComptable;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_type_compte", nullable = false)
	public Nomenclature getType() {
		return this.type;
	}

	public void setType(Nomenclature type) {
		this.type = type;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_situation", nullable = false)
	public SituationEntite getSituation() {
		return this.situation;
	}

	public void setSituation(SituationEntite situation) {
		this.situation = situation;
	}

	@Column(name = "numero", nullable = false, length = 50)
	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	@Column(name = "intitule_fr", nullable = false, length = 200)
	public String getIntituleFr() {
		return this.intituleFr;
	}

	public void setIntituleFr(String intituleFr) {
		this.intituleFr = intituleFr;
	}

	@Column(name = "intitule_ar", nullable = false, length = 200)
	public String getIntituleAr() {
		return this.intituleAr;
	}

	public void setIntituleAr(String intituleAr) {
		this.intituleAr = intituleAr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_ouverture", nullable = false, length = 29)
	public Date getDateOuverture() {
		return this.dateOuverture;
	}

	public void setDateOuverture(Date dateOuverture) {
		this.dateOuverture = dateOuverture;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_cloture", length = 29)
	public Date getDateCloture() {
		return this.dateCloture;
	}

	public void setDateCloture(Date dateCloture) {
		this.dateCloture = dateCloture;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_creation", length = 29)
	public Date getDateCreation() {
		return this.dateCreation;
	}

	public void setDateCreation(Date dateCreation) {
		this.dateCreation = dateCreation;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_modification", length = 29)
	public Date getDateModification() {
		return this.dateModification;
	}

	public void setDateModification(Date dateModification) {
		this.dateModification = dateModification;
	}

	@Column(name = "observation", length = 200)
	public String getObservation() {
		return this.observation;
	}

	public void setObservation(String observation) {
		this.observation = observation;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "compteCcp")
	public List<Regie> getRegiesForIdCompteCcp() {
		return this.regiesForIdCompteCcp;
	}

	public void setRegiesForIdCompteCcp(List<Regie> regiesForIdCompteCcp) {
		this.regiesForIdCompteCcp = regiesForIdCompteCcp;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "compteDepot")
	public List<Regie> getRegiesForIdCompteDepot() {
		return this.regiesForIdCompteDepot;
	}

	public void setRegiesForIdCompteDepot(List<Regie> regiesForIdCompteDepot) {
		this.regiesForIdCompteDepot = regiesForIdCompteDepot;
	}

	@Transient
	@Override
	public Integer getIdenfiant() {
		return id;
	}

	@Transient
	@Override
	public String getIdentifiantName() {
		return "id";
	}

}
