package dz.gov.mesrs.sii.commons.data.model.gfc;

// Generated 24 nov. 2014 16:52:54 by Hibernate Tools 3.6.0

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import dz.gov.mesrs.sii.commons.data.model.Identifiable;
import dz.gov.mesrs.sii.commons.data.model.bpm.SituationEntite;
import dz.gov.mesrs.sii.commons.data.model.referentiel.Nomenclature;
import dz.gov.mesrs.sii.commons.data.model.referentiel.RefEtablissement;

/**
 * DecisionBudget generated by hbm2java
 */
@Entity
@Table(name = "decision_budget", schema = "gfc")
public class DecisionBudget implements java.io.Serializable, Identifiable<Integer> {

	/**
	 * @author Mounir.MESSAOUDI on : 24 nov. 2014 17:32:22
	 */
	private static final long serialVersionUID = 1L;

	private Integer id;
	private ProjetBudget projetBudget;
	private RefEtablissement etablissement;
	private Nomenclature uniteMonetaire;
	private SituationEntite situation;
	private String reference;
	private Date dateDecision;
	private String intituleFr;
	private String intituleAr;
	private BigDecimal montant;
	private Date dateSiganture;
	private String observation;
	private List<DetailsNotificationDecisionBudget> detailsNotificationDecisionBudgets = new ArrayList<DetailsNotificationDecisionBudget>(
			0);
	private List<RepartitionBudget> repartitionBudgets = new ArrayList<RepartitionBudget>(0);
	
	public DecisionBudget() {
	}

	public DecisionBudget(Integer id, ProjetBudget projetBudget, RefEtablissement etablissement,
			Nomenclature nomenclature, SituationEntite situationEntite, String reference, Date dateDecision,
			String intituleFr, BigDecimal montant) {
		this.id = id;
		this.projetBudget = projetBudget;
		this.etablissement = etablissement;
		this.uniteMonetaire = nomenclature;
		this.situation = situationEntite;
		this.reference = reference;
		this.dateDecision = dateDecision;
		this.intituleFr = intituleFr;
		this.montant = montant;
	}

	public DecisionBudget(Integer id, ProjetBudget projetBudget, RefEtablissement etablissement,
			Nomenclature nomenclature, SituationEntite situationEntite, String reference, Date dateDecision,
			String intituleFr, String intituleAr, BigDecimal montant, Date dateSiganture, String observation,
			List<DetailsNotificationDecisionBudget> detailsNotificationDecisionBudgets,
			List<RepartitionBudget> repartitionBudgets) {
		this.id = id;
		this.projetBudget = projetBudget;
		this.etablissement = etablissement;
		this.uniteMonetaire = nomenclature;
		this.situation = situationEntite;
		this.reference = reference;
		this.dateDecision = dateDecision;
		this.intituleFr = intituleFr;
		this.intituleAr = intituleAr;
		this.montant = montant;
		this.dateSiganture = dateSiganture;
		this.observation = observation;
		this.detailsNotificationDecisionBudgets = detailsNotificationDecisionBudgets;
		this.repartitionBudgets = repartitionBudgets;
		
	}

	@SequenceGenerator(name = "decision_budget_id_seq", sequenceName = "gfc.decision_budget_id_seq")
	@Id
	@GeneratedValue(generator = "decision_budget_id_seq")
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_projet_budget", nullable = false)
	public ProjetBudget getProjetBudget() {
		return this.projetBudget;
	}

	public void setProjetBudget(ProjetBudget projetBudget) {
		this.projetBudget = projetBudget;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_etablissement", nullable = false)
	public RefEtablissement getEtablissement() {
		return this.etablissement;
	}

	public void setEtablissement(RefEtablissement etablissement) {
		this.etablissement = etablissement;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_unite_monetaire", nullable = false)
	public Nomenclature getUniteMonetaire() {
		return this.uniteMonetaire;
	}

	public void setUniteMonetaire(Nomenclature uniteMonetaire) {
		this.uniteMonetaire = uniteMonetaire;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_situation", nullable = false)
	public SituationEntite getSituation() {
		return this.situation;
	}

	public void setSituation(SituationEntite situation) {
		this.situation = situation;
	}

	@Column(name = "reference", nullable = false, length = 50)
	public String getReference() {
		return this.reference;
	}

	public void setReference(String reference) {
		this.reference = reference;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_decision", nullable = false, length = 29)
	public Date getDateDecision() {
		return this.dateDecision;
	}

	public void setDateDecision(Date dateDecision) {
		this.dateDecision = dateDecision;
	}

	@Column(name = "intitule_fr", nullable = false, length = 200)
	public String getIntituleFr() {
		return this.intituleFr;
	}

	public void setIntituleFr(String intituleFr) {
		this.intituleFr = intituleFr;
	}

	@Column(name = "intitule_ar", length = 200)
	public String getIntituleAr() {
		return this.intituleAr;
	}

	public void setIntituleAr(String intituleAr) {
		this.intituleAr = intituleAr;
	}

	@Column(name = "montant", nullable = false, precision = 10)
	public BigDecimal getMontant() {
		return this.montant;
	}

	public void setMontant(BigDecimal montant) {
		this.montant = montant;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_siganture", length = 29)
	public Date getDateSiganture() {
		return this.dateSiganture;
	}

	public void setDateSiganture(Date dateSiganture) {
		this.dateSiganture = dateSiganture;
	}

	@Column(name = "observation", length = 200)
	public String getObservation() {
		return this.observation;
	}

	public void setObservation(String observation) {
		this.observation = observation;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "decisionBudget")
	public List<DetailsNotificationDecisionBudget> getDetailsNotificationDecisionBudgets() {
		return this.detailsNotificationDecisionBudgets;
	}

	public void setDetailsNotificationDecisionBudgets(
			List<DetailsNotificationDecisionBudget> detailsNotificationDecisionBudgets) {
		this.detailsNotificationDecisionBudgets = detailsNotificationDecisionBudgets;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "decisionBudget")
	public List<RepartitionBudget> getRepartitionBudgets() {
		return this.repartitionBudgets;
	}

	public void setRepartitionBudgets(List<RepartitionBudget> repartitionBudgets) {
		this.repartitionBudgets = repartitionBudgets;
	}


	@Transient
	@Override
	public Integer getIdenfiant() {
		return id;
	}

	@Transient
	@Override
	public String getIdentifiantName() {
		return "id";
	}

}
