package dz.gov.mesrs.sii.commons.data.model.gfc;

// Generated 24 nov. 2014 16:52:54 by Hibernate Tools 3.6.0

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;

import dz.gov.mesrs.sii.commons.data.model.Identifiable;

/**
 * DetailsMouvementBudget generated by hbm2java
 */
@Entity
@Table(name = "details_mouvement_budget", schema = "gfc")
public class DetailsMouvementBudget implements java.io.Serializable, Identifiable<Integer> {

	/**
	 * @author Mounir.MESSAOUDI on : 24 nov. 2014 17:32:33
	 */
	private static final long serialVersionUID = 1L;

	private Integer id;
	private DetailsReparatitionBudget detailsRepartitionBudgetCible;
	private DetailsReparatitionBudget detailsRepartitionBudgetSource;
	private MouvementBudget mouvementBudget;
	private BigDecimal montant;
	private String observation;

	public DetailsMouvementBudget() {
	}

	public DetailsMouvementBudget(Integer id,
			DetailsReparatitionBudget detailsRepartitionBudgetSource,
			MouvementBudget mouvementBudget, BigDecimal montant) {
		this.id = id;
		this.detailsRepartitionBudgetSource = detailsRepartitionBudgetSource;
		this.mouvementBudget = mouvementBudget;
		this.montant = montant;
	}

	public DetailsMouvementBudget(Integer id,
			DetailsReparatitionBudget detailsRepartitionBudgetCible,
			DetailsReparatitionBudget detailsRepartitionBudgetSource,
			MouvementBudget mouvementBudget, BigDecimal montant, String observation) {
		this.id = id;
		this.detailsRepartitionBudgetCible = detailsRepartitionBudgetCible;
		this.detailsRepartitionBudgetSource = detailsRepartitionBudgetSource;
		this.mouvementBudget = mouvementBudget;
		this.montant = montant;
		this.observation = observation;
	}

	@SequenceGenerator(name = "details_mouvement_budget_id_seq", sequenceName = "gfc.details_mouvement_budget_id_seq")
	@Id
	@GeneratedValue(generator = "details_mouvement_budget_id_seq")
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_details_repartition_budget_cible")
	public DetailsReparatitionBudget getDetailsRepartitionBudgetCible() {
		return this.detailsRepartitionBudgetCible;
	}

	public void setDetailsRepartitionBudgetCible(
			DetailsReparatitionBudget detailsRepartitionBudgetCible) {
		this.detailsRepartitionBudgetCible = detailsRepartitionBudgetCible;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_details_repartition_budget_source", nullable = false)
	public DetailsReparatitionBudget getDetailsRepartitionBudgetSource() {
		return this.detailsRepartitionBudgetSource;
	}

	public void setDetailsRepartitionBudgetSource(
			DetailsReparatitionBudget detailsRepartitionBudgetSource) {
		this.detailsRepartitionBudgetSource = detailsRepartitionBudgetSource;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_mouvement_budget", nullable = false)
	public MouvementBudget getMouvementBudget() {
		return this.mouvementBudget;
	}

	public void setMouvementBudget(MouvementBudget mouvementBudget) {
		this.mouvementBudget = mouvementBudget;
	}

	@Column(name = "montant", nullable = false, precision = 10)
	public BigDecimal getMontant() {
		return this.montant;
	}

	public void setMontant(BigDecimal montant) {
		this.montant = montant;
	}

	@Column(name = "observation", length = 100)
	public String getObservation() {
		return this.observation;
	}

	public void setObservation(String observation) {
		this.observation = observation;
	}

	@Transient
	@Override
	public Integer getIdenfiant() {
		return id;
	}

	@Transient
	@Override
	public String getIdentifiantName() {
		return "id";
	}

}
