package dz.gov.mesrs.sii.commons.data.model.gfc;

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;

import dz.gov.mesrs.sii.commons.data.model.Identifiable;
import dz.gov.mesrs.sii.commons.data.model.bpm.SituationEntite;
import dz.gov.mesrs.sii.commons.data.model.referentiel.RefStructure;

/**
 * DetailEngagementMarche generated by hbm2java
 */
@Entity
@Table(name = "detail_engagement_marche", schema = "gfc")
public class DetailEngagementMarche implements java.io.Serializable, Identifiable<Integer> {

	private static final long serialVersionUID = 1L;

	private Integer id;
	private Article article;
	private Chapitre chapitre;
	private RefStructure structure;
	private EngagementMarche engagementMarche;
	private BigDecimal montant;
	private String observation;
	private SituationEntite situation;

	public DetailEngagementMarche() {
	}

	public DetailEngagementMarche(Integer id, Article article, Chapitre chapitre, EngagementMarche engagementMarche,
			BigDecimal montant) {
		this.id = id;
		this.article = article;
		this.chapitre = chapitre;
		this.engagementMarche = engagementMarche;
		this.montant = montant;
	}

	public DetailEngagementMarche(Integer id, Article article, Chapitre chapitre, EngagementMarche engagementMarche,
			BigDecimal montant, String observation) {
		this.id = id;
		this.article = article;
		this.chapitre = chapitre;
		this.engagementMarche = engagementMarche;
		this.montant = montant;
		this.observation = observation;
	}

	@SequenceGenerator(name = "detail_engagement_marche_id_seq", sequenceName = "gfc.detail_engagement_marche_id_seq")
	@Id
	@GeneratedValue(generator = "detail_engagement_marche_id_seq")
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_article", nullable = false)
	public Article getArticle() {
		return this.article;
	}

	public void setArticle(Article article) {
		this.article = article;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_chapitre", nullable = false)
	public Chapitre getChapitre() {
		return this.chapitre;
	}

	public void setChapitre(Chapitre chapitre) {
		this.chapitre = chapitre;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_demande_engagement", nullable = false)
	public EngagementMarche getEngagementMarche() {
		return this.engagementMarche;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_structure", nullable = false)
	public RefStructure getStructure() {
		return structure;
	}

	public void setStructure(RefStructure structure) {
		this.structure = structure;
	}

	public void setEngagementMarche(EngagementMarche engagementMarche) {
		this.engagementMarche = engagementMarche;
	}

	@Column(name = "montant", nullable = false, precision = 10)
	public BigDecimal getMontant() {
		return this.montant;
	}

	public void setMontant(BigDecimal montant) {
		this.montant = montant;
	}

	@Column(name = "observation", length = 200)
	public String getObservation() {
		return this.observation;
	}

	public void setObservation(String observation) {
		this.observation = observation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_situation", nullable = false)
	public SituationEntite getSituation() {
		return this.situation;
	}

	public void setSituation(SituationEntite situation) {
		this.situation = situation;
	}

	@Transient
	@Override
	public Integer getIdenfiant() {
		return id;
	}

	@Transient
	@Override
	public String getIdentifiantName() {
		return "id";
	}
}