package dz.gov.mesrs.sii.commons.data.model.gfc;

// Generated 24 nov. 2014 16:52:54 by Hibernate Tools 3.6.0

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;

import dz.gov.mesrs.sii.commons.data.model.Identifiable;

/**
 * DetailsReparatitionBudget generated by hbm2java
 */
@Entity
@Table(name = "details_reparatition_budget", schema = "gfc")
public class DetailsReparatitionBudget implements java.io.Serializable, Identifiable<Integer> {

	/**
	 * @author Mounir.MESSAOUDI on : 24 nov. 2014 17:32:54
	 */
	private static final long serialVersionUID = 1L;

	private Integer id;
	private DetailsNotificationDecisionBudget detailsNotificationDecisionBudget;
	private Chapitre chapitre;
	private RepartitionBudget repartitionBudget;
	private Article article;
	private BigDecimal montant;
	private String observation;
	private List<DetailsMouvementBudget> detailsRepartitionBudgetCible = new ArrayList<DetailsMouvementBudget>(
			0);
	private List<DetailsMouvementBudget> detailsRepartitionBudgetSource = new ArrayList<DetailsMouvementBudget>(
			0);

	public DetailsReparatitionBudget() {
	}

	public DetailsReparatitionBudget(Integer id, Chapitre chapitre) {
		this.id = id;
		this.chapitre = chapitre;
	}

	@SequenceGenerator(name = "details_reparatition_budget_id_seq", sequenceName = "gfc.details_reparatition_budget_id_seq")
	@Id
	@GeneratedValue(generator = "details_reparatition_budget_id_seq")
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_details_notification_decision_budget")
	public DetailsNotificationDecisionBudget getDetailsNotificationDecisionBudget() {
		return this.detailsNotificationDecisionBudget;
	}

	public void setDetailsNotificationDecisionBudget(DetailsNotificationDecisionBudget detailsNotificationDecisionBudget) {
		this.detailsNotificationDecisionBudget = detailsNotificationDecisionBudget;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_chapitre", nullable = false)
	public Chapitre getChapitre() {
		return this.chapitre;
	}

	public void setChapitre(Chapitre chapitre) {
		this.chapitre = chapitre;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_repartition_budget")
	public RepartitionBudget getRepartitionBudget() {
		return this.repartitionBudget;
	}

	public void setRepartitionBudget(RepartitionBudget repartitionBudget) {
		this.repartitionBudget = repartitionBudget;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_article")
	public Article getArticle() {
		return this.article;
	}

	public void setArticle(Article article) {
		this.article = article;
	}

	@Column(name = "montant", precision = 10)
	public BigDecimal getMontant() {
		return this.montant;
	}

	public void setMontant(BigDecimal montant) {
		this.montant = montant;
	}

	@Column(name = "observation", length = 100)
	public String getObservation() {
		return this.observation;
	}

	public void setObservation(String observation) {
		this.observation = observation;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "detailsRepartitionBudgetCible")
	public List<DetailsMouvementBudget> getDetailsRepartitionBudgetCible() {
		return this.detailsRepartitionBudgetCible;
	}

	public void setDetailsRepartitionBudgetCible(
			List<DetailsMouvementBudget> detailsRepartitionBudgetCible) {
		this.detailsRepartitionBudgetCible = detailsRepartitionBudgetCible;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "detailsRepartitionBudgetSource")
	public List<DetailsMouvementBudget> getDetailsRepartitionBudgetSource() {
		return this.detailsRepartitionBudgetSource;
	}

	public void setDetailsRepartitionBudgetSource(
			List<DetailsMouvementBudget> detailsRepartitionBudgetSource) {
		this.detailsRepartitionBudgetSource = detailsRepartitionBudgetSource;
	}

	@Transient
	@Override
	public Integer getIdenfiant() {
		// TODO Auto-generated method stub
		return id;
	}

	@Transient
	@Override
	public String getIdentifiantName() {
		// TODO Auto-generated method stub
		return "id";
	}

}
