package dz.gov.mesrs.sii.commons.data.model.gfc;

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;

import dz.gov.mesrs.sii.commons.data.model.Identifiable;

/**
 * DetailRealisationPrestation generated by hbm2java
 */
@Entity
@Table(name = "detail_realisation_prestation", schema = "gfc")
public class DetailRealisationPrestation implements java.io.Serializable, Identifiable<Integer> {

	private static final long serialVersionUID = 1L;

	private Integer id;
	private DocumentRealisationMarche documentRealisationMarche;
	private PrestationMarche prestationMarche;
	private Integer quantite;
	private BigDecimal montantRealise;
	private String observation;

	public DetailRealisationPrestation() {
	}

	public DetailRealisationPrestation(Integer id, DocumentRealisationMarche documentRealisationMarche,
			PrestationMarche prestationMarche, Integer quantite, BigDecimal montantRealise) {
		this.id = id;
		this.documentRealisationMarche = documentRealisationMarche;
		this.prestationMarche = prestationMarche;
		this.quantite = quantite;
		this.montantRealise = montantRealise;
	}

	public DetailRealisationPrestation(Integer id, DocumentRealisationMarche documentRealisationMarche,
			PrestationMarche prestationMarche, Integer quantite, BigDecimal montantRealise, String observation) {
		this.id = id;
		this.documentRealisationMarche = documentRealisationMarche;
		this.prestationMarche = prestationMarche;
		this.quantite = quantite;
		this.montantRealise = montantRealise;
		this.observation = observation;
	}

	@SequenceGenerator(name = "detail_realisation_prestation_id_seq", sequenceName = "gfc.detail_realisation_prestation_id_seq")
	@Id
	@GeneratedValue(generator = "detail_realisation_prestation_id_seq")
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_document_realisation", nullable = false)
	public DocumentRealisationMarche getDocumentRealisationMarche() {
		return this.documentRealisationMarche;
	}

	public void setDocumentRealisationMarche(DocumentRealisationMarche documentRealisationMarche) {
		this.documentRealisationMarche = documentRealisationMarche;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_prestation_marche", nullable = false)
	public PrestationMarche getPrestationMarche() {
		return this.prestationMarche;
	}

	public void setPrestationMarche(PrestationMarche prestationMarche) {
		this.prestationMarche = prestationMarche;
	}

	@Column(name = "quantite", nullable = false)
	public Integer getQuantite() {
		return this.quantite;
	}

	public void setQuantite(Integer quantite) {
		this.quantite = quantite;
	}

	@Column(name = "montant_realise", nullable = false, precision = 10)
	public BigDecimal getMontantRealise() {
		return this.montantRealise;
	}

	public void setMontantRealise(BigDecimal montantRealise) {
		this.montantRealise = montantRealise;
	}

	@Column(name = "observation", length = 200)
	public String getObservation() {
		return this.observation;
	}

	public void setObservation(String observation) {
		this.observation = observation;
	}

	@Transient
	@Override
	public Integer getIdenfiant() {
		return id;
	}

	@Transient
	@Override
	public String getIdentifiantName() {
		return "id";
	}
}