package dz.gov.mesrs.sii.commons.data.model.gfc;

// Generated 24 nov. 2014 16:52:54 by Hibernate Tools 3.6.0

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;

import dz.gov.mesrs.sii.commons.data.model.Identifiable;
import dz.gov.mesrs.sii.commons.data.model.referentiel.RefEtablissement;

/**
 * DetailsProjetBudget generated by hbm2java
 */
@Entity
@Table(name = "details_projet_budget_etablissement", schema = "gfc")
public class DetailsProjetBudgetEtablissement implements java.io.Serializable, Identifiable<Integer> {

	/**
	 * @author Mounir.MESSAOUDI on : 24 nov. 2014 17:32:50
	 */
	private static final long serialVersionUID = 1L;

	private Integer id;
	private ProjetBudget projetBudget;
	private Chapitre chapitre;
	private Article article;

	private RefEtablissement etablissement;

	private BigDecimal montantBesoins;
	private BigDecimal montantFinal;
	private String description;

	public DetailsProjetBudgetEtablissement() {
	}

	@SequenceGenerator(name = "detail_projet_budget_etablissement_id_seq", sequenceName = "gfc.detail_projet_budget_etablissement_id_seq")
	@Id
	@GeneratedValue(generator = "detail_projet_budget_etablissement_id_seq")
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_projet_budget", nullable = false)
	public ProjetBudget getProjetBudget() {
		return this.projetBudget;
	}

	public void setProjetBudget(ProjetBudget projetBudget) {
		this.projetBudget = projetBudget;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_chapitre", nullable = false)
	public Chapitre getChapitre() {
		return this.chapitre;
	}

	public void setChapitre(Chapitre chapitre) {
		this.chapitre = chapitre;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_article")
	public Article getArticle() {
		return this.article;
	}

	public void setArticle(Article article) {
		this.article = article;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_etablissement", nullable = false)
	public RefEtablissement getEtablissement() {
		return this.etablissement;
	}

	public void setEtablissement(RefEtablissement etablissement) {
		this.etablissement = etablissement;
	}

	@Column(name = "montant_besoins", nullable = false, precision = 10)
	public BigDecimal getMontantBesoins() {
		return this.montantBesoins;
	}

	public void setMontantBesoins(BigDecimal montantBesoins) {
		this.montantBesoins = montantBesoins;
	}

	@Column(name = "montant_final", precision = 10)
	public BigDecimal getMontantFinal() {
		return this.montantFinal;
	}

	public void setMontantFinal(BigDecimal montantFinal) {
		this.montantFinal = montantFinal;
	}

	@Column(name = "description", length = 200)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Transient
	@Override
	public Integer getIdenfiant() {
		return id;
	}

	@Transient
	@Override
	public String getIdentifiantName() {
		return "id";
	}

}
