package dz.gov.mesrs.sii.commons.data.model.gfc;

// Generated 24 nov. 2014 16:52:54 by Hibernate Tools 3.6.0

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;

import dz.gov.mesrs.sii.commons.data.model.Identifiable;
import dz.gov.mesrs.sii.commons.data.model.referentiel.RefEtablissement;
import dz.gov.mesrs.sii.commons.data.model.referentiel.RefStructure;

/**
 * DetailsFicheBesoins generated by hbm2java
 */
@Entity
@Table(name = "details_fiche_besoins", schema = "gfc")
public class DetailsFicheBesoins implements java.io.Serializable, Identifiable<Integer> {

	/**
	 * @author Mounir.MESSAOUDI on : 24 nov. 2014 17:32:27
	 */
	private static final long serialVersionUID = 1L;

	private Integer id;
	private RefEtablissement etablissement;
	private RefStructure structure;

	private FicheBesoins ficheBesoins;

	private Chapitre chapitre;
	private Article article;
	private Paragraphe paragraphe;
	private BigDecimal montant;
	private String description;

	private boolean budgetRecette;

	public DetailsFicheBesoins() {
	}

	public DetailsFicheBesoins(Integer id, Chapitre chapitre, RefEtablissement etablissement,
			FicheBesoins ficheBesoins, boolean budgetRecette) {
		this.id = id;
		this.chapitre = chapitre;
		this.etablissement = etablissement;
		this.ficheBesoins = ficheBesoins;
		this.budgetRecette = budgetRecette;
	}

	public DetailsFicheBesoins(Integer id, Chapitre chapitre, RefStructure structure, Paragraphe paragraphe,
			RefEtablissement etablissement, FicheBesoins ficheBesoins, Article article, BigDecimal montant,
			String description, boolean budgetRecette) {
		this.id = id;
		this.chapitre = chapitre;
		this.structure = structure;
		this.paragraphe = paragraphe;
		this.etablissement = etablissement;
		this.ficheBesoins = ficheBesoins;
		this.article = article;
		this.montant = montant;
		this.description = description;
		this.budgetRecette = budgetRecette;
	}

	@SequenceGenerator(name = "details_fiche_besoins_id_seq", sequenceName = "gfc.details_fiche_besoins_id_seq")
	@Id
	@GeneratedValue(generator = "details_fiche_besoins_id_seq")
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_chapitre", nullable = false)
	public Chapitre getChapitre() {
		return this.chapitre;
	}

	public void setChapitre(Chapitre chapitre) {
		this.chapitre = chapitre;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_structure", nullable = false)
	public RefStructure getStructure() {
		return this.structure;
	}

	public void setStructure(RefStructure structure) {
		this.structure = structure;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_paragraphe")
	public Paragraphe getParagraphe() {
		return this.paragraphe;
	}

	public void setParagraphe(Paragraphe paragraphe) {
		this.paragraphe = paragraphe;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_etablissement", nullable = false)
	public RefEtablissement getEtablissement() {
		return this.etablissement;
	}

	public void setEtablissement(RefEtablissement etablissement) {
		this.etablissement = etablissement;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_fiche_besoins", nullable = false)
	public FicheBesoins getFicheBesoins() {
		return this.ficheBesoins;
	}

	public void setFicheBesoins(FicheBesoins ficheBesoins) {
		this.ficheBesoins = ficheBesoins;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_article")
	public Article getArticle() {
		return this.article;
	}

	public void setArticle(Article article) {
		this.article = article;
	}

	@Column(name = "montant", precision = 10)
	public BigDecimal getMontant() {
		return this.montant;
	}

	public void setMontant(BigDecimal montant) {
		this.montant = montant;
	}

	@Column(name = "description", length = 200)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "budget_recette", nullable = false)
	public boolean isBudgetRecette() {
		return this.budgetRecette;
	}

	public void setBudgetRecette(boolean budgetRecette) {
		this.budgetRecette = budgetRecette;
	}

	@Transient
	@Override
	public Integer getIdenfiant() {
		return id;
	}

	@Transient
	@Override
	public String getIdentifiantName() {
		return "id";
	}

}
