package dz.gov.mesrs.sii.commons.data.model.gfc;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import dz.gov.mesrs.sii.commons.data.model.Identifiable;
import dz.gov.mesrs.sii.commons.data.model.bpm.SituationEntite;
import dz.gov.mesrs.sii.commons.data.model.referentiel.Nomenclature;

/**
 * DocumentRealisationMarche generated by hbm2java
 */
@Entity
@Table(name = "document_realisation_marche", schema = "gfc")
public class DocumentRealisationMarche implements java.io.Serializable, Identifiable<Integer> {

	private static final long serialVersionUID = 1L;

	private Integer id;
	private Marche marche;
	private Date dateDocument;
	private Nomenclature typeDocument;
	private BigDecimal montantHt;
	private BigDecimal montantTva;
	private BigDecimal montantTtc;
	private String observation;
	private SituationEntite situation;
	private List<DetailRealisationEquipement> detailRealisationEquipements = new ArrayList<DetailRealisationEquipement>();
	private List<DetailRealisationPrestation> detailRealisationPrestations = new ArrayList<DetailRealisationPrestation>();
	private List<DetailRealisationProduit> detailRealisationProduits = new ArrayList<DetailRealisationProduit>();
	private DossierPaiement dossierPaiement;

	public DocumentRealisationMarche() {
	}

	public DocumentRealisationMarche(Integer id, Marche marche, Nomenclature typeDocument, BigDecimal montantHt,
			BigDecimal montantTva, BigDecimal montantTtc) {
		this.id = id;
		this.marche = marche;
		this.typeDocument = typeDocument;
		this.montantHt = montantHt;
		this.montantTva = montantTva;
		this.montantTtc = montantTtc;
	}

	public DocumentRealisationMarche(Integer id, Marche marche, Nomenclature typeDocument, BigDecimal montantHt,
			BigDecimal montantTva, BigDecimal montantTtc, String observation, SituationEntite situation,
			List<DetailRealisationEquipement> detailRealisationEquipements,
			List<DetailRealisationPrestation> detailRealisationPrestations,
			List<DetailRealisationProduit> detailRealisationProduits, DossierPaiement dossierPaiement) {
		this.id = id;
		this.marche = marche;
		this.typeDocument = typeDocument;
		this.montantHt = montantHt;
		this.montantTva = montantTva;
		this.montantTtc = montantTtc;
		this.observation = observation;
		this.situation = situation;
		this.detailRealisationEquipements = detailRealisationEquipements;
		this.detailRealisationPrestations = detailRealisationPrestations;
		this.detailRealisationProduits = detailRealisationProduits;
		this.dossierPaiement = dossierPaiement;
	}

	@SequenceGenerator(name = "document_realisation_marche_id_seq", sequenceName = "gfc.document_realisation_marche_id_seq")
	@Id
	@GeneratedValue(generator = "document_realisation_marche_id_seq")
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_marche", nullable = false)
	public Marche getMarche() {
		return this.marche;
	}

	public void setMarche(Marche marche) {
		this.marche = marche;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_document", nullable = false, length = 29)
	public Date getDateDocument() {
		return this.dateDocument;
	}

	public void setDateDocument(Date dateDocument) {
		this.dateDocument = dateDocument;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_type_document", nullable = false)
	public Nomenclature getTypeDocument() {
		return this.typeDocument;
	}

	public void setTypeDocument(Nomenclature typeDocument) {
		this.typeDocument = typeDocument;
	}

	@Column(name = "montant_ht", nullable = false, precision = 10)
	public BigDecimal getMontantHt() {
		return this.montantHt;
	}

	public void setMontantHt(BigDecimal montantHt) {
		this.montantHt = montantHt;
	}

	@Column(name = "montant_tva", nullable = false, precision = 10)
	public BigDecimal getMontantTva() {
		return this.montantTva;
	}

	public void setMontantTva(BigDecimal montantTva) {
		this.montantTva = montantTva;
	}

	@Column(name = "montant_ttc", nullable = false, precision = 10)
	public BigDecimal getMontantTtc() {
		return this.montantTtc;
	}

	public void setMontantTtc(BigDecimal montantTtc) {
		this.montantTtc = montantTtc;
	}

	@Column(name = "observation", length = 200)
	public String getObservation() {
		return this.observation;
	}

	public void setObservation(String observation) {
		this.observation = observation;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_situation", nullable = false)
	public SituationEntite getSituation() {
		return this.situation;
	}

	public void setSituation(SituationEntite situation) {
		this.situation = situation;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "documentRealisationMarche")
	public List<DetailRealisationEquipement> getDetailRealisationEquipements() {
		return this.detailRealisationEquipements;
	}

	public void setDetailRealisationEquipements(List<DetailRealisationEquipement> detailRealisationEquipements) {
		this.detailRealisationEquipements = detailRealisationEquipements;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "documentRealisationMarche")
	public List<DetailRealisationPrestation> getDetailRealisationPrestations() {
		return this.detailRealisationPrestations;
	}

	public void setDetailRealisationPrestations(List<DetailRealisationPrestation> detailRealisationPrestations) {
		this.detailRealisationPrestations = detailRealisationPrestations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "documentRealisationMarche")
	public List<DetailRealisationProduit> getDetailRealisationProduits() {
		return this.detailRealisationProduits;
	}

	public void setDetailRealisationProduits(List<DetailRealisationProduit> detailRealisationProduits) {
		this.detailRealisationProduits = detailRealisationProduits;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "documentRealisationMarche", targetEntity = DossierPaiement.class)
	@JoinColumn(name = "id_dossier_paiement", nullable = true)
	public DossierPaiement getDossierPaiement() {
		return this.dossierPaiement;
	}

	public void setDossierPaiement(DossierPaiement dossierPaiement) {
		this.dossierPaiement = dossierPaiement;
	}

	@Transient
	@Override
	public Integer getIdenfiant() {
		return id;
	}

	@Transient
	@Override
	public String getIdentifiantName() {
		return "id";
	}
}