package dz.gov.mesrs.sii.commons.data.model.gfc;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import dz.gov.mesrs.sii.commons.data.model.Identifiable;
import dz.gov.mesrs.sii.commons.data.model.bpm.SituationEntite;
import dz.gov.mesrs.sii.commons.data.model.referentiel.Nomenclature;

/**
 * DossierPayment generated by hbm2java
 */
@Entity
@Table(name = "dossier_paiement", schema = "gfc")
public class DossierPaiement implements java.io.Serializable, Identifiable<Integer> {

	private static final long serialVersionUID = 1L;

	private Integer id;
	private DocumentRealisationMarche documentRealisationMarche;
	private DossierMission dossierMission;
	private String objet;
	private Date dateDossier;
	private Nomenclature modePaiement;
	private String referenceBancaire;
	private SituationEntite situation;
	private String observation;

	public DossierPaiement() {
	}

	public DossierPaiement(Integer id, DocumentRealisationMarche documentRealisationMarche, String objet,
			Date dateDossier, Nomenclature modePaiement, String referenceBancaire) {
		this.id = id;
		this.documentRealisationMarche = documentRealisationMarche;
		this.objet = objet;
		this.dateDossier = dateDossier;
		this.modePaiement = modePaiement;
		this.referenceBancaire = referenceBancaire;
	}

	public DossierPaiement(Integer id, DocumentRealisationMarche documentRealisationMarche, String objet,
			Date dateDossier, Nomenclature modePaiement, String referenceBancaire, SituationEntite situation) {
		this.id = id;
		this.documentRealisationMarche = documentRealisationMarche;
		this.objet = objet;
		this.dateDossier = dateDossier;
		this.modePaiement = modePaiement;
		this.referenceBancaire = referenceBancaire;
		this.situation = situation;
	}

	@SequenceGenerator(name = "dossier_paiement_id_seq", sequenceName = "gfc.dossier_paiement_id_seq")
	@Id
	@GeneratedValue(generator = "dossier_paiement_id_seq")
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_document_realisation_marche", nullable = true)
	public DocumentRealisationMarche getDocumentRealisationMarche() {
		return this.documentRealisationMarche;
	}

	public void setDocumentRealisationMarche(DocumentRealisationMarche documentRealisationMarche) {
		this.documentRealisationMarche = documentRealisationMarche;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_dossier_mission", nullable = true)
	public DossierMission getDossierMission() {
		return dossierMission;
	}

	public void setDossierMission(DossierMission dossierMission) {
		this.dossierMission = dossierMission;
	}

	@Column(name = "objet", nullable = false, length = 200)
	public String getObjet() {
		return this.objet;
	}

	public void setObjet(String objet) {
		this.objet = objet;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_dossier", nullable = false, length = 29)
	public Date getDateDossier() {
		return this.dateDossier;
	}

	public void setDateDossier(Date dateDossier) {
		this.dateDossier = dateDossier;
	}

	@ManyToOne()
	@JoinColumn(name = "id_mode_paiement", nullable = false)
	public Nomenclature getModePaiement() {
		return this.modePaiement;
	}

	public void setModePaiement(Nomenclature modePaiement) {
		this.modePaiement = modePaiement;
	}

	@Column(name = "reference_bancaire", nullable = false, length = 50)
	public String getReferenceBancaire() {
		return this.referenceBancaire;
	}

	public void setReferenceBancaire(String referenceBancaire) {
		this.referenceBancaire = referenceBancaire;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_situation", nullable = false)
	public SituationEntite getSituation() {
		return this.situation;
	}

	public void setSituation(SituationEntite situation) {
		this.situation = situation;
	}

	@Column(name = "observation", nullable = true)
	public String getObservation() {
		return observation;
	}

	public void setObservation(String observation) {
		this.observation = observation;
	}

	@Transient
	@Override
	public Integer getIdenfiant() {
		return id;
	}

	@Transient
	@Override
	public String getIdentifiantName() {
		return "id";
	}
}
