package dz.gov.mesrs.sii.commons.data.model.gfc;

// Generated 12 févr. 2015 16:22:41 by Mounir MESSAOUDI Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import dz.gov.mesrs.sii.commons.data.model.Identifiable;
import dz.gov.mesrs.sii.commons.data.model.bpm.SituationEntite;
import dz.gov.mesrs.sii.commons.data.model.grh.DossierEmploye;

/**
 * DossierMission generated by hbm2java
 */
@Entity
@Table(name = "dossier_mission", schema = "gfc")
public class DossierMission implements java.io.Serializable, Identifiable<Integer> {

	private static final long serialVersionUID = 1L;

	private Integer id;
	private Mission mission;
	private TarifMission tarifMission;
	private DossierEmploye dossierEmploye;

	private Date dateDebut;
	private Date dateFin;
	private Integer nombreResauration;
	private BigDecimal fraisRestauration;
	private Integer nombreHebergement;
	private BigDecimal fraisHebergement;
	private BigDecimal fraisVoyage;
	private BigDecimal montantTotal;
	private BigDecimal montantAvance;
	private Date dateSignature;
	private Integer nombreResaurationReel;
	private BigDecimal fraisRestaurationReel;
	private Integer nombreHebergementReel;
	private BigDecimal fraisHebergementReel;
	private BigDecimal fraisVoyageReel;
	private Date dateDebutReel;
	private Date dateFinReel;
	private BigDecimal resteAPayer;
	private BigDecimal montantARembourser;

	private SituationEntite situation;

	private List<DossierPaiement> dossierPaiements = new ArrayList<DossierPaiement>(0);

	public DossierMission() {
	}

	public DossierMission(Integer id, Mission mission, TarifMission tarifMission, DossierEmploye dossierEmploye,
			Date dateDebut, Date dateFin, BigDecimal montantTotal, BigDecimal montantAvance) {
		this.id = id;
		this.mission = mission;
		this.tarifMission = tarifMission;
		this.dossierEmploye = dossierEmploye;
		this.dateDebut = dateDebut;
		this.dateFin = dateFin;
		this.montantTotal = montantTotal;
		this.montantAvance = montantAvance;
	}

	public DossierMission(Integer id, Mission mission, TarifMission tarifMission, DossierEmploye dossierEmploye,
			Date dateDebut, Date dateFin, Integer nombreResauration, BigDecimal fraisRestauration,
			Integer nombreHebergement, BigDecimal fraisHebergement, BigDecimal fraisVoyage, BigDecimal montantTotal,
			BigDecimal montantAvance, Date dateSignature, Integer nombreResaurationReel,
			BigDecimal fraisRestaurationReel, Integer nombreHebergementReel, BigDecimal fraisHebergementReel,
			BigDecimal fraisVoyageReel, Date dateDebutReel, Date dateFinReel, BigDecimal resteAPayer,
			BigDecimal montantARembourser, SituationEntite situation, List<DossierPaiement> dossierPaiements) {
		this.id = id;
		this.mission = mission;
		this.tarifMission = tarifMission;
		this.dossierEmploye = dossierEmploye;
		this.dateDebut = dateDebut;
		this.dateFin = dateFin;
		this.nombreResauration = nombreResauration;
		this.fraisRestauration = fraisRestauration;
		this.nombreHebergement = nombreHebergement;
		this.fraisHebergement = fraisHebergement;
		this.fraisVoyage = fraisVoyage;
		this.montantTotal = montantTotal;
		this.montantAvance = montantAvance;
		this.dateSignature = dateSignature;
		this.nombreResaurationReel = nombreResaurationReel;
		this.fraisRestaurationReel = fraisRestaurationReel;
		this.nombreHebergementReel = nombreHebergementReel;
		this.fraisHebergementReel = fraisHebergementReel;
		this.fraisVoyageReel = fraisVoyageReel;
		this.dateDebutReel = dateDebutReel;
		this.dateFinReel = dateFinReel;
		this.resteAPayer = resteAPayer;
		this.montantARembourser = montantARembourser;
		this.situation = situation;
		this.dossierPaiements = dossierPaiements;
	}

	@SequenceGenerator(name = "dossier_mission_id_seq", sequenceName = "gfc.dossier_mission_id_seq")
	@Id
	@GeneratedValue(generator = "dossier_mission_id_seq")
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_mission", nullable = false)
	public Mission getMission() {
		return this.mission;
	}

	public void setMission(Mission mission) {
		this.mission = mission;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tarif_mission", nullable = false)
	public TarifMission getTarifMission() {
		return this.tarifMission;
	}

	public void setTarifMission(TarifMission tarifMission) {
		this.tarifMission = tarifMission;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_employe", nullable = false)
	public DossierEmploye getDossierEmploye() {
		return dossierEmploye;
	}

	public void setDossierEmploye(DossierEmploye dossierEmploye) {
		this.dossierEmploye = dossierEmploye;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_debut", nullable = false, length = 29)
	public Date getDateDebut() {
		return this.dateDebut;
	}

	public void setDateDebut(Date dateDebut) {
		this.dateDebut = dateDebut;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_fin", nullable = false, length = 29)
	public Date getDateFin() {
		return this.dateFin;
	}

	public void setDateFin(Date dateFin) {
		this.dateFin = dateFin;
	}

	@Column(name = "nombre_resauration")
	public Integer getNombreResauration() {
		return this.nombreResauration;
	}

	public void setNombreResauration(Integer nombreResauration) {
		this.nombreResauration = nombreResauration;
	}

	@Column(name = "frais_restauration", precision = 10)
	public BigDecimal getFraisRestauration() {
		return this.fraisRestauration;
	}

	public void setFraisRestauration(BigDecimal fraisRestauration) {
		this.fraisRestauration = fraisRestauration;
	}

	@Column(name = "nombre_hebergement")
	public Integer getNombreHebergement() {
		return this.nombreHebergement;
	}

	public void setNombreHebergement(Integer nombreHebergement) {
		this.nombreHebergement = nombreHebergement;
	}

	@Column(name = "frais_hebergement", precision = 10)
	public BigDecimal getFraisHebergement() {
		return this.fraisHebergement;
	}

	public void setFraisHebergement(BigDecimal fraisHebergement) {
		this.fraisHebergement = fraisHebergement;
	}

	@Column(name = "frais_voyage", precision = 10)
	public BigDecimal getFraisVoyage() {
		return this.fraisVoyage;
	}

	public void setFraisVoyage(BigDecimal fraisVoyage) {
		this.fraisVoyage = fraisVoyage;
	}

	@Column(name = "montant_total", nullable = false, precision = 10)
	public BigDecimal getMontantTotal() {
		return this.montantTotal;
	}

	public void setMontantTotal(BigDecimal montantTotal) {
		this.montantTotal = montantTotal;
	}

	@Column(name = "montant_avance", nullable = false, precision = 10)
	public BigDecimal getMontantAvance() {
		return this.montantAvance;
	}

	public void setMontantAvance(BigDecimal montantAvance) {
		this.montantAvance = montantAvance;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_signature", length = 29)
	public Date getDateSignature() {
		return this.dateSignature;
	}

	public void setDateSignature(Date dateSignature) {
		this.dateSignature = dateSignature;
	}

	@Column(name = "nombre_resauration_reel")
	public Integer getNombreResaurationReel() {
		return this.nombreResaurationReel;
	}

	public void setNombreResaurationReel(Integer nombreResaurationReel) {
		this.nombreResaurationReel = nombreResaurationReel;
	}

	@Column(name = "frais_restauration_reel")
	public BigDecimal getFraisRestaurationReel() {
		return this.fraisRestaurationReel;
	}

	public void setFraisRestaurationReel(BigDecimal fraisRestaurationReel) {
		this.fraisRestaurationReel = fraisRestaurationReel;
	}

	@Column(name = "nombre_hebergement_reel")
	public Integer getNombreHebergementReel() {
		return this.nombreHebergementReel;
	}

	public void setNombreHebergementReel(Integer nombreHebergementReel) {
		this.nombreHebergementReel = nombreHebergementReel;
	}

	@Column(name = "frais_hebergement_reel", precision = 10)
	public BigDecimal getFraisHebergementReel() {
		return this.fraisHebergementReel;
	}

	public void setFraisHebergementReel(BigDecimal fraisHebergementReel) {
		this.fraisHebergementReel = fraisHebergementReel;
	}

	@Column(name = "frais_voyage_reel", precision = 10)
	public BigDecimal getFraisVoyageReel() {
		return this.fraisVoyageReel;
	}

	public void setFraisVoyageReel(BigDecimal fraisVoyageReel) {
		this.fraisVoyageReel = fraisVoyageReel;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_debut_reel", length = 29)
	public Date getDateDebutReel() {
		return this.dateDebutReel;
	}

	public void setDateDebutReel(Date dateDebutReel) {
		this.dateDebutReel = dateDebutReel;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_fin_reel", length = 29)
	public Date getDateFinReel() {
		return this.dateFinReel;
	}

	public void setDateFinReel(Date dateFinReel) {
		this.dateFinReel = dateFinReel;
	}

	@Column(name = "reste_a_payer", precision = 10)
	public BigDecimal getResteAPayer() {
		return this.resteAPayer;
	}

	public void setResteAPayer(BigDecimal resteAPayer) {
		this.resteAPayer = resteAPayer;
	}

	@Column(name = "montant_a_rembourser", precision = 10)
	public BigDecimal getMontantARembourser() {
		return this.montantARembourser;
	}

	public void setMontantARembourser(BigDecimal montantARembourser) {
		this.montantARembourser = montantARembourser;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_situation", nullable = true)
	public SituationEntite getSituation() {
		return this.situation;
	}

	public void setSituation(SituationEntite situation) {
		this.situation = situation;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dossierMission")
	public List<DossierPaiement> getDossierPaiements() {
		return this.dossierPaiements;
	}

	public void setDossierPaiements(List<DossierPaiement> dossierPaiements) {
		this.dossierPaiements = dossierPaiements;
	}

	@Transient
	@Override
	public Integer getIdenfiant() {
		return id;
	}

	@Transient
	@Override
	public String getIdentifiantName() {
		return "id";
	}

}
