package dz.gov.mesrs.sii.commons.data.model.gfc;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import dz.gov.mesrs.sii.commons.data.model.Identifiable;
import dz.gov.mesrs.sii.commons.data.model.bpm.SituationEntite;
import dz.gov.mesrs.sii.commons.data.model.referentiel.Nomenclature;

/**
 * EngagementMarche generated by hbm2java
 */
@Entity
@Table(name = "engagement_marche", schema = "gfc")
public class EngagementMarche implements java.io.Serializable, Identifiable<Integer> {

	private static final long serialVersionUID = 1L;

	private Integer id;
	private Marche marche;
	private String numero;
	private Date dateDemande;
	private String objet;
	private BigDecimal montantAEngager;
	private Nomenclature typeEngagement;
	private Nomenclature natureEngagement;
	private String numeroFiche;
	private Date dateSignature;
	private String numeroVisa;
	private Date dateVisa;
	private String observation;
	private SituationEntite situation;

	private List<DetailEngagementMarche> detailEngagementMarches = new ArrayList<DetailEngagementMarche>();

	public EngagementMarche() {
	}

	public EngagementMarche(Integer id, Marche marche, String numero, Date dateDemande, String objet,
			BigDecimal montantAEngager, Nomenclature typeEngagement) {
		this.id = id;
		this.marche = marche;
		this.numero = numero;
		this.dateDemande = dateDemande;
		this.objet = objet;
		this.montantAEngager = montantAEngager;
		this.typeEngagement = typeEngagement;
	}

	public EngagementMarche(Integer id, Marche marche, String numero, Date dateDemande, String objet,
			BigDecimal montantAEngager, Nomenclature typeEngagement, String numeroFiche, Date dateSignature,
			String numeroVisa, Date dateVisa, String observation, SituationEntite situation,
			List<DetailEngagementMarche> detailEngagementMarches) {
		this.id = id;
		this.marche = marche;
		this.numero = numero;
		this.dateDemande = dateDemande;
		this.objet = objet;
		this.montantAEngager = montantAEngager;
		this.typeEngagement = typeEngagement;
		this.numeroFiche = numeroFiche;
		this.dateSignature = dateSignature;
		this.numeroVisa = numeroVisa;
		this.dateVisa = dateVisa;
		this.observation = observation;
		this.situation = situation;
		this.detailEngagementMarches = detailEngagementMarches;
	}

	@SequenceGenerator(name = "engagement_marche_id_seq", sequenceName = "gfc.engagement_marche_id_seq")
	@Id
	@GeneratedValue(generator = "engagement_marche_id_seq")
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_marche", nullable = false)
	public Marche getMarche() {
		return this.marche;
	}

	public void setMarche(Marche marche) {
		this.marche = marche;
	}

	@Column(name = "numero", nullable = false, length = 50)
	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_demande", nullable = false, length = 29)
	public Date getDateDemande() {
		return this.dateDemande;
	}

	public void setDateDemande(Date dateDemande) {
		this.dateDemande = dateDemande;
	}

	@Column(name = "objet", nullable = false, length = 200)
	public String getObjet() {
		return this.objet;
	}

	public void setObjet(String objet) {
		this.objet = objet;
	}

	@Column(name = "montant_a_engager", nullable = false, precision = 10)
	public BigDecimal getMontantAEngager() {
		return this.montantAEngager;
	}

	public void setMontantAEngager(BigDecimal montantAEngager) {
		this.montantAEngager = montantAEngager;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_type_engagement", nullable = true)
	public Nomenclature getTypeEngagement() {
		return this.typeEngagement;
	}

	public void setTypeEngagement(Nomenclature typeEngagement) {
		this.typeEngagement = typeEngagement;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_nature_engagement", nullable = true)
	public Nomenclature getNatureEngagement() {
		return natureEngagement;
	}

	public void setNatureEngagement(Nomenclature natureEngagement) {
		this.natureEngagement = natureEngagement;
	}

	@Column(name = "numero_fiche", length = 50)
	public String getNumeroFiche() {
		return this.numeroFiche;
	}

	public void setNumeroFiche(String numeroFiche) {
		this.numeroFiche = numeroFiche;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_signature", length = 29)
	public Date getDateSignature() {
		return this.dateSignature;
	}

	public void setDateSignature(Date dateSignature) {
		this.dateSignature = dateSignature;
	}

	@Column(name = "numero_visa", length = 50)
	public String getNumeroVisa() {
		return this.numeroVisa;
	}

	public void setNumeroVisa(String numeroVisa) {
		this.numeroVisa = numeroVisa;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_visa", length = 29)
	public Date getDateVisa() {
		return this.dateVisa;
	}

	public void setDateVisa(Date dateVisa) {
		this.dateVisa = dateVisa;
	}

	@Column(name = "observation", length = 200)
	public String getObservation() {
		return this.observation;
	}

	public void setObservation(String observation) {
		this.observation = observation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_situation", nullable = false)
	public SituationEntite getSituation() {
		return this.situation;
	}

	public void setSituation(SituationEntite situation) {
		this.situation = situation;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "engagementMarche")
	public List<DetailEngagementMarche> getDetailEngagementMarches() {
		return this.detailEngagementMarches;
	}

	public void setDetailEngagementMarches(List<DetailEngagementMarche> detailEngagementMarches) {
		this.detailEngagementMarches = detailEngagementMarches;
	}

	@Transient
	@Override
	public Integer getIdenfiant() {
		return id;
	}

	@Transient
	@Override
	public String getIdentifiantName() {
		return "id";
	}
}