package dz.gov.mesrs.sii.commons.data.model.gfc;

// Generated 24 nov. 2014 16:52:54 by Hibernate Tools 3.6.0

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import dz.gov.mesrs.sii.commons.data.model.Identifiable;
import dz.gov.mesrs.sii.commons.data.model.bpm.SituationEntite;
import dz.gov.mesrs.sii.commons.data.model.referentiel.Nomenclature;
import dz.gov.mesrs.sii.commons.data.model.referentiel.RefEtablissement;

/**
 * FicheBesoins generated by hbm2java
 */
@Entity
// has been deprecated in Hibernate 4.0, use @DynamicUpdate
// @org.hibernate.annotations.Entity(dynamicInsert = true, dynamicUpdate = true)
// @org.hibernate.annotations.Entity(selectBeforeUpdate = true, dynamicInsert =
// true, dynamicUpdate = true, optimisticLock = OptimisticLockType.ALL,
// polymorphism = PolymorphismType.EXPLICIT, mutable = false)
@Table(name = "fiche_besoins", schema = "gfc")
public class FicheBesoins implements java.io.Serializable, Identifiable<Integer> {

	/**
	 * @author Mounir.MESSAOUDI on : 24 nov. 2014 17:33:05
	 */
	private static final long serialVersionUID = 1L;

	private Integer id;
	private String identite;
	private ProjetBudget projetBudget;
	private RefEtablissement etablissement;
	private Nomenclature uniteMonetaire;
	private SituationEntite situation;
	private Date dateEnvoi;
	private Date dateReception;
	private String intituleFr;
	private String intituleAr;
	private String description;
	private Date dateValidation;
	private Date dateVisaCF;
	private String observation;
	private List<ConsolidationBesoins> consolidationBesoins = new ArrayList<ConsolidationBesoins>(0);
	private List<DetailsFicheBesoins> detailsFicheBesoins = new ArrayList<DetailsFicheBesoins>(0);

	public FicheBesoins() {
	}

	public FicheBesoins(Integer id, RefEtablissement etablissement, Nomenclature uniteMonetaire,
			SituationEntite situation, String intituleFr, String intituleAr) {
		this.id = id;
		this.etablissement = etablissement;
		this.uniteMonetaire = uniteMonetaire;
		this.situation = situation;
		this.intituleFr = intituleFr;
		this.intituleAr = intituleAr;
	}

	public FicheBesoins(Integer id, ProjetBudget projetBudget, RefEtablissement etablissement,
			Nomenclature uniteMonetaire, SituationEntite situation, Date dateEnvoi, Date dateReception,
			String intituleFr, String intituleAr, String description, Date dateValidation, Date dateVisaCF,
			String observation, List<ConsolidationBesoins> consolidationBesoins,
			List<DetailsFicheBesoins> detailsFicheBesoins) {
		this.id = id;
		this.projetBudget = projetBudget;
		this.etablissement = etablissement;
		this.uniteMonetaire = uniteMonetaire;
		this.situation = situation;
		this.dateEnvoi = dateEnvoi;
		this.dateReception = dateReception;
		this.intituleFr = intituleFr;
		this.intituleAr = intituleAr;
		this.description = description;
		this.dateValidation = dateValidation;
		this.dateVisaCF = dateVisaCF;
		this.observation = observation;
		this.consolidationBesoins = consolidationBesoins;
		this.detailsFicheBesoins = detailsFicheBesoins;
	}

	@SequenceGenerator(name = "fiche_besoins_id_seq", sequenceName = "gfc.fiche_besoins_id_seq")
	@Id
	@GeneratedValue(generator = "fiche_besoins_id_seq")
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "identite", nullable = false, length = 50)
	public String getIdentite() {
		return this.identite;
	}

	public void setIdentite(String identite) {
		this.identite = identite;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_projet_budget")
	public ProjetBudget getProjetBudget() {
		return this.projetBudget;
	}

	public void setProjetBudget(ProjetBudget projetBudget) {
		this.projetBudget = projetBudget;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_etablissement", nullable = false)
	public RefEtablissement getEtablissement() {
		return this.etablissement;
	}

	public void setEtablissement(RefEtablissement etablissement) {
		this.etablissement = etablissement;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_unite_monetaire", nullable = false)
	public Nomenclature getUniteMonetaire() {
		return this.uniteMonetaire;
	}

	public void setUniteMonetaire(Nomenclature uniteMonetaire) {
		this.uniteMonetaire = uniteMonetaire;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_situation", nullable = false)
	public SituationEntite getSituation() {
		return this.situation;
	}

	public void setSituation(SituationEntite situation) {
		this.situation = situation;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_envoi", length = 29)
	public Date getDateEnvoi() {
		return this.dateEnvoi;
	}

	public void setDateEnvoi(Date dateEnvoi) {
		this.dateEnvoi = dateEnvoi;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_reception", length = 29)
	public Date getDateReception() {
		return this.dateReception;
	}

	public void setDateReception(Date dateReception) {
		this.dateReception = dateReception;
	}

	@Column(name = "intitule_fr", nullable = false, length = 200)
	public String getIntituleFr() {
		return this.intituleFr;
	}

	public void setIntituleFr(String intituleFr) {
		this.intituleFr = intituleFr;
	}

	@Column(name = "intitule_ar", nullable = false, length = 200)
	public String getIntituleAr() {
		return this.intituleAr;
	}

	public void setIntituleAr(String intituleAr) {
		this.intituleAr = intituleAr;
	}

	@Column(name = "description", length = 200)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_validation", length = 29)
	public Date getDateValidation() {
		return this.dateValidation;
	}

	public void setDateValidation(Date dateValidation) {
		this.dateValidation = dateValidation;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_visa_cf", length = 29)
	public Date getdateVisaCF() {
		return this.dateVisaCF;
	}

	public void setdateVisaCF(Date dateVisaCF) {
		this.dateVisaCF = dateVisaCF;
	}

	@Column(name = "observation", length = 200)
	public String getObservation() {
		return this.observation;
	}

	public void setObservation(String observation) {
		this.observation = observation;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ficheBesoins", cascade = { CascadeType.MERGE, CascadeType.REMOVE,
			CascadeType.REFRESH }, orphanRemoval = true)
	public List<ConsolidationBesoins> getConsolidationBesoins() {
		return this.consolidationBesoins;
	}

	public void setConsolidationBesoins(List<ConsolidationBesoins> consolidationBesoins) {
		this.consolidationBesoins = consolidationBesoins;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ficheBesoins", cascade = { CascadeType.REMOVE }, orphanRemoval = true)
	public List<DetailsFicheBesoins> getDetailsFicheBesoins() {
		return this.detailsFicheBesoins;
	}

	public void setDetailsFicheBesoins(List<DetailsFicheBesoins> detailsFicheBesoins) {
		this.detailsFicheBesoins = detailsFicheBesoins;
	}

	@Transient
	@Override
	public Integer getIdenfiant() {
		return id;
	}

	@Transient
	@Override
	public String getIdentifiantName() {
		return "id";
	}

}
