package dz.gov.mesrs.sii.commons.data.model.gfc;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import dz.gov.mesrs.sii.commons.data.model.Identifiable;
import dz.gov.mesrs.sii.commons.data.model.bpm.SituationEntite;
import dz.gov.mesrs.sii.commons.data.model.referentiel.Nomenclature;
import dz.gov.mesrs.sii.commons.data.model.referentiel.RefContrat;
import dz.gov.mesrs.sii.commons.data.model.referentiel.RefEtablissement;
import dz.gov.mesrs.sii.commons.data.model.referentiel.RefIndividu;
import dz.gov.mesrs.sii.commons.data.model.referentiel.RefStructure;

/**
 * Marche generated by hbm2java
 */
@Entity
@Table(name = "marche", schema = "gfc")
public class Marche implements java.io.Serializable, Identifiable<Integer> {

	private static final long serialVersionUID = 1L;

	private Integer id;

	private String intituleFr;
	private String intituleAr;

	private RefContrat contrat;
	private RefIndividu contact;
	private Nomenclature type;

	private RefEtablissement etablissement;
	private RefStructure structure;

	private BigDecimal montant;
	private BigDecimal montantEngage;
	private Nomenclature modePassation;
	private Date dateApprobation;
	private Date datePublication;
	private Date dateSignature;
	private Boolean prestation;
	private Boolean equipement;
	private Boolean produit;
	private Date dateOds;
	private String observation;

	private SituationEntite situation;

	private Nomenclature typeCloture;

	private Date dateCloture;
	private Date dateProvisoire;
	private Date dateReceptionDefinitive;
	private Date dateDebutGarantie;
	private Date dateFinGarantie;

	private List<EvenementMarche> evenementMarches = new ArrayList<EvenementMarche>();
	private List<DocumentRealisationMarche> documentRealisationMarches = new ArrayList<DocumentRealisationMarche>();
	private List<ProduitMarche> produitMarches = new ArrayList<ProduitMarche>();
	private List<PrestationMarche> prestationMarches = new ArrayList<PrestationMarche>();
	private List<EquipementMarche> equipementMarches = new ArrayList<EquipementMarche>();
	private List<EngagementMarche> engagementMarches = new ArrayList<EngagementMarche>();

	public Marche() {
	}

	@SequenceGenerator(name = "marche_id_seq", sequenceName = "gfc.marche_id_seq")
	@Id
	@GeneratedValue(generator = "marche_id_seq")
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_contrat", nullable = false)
	public RefContrat getContrat() {
		return this.contrat;
	}

	public void setContrat(RefContrat contrat) {
		this.contrat = contrat;
	}

	@Column(name = "intitule_fr", nullable = false, length = 100)
	public String getIntituleFr() {
		return this.intituleFr;
	}

	public void setIntituleFr(String intituleFr) {
		this.intituleFr = intituleFr;
	}

	@Column(name = "intitule_ar", length = 100)
	public String getIntituleAr() {
		return this.intituleAr;
	}

	public void setIntituleAr(String intituleAr) {
		this.intituleAr = intituleAr;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_type_marche", nullable = false)
	public Nomenclature getType() {
		return this.type;
	}

	public void setType(Nomenclature type) {
		this.type = type;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_etablissement", nullable = false)
	public RefEtablissement getEtablissement() {
		return etablissement;
	}

	public void setEtablissement(RefEtablissement etablissement) {
		this.etablissement = etablissement;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_structure", nullable = false)
	public RefStructure getStructure() {
		return structure;
	}

	public void setStructure(RefStructure structure) {
		this.structure = structure;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_contact", nullable = false)
	public RefIndividu getContact() {
		return this.contact;
	}

	public void setContact(RefIndividu contact) {
		this.contact = contact;
	}

	@Column(name = "montant", precision = 10)
	public BigDecimal getMontant() {
		return this.montant;
	}

	public void setMontant(BigDecimal montant) {
		this.montant = montant;
	}

	@Column(name = "montant_engage", precision = 10)
	public BigDecimal getMontantEngage() {
		return this.montantEngage;
	}

	public void setMontantEngage(BigDecimal montantEngage) {
		this.montantEngage = montantEngage;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_mode_passation", nullable = false)
	public Nomenclature getModePassation() {
		return this.modePassation;

	}

	public void setModePassation(Nomenclature modePassation) {
		this.modePassation = modePassation;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_approbation", nullable = false, length = 29)
	public Date getDateApprobation() {
		return this.dateApprobation;
	}

	public void setDateApprobation(Date dateApprobation) {
		this.dateApprobation = dateApprobation;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_publication", nullable = false, length = 29)
	public Date getDatePublication() {
		return this.datePublication;
	}

	public void setDatePublication(Date datePublication) {
		this.datePublication = datePublication;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_signature", length = 29)
	public Date getDateSignature() {
		return this.dateSignature;
	}

	public void setDateSignature(Date dateSignature) {
		this.dateSignature = dateSignature;
	}

	@Column(name = "prestation")
	public Boolean getPrestation() {
		return this.prestation;
	}

	public void setPrestation(Boolean prestation) {
		this.prestation = prestation;
	}

	@Column(name = "equipement")
	public Boolean getEquipement() {
		return this.equipement;
	}

	public void setEquipement(Boolean equipement) {
		this.equipement = equipement;
	}

	@Column(name = "produit")
	public Boolean getProduit() {
		return this.produit;
	}

	public void setProduit(Boolean produit) {
		this.produit = produit;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_ods", length = 29)
	public Date getDateOds() {
		return this.dateOds;
	}

	public void setDateOds(Date dateOds) {
		this.dateOds = dateOds;
	}

	@Column(name = "observation", length = 200)
	public String getObservation() {
		return this.observation;
	}

	public void setObservation(String observation) {
		this.observation = observation;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_situation", nullable = false)
	public SituationEntite getSituation() {
		return this.situation;

	}

	public void setSituation(SituationEntite situation) {
		this.situation = situation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_type_cloture", nullable = false)
	public Nomenclature getTypeCloture() {
		return this.typeCloture;
	}

	public void setTypeCloture(Nomenclature typeCloture) {
		this.typeCloture = typeCloture;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_cloture", length = 29)
	public Date getDateCloture() {
		return this.dateCloture;
	}

	public void setDateCloture(Date dateCloture) {
		this.dateCloture = dateCloture;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_provisoire", length = 29)
	public Date getDateProvisoire() {
		return this.dateProvisoire;
	}

	public void setDateProvisoire(Date dateProvisoire) {
		this.dateProvisoire = dateProvisoire;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_reception_definitive", length = 29)
	public Date getDateReceptionDefinitive() {
		return this.dateReceptionDefinitive;
	}

	public void setDateReceptionDefinitive(Date dateReceptionDefinitive) {
		this.dateReceptionDefinitive = dateReceptionDefinitive;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_debut_garantie", length = 29)
	public Date getDateDebutGarantie() {
		return this.dateDebutGarantie;
	}

	public void setDateDebutGarantie(Date dateDebutGarantie) {
		this.dateDebutGarantie = dateDebutGarantie;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_fin_garantie", length = 29)
	public Date getDateFinGarantie() {
		return this.dateFinGarantie;
	}

	public void setDateFinGarantie(Date dateFinGarantie) {
		this.dateFinGarantie = dateFinGarantie;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "marche")
	public List<EvenementMarche> getEvenementMarches() {
		return this.evenementMarches;
	}

	public void setEvenementMarches(List<EvenementMarche> evenementMarches) {
		this.evenementMarches = evenementMarches;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "marche")
	public List<DocumentRealisationMarche> getDocumentRealisationMarches() {
		return this.documentRealisationMarches;
	}

	public void setDocumentRealisationMarches(List<DocumentRealisationMarche> documentRealisationMarches) {
		this.documentRealisationMarches = documentRealisationMarches;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "marche")
	public List<ProduitMarche> getProduitMarches() {
		return this.produitMarches;
	}

	public void setProduitMarches(List<ProduitMarche> produitMarches) {
		this.produitMarches = produitMarches;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "marche")
	public List<PrestationMarche> getPrestationMarches() {
		return this.prestationMarches;
	}

	public void setPrestationMarches(List<PrestationMarche> prestationMarches) {
		this.prestationMarches = prestationMarches;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "marche")
	public List<EquipementMarche> getEquipementMarches() {
		return this.equipementMarches;
	}

	public void setEquipementMarches(List<EquipementMarche> equipementMarches) {
		this.equipementMarches = equipementMarches;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "marche")
	public List<EngagementMarche> getEngagementMarches() {
		return this.engagementMarches;
	}

	public void setEngagementMarches(List<EngagementMarche> engagementMarches) {
		this.engagementMarches = engagementMarches;
	}

	@Transient
	@Override
	public Integer getIdenfiant() {
		return id;
	}

	@Transient
	@Override
	public String getIdentifiantName() {
		return "id";
	}

}