package dz.gov.mesrs.sii.commons.data.model.gfc;

// Generated 24 nov. 2014 16:52:54 by Hibernate Tools 3.6.0

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import dz.gov.mesrs.sii.commons.data.model.Identifiable;
import dz.gov.mesrs.sii.commons.data.model.referentiel.Nomenclature;
import dz.gov.mesrs.sii.commons.data.model.referentiel.RefEtablissement;
import dz.gov.mesrs.sii.commons.data.model.referentiel.RefStructure;

/**
 * MouvementBudget generated by hbm2java
 */
@Entity
@Table(name = "mouvement_budget", schema = "gfc")
public class MouvementBudget implements java.io.Serializable, Identifiable<Integer> {

	/**
	 * @author Mounir.MESSAOUDI on : 24 nov. 2014 17:33:21
	 */
	private static final long serialVersionUID = 1L;

	private Integer id;
	private Nomenclature typeMouvement;
	private RepartitionBudget repartitionBudget;
	private RefStructure refStructure;
	private RefEtablissement refEtablissement;
	private Nomenclature uniteMonitaire;
	private String reference;
	private Date dateDecision;
	private String intituleFr;
	private String intituleAr;
	private BigDecimal montant;
	private Integer idSituation;
	private String observation;
	private Date dateSignature;
	private List<DetailsMouvementBudget> detailsMouvementBudgets = new ArrayList<DetailsMouvementBudget>(0);

	public MouvementBudget() {
	}

	public MouvementBudget(Integer id, Nomenclature typeMouvement, RefStructure refStructure,
			RefEtablissement refEtablissement, Nomenclature uniteMonitaire, String reference,
			Date dateDecision, String intituleFr, String intituleAr, BigDecimal montant, Integer idSituation) {
		this.id = id;
		this.typeMouvement = typeMouvement;
		this.refStructure = refStructure;
		this.refEtablissement = refEtablissement;
		this.uniteMonitaire = uniteMonitaire;
		this.reference = reference;
		this.dateDecision = dateDecision;
		this.intituleFr = intituleFr;
		this.intituleAr = intituleAr;
		this.montant = montant;
		this.idSituation = idSituation;
	}

	public MouvementBudget(Integer id, Nomenclature typeMouvement, RepartitionBudget repartitionBudget,
			RefStructure refStructure, RefEtablissement refEtablissement, Nomenclature uniteMonitaire,
			String reference, Date dateDecision, String intituleFr, String intituleAr, BigDecimal montant,
			Integer idSituation, String observation,Date dateSignature, List<DetailsMouvementBudget> detailsMouvementBudgets) {
		this.id = id;
		this.typeMouvement = typeMouvement;
		this.repartitionBudget = repartitionBudget;
		this.refStructure = refStructure;
		this.refEtablissement = refEtablissement;
		this.uniteMonitaire = uniteMonitaire;
		this.reference = reference;
		this.dateDecision = dateDecision;
		this.intituleFr = intituleFr;
		this.intituleAr = intituleAr;
		this.montant = montant;
		this.idSituation = idSituation;
		this.observation = observation;
		this.dateSignature= dateSignature;
		this.detailsMouvementBudgets = detailsMouvementBudgets;
	}

	@SequenceGenerator(name = "mouvement_budget_id_seq", sequenceName = "gfc.mouvement_budget_id_seq")
	@Id
	@GeneratedValue(generator = "mouvement_budget_id_seq")
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_type_mouvement_budget")
	public Nomenclature getTypeMouvement() {
		return this.typeMouvement;
	}

	public void setTypeMouvement(Nomenclature typeMouvement) {
		this.typeMouvement = typeMouvement;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_repartition_budget")
	public RepartitionBudget getRepartitionBudget() {
		return this.repartitionBudget;
	}

	public void setRepartitionBudget(RepartitionBudget repartitionBudget) {
		this.repartitionBudget = repartitionBudget;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_structure", nullable = false)
	public RefStructure getRefStructure() {
		return this.refStructure;
	}

	public void setRefStructure(RefStructure refStructure) {
		this.refStructure = refStructure;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_etablissement", nullable = false)
	public RefEtablissement getRefEtablissement() {
		return this.refEtablissement;
	}

	public void setRefEtablissement(RefEtablissement refEtablissement) {
		this.refEtablissement = refEtablissement;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_unite_monetaire")
	public Nomenclature getUniteMonitaire() {
		return this.uniteMonitaire;
	}

	public void setUniteMonitaire(Nomenclature uniteMonitaire) {
		this.uniteMonitaire = uniteMonitaire;
	}

	@Column(name = "reference",  length = 50)
	public String getReference() {
		return this.reference;
	}

	public void setReference(String reference) {
		this.reference = reference;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_decision", nullable = false, length = 29)
	public Date getDateDecision() {
		return this.dateDecision;
	}

	public void setDateDecision(Date dateDecision) {
		this.dateDecision = dateDecision;
	}

	@Column(name = "intitule_fr", nullable = false, length = 200)
	public String getIntituleFr() {
		return this.intituleFr;
	}

	public void setIntituleFr(String intituleFr) {
		this.intituleFr = intituleFr;
	}

	@Column(name = "intitule_ar",  length = 200)
	public String getIntituleAr() {
		return this.intituleAr;
	}

	public void setIntituleAr(String intituleAr) {
		this.intituleAr = intituleAr;
	}

	@Column(name = "montant", nullable = false, precision = 10)
	public BigDecimal getMontant() {
		return this.montant;
	}

	public void setMontant(BigDecimal montant) {
		this.montant = montant;
	}

	@Column(name = "id_situation", nullable = false)
	public Integer getIdSituation() {
		return this.idSituation;
	}

	public void setIdSituation(Integer idSituation) {
		this.idSituation = idSituation;
	}

	@Column(name = "observation", length = 200)
	public String getObservation() {
		return this.observation;
	}

	public void setObservation(String observation) {
		this.observation = observation;
	}

	
	/**
	 * @return the dateSignature
	 */
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_signature",  length = 29)
	public Date getDateSignature() {
		return dateSignature;
	}

	/**
	 * @param dateSignature the dateSignature to set
	 */
	public void setDateSignature(Date dateSignature) {
		this.dateSignature = dateSignature;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mouvementBudget")
	public List<DetailsMouvementBudget> getDetailsMouvementBudgets() {
		return this.detailsMouvementBudgets;
	}

	public void setDetailsMouvementBudgets(List<DetailsMouvementBudget> detailsMouvementBudgets) {
		this.detailsMouvementBudgets = detailsMouvementBudgets;
	}

	@Transient
	@Override
	public Integer getIdenfiant() {
		return id;
	}

	@Transient
	@Override
	public String getIdentifiantName() {
		return "id";
	}

}
