package dz.gov.mesrs.sii.commons.data.model.gfc;

// Generated 24 nov. 2014 16:52:54 by Hibernate Tools 3.6.0

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import dz.gov.mesrs.sii.commons.data.model.Identifiable;
import dz.gov.mesrs.sii.commons.data.model.referentiel.Nomenclature;
import dz.gov.mesrs.sii.commons.data.model.referentiel.RefEtablissement;
import dz.gov.mesrs.sii.commons.data.model.referentiel.RefIndividu;
import dz.gov.mesrs.sii.commons.data.model.referentiel.RefStructure;

/**
 * Ordonnateur generated by hbm2java
 */
@Entity
@Table(name = "ordonnateur", schema = "gfc")
public class Ordonnateur implements java.io.Serializable, Identifiable<Integer> {

	/**
	 * @author Mounir.MESSAOUDI on : 24 nov. 2014 17:33:26
	 */
	private static final long serialVersionUID = 1L;

	private Integer id;
	private RefIndividu refIndividu;
	private Nomenclature type;
	private String code;
	private String decisionNomination;
	private Date dateNomination;
	private Date dateFinNomination;

	private List<Regie> regies = new ArrayList<Regie>(0);

	private RefEtablissement etablissement;
	private RefStructure structure;

	public Ordonnateur() {
	}

	public Ordonnateur(Integer id, RefIndividu refIndividu, Nomenclature type) {
		this.id = id;
		this.refIndividu = refIndividu;
		this.type = type;
	}

	public Ordonnateur(Integer id, RefIndividu refIndividu, Nomenclature type, String code, String decisionNomination,
			Date dateNomination, Date dateFinNomination, List<Regie> regies) {
		this.id = id;
		this.refIndividu = refIndividu;
		this.type = type;
		this.code = code;
		this.decisionNomination = decisionNomination;
		this.dateNomination = dateNomination;
		this.dateFinNomination = dateFinNomination;
		this.regies = regies;
	}

	@SequenceGenerator(name = "ordonnateur_id_seq", sequenceName = "gfc.ordonnateur_id_seq")
	@Id
	@GeneratedValue(generator = "ordonnateur_id_seq")
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_individu", nullable = false)
	public RefIndividu getRefIndividu() {
		return this.refIndividu;
	}

	public void setRefIndividu(RefIndividu refIndividu) {
		this.refIndividu = refIndividu;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_type_ordonnateur", nullable = false)
	public Nomenclature getType() {
		return this.type;
	}

	public void setType(Nomenclature type) {
		this.type = type;
	}

	@Column(name = "code", length = 10)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_etablissement", nullable = false)
	public RefEtablissement getEtablissement() {
		return etablissement;
	}

	public void setEtablissement(RefEtablissement etablissement) {
		this.etablissement = etablissement;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_structure", nullable = false)
	public RefStructure getStructure() {
		return structure;
	}

	public void setStructure(RefStructure structure) {
		this.structure = structure;
	}

	@Column(name = "decision_nomination", length = 200)
	public String getDecisionNomination() {
		return this.decisionNomination;
	}

	public void setDecisionNomination(String decisionNomination) {
		this.decisionNomination = decisionNomination;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_nomination", length = 29)
	public Date getDateNomination() {
		return this.dateNomination;
	}

	public void setDateNomination(Date dateNomination) {
		this.dateNomination = dateNomination;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_fin_nomination", length = 29)
	public Date getDateFinNomination() {
		return this.dateFinNomination;
	}

	public void setDateFinNomination(Date dateFinNomination) {
		this.dateFinNomination = dateFinNomination;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ordonnateur")
	public List<Regie> getRegies() {
		return this.regies;
	}

	public void setRegies(List<Regie> regies) {
		this.regies = regies;
	}

	@Transient
	@Override
	public Integer getIdenfiant() {
		return id;
	}

	@Transient
	@Override
	public String getIdentifiantName() {
		return "id";
	}

}
