package dz.gov.mesrs.sii.commons.data.model.gfc;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;

import dz.gov.mesrs.sii.commons.data.model.Identifiable;
import dz.gov.mesrs.sii.commons.data.model.referentiel.Nomenclature;

/**
 * PrestationMarche generated by hbm2java
 */
@Entity
@Table(name = "prestation_marche", schema = "gfc")
public class PrestationMarche implements java.io.Serializable, Identifiable<Integer> {

	private static final long serialVersionUID = 1L;

	private Integer id;
	private Marche marche;
	private String description;
	private Nomenclature type;
	private Integer quantite;
	private BigDecimal prixUnitaire;
	private Float tauxTva;
	private BigDecimal montantTtc;

	private List<DetailRealisationPrestation> detailRealisationPrestations = new ArrayList<DetailRealisationPrestation>();

	public PrestationMarche() {
	}

	public PrestationMarche(Integer id, Marche marche, String description, Nomenclature type, Integer quantite,
			BigDecimal prixUnitaire, BigDecimal montantTtc) {
		this.id = id;
		this.marche = marche;
		this.description = description;
		this.type = type;
		this.quantite = quantite;
		this.prixUnitaire = prixUnitaire;
		this.montantTtc = montantTtc;
	}

	public PrestationMarche(Integer id, Marche marche, String description, Nomenclature type, Integer quantite,
			BigDecimal prixUnitaire, Float tauxTva, BigDecimal montantTtc,
			List<DetailRealisationPrestation> detailRealisationPrestations) {
		this.id = id;
		this.marche = marche;
		this.description = description;
		this.type = type;
		this.quantite = quantite;
		this.prixUnitaire = prixUnitaire;
		this.tauxTva = tauxTva;
		this.montantTtc = montantTtc;
		this.detailRealisationPrestations = detailRealisationPrestations;
	}

	@SequenceGenerator(name = "prestation_marche_id_seq", sequenceName = "gfc.prestation_marche_id_seq")
	@Id
	@GeneratedValue(generator = "prestation_marche_id_seq")
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_marche", nullable = false)
	public Marche getMarche() {
		return this.marche;
	}

	public void setMarche(Marche marche) {
		this.marche = marche;
	}

	@Column(name = "description", nullable = false, length = 200)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_type_prestation", nullable = false)
	public Nomenclature getType() {
		return this.type;
	}

	public void setType(Nomenclature type) {
		this.type = type;
	}

	@Column(name = "quantite", nullable = false, precision = 10)
	public Integer getQuantite() {
		return this.quantite;
	}

	public void setQuantite(Integer quantite) {
		this.quantite = quantite;
	}

	@Column(name = "prix_unitaire", nullable = false, precision = 10)
	public BigDecimal getPrixUnitaire() {
		return this.prixUnitaire;
	}

	public void setPrixUnitaire(BigDecimal prixUnitaire) {
		this.prixUnitaire = prixUnitaire;
	}

	@Column(name = "taux_tva", precision = 10)
	public Float getTauxTva() {
		return this.tauxTva;
	}

	public void setTauxTva(Float tauxTva) {
		this.tauxTva = tauxTva;
	}

	@Column(name = "montant_ttc", nullable = false, precision = 10)
	public BigDecimal getMontantTtc() {
		return this.montantTtc;
	}

	public void setMontantTtc(BigDecimal montantTtc) {
		this.montantTtc = montantTtc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "prestationMarche")
	public List<DetailRealisationPrestation> getDetailRealisationPrestations() {
		return this.detailRealisationPrestations;
	}

	public void setDetailRealisationPrestations(List<DetailRealisationPrestation> detailRealisationPrestations) {
		this.detailRealisationPrestations = detailRealisationPrestations;
	}

	@Transient
	@Override
	public Integer getIdenfiant() {
		return id;
	}

	@Transient
	@Override
	public String getIdentifiantName() {
		return "id";
	}
}