package dz.gov.mesrs.sii.commons.data.model.gfc;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;

import dz.gov.mesrs.sii.commons.data.model.Identifiable;
import dz.gov.mesrs.sii.commons.data.model.referentiel.Nomenclature;

/**
 * ProduitMarche generated by hbm2java
 */
@Entity
@Table(name = "produit_marche", schema = "gfc")
public class ProduitMarche implements java.io.Serializable, Identifiable<Integer> {

	private static final long serialVersionUID = 1L;

	private Integer id;
	private Marche marche;
	private Integer idProduit;
	private Float quantite;
	private Nomenclature unite;
	private BigDecimal prixUnitaire;
	private Float tauxTva;
	private BigDecimal montantTtc;
	private List<DetailRealisationProduit> detailRealisationProduits = new ArrayList<DetailRealisationProduit>();

	public ProduitMarche() {
	}

	public ProduitMarche(Integer id, Marche marche, Integer idProduit, Float quantite, Nomenclature unite,
			BigDecimal montantTtc) {
		this.id = id;
		this.marche = marche;
		this.idProduit = idProduit;
		this.quantite = quantite;
		this.unite = unite;
		this.montantTtc = montantTtc;
	}

	public ProduitMarche(Integer id, Marche marche, Integer idProduit, Float quantite, Nomenclature unite,
			BigDecimal prixUnitaire, Float tauxTva, BigDecimal montantTtc,
			List<DetailRealisationProduit> detailRealisationProduits) {
		this.id = id;
		this.marche = marche;
		this.idProduit = idProduit;
		this.quantite = quantite;
		this.unite = unite;
		this.prixUnitaire = prixUnitaire;
		this.tauxTva = tauxTva;
		this.montantTtc = montantTtc;
		this.detailRealisationProduits = detailRealisationProduits;
	}

	@SequenceGenerator(name = "produit_marche_id_seq", sequenceName = "gfc.produit_marche_id_seq")
	@Id
	@GeneratedValue(generator = "produit_marche_id_seq")
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_marche", nullable = false)
	public Marche getMarche() {
		return this.marche;
	}

	public void setMarche(Marche marche) {
		this.marche = marche;
	}

	@Column(name = "id_produit", nullable = false)
	public Integer getIdProduit() {
		return this.idProduit;
	}

	public void setIdProduit(Integer idProduit) {
		this.idProduit = idProduit;
	}

	@Column(name = "quantite", nullable = false, precision = 10)
	public Float getQuantite() {
		return this.quantite;
	}

	public void setQuantite(Float quantite) {
		this.quantite = quantite;
	}

	@Column(name = "id_unite", nullable = false)
	public Nomenclature getUnite() {
		return this.unite;
	}

	public void setUnite(Nomenclature unite) {
		this.unite = unite;
	}

	@Column(name = "prix_unitaire", precision = 10)
	public BigDecimal getPrixUnitaire() {
		return this.prixUnitaire;
	}

	public void setPrixUnitaire(BigDecimal prixUnitaire) {
		this.prixUnitaire = prixUnitaire;
	}

	@Column(name = "taux_tva", precision = 10)
	public Float getTauxTva() {
		return this.tauxTva;
	}

	public void setTauxTva(Float tauxTva) {
		this.tauxTva = tauxTva;
	}

	@Column(name = "montant_ttc", nullable = false, precision = 10)
	public BigDecimal getMontantTtc() {
		return this.montantTtc;
	}

	public void setMontantTtc(BigDecimal montantTtc) {
		this.montantTtc = montantTtc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "produitMarche")
	public List<DetailRealisationProduit> getDetailRealisationProduits() {
		return this.detailRealisationProduits;
	}

	public void setDetailRealisationProduits(List<DetailRealisationProduit> detailRealisationProduits) {
		this.detailRealisationProduits = detailRealisationProduits;
	}

	@Transient
	@Override
	public Integer getIdenfiant() {
		return id;
	}

	@Transient
	@Override
	public String getIdentifiantName() {
		return "id";
	}
}