package dz.gov.mesrs.sii.commons.data.model.gfc;

// Generated 24 nov. 2014 16:52:54 by Hibernate Tools 3.6.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import dz.gov.mesrs.sii.commons.data.model.Identifiable;
import dz.gov.mesrs.sii.commons.data.model.bpm.SituationEntite;
import dz.gov.mesrs.sii.commons.data.model.referentiel.Nomenclature;

/**
 * ProgrammeNational generated by hbm2java
 */
@Entity
@Table(name = "programme_national", schema = "gfc")
public class ProgrammeNational implements java.io.Serializable, Identifiable<Integer> {

	/**
	 * @author Mounir.MESSAOUDI on : 24 nov. 2014 17:33:48
	 */
	private static final long serialVersionUID = 1L;

	private Integer id;
	private Nomenclature type;
	private SituationEntite situation;
	private String code;
	private String intituleFr;
	private String intituleAr;
	private Short anneeDebut;
	private Short anneeFin;
	private Date dateCreation;
	private Date dateCloture;
	private String observation;

	public ProgrammeNational() {
	}

	public ProgrammeNational(Integer id, Nomenclature nomenclature, SituationEntite situationEntite, String intituleFr,
			String intituleAr, Short anneeDebut) {
		this.id = id;
		this.type = nomenclature;
		this.situation = situationEntite;
		this.intituleFr = intituleFr;
		this.intituleAr = intituleAr;
		this.anneeDebut = anneeDebut;
	}

	public ProgrammeNational(Integer id, Nomenclature nomenclature, SituationEntite situationEntite, String code,
			String intituleFr, String intituleAr, Short anneeDebut, Short anneeFin, Date dateCreation,
			Date dateCloture, String observation) {
		this.id = id;
		this.type = nomenclature;
		this.situation = situationEntite;
		this.code = code;
		this.intituleFr = intituleFr;
		this.intituleAr = intituleAr;
		this.anneeDebut = anneeDebut;
		this.anneeFin = anneeFin;
		this.dateCreation = dateCreation;
		this.dateCloture = dateCloture;
		this.observation = observation;
	}

	@SequenceGenerator(name = "programme_national_id_seq", sequenceName = "gfc.programme_national_id_seq")
	@Id
	@GeneratedValue(generator = "programme_national_id_seq")
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_type_programme", nullable = false)
	public Nomenclature getType() {
		return this.type;
	}

	public void setType(Nomenclature type) {
		this.type = type;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_situation", nullable = false)
	public SituationEntite getSituation() {
		return this.situation;
	}

	public void setSituation(SituationEntite situation) {
		this.situation = situation;
	}

	@Column(name = "code", nullable = false, unique = true, length = 10)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "intitule_fr", nullable = false, length = 200)
	public String getIntituleFr() {
		return this.intituleFr;
	}

	public void setIntituleFr(String intituleFr) {
		this.intituleFr = intituleFr;
	}

	@Column(name = "intitule_ar", nullable = false, length = 200)
	public String getIntituleAr() {
		return this.intituleAr;
	}

	public void setIntituleAr(String intituleAr) {
		this.intituleAr = intituleAr;
	}

	@Column(name = "annee_debut", nullable = false)
	public Short getAnneeDebut() {
		return this.anneeDebut;
	}

	public void setAnneeDebut(Short anneeDebut) {
		this.anneeDebut = anneeDebut;
	}

	@Column(name = "annee_fin")
	public Short getAnneeFin() {
		return this.anneeFin;
	}

	public void setAnneeFin(Short anneeFin) {
		this.anneeFin = anneeFin;
	}

	@Column(name = "date_creation", length = 29)
	public Date getDateCreation() {
		return this.dateCreation;
	}

	public void setDateCreation(Date dateCreation) {
		this.dateCreation = dateCreation;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_cloture", length = 29)
	public Date getDateCloture() {
		return this.dateCloture;
	}

	public void setDateCloture(Date dateCloture) {
		this.dateCloture = dateCloture;
	}

	@Column(name = "observation", length = 200)
	public String getObservation() {
		return this.observation;
	}

	public void setObservation(String observation) {
		this.observation = observation;
	}

	@Transient
	@Override
	public Integer getIdenfiant() {
		return id;
	}

	@Transient
	@Override
	public String getIdentifiantName() {
		return "id";
	}

}
