package dz.gov.mesrs.sii.commons.data.model.gfc;

// Generated 24 nov. 2014 16:52:54 by Hibernate Tools 3.6.0

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import dz.gov.mesrs.sii.commons.data.model.Identifiable;
import dz.gov.mesrs.sii.commons.data.model.bpm.SituationEntite;
import dz.gov.mesrs.sii.commons.data.model.referentiel.Nomenclature;
import dz.gov.mesrs.sii.commons.data.model.referentiel.RefEtablissement;
import dz.gov.mesrs.sii.commons.data.model.referentiel.RefStructure;

/**
 * Regie generated by hbm2java
 */
@Entity
@Table(name = "regie", schema = "gfc")
public class Regie implements java.io.Serializable, Identifiable<Integer> {

	/**
	 * @author Mounir.MESSAOUDI on : 24 nov. 2014 17:34:14
	 */
	private static final long serialVersionUID = 1L;

	private Integer id;
	private RefStructure refStructure;
	private Nomenclature typeRegie;
	private Ordonnateur ordonnateur;
	private Compte compteDepot;
	private AgentComptable agentComptable;
	private Compte compteCcp;
	private RefEtablissement refEtablissement;
	private SituationEntite situationEntite;
	private String objetFr;
	private String objetAr;
	private Date dateOuverture;
	private String observationOuverture;
	private Date dateCloture;
	private String observationCloture;
	private List<Regisseur> regisseurs = new ArrayList<Regisseur>(0);
	private List<AffectationRegieChapitreArticle> affectationRegieChapitreArticles = new ArrayList<AffectationRegieChapitreArticle>(0);

	public Regie() {
	}

	public Regie(Integer id, RefStructure refStructure, Nomenclature typeRegie, Ordonnateur ordonnateur,
			AgentComptable agentComptable, RefEtablissement refEtablissement, SituationEntite situationEntite,
			String objetFr, String objetAr) {
		this.id = id;
		this.refStructure = refStructure;
		this.typeRegie = typeRegie;
		this.ordonnateur = ordonnateur;
		this.agentComptable = agentComptable;
		this.refEtablissement = refEtablissement;
		this.situationEntite = situationEntite;
		this.objetFr = objetFr;
		this.objetAr = objetAr;
	}

	public Regie(Integer id, RefStructure refStructure, Nomenclature typeRegie, Ordonnateur ordonnateur,
			Compte compteDepot, AgentComptable agentComptable, Compte compteCcp,
			RefEtablissement refEtablissement, SituationEntite situationEntite, String objetFr, String objetAr,
			Date dateOuverture, String observationOuverture, Date dateCloture, String observationCloture,
			List<Regisseur> regisseurs, List<AffectationRegieChapitreArticle> affectationRegieChapitreArticles) {
		this.id = id;
		this.refStructure = refStructure;
		this.typeRegie = typeRegie;
		this.ordonnateur = ordonnateur;
		this.compteDepot = compteDepot;
		this.agentComptable = agentComptable;
		this.compteCcp = compteCcp;
		this.refEtablissement = refEtablissement;
		this.situationEntite = situationEntite;
		this.objetFr = objetFr;
		this.objetAr = objetAr;
		this.dateOuverture = dateOuverture;
		this.observationOuverture = observationOuverture;
		this.dateCloture = dateCloture;
		this.observationCloture = observationCloture;
		this.regisseurs = regisseurs;
		this.affectationRegieChapitreArticles = affectationRegieChapitreArticles;
	}

	@SequenceGenerator(name = "regie_id_seq", sequenceName = "gfc.regie_id_seq")
	@Id
	@GeneratedValue(generator = "regie_id_seq")
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_structure", nullable = false)
	public RefStructure getRefStructure() {
		return this.refStructure;
	}

	public void setRefStructure(RefStructure refStructure) {
		this.refStructure = refStructure;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_type_regie", nullable = false)
	public Nomenclature getTypeRegie() {
		return this.typeRegie;
	}

	public void setTypeRegie(Nomenclature typeRegie) {
		this.typeRegie = typeRegie;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_ordonnateur", nullable = false)
	public Ordonnateur getOrdonnateur() {
		return this.ordonnateur;
	}

	public void setOrdonnateur(Ordonnateur ordonnateur) {
		this.ordonnateur = ordonnateur;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_compte_depot")
	public Compte getCompteDepot() {
		return this.compteDepot;
	}

	public void setCompteDepot(Compte compteDepot) {
		this.compteDepot = compteDepot;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_agent_comptable", nullable = false)
	public AgentComptable getAgentComptable() {
		return this.agentComptable;
	}

	public void setAgentComptable(AgentComptable agentComptable) {
		this.agentComptable = agentComptable;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_compte_ccp")
	public Compte getCompteCcp() {
		return this.compteCcp;
	}

	public void setCompteCcp(Compte compteCcp) {
		this.compteCcp = compteCcp;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_etablissement", nullable = false)
	public RefEtablissement getRefEtablissement() {
		return this.refEtablissement;
	}

	public void setRefEtablissement(RefEtablissement refEtablissement) {
		this.refEtablissement = refEtablissement;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_situation", nullable = false)
	public SituationEntite getSituationEntite() {
		return this.situationEntite;
	}

	public void setSituationEntite(SituationEntite situationEntite) {
		this.situationEntite = situationEntite;
	}

	@Column(name = "objet_fr", nullable = false, length = 200)
	public String getObjetFr() {
		return this.objetFr;
	}

	public void setObjetFr(String objetFr) {
		this.objetFr = objetFr;
	}

	@Column(name = "objet_ar", nullable = true, length = 200)
	public String getObjetAr() {
		return this.objetAr;
	}

	public void setObjetAr(String objetAr) {
		this.objetAr = objetAr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_ouverture", length = 29)
	public Date getDateOuverture() {
		return this.dateOuverture;
	}

	public void setDateOuverture(Date dateOuverture) {
		this.dateOuverture = dateOuverture;
	}

	@Column(name = "observation_ouverture", length = 200)
	public String getObservationOuverture() {
		return this.observationOuverture;
	}

	public void setObservationOuverture(String observationOuverture) {
		this.observationOuverture = observationOuverture;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_cloture", length = 29)
	public Date getDateCloture() {
		return this.dateCloture;
	}

	public void setDateCloture(Date dateCloture) {
		this.dateCloture = dateCloture;
	}

	@Column(name = "observation_cloture", length = 200)
	public String getObservationCloture() {
		return this.observationCloture;
	}

	public void setObservationCloture(String observationCloture) {
		this.observationCloture = observationCloture;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "regie")
	public List<Regisseur> getRegisseurs() {
		return this.regisseurs;
	}

	public void setRegisseurs(List<Regisseur> regisseurs) {
		this.regisseurs = regisseurs;
	}

	/*
	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "affectation_regie_chapitre_article", schema = "gfc", 
	joinColumns = { @JoinColumn(name = "id_regie", nullable = false, updatable = false) }, 
	inverseJoinColumns = { @JoinColumn(name = "id_affectation_etab_chapitre_article", nullable = false, updatable = false) })
	*/
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "regie", cascade = { CascadeType.ALL }, orphanRemoval = true)
	public List<AffectationRegieChapitreArticle> getAffectationRegieChapitreArticles() {
		return this.affectationRegieChapitreArticles;
	}

	public void setAffectationRegieChapitreArticles(List<AffectationRegieChapitreArticle> affectationRegieChapitreArticles) {
		this.affectationRegieChapitreArticles = affectationRegieChapitreArticles;
	}

	@Transient
	@Override
	public Integer getIdenfiant() {
		return id;
	}

	@Transient
	@Override
	public String getIdentifiantName() {
		return "id";
	}

}
