package dz.gov.mesrs.sii.commons.data.model.grh;

// Generated 21 oct. 2014 11:36:27 by Hibernate Tools 3.6.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import dz.gov.mesrs.sii.commons.data.model.Identifiable;
import dz.gov.mesrs.sii.commons.data.model.bpm.SituationEntite;
import dz.gov.mesrs.sii.commons.data.model.referentiel.Nomenclature;
import dz.gov.mesrs.sii.commons.data.model.referentiel.RefEtablissement;

/**
 * BesoinRecrutement generated by hbm2java
 */
@Entity
@Table(name = "besoin_recrutement", schema = "grh")
public class BesoinRecrutement implements java.io.Serializable, Identifiable<Integer> {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private RefEtablissement refEtablissement;
	private Nomenclature nomenclatureByTypeRecrutement;
	private Date dateOuverture;
	private String objet;
	private Nomenclature nomenclatureByModeRecrutement;
	private Date dateDepot;
	private Date dateRecrutement;
	private Date datePublication;
	private String observation;
	private Boolean cloture;
	private Date dateCloture;
	private Set<DetailRecrutement> detailRecrutements = new HashSet<DetailRecrutement>(0);
	private SituationEntite situationEntite;

	public BesoinRecrutement() {
	}

	public BesoinRecrutement(Integer id) {
		this.id = id;
	}

	@Id
	@SequenceGenerator(name = "grh_besoin_recrutement_id_seq", initialValue = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "grh_besoin_recrutement_id_seq")
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "etablissement")
	public RefEtablissement getRefEtablissement() {
		return this.refEtablissement;
	}

	public void setRefEtablissement(RefEtablissement refEtablissement) {
		this.refEtablissement = refEtablissement;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "type_recrutement")
	public Nomenclature getNomenclatureByTypeRecrutement() {
		return nomenclatureByTypeRecrutement;
	}

	public void setNomenclatureByTypeRecrutement(Nomenclature nomenclatureByTypeRecrutement) {
		this.nomenclatureByTypeRecrutement = nomenclatureByTypeRecrutement;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_ouverture", length = 13)
	public Date getDateOuverture() {
		return this.dateOuverture;
	}

	public void setDateOuverture(Date dateOuverture) {
		this.dateOuverture = dateOuverture;
	}

	@Column(name = "objet", length = 256)
	public String getObjet() {
		return this.objet;
	}

	public void setObjet(String objet) {
		this.objet = objet;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "mode_recrutement")
	public Nomenclature getNomenclatureByModeRecrutement() {
		return nomenclatureByModeRecrutement;
	}

	public void setNomenclatureByModeRecrutement(Nomenclature nomenclatureByModeRecrutement) {
		this.nomenclatureByModeRecrutement = nomenclatureByModeRecrutement;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_depot", length = 13)
	public Date getDateDepot() {
		return this.dateDepot;
	}

	public void setDateDepot(Date dateDepot) {
		this.dateDepot = dateDepot;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_recrutement", length = 13)
	public Date getDateRecrutement() {
		return this.dateRecrutement;
	}

	public void setDateRecrutement(Date dateRecrutement) {
		this.dateRecrutement = dateRecrutement;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_publication", length = 13)
	public Date getDatePublication() {
		return this.datePublication;
	}

	public void setDatePublication(Date datePublication) {
		this.datePublication = datePublication;
	}

	@Column(name = "observation")
	public String getObservation() {
		return this.observation;
	}

	public void setObservation(String observation) {
		this.observation = observation;
	}

	@Column(name = "cloture")
	public Boolean getCloture() {
		return this.cloture;
	}

	public void setCloture(Boolean cloture) {
		this.cloture = cloture;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_cloture", length = 13)
	public Date getDateCloture() {
		return this.dateCloture;
	}

	public void setDateCloture(Date dateCloture) {
		this.dateCloture = dateCloture;
	}

	@OneToMany(orphanRemoval = true, cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "besoinRecrutement")
	public Set<DetailRecrutement> getDetailRecrutements() {
		return this.detailRecrutements;
	}

	public void setDetailRecrutements(Set<DetailRecrutement> detailRecrutements) {
		this.detailRecrutements = detailRecrutements;
	}

	@Transient
	@Override
	public Integer getIdenfiant() {
		return this.getId();
	}

	@Transient
	@Override
	public String getIdentifiantName() {
		return "id";
	}

	/**
	 * [BesoinRecrutement.situationEntite] Getter
	 * 
	 * @author BELDI Jamel on : 18 déc. 2014 12:35:01
	 * @return the situationEntite
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "situation")
	public SituationEntite getSituationEntite() {
		return situationEntite;
	}

	/**
	 * [BesoinRecrutement.situationEntite] Setter
	 * 
	 * @author BELDI Jamel on : 18 déc. 2014 12:35:01
	 * @param situationEntite
	 *            the situationEntite to set
	 */
	public void setSituationEntite(SituationEntite situationEntite) {
		this.situationEntite = situationEntite;
	}

}
