package dz.gov.mesrs.sii.commons.data.model.grh;

// Generated 21 oct. 2014 11:36:27 by Hibernate Tools 3.6.0

import java.util.Date;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import dz.gov.mesrs.sii.commons.data.model.Identifiable;
import dz.gov.mesrs.sii.commons.data.model.referentiel.RefIndividu;
import dz.gov.mesrs.sii.commons.data.model.referentiel.RefStructure;

/**
 * CandidatEmploye generated by hbm2java
 */
@Entity
@Table(name = "candidat_employe", schema = "grh")
public class CandidatEmploye implements java.io.Serializable, Identifiable<Integer> {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private RefIndividu refIndividu;
	private DetailRecrutement detailRecrutement;
	private Date dateDepot;
	private String observation;
	private Date dateSelection;
	private Boolean retenu;
	private Date dateConvocation;
	private String motifConvocation;
	private Boolean installe;
	private Date dateDecesion;
	private Date dateConvocationRec;
	private Integer classement;
	private Boolean desistement;
	private Date dateDesistement;
	private String motifDesistement;
	private Boolean admis;
	private Date dateSignature;
	private Date dateInstallation;
	private String matricule;
	private String referenceDecision;
	private RefStructure refStructure;
	private Boolean valide;
	private Date dateValidation;

	public CandidatEmploye() {
	}

	public CandidatEmploye(Integer id) {
		this.id = id;
	}

	public CandidatEmploye(Integer id, RefIndividu refIndividu, DetailRecrutement detailRecrutement, Date dateDepot,
			String observation, Integer dossierEmploye, Date dateSelection, Boolean retenu, Date dateConvocation,
			String motifConvocation, Boolean installe, Date dateDecesion, Date dateConvocationRec, Integer classement,
			Boolean desistement, Date dateDesistement, String motifDesistement, Boolean admis, Date dateSignature,
			Date dateInstallation, String matricule, Boolean titularise, Set<Stage> stages) {
		this.id = id;
		this.refIndividu = refIndividu;
		this.detailRecrutement = detailRecrutement;
		this.dateDepot = dateDepot;
		this.observation = observation;
		this.dateSelection = dateSelection;
		this.retenu = retenu;
		this.dateConvocation = dateConvocation;
		this.motifConvocation = motifConvocation;
		this.installe = installe;
		this.dateDecesion = dateDecesion;
		this.dateConvocationRec = dateConvocationRec;
		this.classement = classement;
		this.desistement = desistement;
		this.dateDesistement = dateDesistement;
		this.motifDesistement = motifDesistement;
		this.admis = admis;
		this.dateSignature = dateSignature;
		this.dateInstallation = dateInstallation;
		this.matricule = matricule;

	}

	@Id
	@SequenceGenerator(name = "grh_candidat_employe_id_seq", initialValue = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "grh_candidat_employe_id_seq")
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "individu")
	public RefIndividu getRefIndividu() {
		return this.refIndividu;
	}

	public void setRefIndividu(RefIndividu refIndividu) {
		this.refIndividu = refIndividu;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "detail_recrutement")
	public DetailRecrutement getDetailRecrutement() {
		return this.detailRecrutement;
	}

	public void setDetailRecrutement(DetailRecrutement detailRecrutement) {
		this.detailRecrutement = detailRecrutement;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_depot", length = 13)
	public Date getDateDepot() {
		return this.dateDepot;
	}

	public void setDateDepot(Date dateDepot) {
		this.dateDepot = dateDepot;
	}

	@Column(name = "observation")
	public String getObservation() {
		return this.observation;
	}

	public void setObservation(String observation) {
		this.observation = observation;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_selection", length = 13)
	public Date getDateSelection() {
		return this.dateSelection;
	}

	public void setDateSelection(Date dateSelection) {
		this.dateSelection = dateSelection;
	}

	@Column(name = "retenu")
	public Boolean getRetenu() {
		return this.retenu;
	}

	public void setRetenu(Boolean retenu) {
		this.retenu = retenu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_convocation", length = 13)
	public Date getDateConvocation() {
		return this.dateConvocation;
	}

	public void setDateConvocation(Date dateConvocation) {
		this.dateConvocation = dateConvocation;
	}

	@Column(name = "motif_convocation")
	public String getMotifConvocation() {
		return this.motifConvocation;
	}

	public void setMotifConvocation(String motifConvocation) {
		this.motifConvocation = motifConvocation;
	}

	@Column(name = "installe")
	public Boolean getInstalle() {
		return installe;
	}

	public void setInstalle(Boolean installe) {
		this.installe = installe;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_decesion", length = 13)
	public Date getDateDecesion() {
		return this.dateDecesion;
	}

	public void setDateDecesion(Date dateDecesion) {
		this.dateDecesion = dateDecesion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_convocation_rec", length = 13)
	public Date getDateConvocationRec() {
		return this.dateConvocationRec;
	}

	public void setDateConvocationRec(Date dateConvocationRec) {
		this.dateConvocationRec = dateConvocationRec;
	}

	@Column(name = "classement")
	public Integer getClassement() {
		return this.classement;
	}

	public void setClassement(Integer classement) {
		this.classement = classement;
	}

	@Column(name = "desistement")
	public Boolean getDesistement() {
		return this.desistement;
	}

	public void setDesistement(Boolean desistement) {
		this.desistement = desistement;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_desistement", length = 13)
	public Date getDateDesistement() {
		return this.dateDesistement;
	}

	public void setDateDesistement(Date dateDesistement) {
		this.dateDesistement = dateDesistement;
	}

	@Column(name = "motif_desistement")
	public String getMotifDesistement() {
		return this.motifDesistement;
	}

	public void setMotifDesistement(String motifDesistement) {
		this.motifDesistement = motifDesistement;
	}

	@Column(name = "admis")
	public Boolean getAdmis() {
		return this.admis;
	}

	public void setAdmis(Boolean admis) {
		this.admis = admis;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_signature", length = 13)
	public Date getDateSignature() {
		return this.dateSignature;
	}

	public void setDateSignature(Date dateSignature) {
		this.dateSignature = dateSignature;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_installation", length = 13)
	public Date getDateInstallation() {
		return this.dateInstallation;
	}

	public void setDateInstallation(Date dateInstallation) {
		this.dateInstallation = dateInstallation;
	}

	@Column(name = "matricule", length = 256)
	public String getMatricule() {
		return this.matricule;
	}

	public void setMatricule(String matricule) {
		this.matricule = matricule;
	}

	@Column(name = "reference_decision")
	public String getReferenceDecision() {
		return referenceDecision;
	}

	public void setReferenceDecision(String referenceDecision) {
		this.referenceDecision = referenceDecision;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "structure")
	public RefStructure getRefStructure() {
		return refStructure;
	}

	public void setRefStructure(RefStructure refStructure) {
		this.refStructure = refStructure;
	}

	@Column(name = "valide")
	public Boolean getValide() {
		return valide;
	}

	public void setValide(Boolean valide) {
		this.valide = valide;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_validation", length = 13)
	public Date getDateValidation() {
		return dateValidation;
	}

	public void setDateValidation(Date dateValidation) {
		this.dateValidation = dateValidation;
	}

	@Transient
	@Override
	public Integer getIdenfiant() {
		return this.getId();
	}

	@Transient
	@Override
	public String getIdentifiantName() {
		return "id";
	}

}
