package dz.gov.mesrs.sii.commons.data.model.grh;

// Generated 21 oct. 2014 11:36:27 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;

import dz.gov.mesrs.sii.commons.data.model.Identifiable;
import dz.gov.mesrs.sii.commons.data.model.referentiel.Nomenclature;

/**
 * Corps generated by hbm2java
 */
@Entity
@Table(name = "corps", schema = "grh")
public class Corps implements java.io.Serializable, Identifiable<Integer> {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Nomenclature nomenclatureByIdNomenclatureFiliere;
	private Statut statut;
	private Nomenclature nomenclatureByIdNomenclatureCorps;
	private String label;
	private Set<Carriere> carrieres = new HashSet<Carriere>(0);
	private Set<DetailRecrutement> detailRecrutements = new HashSet<DetailRecrutement>(0);
	private Set<Grade> grades = new HashSet<Grade>(0);

	public Corps() {
	}

	public Corps(Integer id, Statut statut) {
		this.id = id;
		this.statut = statut;
	}

	public Corps(Integer id, Nomenclature nomenclatureByIdNomenclatureFiliere, Statut statut,
			Nomenclature nomenclatureByIdNomenclatureCorps, String label, Set<Carriere> carrieres,
			Set<DetailRecrutement> detailRecrutements, Set<Grade> grades) {
		this.id = id;
		this.nomenclatureByIdNomenclatureFiliere = nomenclatureByIdNomenclatureFiliere;
		this.statut = statut;
		this.nomenclatureByIdNomenclatureCorps = nomenclatureByIdNomenclatureCorps;
		this.label = label;
		this.carrieres = carrieres;
		this.detailRecrutements = detailRecrutements;
		this.grades = grades;
	}

	@Id
	@SequenceGenerator(name = "grh_corps_id_corps_seq", initialValue = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "grh_corps_id_corps_seq")
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_nomenclature_filiere")
	public Nomenclature getNomenclatureByIdNomenclatureFiliere() {
		return this.nomenclatureByIdNomenclatureFiliere;
	}

	public void setNomenclatureByIdNomenclatureFiliere(Nomenclature nomenclatureByIdNomenclatureFiliere) {
		this.nomenclatureByIdNomenclatureFiliere = nomenclatureByIdNomenclatureFiliere;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "status", nullable = false)
	public Statut getStatut() {
		return this.statut;
	}

	public void setStatut(Statut statut) {
		this.statut = statut;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_nomenclature_corps")
	public Nomenclature getNomenclatureByIdNomenclatureCorps() {
		return this.nomenclatureByIdNomenclatureCorps;
	}

	public void setNomenclatureByIdNomenclatureCorps(Nomenclature nomenclatureByIdNomenclatureCorps) {
		this.nomenclatureByIdNomenclatureCorps = nomenclatureByIdNomenclatureCorps;
	}

	@Column(name = "label", length = 256)
	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "corps")
	public Set<Carriere> getCarrieres() {
		return this.carrieres;
	}

	public void setCarrieres(Set<Carriere> carrieres) {
		this.carrieres = carrieres;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "corps")
	public Set<DetailRecrutement> getDetailRecrutements() {
		return this.detailRecrutements;
	}

	public void setDetailRecrutements(Set<DetailRecrutement> detailRecrutements) {
		this.detailRecrutements = detailRecrutements;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "corps", cascade = CascadeType.ALL)
	public Set<Grade> getGrades() {
		return this.grades;
	}

	public void setGrades(Set<Grade> grades) {
		this.grades = grades;
	}

	@Transient
	@Override
	public Integer getIdenfiant() {
		return this.getId();
	}

	@Transient
	@Override
	public String getIdentifiantName() {
		return "id";
	}

}
