package dz.gov.mesrs.sii.commons.data.model.grh;

// Generated 21 oct. 2014 11:36:27 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;

import dz.gov.mesrs.sii.commons.data.model.Identifiable;
import dz.gov.mesrs.sii.commons.data.model.referentiel.RefStructure;

/**
 * DetailRecrutement generated by hbm2java
 */
@Entity
@Table(name = "detail_recrutement", schema = "grh")
public class DetailRecrutement implements java.io.Serializable, Identifiable<Integer> {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Grade grade;
	private CategorieProfessionnelle categorieProfessionnelle;
	private BesoinRecrutement besoinRecrutement;
	private Corps corps;
	private PosteSuperieure posteSuperieure;
	private String reference;
	private RefStructure refStructure;
	private Set<CandidatEmploye> candidatEmployes = new HashSet<CandidatEmploye>(0);
	private Integer nbrePoste;

	public DetailRecrutement() {
	}

	public DetailRecrutement(Integer id) {
		this.id = id;
	}

	@Id
	@SequenceGenerator(name = "grh_detail_recrutement_id_seq", initialValue = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "grh_detail_recrutement_id_seq")
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "grade")
	public Grade getGrade() {
		return this.grade;
	}

	public void setGrade(Grade grade) {
		this.grade = grade;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "categorie_prof")
	public CategorieProfessionnelle getCategorieProfessionnelle() {
		return this.categorieProfessionnelle;
	}

	public void setCategorieProfessionnelle(CategorieProfessionnelle categorieProfessionnelle) {
		this.categorieProfessionnelle = categorieProfessionnelle;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "besoin_recrutement")
	public BesoinRecrutement getBesoinRecrutement() {
		return this.besoinRecrutement;
	}

	public void setBesoinRecrutement(BesoinRecrutement besoinRecrutement) {
		this.besoinRecrutement = besoinRecrutement;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "corps")
	public Corps getCorps() {
		return this.corps;
	}

	public void setCorps(Corps corps) {
		this.corps = corps;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "poste_superieure")
	public PosteSuperieure getPosteSuperieure() {
		return this.posteSuperieure;
	}

	public void setPosteSuperieure(PosteSuperieure posteSuperieure) {
		this.posteSuperieure = posteSuperieure;
	}

	@Column(name = "reference")
	public String getReference() {
		return this.reference;
	}

	public void setReference(String reference) {
		this.reference = reference;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "structure")
	public RefStructure getRefStructure() {
		return this.refStructure;
	}

	public void setRefStructure(RefStructure refStructure) {
		this.refStructure = refStructure;
	}
	
	
	@Column(name = "nbre_poste")
	public Integer getNbrePoste() {
		return nbrePoste;
	}

	public void setNbrePoste(Integer nbrePoste) {
		this.nbrePoste = nbrePoste;
	}
	

	@OneToMany(orphanRemoval = true, cascade = CascadeType.REMOVE, fetch = FetchType.LAZY, mappedBy = "detailRecrutement")
	public Set<CandidatEmploye> getCandidatEmployes() {
		return this.candidatEmployes;
	}

	public void setCandidatEmployes(Set<CandidatEmploye> candidatEmployes) {
		this.candidatEmployes = candidatEmployes;
	}

	@Transient
	@Override
	public Integer getIdenfiant() {
		return this.getId();
	}

	@Transient
	@Override
	public String getIdentifiantName() {
		return "id";
	}

	

	
	
	
}
