package dz.gov.mesrs.sii.commons.data.model.grh;

// Generated 2 d�c. 2014 09:40:23 by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;

import dz.gov.mesrs.sii.commons.data.model.Identifiable;
import dz.gov.mesrs.sii.commons.data.model.referentiel.Nomenclature;
import dz.gov.mesrs.sii.commons.data.model.referentiel.RefEtablissement;

/**
 * DiplomeEmploye generated by hbm2java
 */
@Entity
@Table(name = "diplome_employe", schema = "grh")
public class DiplomeEmploye implements java.io.Serializable, Identifiable<Integer> {

	/**
	 * serialVersionUID
	 * 
	 * @author BELDI Jamel on : 2 déc. 2014 09:58:41
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private Nomenclature nomenclatureByTypeDiplome;
	private RefEtablissement refEtablissement;
	private String intitule;
	private int anneeObtention;
	private DossierEmploye dossierEmploye;

	public DiplomeEmploye() {
	}

	@Id
	@SequenceGenerator(name = "grh_diplome_employe_id_seq", initialValue = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "grh_diplome_employe_id_seq")
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "employe", nullable = false)
	public DossierEmploye getDossierEmploye() {
		return dossierEmploye;
	}

	public void setDossierEmploye(DossierEmploye dossierEmploye) {
		this.dossierEmploye = dossierEmploye;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "type_diplome", nullable = false)
	public Nomenclature getNomenclatureByTypeDiplome() {
		return nomenclatureByTypeDiplome;
	}

	public void setNomenclatureByTypeDiplome(Nomenclature nomenclatureByTypeDiplome) {
		this.nomenclatureByTypeDiplome = nomenclatureByTypeDiplome;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "etablissement")
	public RefEtablissement getRefEtablissement() {
		return this.refEtablissement;
	}

	public void setRefEtablissement(RefEtablissement refEtablissement) {
		this.refEtablissement = refEtablissement;
	}

	@Column(name = "intitule")
	public String getIntitule() {
		return this.intitule;
	}

	public void setIntitule(String intitule) {
		this.intitule = intitule;
	}

	@Column(name = "annee_obtention", nullable = false)
	public int getAnneeObtention() {
		return this.anneeObtention;
	}

	public void setAnneeObtention(int anneeObtention) {
		this.anneeObtention = anneeObtention;
	}

	@Transient
	@Override
	public Integer getIdenfiant() {
		return this.getId();
	}

	@Transient
	@Override
	public String getIdentifiantName() {
		return "id";
	}

}
