package dz.gov.mesrs.sii.commons.data.model.grh;

// Generated 21 oct. 2014 11:36:27 by Hibernate Tools 3.6.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import dz.gov.mesrs.sii.commons.data.model.Identifiable;
import dz.gov.mesrs.sii.commons.data.model.referentiel.Nomenclature;

/**
 * Distinction generated by hbm2java
 */
@Entity
@Table(name = "distinction", schema = "grh")
public class Distinction implements java.io.Serializable, Identifiable<Integer> {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Nomenclature nomenclatureByDistinction;
	private DossierEmploye dossierEmploye;
	private Date dateDistinction;

	public Distinction() {
	}

	@Id
	@SequenceGenerator(name = "grh_distinction_id_seq", initialValue = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "grh_distinction_id_seq")
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "employe", nullable = false)
	public DossierEmploye getDossierEmploye() {
		return this.dossierEmploye;
	}

	public void setDossierEmploye(DossierEmploye dossierEmploye) {
		this.dossierEmploye = dossierEmploye;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "distinction", nullable = false)
	public Nomenclature getNomenclatureByDistinction() {
		return this.nomenclatureByDistinction;
	}

	public void setNomenclatureByDistinction(Nomenclature nomenclatureByDistinction) {
		this.nomenclatureByDistinction = nomenclatureByDistinction;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_distinction", length = 13)
	public Date getDateDistinction() {
		return this.dateDistinction;
	}

	public void setDateDistinction(Date dateDistinction) {
		this.dateDistinction = dateDistinction;
	}

	@Transient
	@Override
	public Integer getIdenfiant() {
		return this.getId();
	}

	@Transient
	@Override
	public String getIdentifiantName() {
		return "id";
	}

}
