package dz.gov.mesrs.sii.commons.data.model.grh;

// Generated 21 oct. 2014 11:36:27 by Hibernate Tools 3.6.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;





import dz.gov.mesrs.sii.commons.data.model.Identifiable;

/**
 * EmployePropose generated by hbm2java
 */
@Entity
@Table(name = "employe_propose", schema = "grh")
public class EmployePropose implements java.io.Serializable, Identifiable<Long> {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long id;
	private PropostionAvancement propostionAvancement;
	private DossierEmploye dossierEmploye;
	private Date dateProposition;
	private GrilleIndiciaire grilleIndiciaire;
	private Date dateEffetProposee;
	private Boolean confirm;
	private Date dateEffetRetenue;
	private Carriere carriere;
	private Integer duree;
	private Boolean selection;
	private Grade nouveauGrade;
	

	public EmployePropose() {
	}

	public EmployePropose(Long id) {
		this.id = id;
	}

	public EmployePropose(Long id, PropostionAvancement propostionAvancement, DossierEmploye dossierEmploye,
			Date dateProposition, GrilleIndiciaire grilleIndiciaire, Date dateEffetProposee, Boolean confirm,
			Date dateEffetRetenue,Carriere carriere,Integer duree,Boolean selection,Grade nouveauGrade) {
		this.id = id;
		this.propostionAvancement = propostionAvancement;
		this.dossierEmploye = dossierEmploye;
		this.dateProposition = dateProposition;
		this.grilleIndiciaire = grilleIndiciaire;
		this.dateEffetProposee = dateEffetProposee;
		this.confirm = confirm;
		this.dateEffetRetenue = dateEffetRetenue;
		this.carriere=carriere;
		this.duree=duree;
		this.selection = selection;
		this.nouveauGrade=nouveauGrade;
	}

	@Id
	@SequenceGenerator(name = "grh.employe_propose_id_employe_propose_seq", initialValue = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "grh.employe_propose_id_employe_propose_seq")
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_proposition")
	public PropostionAvancement getPropostionAvancement() {
		return this.propostionAvancement;
	}

	public void setPropostionAvancement(PropostionAvancement propostionAvancement) {
		this.propostionAvancement = propostionAvancement;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "employe")
	public DossierEmploye getDossierEmploye() {
		return this.dossierEmploye;
	}

	public void setDossierEmploye(DossierEmploye dossierEmploye) {
		this.dossierEmploye = dossierEmploye;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_proposition", length = 13)
	public Date getDateProposition() {
		return this.dateProposition;
	}

	public void setDateProposition(Date dateProposition) {
		this.dateProposition = dateProposition;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "avancement")
	public GrilleIndiciaire getgrilleIndiciaire() {
		return this.grilleIndiciaire;
	}

	public void setGrilleIndiciaire(GrilleIndiciaire grilleIndiciaire) {
		this.grilleIndiciaire = grilleIndiciaire;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_effet_proposee", length = 13)
	public Date getDateEffetProposee() {
		return this.dateEffetProposee;
	}

	public void setDateEffetProposee(Date dateEffetProposee) {
		this.dateEffetProposee = dateEffetProposee;
	}

	
	

	@Temporal(TemporalType.DATE)
	@Column(name = "date_effet_retenue", length = 13)
	public Date getDateEffetRetenue() {
		return this.dateEffetRetenue;
	}

	public void setDateEffetRetenue(Date dateEffetRetenue) {
		this.dateEffetRetenue = dateEffetRetenue;
	}
	
	
	
	
	
	/**
	 * [EmployePropose.carriere] Getter 
	 * @author obelbrik on : 14 dc. 2014  10:03:11
	 * @return the carriere
	 */
	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "evenement_carriere")
	public Carriere getCarriere() {
		return carriere;
	}

	/**
	 * [EmployePropose.carriere] Setter 
	 * @author obelbrik on : 14 dc. 2014  10:03:11
	 * @param carriere the carriere to set
	 */
	public void setCarriere(Carriere carriere) {
		this.carriere = carriere;
	}
	
	

	/**
	 * [EmployePropose.duree] Getter 
	 * @author obelbrik on : 14 dc. 2014  11:44:54
	 * @return the duree
	 */
	@JoinColumn(name = "duree")
	public Integer getDuree() {
		return duree;
	}

	/**
	 * [EmployePropose.duree] Setter 
	 * @author obelbrik on : 14 dc. 2014  11:44:54
	 * @param duree the duree to set
	 */
	public void setDuree(Integer duree) {
		this.duree = duree;
	}
	
	
	

	/**
	 * [EmployePropose.confirm] Getter 
	 * @author obelbrik on : 14 dc. 2014  12:18:39
	 * @return the confirm
	 */
	@Column(name = "confirm")
	public Boolean getConfirm() {
		return confirm;
	}

	/**
	 * [EmployePropose.confirm] Setter 
	 * @author obelbrik on : 14 dc. 2014  12:18:39
	 * @param confirm the confirm to set
	 */
	public void setConfirm(Boolean confirm) {
		this.confirm = confirm;
	}

	/**
	 * [EmployePropose.selection] Getter 
	 * @author obelbrik on : 14 dc. 2014  12:18:39
	 * @return the selection
	 */
	@Column(name = "selection")
	public Boolean getSelection() {
		return selection;
	}

	/**
	 * [EmployePropose.selection] Setter 
	 * @author obelbrik on : 14 d. 2014  12:18:39
	 * @param selection the selection to set
	 */
	public void setSelection(Boolean selection) {
		this.selection = selection;
	}
	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "nouveau_grade")
	public Grade getNouveauGrade() {
		return nouveauGrade;
	}

	public void setNouveauGrade(Grade nouveauGrade) {
		this.nouveauGrade = nouveauGrade;
	}
	

	@Transient
	@Override
	public Long getIdenfiant() {
		return this.getId();
	}
	@Transient
	@Override
	public String getIdentifiantName() {
		return "id";
	}
	
	

}
