package dz.gov.mesrs.sii.commons.data.model.grh;

// Generated 21 oct. 2014 11:36:27 by Hibernate Tools 3.6.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import dz.gov.mesrs.sii.commons.data.model.Identifiable;
import dz.gov.mesrs.sii.commons.data.model.referentiel.Nomenclature;

/**
 * Enfant generated by hbm2java
 */
@Entity
@Table(name = "enfant", schema = "grh")
public class Enfant implements java.io.Serializable, Identifiable<Integer> {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Nomenclature nomenclatureByLienFiliation;
	private DossierEmploye dossierEmploye;
	private String prenomLatin;
	private String prenomArabe;
	private Date dateNaissance;
	private Boolean avecDifficulte;

	public Enfant() {
	}

	public Enfant(Integer id) {
		this.id = id;
	}

	@Id
	@SequenceGenerator(name = "grh_enfant_id_seq", initialValue = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "grh_enfant_id_seq")
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "lien_filiation")
	public Nomenclature getNomenclatureByLienFiliation() {
		return this.nomenclatureByLienFiliation;
	}

	public void setNomenclatureByLienFiliation(Nomenclature nomenclatureByLienFiliation) {
		this.nomenclatureByLienFiliation = nomenclatureByLienFiliation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "parent", nullable = false)
	public DossierEmploye getDossierEmploye() {
		return this.dossierEmploye;
	}

	public void setDossierEmploye(DossierEmploye dossierEmploye) {
		this.dossierEmploye = dossierEmploye;
	}

	@Column(name = "prenom_latin")
	public String getPrenomLatin() {
		return prenomLatin;
	}

	public void setPrenomLatin(String prenomLatin) {
		this.prenomLatin = prenomLatin;
	}

	@Column(name = "prenom_arabe")
	public String getPrenomArabe() {
		return prenomArabe;
	}

	public void setPrenomArabe(String prenomArabe) {
		this.prenomArabe = prenomArabe;
	}

	@Column(name = "avec_difficulte")
	public Boolean getAvecDifficulte() {
		return this.avecDifficulte;
	}

	public void setAvecDifficulte(Boolean avecDifficulte) {
		this.avecDifficulte = avecDifficulte;
	}

	@Transient
	@Override
	public Integer getIdenfiant() {
		return this.getId();
	}

	@Transient
	@Override
	public String getIdentifiantName() {
		return "id";
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_naissance", length = 13)
	public Date getDateNaissance() {
		return dateNaissance;
	}

	public void setDateNaissance(Date dateNaissance) {
		this.dateNaissance = dateNaissance;
	}

}
