package dz.gov.mesrs.sii.commons.data.model.grh;

// Generated 21 oct. 2014 11:36:27 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;

import dz.gov.mesrs.sii.commons.data.model.Identifiable;
import dz.gov.mesrs.sii.commons.data.model.referentiel.Nomenclature;

/**
 * Grade generated by hbm2java
 */
@Entity
@Table(name = "grade", schema = "grh")
public class Grade implements java.io.Serializable, Identifiable<Integer> {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Nomenclature nomenclature;
	private Corps corps;
	private Long rangGrade;
	private Long inidiceMinimale;
	private Set<PromotionPropose> promotionProposes = new HashSet<PromotionPropose>(0);
	private Set<Carriere> carrieres = new HashSet<Carriere>(0);
	private Set<DetailRecrutement> detailRecrutements = new HashSet<DetailRecrutement>(0);
	private CategorieProfessionnelle categorieProfessionnelle;

	public Grade() {
	}

	public Grade(Integer id) {
		this.id = id;
	}

	public Grade(Integer id, Nomenclature nomenclature, Corps corps, Long rangGrade, Long inidiceMinimale,
			Set<PromotionPropose> promotionProposes, Set<Carriere> carrieres,
			Set<DetailRecrutement> detailRecrutements, CategorieProfessionnelle categorieProfessionnelle) {
		this.id = id;
		this.nomenclature = nomenclature;
		this.corps = corps;
		this.rangGrade = rangGrade;
		this.inidiceMinimale = inidiceMinimale;
		this.promotionProposes = promotionProposes;
		this.carrieres = carrieres;
		this.detailRecrutements = detailRecrutements;
		this.categorieProfessionnelle = categorieProfessionnelle;
	}

	@Id
	@SequenceGenerator(name = "grh_grade_id_grade_seq", initialValue = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "grh_grade_id_grade_seq")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "grade_nomenclature")
	public Nomenclature getNomenclature() {
		return this.nomenclature;
	}

	public void setNomenclature(Nomenclature nomenclature) {
		this.nomenclature = nomenclature;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "corps")
	public Corps getCorps() {
		return this.corps;
	}

	public void setCorps(Corps corps) {
		this.corps = corps;
	}

	@Column(name = "rang_grade")
	public Long getRangGrade() {
		return this.rangGrade;
	}

	public void setRangGrade(Long rangGrade) {
		this.rangGrade = rangGrade;
	}

	@Column(name = "inidice_minimale")
	public Long getInidiceMinimale() {
		return this.inidiceMinimale;
	}

	public void setInidiceMinimale(Long inidiceMinimale) {
		this.inidiceMinimale = inidiceMinimale;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "grade")
	public Set<PromotionPropose> getPromotionProposes() {
		return this.promotionProposes;
	}

	public void setPromotionProposes(Set<PromotionPropose> promotionProposes) {
		this.promotionProposes = promotionProposes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "grade")
	public Set<Carriere> getCarrieres() {
		return this.carrieres;
	}

	public void setCarrieres(Set<Carriere> carrieres) {
		this.carrieres = carrieres;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "grade")
	public Set<DetailRecrutement> getDetailRecrutements() {
		return this.detailRecrutements;
	}

	public void setDetailRecrutements(Set<DetailRecrutement> detailRecrutements) {
		this.detailRecrutements = detailRecrutements;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "categorie_professionnelle", nullable = true, insertable = true)
	public CategorieProfessionnelle getCategorieProfessionnelle() {
		return categorieProfessionnelle;
	}

	public void setCategorieProfessionnelle(CategorieProfessionnelle categorieProfessionnelle) {
		this.categorieProfessionnelle = categorieProfessionnelle;
	}

	@Transient
	@Override
	public Integer getIdenfiant() {
		return this.getId();
	}

	@Transient
	@Override
	public String getIdentifiantName() {
		return "id";
	}

}
