package dz.gov.mesrs.sii.commons.data.model.grh;

// Generated 21 oct. 2014 11:36:27 by Hibernate Tools 3.6.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import dz.gov.mesrs.sii.commons.data.model.Identifiable;

/**
 * PieceDossierRetraite generated by hbm2java
 */
@Entity
@Table(name = "piece_dossier_retraite", schema = "grh")
public class PieceDossierRetraite implements java.io.Serializable, Identifiable<Integer> {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private FinActivite finActivite;
	private Boolean prepare;
	private Date datePreparation;

	public PieceDossierRetraite() {
	}

	public PieceDossierRetraite(Integer id) {
		this.id = id;
	}

	public PieceDossierRetraite(Integer id, FinActivite finActivite, Boolean prepare, Date datePreparation) {
		this.id = id;
		this.finActivite = finActivite;
		this.prepare = prepare;
		this.datePreparation = datePreparation;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fin_activite")
	public FinActivite getFinActivite() {
		return this.finActivite;
	}

	public void setFinActivite(FinActivite finActivite) {
		this.finActivite = finActivite;
	}

	@Column(name = "prepare")
	public Boolean getPrepare() {
		return this.prepare;
	}

	public void setPrepare(Boolean prepare) {
		this.prepare = prepare;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_preparation", length = 13)
	public Date getDatePreparation() {
		return this.datePreparation;
	}

	public void setDatePreparation(Date datePreparation) {
		this.datePreparation = datePreparation;
	}

	@Transient
	@Override
	public Integer getIdenfiant() {
		return this.getId();
	}

	@Transient
	@Override
	public String getIdentifiantName() {
		return "id";
	}

}
