package dz.gov.mesrs.sii.commons.data.model.grh;

// Generated 21 oct. 2014 11:36:27 by Hibernate Tools 3.6.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import dz.gov.mesrs.sii.commons.data.model.Identifiable;
import dz.gov.mesrs.sii.commons.data.model.referentiel.Nomenclature;


/**
 * PromotionEmploye generated by hbm2java
 */
@Entity
@Table(name = "promotion_employe", schema = "grh")
public class PromotionEmploye implements java.io.Serializable, Identifiable<Integer>  {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Nomenclature nomenclature;
	private Date dateProposition;
	private Integer mois;
	private Integer annee;
	private String observation;
	private Set<PromotionPropose> promotionProposes = new HashSet<PromotionPropose>(
			0);

	public PromotionEmploye() {
	}

	public PromotionEmploye(Integer id) {
		this.id = id;
	}

	public PromotionEmploye(Integer id, Nomenclature nomenclature,
			Date dateProposition, Integer mois, Integer annee,
			String observation, Set<PromotionPropose> promotionProposes) {
		this.id = id;
		this.nomenclature = nomenclature;
		this.dateProposition = dateProposition;
		this.mois = mois;
		this.annee = annee;
		this.observation = observation;
		this.promotionProposes = promotionProposes;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "type_promotion")
	public Nomenclature getNomenclature() {
		return this.nomenclature;
	}

	public void setNomenclature(Nomenclature nomenclature) {
		this.nomenclature = nomenclature;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_proposition", length = 13)
	public Date getDateProposition() {
		return this.dateProposition;
	}

	public void setDateProposition(Date dateProposition) {
		this.dateProposition = dateProposition;
	}

	@Column(name = "mois")
	public Integer getMois() {
		return this.mois;
	}

	public void setMois(Integer mois) {
		this.mois = mois;
	}

	@Column(name = "annee")
	public Integer getAnnee() {
		return this.annee;
	}

	public void setAnnee(Integer annee) {
		this.annee = annee;
	}

	@Column(name = "observation")
	public String getObservation() {
		return this.observation;
	}

	public void setObservation(String observation) {
		this.observation = observation;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "promotionEmploye")
	public Set<PromotionPropose> getPromotionProposes() {
		return this.promotionProposes;
	}

	public void setPromotionProposes(Set<PromotionPropose> promotionProposes) {
		this.promotionProposes = promotionProposes;
	}
	
	@Transient
	@Override
	public Integer getIdenfiant() {
		return this.getId();
	}

	@Transient
	@Override
	public String getIdentifiantName() {
		return "id";
	}

}
