package dz.gov.mesrs.sii.commons.data.model.grh;

// Generated 21 oct. 2014 11:36:27 by Hibernate Tools 3.6.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import dz.gov.mesrs.sii.commons.data.model.Identifiable;

/**
 * PromotionPropose generated by hbm2java
 */
@Entity
@Table(name = "promotion_propose", schema = "grh")
public class PromotionPropose implements java.io.Serializable, Identifiable<Integer> {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Grade grade;
	private PromotionEmploye promotionEmploye;
	private DossierEmploye dossierEmploye;
	private Date dateEffet;
	private Date dateRetenue;
	private Date dateDecesion;

	public PromotionPropose() {
	}

	public PromotionPropose(Integer id) {
		this.id = id;
	}

	public PromotionPropose(Integer id, Grade grade, PromotionEmploye promotionEmploye, DossierEmploye dossierEmploye,
			Date dateEffet, Date dateRetenue, Date dateDecesion) {
		this.id = id;
		this.grade = grade;
		this.promotionEmploye = promotionEmploye;
		this.dossierEmploye = dossierEmploye;
		this.dateEffet = dateEffet;
		this.dateRetenue = dateRetenue;
		this.dateDecesion = dateDecesion;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "grade")
	public Grade getGrade() {
		return this.grade;
	}

	public void setGrade(Grade grade) {
		this.grade = grade;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "promotion")
	public PromotionEmploye getPromotionEmploye() {
		return this.promotionEmploye;
	}

	public void setPromotionEmploye(PromotionEmploye promotionEmploye) {
		this.promotionEmploye = promotionEmploye;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "employe")
	public DossierEmploye getDossierEmploye() {
		return this.dossierEmploye;
	}

	public void setDossierEmploye(DossierEmploye dossierEmploye) {
		this.dossierEmploye = dossierEmploye;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_effet", length = 13)
	public Date getDateEffet() {
		return this.dateEffet;
	}

	public void setDateEffet(Date dateEffet) {
		this.dateEffet = dateEffet;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_retenue", length = 13)
	public Date getDateRetenue() {
		return this.dateRetenue;
	}

	public void setDateRetenue(Date dateRetenue) {
		this.dateRetenue = dateRetenue;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_decesion", length = 13)
	public Date getDateDecesion() {
		return this.dateDecesion;
	}

	public void setDateDecesion(Date dateDecesion) {
		this.dateDecesion = dateDecesion;
	}

	@Transient
	@Override
	public Integer getIdenfiant() {
		return this.getId();
	}

	@Transient
	@Override
	public String getIdentifiantName() {
		return "id";
	}

}
