package dz.gov.mesrs.sii.commons.data.model.grh;

// Generated 21 oct. 2014 11:36:27 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;

import dz.gov.mesrs.sii.commons.data.model.Identifiable;
import dz.gov.mesrs.sii.commons.data.model.referentiel.Nomenclature;

/**
 * Absence generated by Oualid BELBRIK
 */
/**
 * @author Oualid BELBRIK
 * 
 */
@Entity
@Table(name = "rubrique", schema = "grh")
public class Rubrique implements java.io.Serializable, Identifiable<Integer> {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String identifiant;
	private Nomenclature nomenclatureByRubrique;
	private Nomenclature nomenclatureByTypeRubrique;
	private Nomenclature nomenclatureByPeriodicite;
	private String decret;
	private Double taux;
	private Double montant;
	private Boolean commune;
	private Boolean soumise_securite;
	private Boolean TauxOuMantant;
	private Set<Filiere> filieres = new HashSet<Filiere>(0);

	public Rubrique() {
	}

	/**
	 * [Rubrique.id] Getter 
	 * @author BELBRIK Oualid on : 17 nov. 2014  15:41:52
	 * @return the id
	 */
	@SequenceGenerator(name = "rubrique_id_seq", sequenceName = "grh.rubrique_id_seq")
	@Id
	@GeneratedValue(generator = "rubrique_id_seq")
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return id;
	}

	/**
	 * [Rubrique.id] Setter 
	 * @author BELBRIK Oualid on : 17 nov. 2014  15:41:52
	 * @param id the id to set
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * [Rubrique.nomenclatureByRubrique] Getter 
	 * @author BELBRIK Oualid on : 17 nov. 2014  15:41:52
	 * @return the nomenclatureByRubrique
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "nc_rubrique")
	public Nomenclature getNomenclatureByRubrique() {
		return nomenclatureByRubrique;
	}

	/**
	 * [Rubrique.nomenclatureByRubrique] Setter 
	 * @author BELBRIK Oualid on : 17 nov. 2014  15:41:52
	 * @param nomenclatureByRubrique the nomenclatureByRubrique to set
	 */
	public void setNomenclatureByRubrique(Nomenclature nomenclatureByRubrique) {
		this.nomenclatureByRubrique = nomenclatureByRubrique;
	}

	/**
	 * [Rubrique.nomenclatureByTypeRubrique] Getter 
	 * @author BELBRIK Oualid on : 17 nov. 2014  15:41:52
	 * @return the nomenclatureByTypeRubrique
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "nc_type_rubrique")
	public Nomenclature getNomenclatureByTypeRubrique() {
		return nomenclatureByTypeRubrique;
	}

	/**
	 * [Rubrique.nomenclatureByTypeRubrique] Setter 
	 * @author BELBRIK Oualid on : 17 nov. 2014  15:41:52
	 * @param nomenclatureByTypeRubrique the nomenclatureByTypeRubrique to set
	 */
	public void setNomenclatureByTypeRubrique(
			Nomenclature nomenclatureByTypeRubrique) {
		this.nomenclatureByTypeRubrique = nomenclatureByTypeRubrique;
	}

	/**
	 * [Rubrique.nomenclatureByPeriodicite] Getter 
	 * @author BELBRIK Oualid on : 17 nov. 2014  15:41:52
	 * @return the nomenclatureByPeriodicite
	 */
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "nc_periodicite")
	public Nomenclature getNomenclatureByPeriodicite() {
		return nomenclatureByPeriodicite;
	}

	/**
	 * [Rubrique.nomenclatureByPeriodicite] Setter 
	 * @author BELBRIK Oualid on : 17 nov. 2014  15:41:52
	 * @param nomenclatureByPeriodicite the nomenclatureByPeriodicite to set
	 */
	public void setNomenclatureByPeriodicite(Nomenclature nomenclatureByPeriodicite) {
		this.nomenclatureByPeriodicite = nomenclatureByPeriodicite;
	}

	/**
	 * [Rubrique.decret] Getter 
	 * @author BELBRIK Oualid on : 17 nov. 2014  15:41:52
	 * @return the decret
	 */
	@Column(name = "decret")
	public String getDecret() {
		return decret;
	}

	/**
	 * [Rubrique.decret] Setter 
	 * @author BELBRIK Oualid on : 17 nov. 2014  15:41:52
	 * @param decret the decret to set
	 */
	public void setDecret(String decret) {
		this.decret = decret;
	}

	/**
	 * [Rubrique.taux] Getter 
	 * @author BELBRIK Oualid on : 17 nov. 2014  15:41:52
	 * @return the taux
	 */
	@Column(name = "taux", precision = 17, scale = 17)
	public Double getTaux() {
		return taux;
	}

	/**
	 * [Rubrique.taux] Setter 
	 * @author BELBRIK Oualid on : 17 nov. 2014  15:41:52
	 * @param taux the taux to set
	 */
	public void setTaux(Double taux) {
		this.taux = taux;
	}

	/**
	 * [Rubrique.montant] Getter 
	 * @author BELBRIK Oualid on : 17 nov. 2014  15:41:52
	 * @return the montant
	 */
	@Column(name = "montant", precision = 17, scale = 17)
	public Double getMontant() {
		return montant;
	}

	/**
	 * [Rubrique.montant] Setter 
	 * @author BELBRIK Oualid on : 17 nov. 2014  15:41:52
	 * @param montant the montant to set
	 */
	public void setMontant(Double montant) {
		this.montant = montant;
	}

	/**
	 * [Rubrique.commune] Getter 
	 * @author BELBRIK Oualid on : 17 nov. 2014  15:41:52
	 * @return the commune
	 */
	@Column(name = "commune")
	public Boolean getCommune() {
		return commune;
	}

	/**
	 * [Rubrique.commune] Setter 
	 * @author BELBRIK Oualid on : 17 nov. 2014  15:41:52
	 * @param commune the commune to set
	 */
	public void setCommune(Boolean commune) {
		this.commune = commune;
	}

	/**
	 * [Rubrique.soumise_securite] Getter 
	 * @author BELBRIK Oualid on : 17 nov. 2014  15:41:52
	 * @return the soumise_securite
	 */
	@Column(name = "soumise_securite")
	public Boolean getSoumise_securite() {
		return soumise_securite;
	}

	/**
	 * [Rubrique.soumise_securite] Setter 
	 * @author BELBRIK Oualid on : 17 nov. 2014  15:41:52
	 * @param soumise_securite the soumise_securite to set
	 */
	public void setSoumise_securite(Boolean soumise_securite) {
		this.soumise_securite = soumise_securite;
	}


	/**
	 * [Rubrique.identifiant] Getter 
	 * @author BELBRIK Oualid on : 17 nov. 2014  18:57:11
	 * @return the identifiant
	 */
	@Column(name = "identifiant",nullable=false)
	public String getIdentifiant() {
		return identifiant;
	}

	/**
	 * [Rubrique.identifiant] Setter 
	 * @author BELBRIK Oualid on : 17 nov. 2014  18:57:11
	 * @param identifiant the identifiant to set
	 */
	public void setIdentifiant(String identifiant) {
		this.identifiant = identifiant;
	}

	@Transient
	@Override
	public Integer getIdenfiant() {
		return this.getId();
		}

	@Transient
	@Override
	public String getIdentifiantName() {
		return "id";
	}

	@OneToMany(orphanRemoval = true, cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "rubrique")
	public Set<Filiere> getFilieres() {
		return this.filieres;
	}

	public void setFilieres(Set<Filiere> filieres) {
		this.filieres = filieres;
	}

	@Column(name = "taux_ou_mantan")
	public Boolean getTauxOuMantant() {
		return TauxOuMantant;
	}

	public void setTauxOuMantant(Boolean tauxOuMantant) {
		TauxOuMantant = tauxOuMantant;
	}
	  
	 
	
	  
	  
	  
}
