package dz.gov.mesrs.sii.commons.data.model.fve.bac;

// Generated 22 mai 2014 12:17:42 by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * AffectationBachelier generated by hbm2java
 */
@Entity
@Table(name = "affectation_bachelier", schema = "bac")
public class AffectationBachelier implements java.io.Serializable {

	/**
	 * serialVersionUID 
	 * @author BELDI Jamel  on : 22 mai 2014  12:19:34
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private Importation importation;
	private String matriculeBachelier;
	private String refCodeEtablissement;
	private String refCodeFiliere;
	private String numeroChoix;
	private String noteAffectation;
	private String refCodeEtablissementRecours;
	private String refCodeFiliereRecours;
	private String refCodeEtablissementOrientation;
	private String refCodeFiliereOrientation;
	private String refCodeTypeAffectation;
	private String refCodeEtablissementAffectation;
	private String refCodeFiliereAffectation;
	private DossierBachelier dossierBachelier;
	
	public AffectationBachelier() {
	}

	public AffectationBachelier(int id, Importation importation,
			String matriculeBachelier, String  numeroChoix) {
		this.id = id;
		this.importation = importation;
		this.matriculeBachelier = matriculeBachelier;
		this.numeroChoix = numeroChoix;
	}

	public AffectationBachelier(int id, Importation importation,
			String matriculeBachelier, String refCodeEtablissement,
			String refCodeFiliere, String numeroChoix, String noteAffectation,
			String refCodeEtablissementRecours, String refCodeFiliereRecours,
			String refCodeEtablissementOrientation,
			String refCodeFiliereOrientation, String refCodeTypeAffectation,
			String refCodeEtablissementAffectation,
			String refCodeFiliereAffectation) {
		this.id = id;
		this.importation = importation;
		this.matriculeBachelier = matriculeBachelier;
		this.refCodeEtablissement = refCodeEtablissement;
		this.refCodeFiliere = refCodeFiliere;
		this.numeroChoix = numeroChoix;
		this.noteAffectation = noteAffectation;
		this.refCodeEtablissementRecours = refCodeEtablissementRecours;
		this.refCodeFiliereRecours = refCodeFiliereRecours;
		this.refCodeEtablissementOrientation = refCodeEtablissementOrientation;
		this.refCodeFiliereOrientation = refCodeFiliereOrientation;
		this.refCodeTypeAffectation = refCodeTypeAffectation;
		this.refCodeEtablissementAffectation = refCodeEtablissementAffectation;
		this.refCodeFiliereAffectation = refCodeFiliereAffectation;
	}

	@SequenceGenerator(name="affectation_bachelier_id_seq_gen", sequenceName="bac.affectation_bachelier_id_seq")
	@Id 
	@GeneratedValue(generator="affectation_bachelier_id_seq_gen")
	@Column(name = "id")
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_importation", nullable = false)
	public Importation getImportation() {
		return this.importation;
	}

	public void setImportation(Importation importation) {
		this.importation = importation;
	}

	@Column(name = "matricule_bachelier", nullable = false, length = 10)
	public String getMatriculeBachelier() {
		return this.matriculeBachelier;
	}

	public void setMatriculeBachelier(String matriculeBachelier) {
		this.matriculeBachelier = matriculeBachelier;
	}

	@Column(name = "ref_code_etablissement", length = 10)
	public String getRefCodeEtablissement() {
		return this.refCodeEtablissement;
	}

	public void setRefCodeEtablissement(String refCodeEtablissement) {
		this.refCodeEtablissement = refCodeEtablissement;
	}

	@Column(name = "ref_code_filiere", length = 10)
	public String getRefCodeFiliere() {
		return this.refCodeFiliere;
	}

	public void setRefCodeFiliere(String refCodeFiliere) {
		this.refCodeFiliere = refCodeFiliere;
	}

	@Column(name = "numero_choix", nullable = false)
	public String getNumeroChoix() {
		return this.numeroChoix;
	}

	public void setNumeroChoix(String numeroChoix) {
		this.numeroChoix = numeroChoix;
	}

	@Column(name = "note_affectation", precision = 17, scale = 17)
	public String getNoteAffectation() {
		return this.noteAffectation;
	}

	public void setNoteAffectation(String noteAffectation) {
		this.noteAffectation = noteAffectation;
	}

	@Column(name = "ref_code_etablissement_recours", length = 10)
	public String getRefCodeEtablissementRecours() {
		return this.refCodeEtablissementRecours;
	}

	public void setRefCodeEtablissementRecours(
			String refCodeEtablissementRecours) {
		this.refCodeEtablissementRecours = refCodeEtablissementRecours;
	}

	@Column(name = "ref_code_filiere_recours", length = 10)
	public String getRefCodeFiliereRecours() {
		return this.refCodeFiliereRecours;
	}

	public void setRefCodeFiliereRecours(String refCodeFiliereRecours) {
		this.refCodeFiliereRecours = refCodeFiliereRecours;
	}

	@Column(name = "ref_code_etablissement_orientation", length = 10)
	public String getRefCodeEtablissementOrientation() {
		return this.refCodeEtablissementOrientation;
	}

	public void setRefCodeEtablissementOrientation(
			String refCodeEtablissementOrientation) {
		this.refCodeEtablissementOrientation = refCodeEtablissementOrientation;
	}

	@Column(name = "ref_code_filiere_orientation", length = 10)
	public String getRefCodeFiliereOrientation() {
		return this.refCodeFiliereOrientation;
	}

	public void setRefCodeFiliereOrientation(String refCodeFiliereOrientation) {
		this.refCodeFiliereOrientation = refCodeFiliereOrientation;
	}

	@Column(name = "ref_code_type_affectation", length = 10)
	public String getRefCodeTypeAffectation() {
		return this.refCodeTypeAffectation;
	}

	public void setRefCodeTypeAffectation(String refCodeTypeAffectation) {
		this.refCodeTypeAffectation = refCodeTypeAffectation;
	}

	@Column(name = "ref_code_etablissement_affectation", length = 10)
	public String getRefCodeEtablissementAffectation() {
		return this.refCodeEtablissementAffectation;
	}

	public void setRefCodeEtablissementAffectation(
			String refCodeEtablissementAffectation) {
		this.refCodeEtablissementAffectation = refCodeEtablissementAffectation;
	}

	@Column(name = "ref_code_filiere_affectation", length = 10)
	public String getRefCodeFiliereAffectation() {
		return this.refCodeFiliereAffectation;
	}

	public void setRefCodeFiliereAffectation(String refCodeFiliereAffectation) {
		this.refCodeFiliereAffectation = refCodeFiliereAffectation;
	}

	/**
	 * [AffectationBachelier.dossierBachelier] Getter 
	 * @author rlaib on : 19 juin 2014  12:06:44
	 * @return the dossierBachelier
	 */
	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name="id_dossier_bachelier")
	public DossierBachelier getDossierBachelier() {
		return dossierBachelier;
	}

	/**
	 * [AffectationBachelier.dossierBachelier] Setter 
	 * @author rlaib on : 19 juin 2014  12:06:44
	 * @param dossierBachelier the dossierBachelier to set
	 */
	public void setDossierBachelier(DossierBachelier dossierBachelier) {
		this.dossierBachelier = dossierBachelier;
	}

	
}
