package dz.gov.mesrs.sii.commons.data.model.fve.bac;

// Generated 22 mai 2014 12:17:42 by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * FicheVoeuxBachelier generated by hbm2java
 */
@Entity
@Table(name = "fiche_voeux_bachelier", schema = "bac")
public class FicheVoeuxBachelier implements java.io.Serializable {

	/**
	 * serialVersionUID 
	 * @author BELDI Jamel  on : 22 mai 2014  12:19:40
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private DossierBachelier dossierBachelier;
	private String refCodeFiliere;
	private int rang;

	public FicheVoeuxBachelier() {
	}

	public FicheVoeuxBachelier(int id, DossierBachelier dossierBachelier,
			String refCodeFiliere, int rang) {
		this.id = id;
		this.dossierBachelier = dossierBachelier;
		this.refCodeFiliere = refCodeFiliere;
		this.rang = rang;
	}

	@SequenceGenerator(name="fiche_voeux_id_seq_gen", sequenceName="bac.fiche_voeux_id_seq")
	@Id @GeneratedValue(generator="fiche_voeux_id_seq_gen")
	@Column(name = "id")
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "matricule_bachelier", nullable = false)
	public DossierBachelier getDossierBachelier() {
		return this.dossierBachelier;
	}

	public void setDossierBachelier(DossierBachelier dossierBachelier) {
		this.dossierBachelier = dossierBachelier;
	}

	@Column(name = "ref_code_filiere", nullable = false, length = 10)
	public String getRefCodeFiliere() {
		return this.refCodeFiliere;
	}

	public void setRefCodeFiliere(String refCodeFiliere) {
		this.refCodeFiliere = refCodeFiliere;
	}

	@Column(name = "rang", nullable = false)
	public int getRang() {
		return this.rang;
	}

	public void setRang(int rang) {
		this.rang = rang;
	}

}
