package dz.gov.mesrs.sii.commons.data.model.fve.bac;

// Generated 22 mai 2014 12:17:42 by Hibernate Tools 3.6.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Importation generated by hbm2java
 */
@Entity
@Table(name = "importation", schema = "bac")
public class Importation implements java.io.Serializable {

	/**
	 * serialVersionUID 
	 * @author BELDI Jamel  on : 22 mai 2014  12:19:45
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private TypeImportation typeImportation;
	private Date dateDebutImportation;
	private Date dateFinImportation;
	private String anneeBac;
	private String situation;
	private Set<DossierBachelier> dossierBacheliers = new HashSet<DossierBachelier>(
			0);
	private Set<NotesBachelier> notesBacheliers = new HashSet<NotesBachelier>(0);
	private Set<AffectationBachelier> affectationBacheliers = new HashSet<AffectationBachelier>(
			0);
	private int nbDepart;
	private int nbImportes;
	private int nbIgnores;

	
	public Importation() {
	}

	public Importation(int id, TypeImportation typeImportation,
			Date dateImportation, String anneeBac) {
		this.id = id;
		this.typeImportation = typeImportation;
		this.anneeBac = anneeBac;
	}

	public Importation(int id, TypeImportation typeImportation,
			Date dateImportation, String anneeBac, String situation,
			Set<DossierBachelier> dossierBacheliers,
			Set<NotesBachelier> notesBacheliers,
			Set<AffectationBachelier> affectationBacheliers) {
		this.id = id;
		this.typeImportation = typeImportation;
		this.anneeBac = anneeBac;
		this.situation = situation;
		this.dossierBacheliers = dossierBacheliers;
		this.notesBacheliers = notesBacheliers;
		this.affectationBacheliers = affectationBacheliers;
	}

	@SequenceGenerator(name="importation_id_seq_gen", sequenceName="bac.importation_id_seq")
	@Id @GeneratedValue(generator="importation_id_seq_gen")
	@Column(name = "id")
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_type_importation", nullable = false)
	public TypeImportation getTypeImportation() {
		return this.typeImportation;
	}

	public void setTypeImportation(TypeImportation typeImportation) {
		this.typeImportation = typeImportation;
	}
	

	@Column(name = "annee_bac", nullable = false, length = 10)
	public String getAnneeBac() {
		return this.anneeBac;
	}

	public void setAnneeBac(String anneeBac) {
		this.anneeBac = anneeBac;
	}

	@Column(name = "situation", length = 10)
	public String getSituation() {
		return this.situation;
	}

	public void setSituation(String situation) {
		this.situation = situation;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "importation", cascade={CascadeType.REMOVE})
	public Set<DossierBachelier> getDossierBacheliers() {
		return this.dossierBacheliers;
	}

	public void setDossierBacheliers(Set<DossierBachelier> dossierBacheliers) {
		this.dossierBacheliers = dossierBacheliers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "importation")
	public Set<NotesBachelier> getNotesBacheliers() {
		return this.notesBacheliers;
	}

	public void setNotesBacheliers(Set<NotesBachelier> notesBacheliers) {
		this.notesBacheliers = notesBacheliers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "importation", cascade={CascadeType.REMOVE})
	public Set<AffectationBachelier> getAffectationBacheliers() {
		return this.affectationBacheliers;
	}

	public void setAffectationBacheliers(
			Set<AffectationBachelier> affectationBacheliers) {
		this.affectationBacheliers = affectationBacheliers;
	}

	/**
	 * [Importation.dateDebutImportation] Getter 
	 * @author  Rafik LAIB on : 1 ao�t 2014  11:07:25
	 * @return the dateDebutImportation
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_debut_importation", nullable = false, length = 29)
	public Date getDateDebutImportation() {
		return dateDebutImportation;
	}

	/**
	 * [Importation.dateDebutImportation] Setter 
	 * @author  Rafik LAIB on : 1 ao�t 2014  11:07:25
	 * @param dateDebutImportation the dateDebutImportation to set
	 */
	public void setDateDebutImportation(Date dateDebutImportation) {
		this.dateDebutImportation = dateDebutImportation;
	}

	/**
	 * [Importation.dateFinImportation] Getter 
	 * @author  Rafik LAIB on : 1 ao�t 2014  11:07:25
	 * @return the dateFinImportation
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_fin_importation", nullable = false, length = 29)
	public Date getDateFinImportation() {
		return dateFinImportation;
	}

	/**
	 * [Importation.dateFinImportation] Setter 
	 * @author  Rafik LAIB on : 1 ao�t 2014  11:07:25
	 * @param dateFinImportation the dateFinImportation to set
	 */
	public void setDateFinImportation(Date dateFinImportation) {
		this.dateFinImportation = dateFinImportation;
	}

	
	/**
	 * [Importation.nbDepart] Getter 
	 * @author  Rafik LAIB on : 1 ao�t 2014  14:05:38
	 * @return the nbDepart
	 */
	@Column(name = "nb_depart")
	public int getNbDepart() {
		return nbDepart;
	}

	/**
	 * [Importation.nbDepart] Setter 
	 * @author  Rafik LAIB on : 1 ao�t 2014  14:05:38
	 * @param nbDepart the nbDepart to set
	 */
	public void setNbDepart(int nbDepart) {
		this.nbDepart = nbDepart;
	}

	/**
	 * [Importation.nbImportes] Getter 
	 * @author  Rafik LAIB on : 1 ao�t 2014  14:05:38
	 * @return the nbImportes
	 */
	@Column(name = "nb_importes")
	public int getNbImportes() {
		return nbImportes;
	}

	/**
	 * [Importation.nbImportes] Setter 
	 * @author  Rafik LAIB on : 1 ao�t 2014  14:05:38
	 * @param nbImportes the nbImportes to set
	 */
	public void setNbImportes(int nbImportes) {
		this.nbImportes = nbImportes;
	}

	/**
	 * [Importation.nbIgnores] Getter 
	 * @author  Rafik LAIB on : 1 ao�t 2014  14:05:38
	 * @return the nbIgnores
	 */
	@Column(name = "nb_ignores")
	public int getNbIgnores() {
		return nbIgnores;
	}

	/**
	 * [Importation.nbIgnores] Setter 
	 * @author  Rafik LAIB on : 1 ao�t 2014  14:05:38
	 * @param nbIgnores the nbIgnores to set
	 */
	public void setNbIgnores(int nbIgnores) {
		this.nbIgnores = nbIgnores;
	}

	
	
}
