package dz.gov.mesrs.sii.commons.data.model.fve.examen;

// Generated 29 sept. 2014 16:32:23 by Hibernate Tools 3.6.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import dz.gov.mesrs.sii.commons.data.model.bpm.SituationEntite;
import dz.gov.mesrs.sii.commons.data.model.fve.cursus.AssociationGroupePedagogique;
import dz.gov.mesrs.sii.commons.data.model.fve.offreformation.AnneeAcademique;
import dz.gov.mesrs.sii.commons.data.model.fve.offreformation.OuvertureOffreFormation;
import dz.gov.mesrs.sii.commons.data.model.fve.offreformation.Periode;
import dz.gov.mesrs.sii.commons.data.model.referentiel.Nomenclature;

/**
 * EvaluationControleContinu generated by hbm2java
 */
@Entity
@Table(name = "evaluation_controle_continu", schema = "fve_examen")
public class EvaluationControleContinu implements java.io.Serializable {

	/**
	 * serialVersionUID 
	 * @author rlaib  on : 19 nov. 2014  17:27:20
	 */
	private static final long serialVersionUID = 1L;
	private long id;
	private AssociationGroupePedagogique associationGroupePedagogique;
	private OuvertureOffreFormation oof;
	private Periode periode;
	private Nomenclature nomenclature;
	private AnneeAcademique anneeAcademique;
	private SituationEntite situationEntite;
	private Date dateEvaluation;
	private Double coefficient;
	private Boolean comptablise;
	private String objectif;
	private String competence;
	
	public EvaluationControleContinu() {
	}

	public EvaluationControleContinu(int id) {
		this.id = id;
	}

	public EvaluationControleContinu(int id,
			AssociationGroupePedagogique associationGroupePedagogique, Nomenclature nomenclature,
			AnneeAcademique anneeAcademique, SituationEntite situationEntite,
			Date dateEvaluation, Double coefficient, Boolean comptablise) {
		this.id = id;
		this.associationGroupePedagogique = associationGroupePedagogique;
		this.nomenclature = nomenclature;
		this.anneeAcademique = anneeAcademique;
		this.situationEntite = situationEntite;
		this.dateEvaluation = dateEvaluation;
		this.coefficient = coefficient;
		this.comptablise = comptablise;
		
	}

	@SequenceGenerator(name = "evaluation_controle_continu_id_seq", sequenceName = "fve_examen.evaluation_controle_continu_id_seq")
	@Id
	@GeneratedValue(generator = "evaluation_controle_continu_id_seq")
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_association_groupe_pedagogique")
	public AssociationGroupePedagogique getAssociationGroupePedagogique() {
		return associationGroupePedagogique;
	}

	
	public void setAssociationGroupePedagogique(
			AssociationGroupePedagogique associationGroupePedagogique) {
		this.associationGroupePedagogique = associationGroupePedagogique;
	}
	
	

	/**
	 * [EvaluationControleContinu.oof] Getter 
	 * @author MAKERRI Sofiane on : 12 oct. 2014  17:20:47
	 * @return the oof
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_oof")
	public OuvertureOffreFormation getOof() {
		return oof;
	}

	/**
	 * [EvaluationControleContinu.oof] Setter 
	 * @author MAKERRI Sofiane on : 12 oct. 2014  17:20:47
	 * @param oof the oof to set
	 */
	public void setOof(OuvertureOffreFormation oof) {
		this.oof = oof;
	}

	/**
	 * [EvaluationControleContinu.periode] Getter 
	 * @author MAKERRI Sofiane on : 12 oct. 2014  17:20:47
	 * @return the periode
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_periode")
	public Periode getPeriode() {
		return periode;
	}

	/**
	 * [EvaluationControleContinu.periode] Setter 
	 * @author MAKERRI Sofiane on : 12 oct. 2014  17:20:47
	 * @param periode the periode to set
	 */
	public void setPeriode(Periode periode) {
		this.periode = periode;
	}

	public void setNomenclature(Nomenclature nomenclature) {
		this.nomenclature = nomenclature;
	}
	

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "nc_type_evaluation")
	public Nomenclature getNomenclature() {
		return this.nomenclature;
	}

	
	

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_annee_academique")
	public AnneeAcademique getAnneeAcademique() {
		return this.anneeAcademique;
	}

	public void setAnneeAcademique(AnneeAcademique anneeAcademique) {
		this.anneeAcademique = anneeAcademique;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_situation")
	public SituationEntite getSituationEntite() {
		return this.situationEntite;
	}

	public void setSituationEntite(SituationEntite situationEntite) {
		this.situationEntite = situationEntite;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_evaluation", length = 13)
	public Date getDateEvaluation() {
		return this.dateEvaluation;
	}

	public void setDateEvaluation(Date dateEvaluation) {
		this.dateEvaluation = dateEvaluation;
	}

	@Column(name = "coefficient", precision = 17, scale = 17)
	public Double getCoefficient() {
		return this.coefficient;
	}

	public void setCoefficient(Double coefficient) {
		this.coefficient = coefficient;
	}

	@Column(name = "comptablise")
	public Boolean getComptablise() {
		return this.comptablise;
	}

	public void setComptablise(Boolean comptablise) {
		this.comptablise = comptablise;
	}

	/**
	 * [EvaluationControleContinu.objectif] Getter 
	 * @author MAKERRI Sofiane on : 1 oct. 2014  14:52:10
	 * @return the objectif
	 */
	@Column(name = "objectif", length = 250)
	public String getObjectif() {
		return objectif;
	}

	/**
	 * [EvaluationControleContinu.objectif] Setter 
	 * @author MAKERRI Sofiane on : 1 oct. 2014  14:52:10
	 * @param objectif the objectif to set
	 */
	public void setObjectif(String objectif) {
		this.objectif = objectif;
	}

	/**
	 * [EvaluationControleContinu.competence] Getter 
	 * @author MAKERRI Sofiane on : 1 oct. 2014  14:52:10
	 * @return the competence
	 */
	@Column(name = "competence", length = 250)
	public String getCompetence() {
		return competence;
	}

	/**
	 * [EvaluationControleContinu.competence] Setter 
	 * @author MAKERRI Sofiane on : 1 oct. 2014  14:52:10
	 * @param competence the competence to set
	 */
	public void setCompetence(String competence) {
		this.competence = competence;
	}



}
