/**
 * [dz.gov.mesrs.sii.fve.business.model.dto.cursus.AssociationGroupePedagogiqueDto.java] 
 * @author MAKERRI Sofiane on : 2 oct. 2014  09:47:56
 */
package dz.gov.mesrs.sii.fve.business.model.dto.cursus;

import java.util.Date;

// Generated 12 juin 2014 15:40:15 by Hibernate Tools 3.6.0

/**
 * GroupePedagogiqueAp generated by hbm2java
 */
public class AssociationGroupePedagogiqueDto implements java.io.Serializable {

	/**
	 * serialVersionUID
	 * 
	 * @author MAKERRI Sofiane on : 12 juin 2014 15:52:53
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Integer groupePedagogiqueId;
	private String groupePedagogiqueNom;
	
	private String apCode;
	private String refCodeTypeAp;
	private String refCodeModeEnseignement;
	private Double apVolumeHoraire;
	private Integer apSeuil;
	private Integer apGroupesPrevus;
	private Integer apId;
	private String obervation;
	private Date dateAttachement;

	private Integer rattachementMcId;
	private Integer rattachementMcMcId;
	private String rattachementMcMcCode;
	private String rattachementMcMcLibelleFr;
	private String rattachementMcMcAbreviationFr;
	private Integer rattachementMcMcCredits;
	private Double rattachementMcMcVolumeHorairePerso;
	private Double rattachementMcMcVolumeHorairePres;
	private String rattachementMcMcRefCodeTypeMc;
	private Boolean rattachementMcOptionnelle;

	private Integer rattachementMcUeId;
	private String rattachementMcUeCode;
	private String rattachementMcUeLibelleFr;
	private String rattachementMcUeAbreviationFr;
	private String rattachementMcUeRefCodeTypeUe;
	private String rattachementMcUeRefCodeNatureUe;
	private String rattachementMcUeRefCodeStatutUe;
	private Integer rattachementMcUeCredits;
	private Integer periodeId;
	private Integer oofId;

	public AssociationGroupePedagogiqueDto() {
	}

	/**
	 * [GroupePedagogiqueApDto.id] Getter
	 * 
	 * @author MAKERRI Sofiane on : 16 juin 2014 15:29:46
	 * @return the id
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * [GroupePedagogiqueApDto.id] Setter
	 * 
	 * @author MAKERRI Sofiane on : 16 juin 2014 15:29:46
	 * @param id
	 *            the id to set
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * [GroupePedagogiqueApDto.groupePedagogiqueId] Getter
	 * 
	 * @author MAKERRI Sofiane on : 16 juin 2014 15:06:01
	 * @return the groupePedagogiqueId
	 */
	public Integer getGroupePedagogiqueId() {
		return groupePedagogiqueId;
	}

	/**
	 * [GroupePedagogiqueApDto.groupePedagogiqueId] Setter
	 * 
	 * @author MAKERRI Sofiane on : 16 juin 2014 15:06:01
	 * @param groupePedagogiqueId
	 *            the groupePedagogiqueId to set
	 */
	public void setGroupePedagogiqueId(Integer groupePedagogiqueId) {
		this.groupePedagogiqueId = groupePedagogiqueId;
	}

	public String getObervation() {
		return this.obervation;
	}

	public void setObervation(String obervation) {
		this.obervation = obervation;
	}

	/**
	 * [GroupePedagogiqueApDto.dateAttachement] Getter
	 * 
	 * @author MAKERRI Sofiane on : 16 juin 2014 14:56:14
	 * @return the dateAttachement
	 */
	public Date getDateAttachement() {
		return dateAttachement;
	}

	/**
	 * [GroupePedagogiqueApDto.dateAttachement] Setter
	 * 
	 * @author MAKERRI Sofiane on : 16 juin 2014 14:56:14
	 * @param dateAttachement
	 *            the dateAttachement to set
	 */
	public void setDateAttachement(Date dateAttachement) {
		this.dateAttachement = dateAttachement;
	}

	/**
	 * [GroupePedagogiqueApDto.apCode] Getter
	 * 
	 * @author MAKERRI Sofiane on : 9 juil. 2014 14:22:45
	 * @return the apCode
	 */
	public String getApCode() {
		return apCode;
	}

	/**
	 * [GroupePedagogiqueApDto.apCode] Setter
	 * 
	 * @author MAKERRI Sofiane on : 9 juil. 2014 14:22:45
	 * @param apCode
	 *            the apCode to set
	 */
	public void setApCode(String apCode) {
		this.apCode = apCode;
	}

	


	/**
	 * [AssociationGroupePedagogiqueDto.refCodeTypeAp] Getter 
	 * @author MAKERRI Sofiane on : 2 oct. 2014  10:56:19
	 * @return the refCodeTypeAp
	 */
	public String getRefCodeTypeAp() {
		return refCodeTypeAp;
	}

	/**
	 * [AssociationGroupePedagogiqueDto.refCodeTypeAp] Setter 
	 * @author MAKERRI Sofiane on : 2 oct. 2014  10:56:19
	 * @param refCodeTypeAp the refCodeTypeAp to set
	 */
	public void setRefCodeTypeAp(String refCodeTypeAp) {
		this.refCodeTypeAp = refCodeTypeAp;
	}

	/**
	 * [AssociationGroupePedagogiqueDto.refCodeModeEnseignement] Getter 
	 * @author MAKERRI Sofiane on : 2 oct. 2014  10:56:19
	 * @return the refCodeModeEnseignement
	 */
	public String getRefCodeModeEnseignement() {
		return refCodeModeEnseignement;
	}

	/**
	 * [AssociationGroupePedagogiqueDto.refCodeModeEnseignement] Setter 
	 * @author MAKERRI Sofiane on : 2 oct. 2014  10:56:19
	 * @param refCodeModeEnseignement the refCodeModeEnseignement to set
	 */
	public void setRefCodeModeEnseignement(String refCodeModeEnseignement) {
		this.refCodeModeEnseignement = refCodeModeEnseignement;
	}

	/**
	 * [GroupePedagogiqueApDto.apVolumeHoraire] Getter
	 * 
	 * @author MAKERRI Sofiane on : 9 juil. 2014 14:22:45
	 * @return the apVolumeHoraire
	 */
	public Double getApVolumeHoraire() {
		return apVolumeHoraire;
	}

	/**
	 * [GroupePedagogiqueApDto.apVolumeHoraire] Setter
	 * 
	 * @author MAKERRI Sofiane on : 9 juil. 2014 14:22:45
	 * @param apVolumeHoraire
	 *            the apVolumeHoraire to set
	 */
	public void setApVolumeHoraire(Double apVolumeHoraire) {
		this.apVolumeHoraire = apVolumeHoraire;
	}

	/**
	 * [GroupePedagogiqueApDto.apSeuil] Getter
	 * 
	 * @author MAKERRI Sofiane on : 9 juil. 2014 14:22:45
	 * @return the apSeuil
	 */
	public Integer getApSeuil() {
		return apSeuil;
	}

	/**
	 * [GroupePedagogiqueApDto.apSeuil] Setter
	 * 
	 * @author MAKERRI Sofiane on : 9 juil. 2014 14:22:45
	 * @param apSeuil
	 *            the apSeuil to set
	 */
	public void setApSeuil(Integer apSeuil) {
		this.apSeuil = apSeuil;
	}

	/**
	 * [GroupePedagogiqueApDto.apGroupesPrevus] Getter
	 * 
	 * @author MAKERRI Sofiane on : 9 juil. 2014 14:22:45
	 * @return the apGroupesPrevus
	 */
	public Integer getApGroupesPrevus() {
		return apGroupesPrevus;
	}

	/**
	 * [GroupePedagogiqueApDto.apGroupesPrevus] Setter
	 * 
	 * @author MAKERRI Sofiane on : 9 juil. 2014 14:22:45
	 * @param apGroupesPrevus
	 *            the apGroupesPrevus to set
	 */
	public void setApGroupesPrevus(Integer apGroupesPrevus) {
		this.apGroupesPrevus = apGroupesPrevus;
	}

	/**
	 * [GroupePedagogiqueApDto.apId] Getter
	 * 
	 * @author MAKERRI Sofiane on : 9 juil. 2014 14:22:45
	 * @return the apId
	 */
	public Integer getApId() {
		return apId;
	}

	/**
	 * [GroupePedagogiqueApDto.apId] Setter
	 * 
	 * @author MAKERRI Sofiane on : 9 juil. 2014 14:22:45
	 * @param apId
	 *            the apId to set
	 */
	public void setApId(Integer apId) {
		this.apId = apId;
	}

	/**
	 * [AssociationGroupePedagogiqueDto.rattachementMcId] Getter 
	 * @author MAKERRI Sofiane on : 6 oct. 2014  10:19:55
	 * @return the rattachementMcId
	 */
	public Integer getRattachementMcId() {
		return rattachementMcId;
	}

	/**
	 * [AssociationGroupePedagogiqueDto.rattachementMcId] Setter 
	 * @author MAKERRI Sofiane on : 6 oct. 2014  10:19:55
	 * @param rattachementMcId the rattachementMcId to set
	 */
	public void setRattachementMcId(Integer rattachementMcId) {
		this.rattachementMcId = rattachementMcId;
	}

	/**
	 * [AssociationGroupePedagogiqueDto.rattachementMcMcCode] Getter 
	 * @author MAKERRI Sofiane on : 6 oct. 2014  10:19:55
	 * @return the rattachementMcMcCode
	 */
	public String getRattachementMcMcCode() {
		return rattachementMcMcCode;
	}

	/**
	 * [AssociationGroupePedagogiqueDto.rattachementMcMcCode] Setter 
	 * @author MAKERRI Sofiane on : 6 oct. 2014  10:19:55
	 * @param rattachementMcMcCode the rattachementMcMcCode to set
	 */
	public void setRattachementMcMcCode(String rattachementMcMcCode) {
		this.rattachementMcMcCode = rattachementMcMcCode;
	}

	/**
	 * [AssociationGroupePedagogiqueDto.rattachementMcMcLibelleFr] Getter 
	 * @author MAKERRI Sofiane on : 6 oct. 2014  10:19:55
	 * @return the rattachementMcMcLibelleFr
	 */
	public String getRattachementMcMcLibelleFr() {
		return rattachementMcMcLibelleFr;
	}

	/**
	 * [AssociationGroupePedagogiqueDto.rattachementMcMcLibelleFr] Setter 
	 * @author MAKERRI Sofiane on : 6 oct. 2014  10:19:55
	 * @param rattachementMcMcLibelleFr the rattachementMcMcLibelleFr to set
	 */
	public void setRattachementMcMcLibelleFr(String rattachementMcMcLibelleFr) {
		this.rattachementMcMcLibelleFr = rattachementMcMcLibelleFr;
	}

	/**
	 * [AssociationGroupePedagogiqueDto.rattachementMcMcAbreviationFr] Getter 
	 * @author MAKERRI Sofiane on : 6 oct. 2014  10:19:55
	 * @return the rattachementMcMcAbreviationFr
	 */
	public String getRattachementMcMcAbreviationFr() {
		return rattachementMcMcAbreviationFr;
	}

	/**
	 * [AssociationGroupePedagogiqueDto.rattachementMcMcAbreviationFr] Setter 
	 * @author MAKERRI Sofiane on : 6 oct. 2014  10:19:55
	 * @param rattachementMcMcAbreviationFr the rattachementMcMcAbreviationFr to set
	 */
	public void setRattachementMcMcAbreviationFr(
			String rattachementMcMcAbreviationFr) {
		this.rattachementMcMcAbreviationFr = rattachementMcMcAbreviationFr;
	}

	/**
	 * [AssociationGroupePedagogiqueDto.rattachementMcMcCredits] Getter 
	 * @author MAKERRI Sofiane on : 6 oct. 2014  10:19:55
	 * @return the rattachementMcMcCredits
	 */
	public Integer getRattachementMcMcCredits() {
		return rattachementMcMcCredits;
	}

	/**
	 * [AssociationGroupePedagogiqueDto.rattachementMcMcCredits] Setter 
	 * @author MAKERRI Sofiane on : 6 oct. 2014  10:19:55
	 * @param rattachementMcMcCredits the rattachementMcMcCredits to set
	 */
	public void setRattachementMcMcCredits(Integer rattachementMcMcCredits) {
		this.rattachementMcMcCredits = rattachementMcMcCredits;
	}

	/**
	 * [AssociationGroupePedagogiqueDto.rattachementMcMcVolumeHorairePerso] Getter 
	 * @author MAKERRI Sofiane on : 6 oct. 2014  10:19:55
	 * @return the rattachementMcMcVolumeHorairePerso
	 */
	public Double getRattachementMcMcVolumeHorairePerso() {
		return rattachementMcMcVolumeHorairePerso;
	}

	/**
	 * [AssociationGroupePedagogiqueDto.rattachementMcMcVolumeHorairePerso] Setter 
	 * @author MAKERRI Sofiane on : 6 oct. 2014  10:19:55
	 * @param rattachementMcMcVolumeHorairePerso the rattachementMcMcVolumeHorairePerso to set
	 */
	public void setRattachementMcMcVolumeHorairePerso(
			Double rattachementMcMcVolumeHorairePerso) {
		this.rattachementMcMcVolumeHorairePerso = rattachementMcMcVolumeHorairePerso;
	}

	/**
	 * [AssociationGroupePedagogiqueDto.rattachementMcMcVolumeHorairePres] Getter 
	 * @author MAKERRI Sofiane on : 6 oct. 2014  10:19:55
	 * @return the rattachementMcMcVolumeHorairePres
	 */
	public Double getRattachementMcMcVolumeHorairePres() {
		return rattachementMcMcVolumeHorairePres;
	}

	/**
	 * [AssociationGroupePedagogiqueDto.rattachementMcMcVolumeHorairePres] Setter 
	 * @author MAKERRI Sofiane on : 6 oct. 2014  10:19:55
	 * @param rattachementMcMcVolumeHorairePres the rattachementMcMcVolumeHorairePres to set
	 */
	public void setRattachementMcMcVolumeHorairePres(
			Double rattachementMcMcVolumeHorairePres) {
		this.rattachementMcMcVolumeHorairePres = rattachementMcMcVolumeHorairePres;
	}

	/**
	 * [AssociationGroupePedagogiqueDto.rattachementMcMcRefCodeTypeMc] Getter 
	 * @author MAKERRI Sofiane on : 6 oct. 2014  10:19:55
	 * @return the rattachementMcMcRefCodeTypeMc
	 */
	public String getRattachementMcMcRefCodeTypeMc() {
		return rattachementMcMcRefCodeTypeMc;
	}

	/**
	 * [AssociationGroupePedagogiqueDto.rattachementMcMcRefCodeTypeMc] Setter 
	 * @author MAKERRI Sofiane on : 6 oct. 2014  10:19:55
	 * @param rattachementMcMcRefCodeTypeMc the rattachementMcMcRefCodeTypeMc to set
	 */
	public void setRattachementMcMcRefCodeTypeMc(
			String rattachementMcMcRefCodeTypeMc) {
		this.rattachementMcMcRefCodeTypeMc = rattachementMcMcRefCodeTypeMc;
	}

	/**
	 * [AssociationGroupePedagogiqueDto.rattachementMcUeId] Getter 
	 * @author MAKERRI Sofiane on : 6 oct. 2014  10:19:55
	 * @return the rattachementMcUeId
	 */
	public Integer getRattachementMcUeId() {
		return rattachementMcUeId;
	}

	/**
	 * [AssociationGroupePedagogiqueDto.rattachementMcUeId] Setter 
	 * @author MAKERRI Sofiane on : 6 oct. 2014  10:19:55
	 * @param rattachementMcUeId the rattachementMcUeId to set
	 */
	public void setRattachementMcUeId(Integer rattachementMcUeId) {
		this.rattachementMcUeId = rattachementMcUeId;
	}

	/**
	 * [AssociationGroupePedagogiqueDto.rattachementMcUeCode] Getter 
	 * @author MAKERRI Sofiane on : 6 oct. 2014  10:19:55
	 * @return the rattachementMcUeCode
	 */
	public String getRattachementMcUeCode() {
		return rattachementMcUeCode;
	}

	/**
	 * [AssociationGroupePedagogiqueDto.rattachementMcUeCode] Setter 
	 * @author MAKERRI Sofiane on : 6 oct. 2014  10:19:55
	 * @param rattachementMcUeCode the rattachementMcUeCode to set
	 */
	public void setRattachementMcUeCode(String rattachementMcUeCode) {
		this.rattachementMcUeCode = rattachementMcUeCode;
	}

	/**
	 * [AssociationGroupePedagogiqueDto.rattachementMcUeLibelleFr] Getter 
	 * @author MAKERRI Sofiane on : 6 oct. 2014  10:19:55
	 * @return the rattachementMcUeLibelleFr
	 */
	public String getRattachementMcUeLibelleFr() {
		return rattachementMcUeLibelleFr;
	}

	/**
	 * [AssociationGroupePedagogiqueDto.rattachementMcUeLibelleFr] Setter 
	 * @author MAKERRI Sofiane on : 6 oct. 2014  10:19:55
	 * @param rattachementMcUeLibelleFr the rattachementMcUeLibelleFr to set
	 */
	public void setRattachementMcUeLibelleFr(String rattachementMcUeLibelleFr) {
		this.rattachementMcUeLibelleFr = rattachementMcUeLibelleFr;
	}

	/**
	 * [AssociationGroupePedagogiqueDto.rattachementMcUeAbreviationFr] Getter 
	 * @author MAKERRI Sofiane on : 6 oct. 2014  10:19:55
	 * @return the rattachementMcUeAbreviationFr
	 */
	public String getRattachementMcUeAbreviationFr() {
		return rattachementMcUeAbreviationFr;
	}

	/**
	 * [AssociationGroupePedagogiqueDto.rattachementMcUeAbreviationFr] Setter 
	 * @author MAKERRI Sofiane on : 6 oct. 2014  10:19:55
	 * @param rattachementMcUeAbreviationFr the rattachementMcUeAbreviationFr to set
	 */
	public void setRattachementMcUeAbreviationFr(
			String rattachementMcUeAbreviationFr) {
		this.rattachementMcUeAbreviationFr = rattachementMcUeAbreviationFr;
	}

	/**
	 * [AssociationGroupePedagogiqueDto.rattachementMcUeRefCodeTypeUe] Getter 
	 * @author MAKERRI Sofiane on : 6 oct. 2014  10:19:55
	 * @return the rattachementMcUeRefCodeTypeUe
	 */
	public String getRattachementMcUeRefCodeTypeUe() {
		return rattachementMcUeRefCodeTypeUe;
	}

	/**
	 * [AssociationGroupePedagogiqueDto.rattachementMcUeRefCodeTypeUe] Setter 
	 * @author MAKERRI Sofiane on : 6 oct. 2014  10:19:55
	 * @param rattachementMcUeRefCodeTypeUe the rattachementMcUeRefCodeTypeUe to set
	 */
	public void setRattachementMcUeRefCodeTypeUe(
			String rattachementMcUeRefCodeTypeUe) {
		this.rattachementMcUeRefCodeTypeUe = rattachementMcUeRefCodeTypeUe;
	}

	/**
	 * [AssociationGroupePedagogiqueDto.rattachementMcUeRefCodeNatureUe] Getter 
	 * @author MAKERRI Sofiane on : 6 oct. 2014  10:19:55
	 * @return the rattachementMcUeRefCodeNatureUe
	 */
	public String getRattachementMcUeRefCodeNatureUe() {
		return rattachementMcUeRefCodeNatureUe;
	}

	/**
	 * [AssociationGroupePedagogiqueDto.rattachementMcUeRefCodeNatureUe] Setter 
	 * @author MAKERRI Sofiane on : 6 oct. 2014  10:19:55
	 * @param rattachementMcUeRefCodeNatureUe the rattachementMcUeRefCodeNatureUe to set
	 */
	public void setRattachementMcUeRefCodeNatureUe(
			String rattachementMcUeRefCodeNatureUe) {
		this.rattachementMcUeRefCodeNatureUe = rattachementMcUeRefCodeNatureUe;
	}

	/**
	 * [AssociationGroupePedagogiqueDto.rattachementMcUeRefCodeStatutUe] Getter 
	 * @author MAKERRI Sofiane on : 6 oct. 2014  10:19:55
	 * @return the rattachementMcUeRefCodeStatutUe
	 */
	public String getRattachementMcUeRefCodeStatutUe() {
		return rattachementMcUeRefCodeStatutUe;
	}

	/**
	 * [AssociationGroupePedagogiqueDto.rattachementMcUeRefCodeStatutUe] Setter 
	 * @author MAKERRI Sofiane on : 6 oct. 2014  10:19:55
	 * @param rattachementMcUeRefCodeStatutUe the rattachementMcUeRefCodeStatutUe to set
	 */
	public void setRattachementMcUeRefCodeStatutUe(
			String rattachementMcUeRefCodeStatutUe) {
		this.rattachementMcUeRefCodeStatutUe = rattachementMcUeRefCodeStatutUe;
	}

	/**
	 * [AssociationGroupePedagogiqueDto.rattachementMcUeCredits] Getter 
	 * @author MAKERRI Sofiane on : 6 oct. 2014  10:19:55
	 * @return the rattachementMcUeCredits
	 */
	public Integer getRattachementMcUeCredits() {
		return rattachementMcUeCredits;
	}

	/**
	 * [AssociationGroupePedagogiqueDto.rattachementMcUeCredits] Setter 
	 * @author MAKERRI Sofiane on : 6 oct. 2014  10:19:55
	 * @param rattachementMcUeCredits the rattachementMcUeCredits to set
	 */
	public void setRattachementMcUeCredits(Integer rattachementMcUeCredits) {
		this.rattachementMcUeCredits = rattachementMcUeCredits;
	}

	/**
	 * [AssociationGroupePedagogiqueDto.rattachementMcMcId] Getter 
	 * @author MAKERRI Sofiane on : 6 oct. 2014  10:36:26
	 * @return the rattachementMcMcId
	 */
	public Integer getRattachementMcMcId() {
		return rattachementMcMcId;
	}

	/**
	 * [AssociationGroupePedagogiqueDto.rattachementMcMcId] Setter 
	 * @author MAKERRI Sofiane on : 6 oct. 2014  10:36:26
	 * @param rattachementMcMcId the rattachementMcMcId to set
	 */
	public void setRattachementMcMcId(Integer rattachementMcMcId) {
		this.rattachementMcMcId = rattachementMcMcId;
	}

	/**
	 * [AssociationGroupePedagogiqueDto.rattachementMcOptionnelle] Getter 
	 * @author MAKERRI Sofiane on : 6 oct. 2014  16:07:37
	 * @return the rattachementMcOptionnelle
	 */
	public Boolean getRattachementMcOptionnelle() {
		return rattachementMcOptionnelle;
	}

	/**
	 * [AssociationGroupePedagogiqueDto.rattachementMcOptionnelle] Setter 
	 * @author MAKERRI Sofiane on : 6 oct. 2014  16:07:37
	 * @param rattachementMcOptionnelle the rattachementMcOptionnelle to set
	 */
	public void setRattachementMcOptionnelle(Boolean rattachementMcOptionnelle) {
		this.rattachementMcOptionnelle = rattachementMcOptionnelle;
	}

	/**
	 * [AssociationGroupePedagogiqueDto.groupePedagogiqueNom] Getter 
	 * @author MAKERRI Sofiane on : 12 oct. 2014  11:44:55
	 * @return the groupePedagogiqueNom
	 */
	public String getGroupePedagogiqueNom() {
		return groupePedagogiqueNom;
	}

	/**
	 * [AssociationGroupePedagogiqueDto.groupePedagogiqueNom] Setter 
	 * @author MAKERRI Sofiane on : 12 oct. 2014  11:44:55
	 * @param groupePedagogiqueNom the groupePedagogiqueNom to set
	 */
	public void setGroupePedagogiqueNom(String groupePedagogiqueNom) {
		this.groupePedagogiqueNom = groupePedagogiqueNom;
	}

	/**
	 * [AssociationGroupePedagogiqueDto.periodeId] Getter 
	 * @author MAKERRI Sofiane on : 20 oct. 2014  11:59:19
	 * @return the periodeId
	 */
	public Integer getPeriodeId() {
		return periodeId;
	}

	/**
	 * [AssociationGroupePedagogiqueDto.periodeId] Setter 
	 * @author MAKERRI Sofiane on : 20 oct. 2014  11:59:19
	 * @param periodeId the periodeId to set
	 */
	public void setPeriodeId(Integer periodeId) {
		this.periodeId = periodeId;
	}

	/**
	 * [AssociationGroupePedagogiqueDto.oofId] Getter 
	 * @author MAKERRI Sofiane on : 20 oct. 2014  12:02:05
	 * @return the oofId
	 */
	public Integer getOofId() {
		return oofId;
	}

	/**
	 * [AssociationGroupePedagogiqueDto.oofId] Setter 
	 * @author MAKERRI Sofiane on : 20 oct. 2014  12:02:05
	 * @param oofId the oofId to set
	 */
	public void setOofId(Integer oofId) {
		this.oofId = oofId;
	}

	
	
}
