package dz.gov.mesrs.sii.fve.ws.bo.offreformation;

//import dz.gov.mesrs.sii.referentiel.business.model.dto.nc.LangueDto;
//import dz.gov.mesrs.sii.referentiel.business.model.dto.nc.ModeEvaluationDto;
//import dz.gov.mesrs.sii.referentiel.business.model.dto.nc.TypeMCDto;
import java.util.HashSet;
import java.util.Set;

/**
 * MatiereConstitutiveDto generated by hbm2java
 */
public class MatiereConstitutive implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4894516154102281931L;
	private int id;
//	private TypeMCDto typeMCDto;
//	private ModeEvaluationDto modeEvaluationDto;
//	private LangueDto langueDto;
	private UniteEnseignement uniteEnseignementDto;
	private String code;
	private String libelleFr;
	private String abreviationFr;
	private String libelleAr;
	private String abreviationAr;
	private String abreviation;
	private String description;
	private String appreciation;
	private Integer credits;
	private Double coefficient;
	private Double noteDeBase;
	private Double noteEliminatoire;
	private Double noteObtension;
	private Boolean requise;
	private Double volumeHorairePerso;
	private Double volumeHorairePres;
	private String objectifs;
	private String contenu;
	private String competences;
	private String connaissancesRequises;
	private String recommandations;
	private String publicCible;
	private String aidesEtudiant;
	private String admission;
	private String observation;
	private String organisation;
	private Double points;
	private Set<AtomePedagogique> atomePedagogiqueDtos = new HashSet<AtomePedagogique>(
			0);

	public MatiereConstitutive() {
	}

	public MatiereConstitutive(int id,
			UniteEnseignement uniteEnseignementDto, String code,
			String libelleFr) {
		this.id = id;
		this.uniteEnseignementDto = uniteEnseignementDto;
		this.code = code;
		this.libelleFr = libelleFr;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

//	public TypeMCDto getTypeMCDto() {
//		return this.typeMCDto;
//	}
//
//	public void setTypeMCDto(TypeMCDto typeMCDto) {
//		this.typeMCDto = typeMCDto;
//	}
//
//	public ModeEvaluationDto getModeEvaluationDto() {
//		return this.modeEvaluationDto;
//	}
//
//	public void setModeEvaluationDto(ModeEvaluationDto modeEvaluationDto) {
//		this.modeEvaluationDto = modeEvaluationDto;
//	}
//
//	public LangueDto getLangueDto() {
//		return this.langueDto;
//	}
//
//	public void setLangueDto(LangueDto langueDto) {
//		this.langueDto = langueDto;
//	}

	public UniteEnseignement getUniteEnseignementDto() {
		return this.uniteEnseignementDto;
	}

	public void setUniteEnseignementDto(
			UniteEnseignement uniteEnseignementDto) {
		this.uniteEnseignementDto = uniteEnseignementDto;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getLibelleFr() {
		return this.libelleFr;
	}

	public void setLibelleFr(String libelleFr) {
		this.libelleFr = libelleFr;
	}

	public String getAbreviationFr() {
		return this.abreviationFr;
	}

	public void setAbreviationFr(String abreviationFr) {
		this.abreviationFr = abreviationFr;
	}

	public String getLibelleAr() {
		return this.libelleAr;
	}

	public void setLibelleAr(String libelleAr) {
		this.libelleAr = libelleAr;
	}

	public String getAbreviationAr() {
		return this.abreviationAr;
	}

	public void setAbreviationAr(String abreviationAr) {
		this.abreviationAr = abreviationAr;
	}

	public String getAbreviation() {
		return this.abreviation;
	}

	public void setAbreviation(String abreviation) {
		this.abreviation = abreviation;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getAppreciation() {
		return this.appreciation;
	}

	public void setAppreciation(String appreciation) {
		this.appreciation = appreciation;
	}

	public Integer getCredits() {
		return this.credits;
	}

	public void setCredits(Integer credits) {
		this.credits = credits;
	}

	public Double getCoefficient() {
		return this.coefficient;
	}

	public void setCoefficient(Double coefficient) {
		this.coefficient = coefficient;
	}

	public Double getNoteDeBase() {
		return this.noteDeBase;
	}

	public void setNoteDeBase(Double noteDeBase) {
		this.noteDeBase = noteDeBase;
	}

	public Double getNoteEliminatoire() {
		return this.noteEliminatoire;
	}

	public void setNoteEliminatoire(Double noteEliminatoire) {
		this.noteEliminatoire = noteEliminatoire;
	}

	public Double getNoteObtension() {
		return this.noteObtension;
	}

	public void setNoteObtension(Double noteObtension) {
		this.noteObtension = noteObtension;
	}

	public Boolean getRequise() {
		return this.requise;
	}

	public void setRequise(Boolean requise) {
		this.requise = requise;
	}

	public Double getVolumeHorairePerso() {
		return this.volumeHorairePerso;
	}

	public void setVolumeHorairePerso(Double volumeHorairePerso) {
		this.volumeHorairePerso = volumeHorairePerso;
	}

	public Double getVolumeHorairePres() {
		return this.volumeHorairePres;
	}

	public void setVolumeHorairePres(Double volumeHorairePres) {
		this.volumeHorairePres = volumeHorairePres;
	}

	public String getObjectifs() {
		return this.objectifs;
	}

	public void setObjectifs(String objectifs) {
		this.objectifs = objectifs;
	}

	public String getContenu() {
		return this.contenu;
	}

	public void setContenu(String contenu) {
		this.contenu = contenu;
	}

	public String getCompetences() {
		return this.competences;
	}

	public void setCompetences(String competences) {
		this.competences = competences;
	}

	public String getConnaissancesRequises() {
		return this.connaissancesRequises;
	}

	public void setConnaissancesRequises(String connaissancesRequises) {
		this.connaissancesRequises = connaissancesRequises;
	}

	public String getRecommandations() {
		return this.recommandations;
	}

	public void setRecommandations(String recommandations) {
		this.recommandations = recommandations;
	}

	public String getPublicCible() {
		return this.publicCible;
	}

	public void setPublicCible(String publicCible) {
		this.publicCible = publicCible;
	}

	public String getAidesEtudiant() {
		return this.aidesEtudiant;
	}

	public void setAidesEtudiant(String aidesEtudiant) {
		this.aidesEtudiant = aidesEtudiant;
	}

	public String getAdmission() {
		return this.admission;
	}

	public void setAdmission(String admission) {
		this.admission = admission;
	}

	public String getObservation() {
		return this.observation;
	}

	public void setObservation(String observation) {
		this.observation = observation;
	}

	public String getOrganisation() {
		return this.organisation;
	}

	public void setOrganisation(String organisation) {
		this.organisation = organisation;
	}

	public Double getPoints() {
		return this.points;
	}

	public void setPoints(Double points) {
		this.points = points;
	}

	public Set<AtomePedagogique> getAtomePedagogiqueDtos() {
		return this.atomePedagogiqueDtos;
	}

	public void setAtomePedagogiqueDtos(
			Set<AtomePedagogique> atomePedagogiqueDtos) {
		this.atomePedagogiqueDtos = atomePedagogiqueDtos;
	}

}
