package dz.gov.mesrs.sii.fve.ws.bo.offreformation;

/**
 * ParcoursTypeDto generated by hbm2java
 */
public class ParcoursType implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7098215669753535150L;
	private int id;
	//private OffreFormationDto offreFormationDto;
	private String abreviationAr;
	private String abreviationFr;
	private String code;
	private String libelleAr;
	private String libelleFr;
	
	public ParcoursType() {
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

//	PUBLIC OFFREFORMATIONDTO GETOFFREFORMATIONDTO() {
//		RETURN THIS.OFFREFORMATIONDTO;
//	}
//
//	PUBLIC VOID SETOFFREFORMATIONDTO(OFFREFORMATIONDTO OFFREFORMATIONDTO) {
//		THIS.OFFREFORMATIONDTO = OFFREFORMATIONDTO;
//	}

	public String getAbreviationAr() {
		return this.abreviationAr;
	}

	public void setAbreviationAr(String abreviationAr) {
		this.abreviationAr = abreviationAr;
	}

	public String getAbreviationFr() {
		return this.abreviationFr;
	}

	public void setAbreviationFr(String abreviationFr) {
		this.abreviationFr = abreviationFr;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getLibelleAr() {
		return this.libelleAr;
	}

	public void setLibelleAr(String libelleAr) {
		this.libelleAr = libelleAr;
	}

	public String getLibelleFr() {
		return this.libelleFr;
	}

	public void setLibelleFr(String libelleFr) {
		this.libelleFr = libelleFr;
	}

}
