package dz.gov.mesrs.sii.fve.ws.bo.offreformation;

//import dz.gov.mesrs.sii.referentiel.business.model.dto.nc.CaractereUEDto;
//import dz.gov.mesrs.sii.referentiel.business.model.dto.nc.NatureUEDto;
//import dz.gov.mesrs.sii.referentiel.business.model.dto.nc.StatutUEDto;
//import dz.gov.mesrs.sii.referentiel.business.model.dto.nc.TypeUEDto;

/**
 * UniteEnseignementDto generated by hbm2java
 */
public class UniteEnseignement implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4328349563212300761L;
	private int id;
	// private StatutUEDto statutUEDto;
	// private NatureUEDto natureUEDto;
	// private CaractereUEDto caractereUEDto;
	// private TypeUEDto typeUEDto;
	private String code;
	private String libelleFr;
	private String abreviationFr;
	private String libelleAr;
	private String abreviationAr;
	private Integer credits;
	private Integer coefficient;
	private String requise;
	private String objectifs;
	private String preRequisDesc;
	private Integer etat;

	public UniteEnseignement() {
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	// public StatutUEDto getStatutUEDto() {
	// return this.statutUEDto;
	// }
	//
	// public void setStatutUEDto(StatutUEDto statutUEDto) {
	// this.statutUEDto = statutUEDto;
	// }
	//
	// public NatureUEDto getNatureUEDto() {
	// return this.natureUEDto;
	// }
	//
	// public void setNatureUEDto(NatureUEDto natureUEDto) {
	// this.natureUEDto = natureUEDto;
	// }
	//
	// public CaractereUEDto getCaractereUEDto() {
	// return this.caractereUEDto;
	// }
	//
	// public void setCaractereUEDto(CaractereUEDto caractereUEDto) {
	// this.caractereUEDto = caractereUEDto;
	// }
	//
	// public TypeUEDto getTypeUEDto() {
	// return this.typeUEDto;
	// }
	//
	// public void setTypeUEDto(TypeUEDto typeUEDto) {
	// this.typeUEDto = typeUEDto;
	// }

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getLibelleFr() {
		return this.libelleFr;
	}

	public void setLibelleFr(String libelleFr) {
		this.libelleFr = libelleFr;
	}

	public String getAbreviationFr() {
		return this.abreviationFr;
	}

	public void setAbreviationFr(String abreviationFr) {
		this.abreviationFr = abreviationFr;
	}

	public String getLibelleAr() {
		return this.libelleAr;
	}

	public void setLibelleAr(String libelleAr) {
		this.libelleAr = libelleAr;
	}

	public String getAbreviationAr() {
		return this.abreviationAr;
	}

	public void setAbreviationAr(String abreviationAr) {
		this.abreviationAr = abreviationAr;
	}

	public Integer getCredits() {
		return this.credits;
	}

	public void setCredits(Integer credits) {
		this.credits = credits;
	}

	public Integer getCoefficient() {
		return this.coefficient;
	}

	public void setCoefficient(Integer coefficient) {
		this.coefficient = coefficient;
	}

	public String getRequise() {
		return this.requise;
	}

	public void setRequise(String requise) {
		this.requise = requise;
	}

	public String getObjectifs() {
		return this.objectifs;
	}

	public void setObjectifs(String objectifs) {
		this.objectifs = objectifs;
	}

	public String getPreRequisDesc() {
		return this.preRequisDesc;
	}

	public void setPreRequisDesc(String preRequisDesc) {
		this.preRequisDesc = preRequisDesc;
	}

	public Integer getEtat() {
		return this.etat;
	}

	public void setEtat(Integer etat) {
		this.etat = etat;
	}

}
