package dz.gov.mesrs.sii.commons.data.model.referentiel;

// Generated 20 janv. 2014 11:10:42 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * NcList generated by hbm2java
 */
@Entity
@Table(name = "nc_names", schema = "nc", uniqueConstraints = @UniqueConstraint(columnNames = "nom_nomenclature"))
public class NcNames implements java.io.Serializable {

	/**
	 * serialVersionUID 
	 * @author BELDI Jamel  on : 23 janv. 2014  11:20:00
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private NcNames ncNames;
	private String nomNomenclature;
	private String description;
	private Nomenclature defaultValue;
	private Set<NcNames> ncNamess = new HashSet<NcNames>(0);

	public NcNames() {
	}

	public NcNames(int id, String nomNomenclature) {
		this.id = id;
		this.nomNomenclature = nomNomenclature;
	}

	public NcNames(int id, NcNames ncNames, String nomNomenclature,
			String description, Set<NcNames> ncNamess) {
		this.id = id;
		this.ncNames = ncNames;
		this.nomNomenclature = nomNomenclature;
		this.description = description;
		this.ncNamess = ncNamess;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ref_etrangere")
	public NcNames getNcNames() {
		return this.ncNames;
	}

	public void setNcNames(NcNames ncNames) {
		this.ncNames = ncNames;
	}

	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "default_value")
	public Nomenclature getDefaultValue() {
		return defaultValue;
	}

	public void setDefaultValue(Nomenclature defaultValue) {
		this.defaultValue = defaultValue;
	}

	@Column(name = "nom_nomenclature", unique = true, nullable = false, length = 100)
	public String getNomNomenclature() {
		return this.nomNomenclature;
	}

	public void setNomNomenclature(String nomNomenclature) {
		this.nomNomenclature = nomNomenclature;
	}

	@Column(name = "description", length = 200)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}


	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ncNames")
	public Set<NcNames> getNcNamess() {
		return this.ncNamess;
	}

	public void setNcNamess(Set<NcNames> ncNamess) {
		this.ncNamess = ncNamess;
	}

}
