package dz.gov.mesrs.sii.commons.data.model.referentiel;

// Generated 20 janv. 2014 11:10:42 by Hibernate Tools 3.6.0

import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * NcValues generated by hbm2java
 */
@Entity
@Table(name = "nomenclature", schema = "nc")
public class Nomenclature implements java.io.Serializable {

	/**
	 * serialVersionUID
	 * 
	 * @author BELDI Jamel on : 23 janv. 2014 11:20:05
	 */
	
	private static final long serialVersionUID = 1L;
	private int id;
	private Nomenclature nomenclature;
	private NcNames ncNames;
	private String libelleLongFr;
	private String libelleLongAr;
	private String libelleCourtFr;
	private String libelleCourtAr;
	private Boolean status;
	private String code;
	// private Set<NcHistory> ncHistories = new HashSet<NcHistory>(0);
	private List<Nomenclature> nomenclatures;

	public Nomenclature() {
	}

	public Nomenclature(int id, String code) {
		this.id = id;
		this.code = code;
	}

	// public Nomenclature(int id, Nomenclature nomenclature, NcNames ncNames,
	// String libelleLongFr, String libelleLongAr, String libelleCourtFr,
	// String libelleCourtAr, Boolean status, String code, Set<NcHistory>
	// ncHistories,
	// Set<Nomenclature> ncValueses) {
	// this.id = id;
	// //this.nomenclature = nomenclature;
	// this.ncNames = ncNames;
	// this.libelleLongFr = libelleLongFr;
	// this.libelleLongAr = libelleLongAr;
	// this.libelleCourtFr = libelleCourtFr;
	// this.libelleCourtAr = libelleCourtAr;
	// this.status = status;
	// this.code = code;
	// this.ncHistories = ncHistories;
	// }

	@Id
	@SequenceGenerator(name = "seq_nc", initialValue = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq_nc")
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ref_valeur")
	public Nomenclature getNomenclature() {
		return this.nomenclature;
	}

	public void setNomenclature(Nomenclature nomenclature) {
		this.nomenclature = nomenclature;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_list")
	public NcNames getNcNames() {
		return this.ncNames;
	}

	public void setNcNames(NcNames ncNames) {
		this.ncNames = ncNames;
	}

	@Column(name = "libelle_long_fr", length = 100)
	public String getLibelleLongFr() {
		return this.libelleLongFr;
	}

	public void setLibelleLongFr(String libelleLongFr) {
		this.libelleLongFr = libelleLongFr;
	}

	@Column(name = "libelle_long_ar", length = 100)
	public String getLibelleLongAr() {
		return this.libelleLongAr;
	}

	public void setLibelleLongAr(String libelleLongAr) {
		this.libelleLongAr = libelleLongAr;
	}

	@Column(name = "libelle_court_fr", length = 100)
	public String getLibelleCourtFr() {
		return this.libelleCourtFr;
	}

	public void setLibelleCourtFr(String libelleCourtFr) {
		this.libelleCourtFr = libelleCourtFr;
	}

	@Column(name = "libelle_court_ar", length = 100)
	public String getLibelleCourtAr() {
		return this.libelleCourtAr;
	}

	public void setLibelleCourtAr(String libelleCourtAr) {
		this.libelleCourtAr = libelleCourtAr;
	}

	@Column(name = "code", unique = false, nullable = false, length = 30)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	
	
	/**
	 * [Nomenclature.nomenclatures] Getter 
	 * @author MAKERRI Sofiane on : 6 janv. 2015  10:59:59
	 * @return the nomenclatures
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nomenclature", cascade = CascadeType.ALL, orphanRemoval = true)
	public List<Nomenclature> getNomenclatures() {
		return nomenclatures;
	}

	/**
	 * [Nomenclature.nomenclatures] Setter 
	 * @author MAKERRI Sofiane on : 6 janv. 2015  10:59:59
	 * @param nomenclatures the nomenclatures to set
	 */
	public void setNomenclatures(List<Nomenclature> nomenclatures) {
		this.nomenclatures = nomenclatures;
	}

	@Column(name = "status")
	public Boolean getStatus() {
		return status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

}
