package dz.gov.mesrs.sii.commons.data.model.referentiel;

// Generated 13 mai 2014 16:25:10 by Hibernate Tools 3.6.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RefAffectDocument generated by hbm2java
 */
@Entity
@Table(name = "ref_affect_document", schema = "ppm")
public class RefAffectDocument implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int id;
	private Nomenclature nomenclature;
	private RefIndividu refIndividu;
	private RefDocument refDocument;
	private RefGroupe refGroupe;
	private RefStructure refStructure;
	private Date dateDebut;
	private Date dateFin;
	private Boolean estAuteur;
	private String observation;

	public RefAffectDocument() {
	}

	public RefAffectDocument(int id, RefDocument refDocument) {
		this.id = id;
		this.refDocument = refDocument;
	}

	public RefAffectDocument(int id, Nomenclature nomenclature,
			RefIndividu refIndividu, RefDocument refDocument,
			RefGroupe refGroupe, RefStructure refStructure, Date dateDebut,
			Date dateFin, Boolean estAuteur, String observation) {
		this.id = id;
		this.nomenclature = nomenclature;
		this.refIndividu = refIndividu;
		this.refDocument = refDocument;
		this.refGroupe = refGroupe;
		this.refStructure = refStructure;
		this.dateDebut = dateDebut;
		this.dateFin = dateFin;
		this.estAuteur = estAuteur;
		this.observation = observation;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "role")
	public Nomenclature getNomenclature() {
		return this.nomenclature;
	}

	public void setNomenclature(Nomenclature nomenclature) {
		this.nomenclature = nomenclature;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "individu")
	public RefIndividu getRefIndividu() {
		return this.refIndividu;
	}

	public void setRefIndividu(RefIndividu refIndividu) {
		this.refIndividu = refIndividu;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "document", nullable = false)
	public RefDocument getRefDocument() {
		return this.refDocument;
	}

	public void setRefDocument(RefDocument refDocument) {
		this.refDocument = refDocument;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "groupe")
	public RefGroupe getRefGroupe() {
		return this.refGroupe;
	}

	public void setRefGroupe(RefGroupe refGroupe) {
		this.refGroupe = refGroupe;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "structure")
	public RefStructure getRefStructure() {
		return this.refStructure;
	}

	public void setRefStructure(RefStructure refStructure) {
		this.refStructure = refStructure;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_debut", length = 29)
	public Date getDateDebut() {
		return this.dateDebut;
	}

	public void setDateDebut(Date dateDebut) {
		this.dateDebut = dateDebut;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_fin", length = 29)
	public Date getDateFin() {
		return this.dateFin;
	}

	public void setDateFin(Date dateFin) {
		this.dateFin = dateFin;
	}

	@Column(name = "est_auteur")
	public Boolean getEstAuteur() {
		return this.estAuteur;
	}

	public void setEstAuteur(Boolean estAuteur) {
		this.estAuteur = estAuteur;
	}

	@Column(name = "observation", length = 200)
	public String getObservation() {
		return this.observation;
	}

	public void setObservation(String observation) {
		this.observation = observation;
	}

}
