package dz.gov.mesrs.sii.commons.data.model.referentiel;

// Generated 20 avr. 2014 10:05:59 by Hibernate Tools 3.6.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * RefAffectDomLmdEtab generated by hbm2java
 */
@Entity
@Table(name = "ref_affect_dom_lmd_etab", schema = "ppm", uniqueConstraints = @UniqueConstraint(columnNames = {
		"domainelmd", "etablissement" }))
public class RefAffectDomLmdEtab implements java.io.Serializable {

	/**
	 * serialVersionUID 
	 * @author BELBRIK Oualid  on : 20 avr. 2014  11:12:56
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private RefEtablissement refEtablissement;
	private RefDomaineLMD refDomaineLMD;
	private Date date;
	private String observation;
	private RefGroupe refGroupe;
	private RefStructure refStructure;

	public RefAffectDomLmdEtab() {
	}

	public RefAffectDomLmdEtab(int id, RefEtablissement refEtablissement,
			RefDomaineLMD refDomaineLMD, Date date, RefGroupe refGroupe, RefStructure refStructure) {
		this.id = id;
		this.refEtablissement = refEtablissement;
		this.refDomaineLMD = refDomaineLMD;
		this.date = date;
		this.refGroupe = refGroupe;
		this.refStructure = refStructure;
		
	}

	public RefAffectDomLmdEtab(int id, RefEtablissement refEtablissement,
			RefDomaineLMD refDomaineLMD, Date date, String observation) {
		this.id = id;
		this.refEtablissement = refEtablissement;
		this.refDomaineLMD = refDomaineLMD;
		this.date = date;
		this.observation = observation;
	}

	
		@Id
	@Column(name = "id", unique = true, nullable = false)
	@SequenceGenerator(name = "seq_affect_dom_lmd_etab", initialValue = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq_affect_dom_lmd_etab")
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "etablissement", nullable = false)
	public RefEtablissement getRefEtablissement() {
		return this.refEtablissement;
	}

	public void setRefEtablissement(RefEtablissement refEtablissement) {
		this.refEtablissement = refEtablissement;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "domainelmd", nullable = false)
	public RefDomaineLMD getRefDomaineLMD() {
		return this.refDomaineLMD;
	}

	public void setRefDomaineLMD(RefDomaineLMD refDomaineLMD) {
		this.refDomaineLMD = refDomaineLMD;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", nullable = false, length = 29)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "observation")
	public String getObservation() {
		return this.observation;
	}

	public void setObservation(String observation) {
		this.observation = observation;
	}
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "groupe")
	public RefGroupe getRefGroupe() {
		return this.refGroupe;
	}

	public void setRefGroupe(RefGroupe refGroupe) {
		this.refGroupe = refGroupe;
	}
	

@ManyToOne(fetch = FetchType.EAGER)
@JoinColumn(name = "structure")
public RefStructure getRefStructure() {
	return this.refStructure;
}

public void setRefStructure(RefStructure refStructure) {
	this.refStructure = refStructure;
}

}
