package dz.gov.mesrs.sii.commons.data.model.referentiel;

// Generated 21 janv. 2014 17:45:57 by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

/**
 * RefAdresse generated by hbm2java
 */
@Entity
@Table(name = "ref_adresse", schema = "ppm")
public class RefAdresse implements java.io.Serializable {

	/**
	 * serialVersionUID 
	 * @author BELDI Jamel  on : 23 janv. 2014  11:20:11
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private Nomenclature nomenclatureByPays;
	private RefCoordonnee refCoordonnee;
	private Nomenclature nomenclatureByDaira;
	private Nomenclature nomenclatureByCommune;
	private Nomenclature nomenclatureByWilaya;
	private Nomenclature nomenclatureByTypeAdresse;
	private Short boitePostale;
	private String codePostal;
	private Short gpsLatitude;
	private Short gpsLongitude;
	private String libelleAdresseArabe;
	private String libelleAdresseLatin;

	public RefAdresse() {
	}

	public RefAdresse(RefCoordonnee refCoordonnee) {
		this.refCoordonnee = refCoordonnee;
	}

	public RefAdresse(Nomenclature nomenclatureByPays,
			RefCoordonnee refCoordonnee, Nomenclature nomenclatureByDaira,
			Nomenclature nomenclatureByCommune,
			Nomenclature nomenclatureByWilaya,
			Nomenclature nomenclatureByTypeAdresse, String  codePostal, Short boitePostale,
			Short gpsLatitude, Short gpsLongitude, String libelleAdresseArabe,
			String libelleAdresseLatin) {
		this.nomenclatureByPays = nomenclatureByPays;
		this.refCoordonnee = refCoordonnee;
		this.nomenclatureByDaira = nomenclatureByDaira;
		this.nomenclatureByCommune = nomenclatureByCommune;
		this.nomenclatureByWilaya = nomenclatureByWilaya;
		this.nomenclatureByTypeAdresse = nomenclatureByTypeAdresse;
		this.boitePostale = boitePostale;
		this.codePostal = codePostal;
		this.gpsLatitude = gpsLatitude;
		this.gpsLongitude = gpsLongitude;
		this.libelleAdresseArabe = libelleAdresseArabe;
		this.libelleAdresseLatin = libelleAdresseLatin;
	}

	//@GenericGenerator(name = "generator_adresse", strategy = "foreign", parameters = @Parameter(name = "property", value = "refCoordonnee"))
	//@GeneratedValue(generator = "generator_adresse")
	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pays")
	public Nomenclature getNomenclatureByPays() {
		return this.nomenclatureByPays;
	}

	public void setNomenclatureByPays(Nomenclature nomenclatureByPays) {
		this.nomenclatureByPays = nomenclatureByPays;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public RefCoordonnee getRefCoordonnee() {
		return this.refCoordonnee;
	}

	public void setRefCoordonnee(RefCoordonnee refCoordonnee) {
		this.refCoordonnee = refCoordonnee;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "daira")
	public Nomenclature getNomenclatureByDaira() {
		return this.nomenclatureByDaira;
	}

	public void setNomenclatureByDaira(Nomenclature nomenclatureByDaira) {
		this.nomenclatureByDaira = nomenclatureByDaira;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "commune")
	public Nomenclature getNomenclatureByCommune() {
		return this.nomenclatureByCommune;
	}

	public void setNomenclatureByCommune(Nomenclature nomenclatureByCommune) {
		this.nomenclatureByCommune = nomenclatureByCommune;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "wilaya")
	public Nomenclature getNomenclatureByWilaya() {
		return this.nomenclatureByWilaya;
	}

	public void setNomenclatureByWilaya(Nomenclature nomenclatureByWilaya) {
		this.nomenclatureByWilaya = nomenclatureByWilaya;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "type_adresse")
	public Nomenclature getNomenclatureByTypeAdresse() {
		return this.nomenclatureByTypeAdresse;
	}

	public void setNomenclatureByTypeAdresse(
			Nomenclature nomenclatureByTypeAdresse) {
		this.nomenclatureByTypeAdresse = nomenclatureByTypeAdresse;
	}

	@Column(name = "boite_postale")
	public Short getBoitePostale() {
		return this.boitePostale;
	}

	public void setBoitePostale(Short boitePostale) {
		this.boitePostale = boitePostale;
	}
	
	@Column(name = "code_postal", length = 15)
	public String getCodePostal() {
		return codePostal;
	}

	public void setCodePostal(String codePostal) {
		this.codePostal = codePostal;
	}

	@Column(name = "gps_latitude")
	public Short getGpsLatitude() {
		return this.gpsLatitude;
	}


	public void setGpsLatitude(Short gpsLatitude) {
		this.gpsLatitude = gpsLatitude;
	}

	@Column(name = "gps_longitude")
	public Short getGpsLongitude() {
		return this.gpsLongitude;
	}

	public void setGpsLongitude(Short gpsLongitude) {
		this.gpsLongitude = gpsLongitude;
	}

	@Column(name = "libelle_adresse_arabe", length = 250)
	public String getLibelleAdresseArabe() {
		return this.libelleAdresseArabe;
	}

	public void setLibelleAdresseArabe(String libelleAdresseArabe) {
		this.libelleAdresseArabe = libelleAdresseArabe;
	}

	@Column(name = "libelle_adresse_latin", nullable = false, length = 250)
	public String getLibelleAdresseLatin() {
		return this.libelleAdresseLatin;
	}

	public void setLibelleAdresseLatin(String libelleAdresseLatin) {
		this.libelleAdresseLatin = libelleAdresseLatin;
	}

}
