package dz.gov.mesrs.sii.commons.data.model.referentiel;

// créated 18 08 2014. 10:05:59 by OualidBELBRIK 

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RefAffectfilierLmdEtab generated by hbm2java
 */
@Entity
@Table(name = "ref_affect_filiere_lmd_etab", schema = "ppm")
public class RefAffectFiliereLmdEtab implements java.io.Serializable {

	/**
	 * serialVersionUID 
	 * @author BELBRIK Oualid  on : 20 08. 2014  11:12:56
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private RefEtablissement refEtablissement;
	private RefFiliereLmd refFiliereLmd;
	private Date date;
	private String observation;
	private RefGroupe refGroupe;
	private String numArrete;
	private RefStructure refStructure;
	
	public RefAffectFiliereLmdEtab() {
	}

	public RefAffectFiliereLmdEtab(int id, RefEtablissement refEtablissement,
			RefFiliereLmd refFiliereLmd, Date date, RefGroupe refGroupe, RefStructure refStructure) {
		this.id = id;
		this.refEtablissement = refEtablissement;
		this.refFiliereLmd = refFiliereLmd;
		this.date = date;
		this.refGroupe = refGroupe;
		this.refStructure = refStructure;
		
	}

	public RefAffectFiliereLmdEtab(int id, RefEtablissement refEtablissement,
			RefFiliereLmd refFiliereLmd, Date date, String observation, String numArrete) {
		this.id = id;
		this.refEtablissement = refEtablissement;
		this.refFiliereLmd = refFiliereLmd;
		this.date = date;
		this.observation = observation;
		this.numArrete = numArrete;
	}

	
		@Id
	@Column(name = "id", unique = true, nullable = false)
	@SequenceGenerator(name = "seq_affect_filiere_lmd_etab", initialValue = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq_affect_filiere_lmd_etab")
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "etablissement", nullable = false)
	public RefEtablissement getRefEtablissement() {
		return this.refEtablissement;
	}

	public void setRefEtablissement(RefEtablissement refEtablissement) {
		this.refEtablissement = refEtablissement;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "filierelmd", nullable = false)
	public RefFiliereLmd getRefFiliereLmd() {
		return this.refFiliereLmd;
	}

	public void setRefFiliereLmd(RefFiliereLmd refFiliereLmd) {
		this.refFiliereLmd = refFiliereLmd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", nullable = false, length = 29)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "observation")
	public String getObservation() {
		return this.observation;
	}

	public void setObservation(String observation) {
		this.observation = observation;
	}
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "groupe")
	public RefGroupe getRefGroupe() {
		return this.refGroupe;
	}

	public void setRefGroupe(RefGroupe refGroupe) {
		this.refGroupe = refGroupe;
	}
	
	@Column(name = "numarrete")
	public String getNumArrete() {
		return this.numArrete;
	}

	public void setNumArrete(String numArrete) {
		this.numArrete = numArrete;
	}


@ManyToOne(fetch = FetchType.EAGER)
@JoinColumn(name = "structure")
public RefStructure getRefStructure() {
	return this.refStructure;
}

public void setRefStructure(RefStructure refStructure) {
	this.refStructure = refStructure;
}
}
