package dz.gov.mesrs.sii.commons.data.model.referentiel;

// Generated 21 janv. 2014 17:45:57 by Hibernate Tools 3.6.0

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RefContrat generated by hbm2java
 */
@Entity
@Table(name = "ref_contrat", schema = "ppm")
public class RefContrat implements java.io.Serializable {

	/**
	 * serialVersionUID
	 * 
	 * @author BELDI Jamel on : 23 janv. 2014 11:20:20
	 */
	private static final long serialVersionUID = 1L;
	private String identifiant;
	private int id;
	private RefContrat refContrat;
	private Nomenclature nomenclatureByNatureContrat;
	//private RefStructure refStructureByEtablissement;
	private RefStructure refStructureByService;
	private RefEtablissement refEtablissement;
	private Nomenclature nomenclatureByDiscipline;
	private Nomenclature nomenclatureByUniteMonetaire;
	private Boolean avenant;
	private Date dateCreation;
	private Date dateDebutValidite;
	private Date dateFinValidite;
	private Date dateSignatureGestionnaire;
	private Short duree;
	private BigDecimal montantHt;
	private BigDecimal montantTtc;
	private BigDecimal montantTva;
	private String objetContratAr;
	private String objetContratFr;
	private String observation;
	private Boolean reconductible;
	private String referenceDocumentaire;
	private Nomenclature nomenclatureByTypeAvenant;
	private Set<RefContrat> refContrats = new HashSet<RefContrat>(0);
	private Set<RefPartenaire> refPartenaires = new HashSet<RefPartenaire>(0);

	public RefContrat() {
	}

	public RefContrat(String identifiant, Date dateCreation,
			Date dateDebutValidite, String objetContratFr) {
		this.identifiant = identifiant;
		this.dateCreation = dateCreation;
		this.dateDebutValidite = dateDebutValidite;
		this.objetContratFr = objetContratFr;
	}

	public RefContrat(String identifiant, RefContrat refContrat,
			Nomenclature nomenclatureByNatureContrat,
			RefEtablissement refEtablissement,
			RefStructure refStructureByEtablissement,
			RefStructure refStructureByService,
			Nomenclature nomenclatureByDiscipline,
			Nomenclature nomenclatureByUniteMonetaire, Boolean avenant,
			Date dateCreation, Date dateDebutValidite, Date dateFinValidite,
			Date dateSignatureGestionnaire, Short duree, BigDecimal montantHt,
			BigDecimal montantTtc, BigDecimal montantTva,
			String objetContratAr, String objetContratFr, String observation,
			Boolean reconductible, String referenceDocumentaire,
			Set<RefContrat> refContrats, Set<RefPartenaire> refPartenaires) {
		this.identifiant = identifiant;
		this.refContrat = refContrat;
		this.nomenclatureByNatureContrat = nomenclatureByNatureContrat;
		this.refEtablissement = refEtablissement;
		//this.refStructureByEtablissement = refStructureByEtablissement;
		this.refStructureByService = refStructureByService;
		this.nomenclatureByDiscipline = nomenclatureByDiscipline;
		this.nomenclatureByUniteMonetaire = nomenclatureByUniteMonetaire;
		this.avenant = avenant;
		this.dateCreation = dateCreation;
		this.dateDebutValidite = dateDebutValidite;
		this.dateFinValidite = dateFinValidite;
		this.dateSignatureGestionnaire = dateSignatureGestionnaire;
		this.duree = duree;
		this.montantHt = montantHt;
		this.montantTtc = montantTtc;
		this.montantTva = montantTva;
		this.objetContratAr = objetContratAr;
		this.objetContratFr = objetContratFr;
		this.observation = observation;
		this.reconductible = reconductible;
		this.referenceDocumentaire = referenceDocumentaire;
		this.refContrats = refContrats;
		this.refPartenaires = refPartenaires;
	}
	
	@Id
	@SequenceGenerator(name = "seq_contrat", initialValue = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq_contrat")
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "identifiant", unique = true, nullable = false, length = 50)
	public String getIdentifiant() {
		return this.identifiant;
	}

	public void setIdentifiant(String identifiant) {
		this.identifiant = identifiant;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "etablissement")
	public RefEtablissement getRefEtablissement() {
		return this.refEtablissement;
	}

	public void setRefEtablissement(RefEtablissement refEtablissement) {
		this.refEtablissement = refEtablissement;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "contrat")
	public RefContrat getRefContrat() {
		return this.refContrat;
	}

	public void setRefContrat(RefContrat refContrat) {
		this.refContrat = refContrat;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "nature_contrat")
	public Nomenclature getNomenclatureByNatureContrat() {
		return this.nomenclatureByNatureContrat;
	}

	public void setNomenclatureByNatureContrat(
			Nomenclature nomenclatureByNatureContrat) {
		this.nomenclatureByNatureContrat = nomenclatureByNatureContrat;
	}

	/*@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "etablissement")
	public RefStructure getRefStructureByEtablissement() {
		return this.refStructureByEtablissement;
	}

	public void setRefStructureByEtablissement(
			RefStructure refStructureByEtablissement) {
		this.refStructureByEtablissement = refStructureByEtablissement;
	}*/

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "service")
	public RefStructure getRefStructureByService() {
		return this.refStructureByService;
	}

	public void setRefStructureByService(RefStructure refStructureByService) {
		this.refStructureByService = refStructureByService;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "discipline")
	public Nomenclature getNomenclatureByDiscipline() {
		return this.nomenclatureByDiscipline;
	}

	public void setNomenclatureByDiscipline(
			Nomenclature nomenclatureByDiscipline) {
		this.nomenclatureByDiscipline = nomenclatureByDiscipline;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "unite_monetaire")
	public Nomenclature getNomenclatureByUniteMonetaire() {
		return this.nomenclatureByUniteMonetaire;
	}

	public void setNomenclatureByUniteMonetaire(
			Nomenclature nomenclatureByUniteMonetaire) {
		this.nomenclatureByUniteMonetaire = nomenclatureByUniteMonetaire;
	}

	@Column(name = "avenant")
	public Boolean getAvenant() {
		return this.avenant;
	}

	public void setAvenant(Boolean avenant) {
		this.avenant = avenant;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_creation", nullable = false, length = 29)
	public Date getDateCreation() {
		return this.dateCreation;
	}

	public void setDateCreation(Date dateCreation) {
		this.dateCreation = dateCreation;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_debut_validite", nullable = false, length = 29)
	public Date getDateDebutValidite() {
		return this.dateDebutValidite;
	}

	public void setDateDebutValidite(Date dateDebutValidite) {
		this.dateDebutValidite = dateDebutValidite;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_fin_validite", length = 29)
	public Date getDateFinValidite() {
		return this.dateFinValidite;
	}

	public void setDateFinValidite(Date dateFinValidite) {
		this.dateFinValidite = dateFinValidite;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_signature_gestionnaire", length = 29)
	public Date getDateSignatureGestionnaire() {
		return this.dateSignatureGestionnaire;
	}

	public void setDateSignatureGestionnaire(Date dateSignatureGestionnaire) {
		this.dateSignatureGestionnaire = dateSignatureGestionnaire;
	}

	@Column(name = "duree")
	public Short getDuree() {
		return this.duree;
	}

	public void setDuree(Short duree) {
		this.duree = duree;
	}

	@Column(name = "montant_ht")
	public BigDecimal getMontantHt() {
		return this.montantHt;
	}

	public void setMontantHt(BigDecimal montantHt) {
		this.montantHt = montantHt;
	}

	@Column(name = "montant_ttc")
	public BigDecimal getMontantTtc() {
		return this.montantTtc;
	}

	public void setMontantTtc(BigDecimal montantTtc) {
		this.montantTtc = montantTtc;
	}

	@Column(name = "montant_tva")
	public BigDecimal getMontantTva() {
		return this.montantTva;
	}

	public void setMontantTva(BigDecimal montantTva) {
		this.montantTva = montantTva;
	}

	@Column(name = "objet_contrat_ar")
	public String getObjetContratAr() {
		return this.objetContratAr;
	}

	public void setObjetContratAr(String objetContratAr) {
		this.objetContratAr = objetContratAr;
	}

	@Column(name = "objet_contrat_fr", nullable = false)
	public String getObjetContratFr() {
		return this.objetContratFr;
	}

	public void setObjetContratFr(String objetContratFr) {
		this.objetContratFr = objetContratFr;
	}

	@Column(name = "observation")
	public String getObservation() {
		return this.observation;
	}

	public void setObservation(String observation) {
		this.observation = observation;
	}

	@Column(name = "reconductible")
	public Boolean getReconductible() {
		return this.reconductible;
	}

	public void setReconductible(Boolean reconductible) {
		this.reconductible = reconductible;
	}

	@Column(name = "reference_documentaire")
	public String getReferenceDocumentaire() {
		return this.referenceDocumentaire;
	}

	public void setReferenceDocumentaire(String referenceDocumentaire) {
		this.referenceDocumentaire = referenceDocumentaire;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refContrat")
	public Set<RefContrat> getRefContrats() {
		return this.refContrats;
	}

	public void setRefContrats(Set<RefContrat> refContrats) {
		this.refContrats = refContrats;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refContrat")
	public Set<RefPartenaire> getRefPartenaires() {
		return this.refPartenaires;
	}

	public void setRefPartenaires(Set<RefPartenaire> refPartenaires) {
		this.refPartenaires = refPartenaires;
	}

	/**
	 * [RefContrat.nomenclatureByTypeAvenant] Getter
	 * 
	 * @author BELDI Jamel on : 6 f�vr. 2014 14:42:07
	 * @return the nomenclatureByTypeAvenant
	 */
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "type_avenant")
	public Nomenclature getNomenclatureByTypeAvenant() {
		return nomenclatureByTypeAvenant;
	}

	/**
	 * [RefContrat.nomenclatureByTypeAvenant] Setter
	 * 
	 * @author BELDI Jamel on : 6 f�vr. 2014 14:42:07
	 * @param nomenclatureByTypeAvenant
	 *            the nomenclatureByTypeAvenant to set
	 */
	public void setNomenclatureByTypeAvenant(
			Nomenclature nomenclatureByTypeAvenant) {
		this.nomenclatureByTypeAvenant = nomenclatureByTypeAvenant;
	}

}
