package dz.gov.mesrs.sii.commons.data.model.referentiel;

// Generated 17 f�vr. 2014 18:36:28 by Hibernate Tools 3.6.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RefCompte generated by hbm2java
 */
@Entity
@Table(name = "ref_compte", schema = "ppm")
public class RefCompte implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int id;
	private RefHoraireAccess refHoraireAccess;
	private RefPlageAdresse refPlageAdresse;
	private String nomUtilisateur;
	private String motPasse;
	private Date dateDebut;
	private Date dateFin;
	private String reponse;
	private Boolean premiereSession;
	private Boolean changementMotPasse;
	private Boolean accessJourFerie;
	private Boolean admin;
	private Nomenclature nomenclatureByQuestionSecrete;
	private RefEtablissement refEtablissement;
	
	private String situation;
	private RefIndividu refIndividu;
//	private Set<RefHistorique> refHistoriques = new HashSet<RefHistorique>(0);

	public RefCompte() {
	}

	public RefCompte(int id, String nomUtilisateur, String motPasse,
			Date dateDebut) {
		this.id = id;
		this.nomUtilisateur = nomUtilisateur;
		this.motPasse = motPasse;
		this.dateDebut = dateDebut;
	}

	public RefCompte(int id, RefHoraireAccess refHoraireAccess,
			RefPlageAdresse refPlageAdresse, String nomUtilisateur,
			String motPasse, Date dateDebut, Date dateFin, String reponse,
			Boolean premiereSession, Boolean changementMotPasse,
			Boolean accessJourFerie, String questionSecrete, String situation,
			RefIndividu refIndividu) {
		this.id = id;
		this.refHoraireAccess = refHoraireAccess;
		this.refPlageAdresse = refPlageAdresse;
		this.nomUtilisateur = nomUtilisateur;
		this.motPasse = motPasse;
		this.dateDebut = dateDebut;
		this.dateFin = dateFin;
		this.reponse = reponse;
		this.premiereSession = premiereSession;
		this.changementMotPasse = changementMotPasse;
		this.accessJourFerie = accessJourFerie;
		
		this.situation = situation;
		this.refIndividu = refIndividu;
	}

	@Id
	@SequenceGenerator(name="seq_compte", initialValue = 1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator = "seq_compte")
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "horaire_access")
	public RefHoraireAccess getRefHoraireAccess() {
		return this.refHoraireAccess;
	}

	public void setRefHoraireAccess(RefHoraireAccess refHoraireAccess) {
		this.refHoraireAccess = refHoraireAccess;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "plage_adresse")
	public RefPlageAdresse getRefPlageAdresse() {
		return this.refPlageAdresse;
	}

	public void setRefPlageAdresse(RefPlageAdresse refPlageAdresse) {
		this.refPlageAdresse = refPlageAdresse;
	}

	@Column(name = "nom_utilisateur", nullable = false, length = 25)
	public String getNomUtilisateur() {
		return this.nomUtilisateur;
	}

	public void setNomUtilisateur(String nomUtilisateur) {
		this.nomUtilisateur = nomUtilisateur;
	}

	@Column(name = "mot_passe", nullable = false, length = 100)
	public String getMotPasse() {
		return this.motPasse;
	}

	public void setMotPasse(String motPasse) {
		this.motPasse = motPasse;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_debut", nullable = false, length = 13)
	public Date getDateDebut() {
		return this.dateDebut;
	}

	public void setDateDebut(Date dateDebut) {
		this.dateDebut = dateDebut;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_fin", length = 13)
	public Date getDateFin() {
		return this.dateFin;
	}

	public void setDateFin(Date dateFin) {
		this.dateFin = dateFin;
	}

	@Column(name = "reponse", length = 200)
	public String getReponse() {
		return this.reponse;
	}

	public void setReponse(String reponse) {
		this.reponse = reponse;
	}

	@Column(name = "premiere_session")
	public Boolean getPremiereSession() {
		return this.premiereSession;
	}

	public void setPremiereSession(Boolean premiereSession) {
		this.premiereSession = premiereSession;
	}

	@Column(name = "changement_mot_passe")
	public Boolean getChangementMotPasse() {
		return this.changementMotPasse;
	}

	public void setChangementMotPasse(Boolean changementMotPasse) {
		this.changementMotPasse = changementMotPasse;
	}

	@Column(name = "access_jour_ferie")
	public Boolean getAccessJourFerie() {
		return this.accessJourFerie;
	}

	public void setAccessJourFerie(Boolean accessJourFerie) {
		this.accessJourFerie = accessJourFerie;
	}

	

	@Column(name = "situation")
	public String getSituation() {
		return this.situation;
	}

	public void setSituation(String situation) {
		this.situation = situation;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "individu")
	public RefIndividu getRefIndividu() {
		return this.refIndividu;
	}

	public void setRefIndividu(RefIndividu refIndividu) {
		this.refIndividu = refIndividu;
	}

	/**
	 * [RefCompte.nomenclatureByQuestionSecrete] Getter 
	 * @author BELDI Jamel on : 1 mars 2014  11:32:31
	 * @return the nomenclatureByQuestionSecrete
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "questionSecrete")
	public Nomenclature getNomenclatureByQuestionSecrete() {
		return nomenclatureByQuestionSecrete;
	}

	/**
	 * [RefCompte.nomenclatureByQuestionSecrete] Setter 
	 * @author BELDI Jamel on : 1 mars 2014  11:32:31
	 * @param nomenclatureByQuestionSecrete the nomenclatureByQuestionSecrete to set
	 */
	public void setNomenclatureByQuestionSecrete(
			Nomenclature nomenclatureByQuestionSecrete) {
		this.nomenclatureByQuestionSecrete = nomenclatureByQuestionSecrete;
	}

	/**
	 * [RefCompte.admin] Getter 
	 * @author MAKERRI Sofiane on : 16 mars 2014  11:10:56
	 * @return the admin
	 */
	@Column(name = "admin")
	public Boolean getAdmin() {
		return admin;
	}

	/**
	 * [RefCompte.admin] Setter 
	 * @author MAKERRI Sofiane on : 16 mars 2014  11:10:57
	 * @param admin the admin to set
	 */
	public void setAdmin(Boolean admin) {
		this.admin = admin;
	}

	
	/**
	 * [RefCompte.getRefEtablissement] Method 
	 * @author MAKERRI Sofiane  on : 16 juil. 2014  10:31:00
	 * @return
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "etablissement")
	public RefEtablissement getRefEtablissement() {
		return this.refEtablissement;
	}

	/**
	 * [RefCompte.setRefEtablissement] Method 
	 * @author MAKERRI Sofiane  on : 16 juil. 2014  10:31:03
	 * @param refEtablissement
	 */
	public void setRefEtablissement(RefEtablissement refEtablissement) {
		this.refEtablissement = refEtablissement;
	}
	
	
	
	
	
}
