package dz.gov.mesrs.sii.commons.data.model.referentiel;

// Generated 21 janv. 2014 17:45:57 by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * RefCoordonnee generated by hbm2java
 */
@Entity
@Table(name = "ref_coordonnee", schema = "ppm")
public class RefCoordonnee implements java.io.Serializable {

	/**
	 * serialVersionUID
	 * 
	 * @author BELDI Jamel on : 23 janv. 2014 11:20:27
	 */
	
	private static final long serialVersionUID = 1L;
	private int id;
	private RefEtablissement refEtablissement;
	private RefIndividu refIndividu;
	private RefStructure refStructure;
	private Boolean listeRouge;
	private Boolean principal;
	private RefTelephone refTelephone;
	private RefAdresseElectronique refAdresseElectronique;
	private RefAdresse refAdresse;
	private int typeCoordonnee;

	private RefLieu refLieu;

	public RefCoordonnee() {
	}

	public RefCoordonnee(int id) {
		this.id = id;
	}

	public RefCoordonnee(int id, int typeCoordonnee,
			RefEtablissement refEtablissement, RefIndividu refIndividu,
			RefStructure refStructure, Boolean listeRouge, Boolean principal,
			RefTelephone refTelephone,
			RefAdresseElectronique refAdresseElectronique,
			RefAdresse refAdresse, RefLieu refLieu) {
		this.id = id;
		this.typeCoordonnee = typeCoordonnee;
		this.refEtablissement = refEtablissement;
		this.refIndividu = refIndividu;
		this.refStructure = refStructure;
		this.listeRouge = listeRouge;
		this.principal = principal;
		this.refTelephone = refTelephone;
		this.refAdresseElectronique = refAdresseElectronique;
		this.refAdresse = refAdresse;
		this.refLieu = refLieu;
	}

	@Id
	@SequenceGenerator(name = "seq_cordonnee", initialValue = 1)
	@GeneratedValue(strategy = GenerationType.IDENTITY, generator = "seq_cordonnee")
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "etablissement")
	public RefEtablissement getRefEtablissement() {
		return this.refEtablissement;
	}

	public void setRefEtablissement(RefEtablissement refEtablissement) {
		this.refEtablissement = refEtablissement;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "individu")
	public RefIndividu getRefIndividu() {
		return this.refIndividu;
	}

	public void setRefIndividu(RefIndividu refIndividu) {
		this.refIndividu = refIndividu;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "structure")
	public RefStructure getRefStructure() {
		return this.refStructure;
	}

	public void setRefStructure(RefStructure refStructure) {
		this.refStructure = refStructure;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "lieu")
	public RefLieu getRefLieu() {
		return this.refLieu;
	}

	public void setRefLieu(RefLieu refLieu) {
		this.refLieu = refLieu;
	}

	@Column(name = "liste_rouge")
	public Boolean getListeRouge() {
		return this.listeRouge;
	}

	public void setListeRouge(Boolean listeRouge) {
		this.listeRouge = listeRouge;
	}

	@Column(name = "principal")
	public Boolean getPrincipal() {
		return this.principal;
	}

	public void setPrincipal(Boolean principal) {
		this.principal = principal;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "refCoordonnee")
	public RefTelephone getRefTelephone() {
		return this.refTelephone;
	}

	public void setRefTelephone(RefTelephone refTelephone) {
		this.refTelephone = refTelephone;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "refCoordonnee")
	public RefAdresseElectronique getRefAdresseElectronique() {
		return this.refAdresseElectronique;
	}

	public void setRefAdresseElectronique(
			RefAdresseElectronique refAdresseElectronique) {
		this.refAdresseElectronique = refAdresseElectronique;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "refCoordonnee")
	public RefAdresse getRefAdresse() {
		return this.refAdresse;
	}

	public void setRefAdresse(RefAdresse refAdresse) {
		this.refAdresse = refAdresse;
	}

	@Column(name = "type_coordonnee", unique = false, nullable = false)
	public int getTypeCoordonnee() {
		return typeCoordonnee;
	}

	public void setTypeCoordonnee(int typeCoordonnee) {
		this.typeCoordonnee = typeCoordonnee;
	}

}
