package dz.gov.mesrs.sii.commons.data.model.referentiel;

// Generated 21 janv. 2014 17:45:57 by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * RefDomaine generated by obelbrik
 */
@Entity
@Table(name = "ref_domaine_lmd", schema = "ppm")
public class RefDomaineLMD implements java.io.Serializable {

	/**
	 * serialVersionUID 
	 * @author obelbrik  on : 06 02. 2014  17:20:38
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private String identifiant;
	private String lcDomaine;
	private String lcDomaineArabe;
	private String llDomaine;
	private String llDomaineArabe;
	private String description;
	private String descriptionArabe;
	private Nomenclature niveauRecrutement;
	private Boolean isPremiereInscription;
	




	public RefDomaineLMD() {
	}

	public RefDomaineLMD(String identifiant, String lcDomaine) {
	
		this.identifiant = identifiant;
		this.lcDomaine = lcDomaine;
	}

	public RefDomaineLMD( String identifiant, String lcDomaine, String lcDomaineArabe,
			String llDomaine, String llDomaineArabe,String description,String descriptionArabe, Nomenclature niveauRecrutement, Boolean isPremiereInscription) {
	
		this.identifiant = identifiant;
		this.lcDomaine = lcDomaine;
		this.lcDomaineArabe = lcDomaineArabe;
		this.llDomaine = llDomaine;
		this.llDomaineArabe = llDomaineArabe;
		this.description= description;
		this.descriptionArabe = descriptionArabe;
		this.niveauRecrutement = niveauRecrutement;
		this.isPremiereInscription = isPremiereInscription;
	
		

	}
	@Id
	@SequenceGenerator(name = "seq_domaine_lmd", initialValue = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq_domaine_lmd")
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}
	
	@Column(name = "identifiant", unique = true, nullable = false, length = 50)
	public String getIdentifiant() {
		return this.identifiant;
	}

	public void setIdentifiant(String identifiant) {
		this.identifiant = identifiant;
	}

	@Column(name = "lc_domaine", nullable = false, length = 100)
	public String getLcDomaine() {
		return this.lcDomaine;
	}

	public void setLcDomaine(String lcDomaine) {
		this.lcDomaine = lcDomaine;
	}

	@Column(name = "lc_domaine_arabe", nullable = false, length = 100)
	public String getLcDomaineArabe() {
		return this.lcDomaineArabe;
	}

	public void setLcDomaineArabe(String lcDomaineArabe) {
		this.lcDomaineArabe = lcDomaineArabe;
	}

	@Column(name = "ll_domaine", nullable = false, length = 200)
	public String getLlDomaine() {
		return this.llDomaine;
	}

	public void setLlDomaine(String llDomaine) {
		this.llDomaine = llDomaine;
	}

	@Column(name = "ll_domaine_arabe", nullable = false, length = 200)
	public String getLlDomaineArabe() {
		return this.llDomaineArabe;
	}

	public void setLlDomaineArabe(String llDomaineArabe) {
		this.llDomaineArabe = llDomaineArabe;
	}
	
	@Column(name = "description", length = 500)
	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
	
	@Column(name = "description_arabe", length = 500)
	public String getDescriptionArabe() {
		return descriptionArabe;
	}

	
	public void setDescriptionArabe(String descriptionArabe) {
		this.descriptionArabe = descriptionArabe;
	}

	/**
	 * [dz.gov.mesrs.sii.referentiel.business.model.bo.RefDomaineLMD.hashCode] Method 
	 * @author rlaib  on : 7 sept. 2014  17:07:14
	 * @return
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((identifiant == null) ? 0 : identifiant.hashCode());
		result = prime * result
				+ ((llDomaine == null) ? 0 : llDomaine.hashCode());
		return result;
	}

	/**
	 * [dz.gov.mesrs.sii.referentiel.business.model.bo.RefDomaineLMD.equals] Method 
	 * @author rlaib  on : 7 sept. 2014  17:07:14
	 * @param obj
	 * @return
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		RefDomaineLMD other = (RefDomaineLMD) obj;
		if (identifiant == null) {
			if (other.identifiant != null)
				return false;
		} else if (!identifiant.equals(other.identifiant))
			return false;
		if (llDomaine == null) {
			if (other.llDomaine != null)
				return false;
		} else if (!llDomaine.equals(other.llDomaine))
			return false;
		return true;
	}
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "niveau_recrutement")
	public Nomenclature getNiveauRecrutement() {
		return this.niveauRecrutement;
	}

	public void setNiveauRecrutement(
			Nomenclature niveauRecrutement) {
		this.niveauRecrutement = niveauRecrutement;
	}
	
	@Column(name = "premiere_inscription ")
	public Boolean getIsPremiereInscription() {
		return this.isPremiereInscription;
	}

	public void setIsPremiereInscription(Boolean isPremiereInscription) {
		this.isPremiereInscription = isPremiereInscription;
	}


}
