package dz.gov.mesrs.sii.commons.data.model.referentiel;

// Generated 10 avr. 2014 10:28:25 by Hibernate Tools 3.6.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RefEtablissement generated by hbm2java
 */
@Entity
@Table(name = "ref_etablissement", schema = "ppm")
public class RefEtablissement implements java.io.Serializable {

	/**
	 * serialVersionUID
	 * 
	 * @author MAKERRI Sofiane on : 10 avr. 2014 12:09:41
	 */
	private static final long serialVersionUID = 1L;
	private Nomenclature nomenclatureByNcFormeJuridiqueId;
	private Nomenclature nomenclatureByNcStatutEtabId;
	private Nomenclature ncTypeEtablissement;
	private Nomenclature ncWilaya;
	private int id;
	private String identifiant;
	private Date dateCreation;
	private String lcEtablissementArabe;
	private String lcEtablissementLatin;
	private String llEtablissementArabe;
	private String llEtablissementLatin;
	private String nif;
	private String nis;
	private String nrc;
	private String nss;
	private String decret;
	private String ancienCode;
	private Set<RefLieu> refLieus = new HashSet<RefLieu>(0);
	private Set<RefContrat> refContrats = new HashSet<RefContrat>(0);
	private Set<RefEquipement> refEquipements = new HashSet<RefEquipement>(0);
	private Set<RefPlageAdresse> refPlageAdresses = new HashSet<RefPlageAdresse>(
			0);
	private Set<RefEvenement> refEvenements = new HashSet<RefEvenement>(0);
	private Set<RefStructure> refStructures = new HashSet<RefStructure>(0);
	private Set<RefCoordonnee> refCoordonnees = new HashSet<RefCoordonnee>(0);
	private Set<RefDocument> refDocuments = new HashSet<RefDocument>(0);
	private Set<RefGroupe> refGroupes = new HashSet<RefGroupe>(0);
//	private Set<RefHistorique> refHistoriques = new HashSet<RefHistorique>(0);

	public RefEtablissement() {
	}

	public RefEtablissement(String identifiant, Date dateCreation,
			String lcEtablissementArabe, String lcEtablissementLatin,
			String llEtablissementArabe, String llEtablissementLatin) {
		this.identifiant = identifiant;
		this.dateCreation = dateCreation;
		this.lcEtablissementArabe = lcEtablissementArabe;
		this.lcEtablissementLatin = lcEtablissementLatin;
		this.llEtablissementArabe = llEtablissementArabe;
		this.llEtablissementLatin = llEtablissementLatin;
	}

	public RefEtablissement(Nomenclature nomenclatureByNcFormeJuridiqueId,
			Nomenclature nomenclatureByNcStatutEtabId, String identifiant,
			Nomenclature ncTypeEtablissement, Date dateCreation,
			Nomenclature ncWilaya,
			String lcEtablissementArabe, String lcEtablissementLatin,
			String llEtablissementArabe, String llEtablissementLatin,
			String nif, String nis, String nrc, String nss,
			Set<RefLieu> refLieus, Set<RefContrat> refContrats,
			Set<RefEquipement> refEquipements,
			Set<RefPlageAdresse> refPlageAdresses,
			Set<RefEvenement> refEvenements,
			Set<RefStructure> refStructures, Set<RefCoordonnee> refCoordonnees,
			Set<RefDocument> refDocuments, Set<RefGroupe> refGroupes) {
		this.nomenclatureByNcFormeJuridiqueId = nomenclatureByNcFormeJuridiqueId;
		this.nomenclatureByNcStatutEtabId = nomenclatureByNcStatutEtabId;
		this.ncTypeEtablissement = ncTypeEtablissement;
		this.ncWilaya = ncWilaya;
		this.identifiant = identifiant;
		this.dateCreation = dateCreation;
		this.lcEtablissementArabe = lcEtablissementArabe;
		this.lcEtablissementLatin = lcEtablissementLatin;
		this.llEtablissementArabe = llEtablissementArabe;
		this.llEtablissementLatin = llEtablissementLatin;
		this.nif = nif;
		this.nis = nis;
		this.nrc = nrc;
		this.nss = nss;
		this.refLieus = refLieus;
		this.refContrats = refContrats;
		this.refEquipements = refEquipements;
		this.refPlageAdresses = refPlageAdresses;
		this.refEvenements = refEvenements;
		this.refStructures = refStructures;
		this.refCoordonnees = refCoordonnees;
		this.refDocuments = refDocuments;
		this.refGroupes = refGroupes;
	}
	
	@Id
	@SequenceGenerator(name = "seq_etab", initialValue = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq_etab")
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "nc_forme_juridique_id")
	public Nomenclature getNomenclatureByNcFormeJuridiqueId() {
		return this.nomenclatureByNcFormeJuridiqueId;
	}

	public void setNomenclatureByNcFormeJuridiqueId(
			Nomenclature nomenclatureByNcFormeJuridiqueId) {
		this.nomenclatureByNcFormeJuridiqueId = nomenclatureByNcFormeJuridiqueId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "type_etablissement")
	public Nomenclature getNcTypeEtablissement() {
		return this.ncTypeEtablissement;
	}

	public void setNcTypeEtablissement(Nomenclature ncTypeEtablissement) {
		this.ncTypeEtablissement = ncTypeEtablissement;
	}
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "wilaya")
	public Nomenclature getNcWilaya() {
		return this.ncWilaya;
	}

	public void setNcWilaya(Nomenclature ncWilaya) {
		this.ncWilaya = ncWilaya;
	}
	

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "nc_statut_etab_id")
	public Nomenclature getNomenclatureByNcStatutEtabId() {
		return this.nomenclatureByNcStatutEtabId;
	}

	public void setNomenclatureByNcStatutEtabId(
			Nomenclature nomenclatureByNcStatutEtabId) {
		this.nomenclatureByNcStatutEtabId = nomenclatureByNcStatutEtabId;
	}

	@Column(name = "identifiant", unique = true, nullable = false, length = 6)
	public String getIdentifiant() {
		return this.identifiant;
	}

	public void setIdentifiant(String identifiant) {
		this.identifiant = identifiant;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_creation", nullable = false, length = 13)
	public Date getDateCreation() {
		return this.dateCreation;
	}

	public void setDateCreation(Date dateCreation) {
		this.dateCreation = dateCreation;
	}

	@Column(name = "lc_etablissement_arabe", nullable = false, length = 250)
	public String getLcEtablissementArabe() {
		return this.lcEtablissementArabe;
	}

	public void setLcEtablissementArabe(String lcEtablissementArabe) {
		this.lcEtablissementArabe = lcEtablissementArabe;
	}

	@Column(name = "lc_etablissement_latin", nullable = false, length = 250)
	public String getLcEtablissementLatin() {
		return this.lcEtablissementLatin;
	}

	public void setLcEtablissementLatin(String lcEtablissementLatin) {
		this.lcEtablissementLatin = lcEtablissementLatin;
	}

	@Column(name = "ll_etablissement_arabe", nullable = false, length = 250)
	public String getLlEtablissementArabe() {
		return this.llEtablissementArabe;
	}

	public void setLlEtablissementArabe(String llEtablissementArabe) {
		this.llEtablissementArabe = llEtablissementArabe;
	}

	@Column(name = "ll_etablissement_latin", nullable = false, length = 250)
	public String getLlEtablissementLatin() {
		return this.llEtablissementLatin;
	}

	public void setLlEtablissementLatin(String llEtablissementLatin) {
		this.llEtablissementLatin = llEtablissementLatin;
	}

	@Column(name = "nif", length = 250)
	public String getNif() {
		return this.nif;
	}

	public void setNif(String nif) {
		this.nif = nif;
	}

	@Column(name = "nis", length = 250)
	public String getNis() {
		return this.nis;
	}

	public void setNis(String nis) {
		this.nis = nis;
	}

	@Column(name = "nrc", length = 250)
	public String getNrc() {
		return this.nrc;
	}

	public void setNrc(String nrc) {
		this.nrc = nrc;
	}

	@Column(name = "nss", length = 250)
	public String getNss() {
		return this.nss;
	}

	public void setNss(String nss) {
		this.nss = nss;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refEtablissement")
	public Set<RefLieu> getRefLieus() {
		return this.refLieus;
	}

	public void setRefLieus(Set<RefLieu> refLieus) {
		this.refLieus = refLieus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refEtablissement")
	public Set<RefContrat> getRefContrats() {
		return this.refContrats;
	}

	public void setRefContrats(Set<RefContrat> refContrats) {
		this.refContrats = refContrats;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refEtablissement")
	public Set<RefEquipement> getRefEquipements() {
		return this.refEquipements;
	}

	public void setRefEquipements(Set<RefEquipement> refEquipements) {
		this.refEquipements = refEquipements;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refEtablissement")
	public Set<RefPlageAdresse> getRefPlageAdresses() {
		return this.refPlageAdresses;
	}

	public void setRefPlageAdresses(Set<RefPlageAdresse> refPlageAdresses) {
		this.refPlageAdresses = refPlageAdresses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refEtablissement")
	public Set<RefEvenement> getRefEvenements() {
		return this.refEvenements;
	}

	public void setRefEvenements(Set<RefEvenement> refEvenements) {
		this.refEvenements = refEvenements;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refEtablissement")
	public Set<RefStructure> getRefStructures() {
		return this.refStructures;
	}

	public void setRefStructures(Set<RefStructure> refStructures) {
		this.refStructures = refStructures;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refEtablissement")
	public Set<RefCoordonnee> getRefCoordonnees() {
		return this.refCoordonnees;
	}

	public void setRefCoordonnees(Set<RefCoordonnee> refCoordonnees) {
		this.refCoordonnees = refCoordonnees;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refEtablissement")
	public Set<RefDocument> getRefDocuments() {
		return this.refDocuments;
	}

	public void setRefDocuments(Set<RefDocument> refDocuments) {
		this.refDocuments = refDocuments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refEtablissement")
	public Set<RefGroupe> getRefGroupes() {
		return this.refGroupes;
	}

	public void setRefGroupes(Set<RefGroupe> refGroupes) {
		this.refGroupes = refGroupes;
	}

	@Column(name = "decret", length = 250)
	public String getDecret() {
		return this.decret;
	}

	public void setDecret(String decret) {
		this.decret = decret;
	}
	
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refEtablissement")
//	public Set<RefHistorique> getRefHistoriques() {
//		return refHistoriques;
//	}
//
//	public void setRefHistoriques(Set<RefHistorique> refHistoriques) {
//		this.refHistoriques = refHistoriques;
//	}
	

	/**
	 * [RefEtablissement.ancienCode] Getter 
	 * @author BELDI Jamel on : 22 juin 2014  09:35:07
	 * @return the ancienCode
	 */
	@Column(name = "ancien_code", nullable = true, length = 6)
	public String getAncienCode() {
		return ancienCode;
	}

	/**
	 * [RefEtablissement.ancienCode] Setter 
	 * @author BELDI Jamel on : 22 juin 2014  09:35:07
	 * @param ancienCode the ancienCode to set
	 */
	public void setAncienCode(String ancienCode) {
		this.ancienCode = ancienCode;
	}

}
