package dz.gov.mesrs.sii.commons.data.model.referentiel;

// Generated 21 janv. 2014 17:45:57 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RefEntiteSituation generated by hbm2java
 */
@Entity
@Table(name = "ref_entite_situation", schema = "ppm")
public class RefEntiteSituation implements java.io.Serializable {

	/**
	 * serialVersionUID 
	 * @author BELDI Jamel  on : 23 janv. 2014  11:20:32
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private Nomenclature nomenclature;
	private String nomEntite;
	private Set<RefSituation> refSituations = new HashSet<RefSituation>(0);

	public RefEntiteSituation() {
	}

	public RefEntiteSituation(int id, Nomenclature nomenclature,
			String nomEntite) {
		this.id = id;
		this.nomenclature = nomenclature;
		this.nomEntite = nomEntite;
	}

	public RefEntiteSituation(int id, Nomenclature nomenclature,
			String nomEntite, Set<RefSituation> refSituations) {
		this.id = id;
		this.nomenclature = nomenclature;
		this.nomEntite = nomEntite;
		this.refSituations = refSituations;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "nctypesituationid", nullable = false)
	public Nomenclature getNomenclature() {
		return this.nomenclature;
	}

	public void setNomenclature(Nomenclature nomenclature) {
		this.nomenclature = nomenclature;
	}

	@Column(name = "nom_entite", nullable = false, length = 50)
	public String getNomEntite() {
		return this.nomEntite;
	}

	public void setNomEntite(String nomEntite) {
		this.nomEntite = nomEntite;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refEntiteSituation")
	public Set<RefSituation> getRefSituations() {
		return this.refSituations;
	}

	public void setRefSituations(Set<RefSituation> refSituations) {
		this.refSituations = refSituations;
	}

}
