package dz.gov.mesrs.sii.commons.data.model.referentiel;

// Generated 12 f�vr. 2014 15:08:55 by Hibernate Tools 3.6.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RefEvenement generated by hbm2java
 */
@Entity
@Table(name = "ref_evenement", schema = "ppm")
public class RefEvenement implements java.io.Serializable {

	/**
	 * serialVersionUID 
	 * @author MAKERRI Sofiane  on : 10 avr. 2014  11:20:09
	 */
	private static final long serialVersionUID = 1L;
	private String identifiant;
	private int id;
	private RefEtablissement refEtablissement;
	private Nomenclature nomenclatureByFrequenceRepetition;
	private Nomenclature nomenclatureByType;
	private String objet;
	private String description;
	private Date dateDebut;
	private Date dateFin;
	private Date heure;
	private Integer nbreJours;
	private String observation;

	public RefEvenement() {
	}

	public RefEvenement(int id, Nomenclature nomenclatureByType, String objet,
			Date dateDebut) {
		this.id = id;
		this.nomenclatureByType = nomenclatureByType;
		this.objet = objet;
		this.dateDebut = dateDebut;
	}

	public RefEvenement(int id, Nomenclature nomenclatureByFrequenceRepetition,
			RefEtablissement refEtablissement, Nomenclature nomenclatureByType,
			String objet, String description, Date dateDebut, Date dateFin,
			Date heure, Integer nbreJours, String observation) {
		this.id = id;
		this.refEtablissement = refEtablissement;
		this.nomenclatureByFrequenceRepetition = nomenclatureByFrequenceRepetition;
		this.nomenclatureByType = nomenclatureByType;
		this.objet = objet;
		this.description = description;
		this.dateDebut = dateDebut;
		this.dateFin = dateFin;
		this.heure = heure;
		this.nbreJours = nbreJours;
		this.observation = observation;
	}

	@Id
	@SequenceGenerator(name = "seq_evenement", initialValue = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq_evenement")
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}
	
	@Column(name = "identifiant", unique = true, nullable = false, length = 10)
	public String getIdentifiant() {
		return this.identifiant;
	}

	public void setIdentifiant(String identifiant) {
		this.identifiant = identifiant;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "etablissement")
	public RefEtablissement getRefEtablissement() {
		return this.refEtablissement;
	}

	public void setRefEtablissement(RefEtablissement refEtablissement) {
		this.refEtablissement = refEtablissement;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "frequence_repetition")
	public Nomenclature getNomenclatureByFrequenceRepetition() {
		return this.nomenclatureByFrequenceRepetition;
	}

	public void setNomenclatureByFrequenceRepetition(
			Nomenclature nomenclatureByFrequenceRepetition) {
		this.nomenclatureByFrequenceRepetition = nomenclatureByFrequenceRepetition;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "type", nullable = false)
	public Nomenclature getNomenclatureByType() {
		return this.nomenclatureByType;
	}

	public void setNomenclatureByType(Nomenclature nomenclatureByType) {
		this.nomenclatureByType = nomenclatureByType;
	}

	@Column(name = "objet", nullable = false, length = 250)
	public String getObjet() {
		return this.objet;
	}

	public void setObjet(String objet) {
		this.objet = objet;
	}

	@Column(name = "description", length = 400)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_debut", nullable = false, length = 13)
	public Date getDateDebut() {
		return this.dateDebut;
	}

	public void setDateDebut(Date dateDebut) {
		this.dateDebut = dateDebut;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_fin", length = 13)
	public Date getDateFin() {
		return this.dateFin;
	}

	public void setDateFin(Date dateFin) {
		this.dateFin = dateFin;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "heure", length = 15)
	public Date getHeure() {
		return this.heure;
	}

	public void setHeure(Date heure) {
		this.heure = heure;
	}

	@Column(name = "nbre_jours")
	public Integer getNbreJours() {
		return this.nbreJours;
	}

	public void setNbreJours(Integer nbreJours) {
		this.nbreJours = nbreJours;
	}

	@Column(name = "observation", length = 400)
	public String getObservation() {
		return this.observation;
	}

	public void setObservation(String observation) {
		this.observation = observation;
	}

}
