package dz.gov.mesrs.sii.commons.data.model.referentiel;

// Generated 6 mars 2014 15:22:23 by Hibernate Tools 3.6.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * RefEquipement generated by hbm2java
 */
@Entity
@Table(name = "ref_equipement", schema = "ppm", uniqueConstraints = @UniqueConstraint(columnNames = "code"))
public class RefEquipement implements java.io.Serializable {

	/**
	 * serialVersionUID
	 * 
	 * @author BELBRIK Oualid on : 6 mars 2014 15:47:04
	 */
	private static final long serialVersionUID = 1L;
	private String identifiant;
	private int id;
	private RefEtablissement refEtablissement;
	private Nomenclature nomenclatureBySousfamilleEquipement;
	private Nomenclature nomenclatureByFamilleEquipement;
	private String code;
	private String designation;
	private String referenceexterne;
	private Date dateMiseDispo;
	private Boolean reservable;
	private Set<RefOccupationLieu> refOccupations = new HashSet<RefOccupationLieu>(
			0);

	public RefEquipement() {
	}

	public RefEquipement(String identifiant,
			Nomenclature nomenclatureBySousfamilleEquipement,
			Nomenclature nomenclatureByFamilleEquipement, String code,
			Set<RefOccupationLieu> refOccupations, String designation,
			Date dateMiseDispo) {
		this.identifiant = identifiant;
		this.nomenclatureBySousfamilleEquipement = nomenclatureBySousfamilleEquipement;
		this.nomenclatureByFamilleEquipement = nomenclatureByFamilleEquipement;
		this.code = code;
		this.designation = designation;
		this.dateMiseDispo = dateMiseDispo;
	}

	public RefEquipement(String identifiant, RefEtablissement refEtablissement,
			Nomenclature nomenclatureBySousfamilleEquipement,
			Nomenclature nomenclatureByFamilleEquipement, String code,
			String designation, String referenceexterne, Date dateMiseDispo,
			Boolean reservable, Set<RefOccupationLieu> refOccupations) {
		this.identifiant = identifiant;
		this.refEtablissement = refEtablissement;
		this.nomenclatureBySousfamilleEquipement = nomenclatureBySousfamilleEquipement;
		this.nomenclatureByFamilleEquipement = nomenclatureByFamilleEquipement;
		this.code = code;
		this.designation = designation;
		this.referenceexterne = referenceexterne;
		this.dateMiseDispo = dateMiseDispo;
		this.reservable = reservable;
		this.refOccupations = refOccupations;
	}
	
	@Id
	@SequenceGenerator(name = "seq_equipement", initialValue = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq_equipement")
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "identifiant", unique = true, nullable = false, length = 10)
	public String getIdentifiant() {
		return this.identifiant;
	}

	public void setIdentifiant(String identifiant) {
		this.identifiant = identifiant;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "etablissement")
	public RefEtablissement getRefEtablissement() {
		return this.refEtablissement;
	}

	public void setRefEtablissement(RefEtablissement refEtablissement) {
		this.refEtablissement = refEtablissement;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sousfamille_equipement", nullable = false)
	public Nomenclature getNomenclatureBySousfamilleEquipement() {
		return this.nomenclatureBySousfamilleEquipement;
	}

	public void setNomenclatureBySousfamilleEquipement(
			Nomenclature nomenclatureBySousfamilleEquipement) {
		this.nomenclatureBySousfamilleEquipement = nomenclatureBySousfamilleEquipement;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "famille_equipement", nullable = false)
	public Nomenclature getNomenclatureByFamilleEquipement() {
		return this.nomenclatureByFamilleEquipement;
	}

	public void setNomenclatureByFamilleEquipement(
			Nomenclature nomenclatureByFamilleEquipement) {
		this.nomenclatureByFamilleEquipement = nomenclatureByFamilleEquipement;
	}

	@Column(name = "code", unique = true, nullable = false, length = 100)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "designation", nullable = false, length = 200)
	public String getDesignation() {
		return this.designation;
	}

	public void setDesignation(String designation) {
		this.designation = designation;
	}

	@Column(name = "referenceexterne", length = 100)
	public String getReferenceexterne() {
		return this.referenceexterne;
	}

	public void setReferenceexterne(String referenceexterne) {
		this.referenceexterne = referenceexterne;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_mise_dispo", nullable = false, length = 29)
	public Date getDateMiseDispo() {
		return this.dateMiseDispo;
	}

	public void setDateMiseDispo(Date dateMiseDispo) {
		this.dateMiseDispo = dateMiseDispo;
	}

	@Column(name = "reservable")
	public Boolean getReservable() {
		return this.reservable;
	}

	public void setReservable(Boolean reservable) {
		this.reservable = reservable;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refEquipement")
	public Set<RefOccupationLieu> getRefOccupations() {
		return this.refOccupations;
	}

	public void setRefOccupations(Set<RefOccupationLieu> refOccupations) {
		this.refOccupations = refOccupations;
	}

}
