package dz.gov.mesrs.sii.commons.data.model.referentiel;

// Generated 17 f�vr. 2014 18:36:28 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * RefFonction generated by hbm2java
 */
@Entity
@Table(name = "ref_fonction", schema = "ppm")
public class RefFonction implements java.io.Serializable {

	/**
	 * serialVersionUID
	 * 
	 * @author MAKERRI Sofiane on : 4 mai 2014 08:58:13
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private RefModule refModule;
	private RefFonction refFonction;
	private String identifiant;
	private String nom;
	private String nomArabe;
	private String url;
	private int rang;
	private boolean action;
	private RefPeriode refPeriode;
	private Set<RefPermission> refPermissions = new HashSet<RefPermission>(0);
	private Set<RefFonction> refFonctions = new HashSet<RefFonction>(0);
	private String helpAnchor;

	// private Set<RefHistorique> refHistoriques = new
	// HashSet<RefHistorique>(0);

	public RefFonction() {
	}

	public RefFonction(int id, String identifiant, String nom, int rang, String url) {
		this.id = id;
		this.identifiant = identifiant;
		this.nom = nom;
		this.rang = rang;
		this.url = url;
	}

	public RefFonction(int id, RefModule refModule, String identifiant, String nom, int rang, String url,
			boolean action, Set<RefPermission> refPermissions) {
		this.id = id;
		this.refModule = refModule;
		this.identifiant = identifiant;
		this.nom = nom;
		this.rang = rang;
		this.action = action;
		this.refPermissions = refPermissions;
		this.url = url;
	}

	@Id
	@SequenceGenerator(name = "seq_fonction", initialValue = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq_fonction")
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "module")
	public RefModule getRefModule() {
		return this.refModule;
	}

	public void setRefModule(RefModule refModule) {
		this.refModule = refModule;
	}

	@Column(name = "identifiant", nullable = false, length = 25)
	public String getIdentifiant() {
		return this.identifiant;
	}

	public void setIdentifiant(String identifiant) {
		this.identifiant = identifiant;
	}

	@Column(name = "nom", nullable = false, length = 120)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "rang", nullable = false)
	public int getRang() {
		return this.rang;
	}

	public void setRang(int rang) {
		this.rang = rang;
	}

	@Column(name = "url", nullable = false)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "action")
	public boolean isAction() {
		return action;
	}

	public void setAction(boolean action) {
		this.action = action;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refFonction")
	public Set<RefPermission> getRefPermissions() {
		return this.refPermissions;
	}

	public void setRefPermissions(Set<RefPermission> refPermissions) {
		this.refPermissions = refPermissions;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fonction")
	public RefFonction getRefFonction() {
		return this.refFonction;
	}

	public void setRefFonction(RefFonction refFonction) {
		this.refFonction = refFonction;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refFonction")
	public Set<RefFonction> getRefFonctions() {
		return this.refFonctions;
	}

	public void setRefFonctions(Set<RefFonction> refFonctions) {
		this.refFonctions = refFonctions;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "periode")
	public RefPeriode getRefPeriode() {
		return refPeriode;
	}

	public void setRefPeriode(RefPeriode refPeriode) {
		this.refPeriode = refPeriode;
	}

	@Column(name = "nom_arabe", nullable = false, length = 120)
	public String getNomArabe() {
		return nomArabe;
	}

	public void setNomArabe(String nomArabe) {
		this.nomArabe = nomArabe;
	}

	@Column(name = "help_anchor", nullable = true)
	public String getHelpAnchor() {
		return helpAnchor;
	}

	public void setHelpAnchor(String helpAnchor) {
		this.helpAnchor = helpAnchor;
	}

	// @OneToMany(fetch = FetchType.LAZY, mappedBy = "refFonction")
	// public Set<RefHistorique> getRefHistoriques() {
	// return refHistoriques;
	// }
	//
	// public void setRefHistoriques(Set<RefHistorique> refHistoriques) {
	// this.refHistoriques = refHistoriques;
	// }

}
