package dz.gov.mesrs.sii.commons.data.model.referentiel;

// Generated 21 avr. 2014 10:16:28 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;



/**
 * RefFiliereLmd generated by hbm2java
 */
@Entity
@Table(name = "ref_filiere_lmd", schema = "ppm")
public class RefFiliereLmd implements java.io.Serializable {

	/**
	 * serialVersionUID 
	 * @author BELBRIK Oualid  on : 22 avr. 2014  12:18:25
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private String identifiant;
	private RefDomaineLMD refDomaineLMD;
	private String lcFiliereArabe;
	private String lcFiliere;
	private String llFiliereArabe;
	private String llFiliere;
	private String descriptionFiliereArabe;
	private String descriptionFiliere;
	private Nomenclature niveauRecrutement;
	private Boolean isPremiereInscription;
	private Set<RefSpecialiteLmd> refSpecialiteLmds = new HashSet<RefSpecialiteLmd>(
			0);
	
	private String ancienCodeFiliere;
	private String ancienCodeFiliereCorrespondance;

	public RefFiliereLmd() {
	}

	public RefFiliereLmd(String identifiant) {
		this.identifiant = identifiant;
	}

	public RefFiliereLmd(String identifiant, String lcFiliereArabe, String lcFiliere, String llFiliereArabe,
			String llFiliere, String descriptionFiliereArabe,Nomenclature niveauRecrutement, Boolean isPremiereInscription,
			String descriptionFiliere, Set<RefSpecialiteLmd> refSpecialiteLmds) {
		this.identifiant = identifiant;
		this.lcFiliereArabe = lcFiliereArabe;
		this.lcFiliere = lcFiliere;
		this.llFiliereArabe = llFiliereArabe;
		this.llFiliere = llFiliere;
		this.descriptionFiliereArabe = descriptionFiliereArabe;
		this.descriptionFiliere = descriptionFiliere;
		this.refSpecialiteLmds = refSpecialiteLmds;
		this.niveauRecrutement = niveauRecrutement;
		this.isPremiereInscription = isPremiereInscription;
	}
	
	@Id
	@SequenceGenerator(name = "seq_filiere_lmd", initialValue = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq_filiere_lmd")
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "identifiant", unique = true, nullable = false, length = 50)
	public String getIdentifiant() {
		return this.identifiant;
	}

	public void setIdentifiant(String identifiant) {
		this.identifiant = identifiant;
	}

	

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "domainelmd")
	public RefDomaineLMD getRefDomaineLMD() {
		return refDomaineLMD;
	}

	public void setRefDomaineLMD(RefDomaineLMD refDomaineLMD) {
		this.refDomaineLMD = refDomaineLMD;
	}


	
	@Column(name = "lc_filiere_arabe", length = 100)
	public String getLcFiliereArabe() {
		return this.lcFiliereArabe;
	}

	public void setLcFiliereArabe(String lcFiliereArabe) {
		this.lcFiliereArabe = lcFiliereArabe;
	}

	@Column(name = "lc_filiere", length = 100)
	public String getLcFiliere() {
		return this.lcFiliere;
	}

	public void setLcFiliere(String lcFiliere) {
		this.lcFiliere = lcFiliere;
	}

	@Column(name = "ll_filiere_arabe", length = 100)
	public String getLlFiliereArabe() {
		return this.llFiliereArabe;
	}

	public void setLlFiliereArabe(String llFiliereArabe) {
		this.llFiliereArabe = llFiliereArabe;
	}

	@Column(name = "ll_filiere", length = 100)
	public String getLlFiliere() {
		return this.llFiliere;
	}

	public void setLlFiliere(String llFiliere) {
		this.llFiliere = llFiliere;
	}

	@Column(name = "description_filiere_arabe", length = 500)
	public String getDescriptionFiliereArabe() {
		return this.descriptionFiliereArabe;
	}

	public void setDescriptionFiliereArabe(String descriptionFiliereArabe) {
		this.descriptionFiliereArabe = descriptionFiliereArabe;
	}

	@Column(name = "description_filiere", length = 500)
	public String getDescriptionFiliere() {
		return this.descriptionFiliere;
	}

	public void setDescriptionFiliere(String descriptionFiliere) {
		this.descriptionFiliere = descriptionFiliere;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refFiliereLmd")
	public Set<RefSpecialiteLmd> getRefSpecialiteLmds() {
		return this.refSpecialiteLmds;
	}

	public void setRefSpecialiteLmds(Set<RefSpecialiteLmd> refSpecialiteLmds) {
		this.refSpecialiteLmds = refSpecialiteLmds;
	}
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "niveau_recrutement")
	public Nomenclature getNiveauRecrutement() {
		return this.niveauRecrutement;
	}

	public void setNiveauRecrutement(
			Nomenclature niveauRecrutement) {
		this.niveauRecrutement = niveauRecrutement;
	}
	
	@Column(name = "premiere_inscription ")
	public Boolean getIsPremiereInscription() {
		return this.isPremiereInscription;
	}

	public void setIsPremiereInscription(Boolean isPremiereInscription) {
		this.isPremiereInscription = isPremiereInscription;
	}

	/**
	 * [RefFiliereLmd.ancienCodeFiliere] Getter 
	 * @author rlaib on : 9 nov. 2014  10:20:49
	 * @return the ancienCodeFiliere
	 */
	@Column(name = "ancien_code_filiere ")
	public String getAncienCodeFiliere() {
		return ancienCodeFiliere;
	}

	/**
	 * [RefFiliereLmd.ancienCodeFiliere] Setter 
	 * @author rlaib on : 9 nov. 2014  10:20:49
	 * @param ancienCodeFiliere the ancienCodeFiliere to set
	 */
	public void setAncienCodeFiliere(String ancienCodeFiliere) {
		this.ancienCodeFiliere = ancienCodeFiliere;
	}

	/**
	 * [RefFiliereLmd.ancienCodeFiliereCorrespondance] Getter 
	 * @author rlaib on : 9 nov. 2014  10:20:49
	 * @return the ancienCodeFiliereCorrespondance
	 */
	@Column(name = "ancien_code_filiere_corres ")
	public String getAncienCodeFiliereCorrespondance() {
		return ancienCodeFiliereCorrespondance;
	}

	/**
	 * [RefFiliereLmd.ancienCodeFiliereCorrespondance] Setter 
	 * @author rlaib on : 9 nov. 2014  10:20:49
	 * @param ancienCodeFiliereCorrespondance the ancienCodeFiliereCorrespondance to set
	 */
	public void setAncienCodeFiliereCorrespondance(
			String ancienCodeFiliereCorrespondance) {
		this.ancienCodeFiliereCorrespondance = ancienCodeFiliereCorrespondance;
	}


	
}
