package dz.gov.mesrs.sii.commons.data.model.referentiel;

// Generated 19 mars 2014 11:15:09 by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * RefFileConfig generated by hbm2java
 */
@Entity
@Table(name = "ref_file_config", schema = "ppm")
public class RefFileConfig implements java.io.Serializable {

	private int id;
	private RefEntity refEntity;
	private Nomenclature nomenclature;
	private RefConfiguration refConfiguration;
	private String name;
	private String url;
	private String type;
	private String defaultFile;

	public RefFileConfig() {
	}

	public RefFileConfig(int id, String name, String url, String type) {
		this.id = id;
		this.name = name;
		this.url = url;
		this.type = type;
	}

	public RefFileConfig(int id, RefEntity refEntity,
			Nomenclature nomenclature, RefConfiguration refConfiguration,
			String name, String url, String type, String defaultFile) {
		this.id = id;
		this.refEntity = refEntity;
		this.nomenclature = nomenclature;
		this.refConfiguration = refConfiguration;
		this.name = name;
		this.url = url;
		this.type = type;
		this.defaultFile = defaultFile;
	}

	@Id
	@SequenceGenerator(name="seq_file_config", initialValue = 1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator = "seq_file_config")
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "entity")
	public RefEntity getRefEntity() {
		return this.refEntity;
	}

	public void setRefEntity(RefEntity refEntity) {
		this.refEntity = refEntity;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "language")
	public Nomenclature getNomenclature() {
		return this.nomenclature;
	}

	public void setNomenclature(Nomenclature nomenclature) {
		this.nomenclature = nomenclature;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "configuration")
	public RefConfiguration getRefConfiguration() {
		return this.refConfiguration;
	}

	public void setRefConfiguration(RefConfiguration refConfiguration) {
		this.refConfiguration = refConfiguration;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "url", nullable = false)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "type", nullable = false)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "default_file")
	public String getDefaultFile() {
		return this.defaultFile;
	}

	public void setDefaultFile(String defaultFile) {
		this.defaultFile = defaultFile;
	}

}
