package dz.gov.mesrs.sii.commons.data.model.referentiel;

//Generated 17 f�vr. 2014 18:36:28 by Hibernate Tools 3.6.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RefHoraireAccess generated by hbm2java
 */
@Entity
@Table(name = "ref_horaire_access", schema = "ppm")
public class RefHoraireAccess implements java.io.Serializable {

	/**
	 * serialVersionUID 
	 * @author BELBRIK Oualid  on : 26 f�vr. 2014  10:01:42
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private String identifiant;
	private String nom;
	private Date heureDebut;
	private Date heureFin;
	private Set<RefCompte> refComptes = new HashSet<RefCompte>(0);

	public RefHoraireAccess() {
	}

	public RefHoraireAccess(int id, String identifiant, Date heureDebut,
			Date heureFin) {
		this.id = id;
		this.identifiant = identifiant;
		this.heureDebut = heureDebut;
		this.heureFin = heureFin;
	}

	public RefHoraireAccess(int id, String identifiant, String nom,
			Date heureDebut, Date heureFin, Set<RefCompte> refComptes) {
		this.id = id;
		this.identifiant = identifiant;
		this.nom = nom;
		this.heureDebut = heureDebut;
		this.heureFin = heureFin;
		this.refComptes = refComptes;
	}

	@Id
	@SequenceGenerator(name="seq_horaire", initialValue = 1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator = "seq_horaire")
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "identifiant", nullable = false)
	public String getIdentifiant() {
		return this.identifiant;
	}

	public void setIdentifiant(String identifiant) {
		this.identifiant = identifiant;
	}

	@Column(name = "nom", length = 25)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "heure_debut", nullable = false, length = 15)
	public Date getHeureDebut() {
		return this.heureDebut;
	}

	public void setHeureDebut(Date heureDebut) {
		this.heureDebut = heureDebut;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "heure_fin", nullable = false, length = 15)
	public Date getHeureFin() {
		return this.heureFin;
	}

	public void setHeureFin(Date heureFin) {
		this.heureFin = heureFin;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refHoraireAccess")
	public Set<RefCompte> getRefComptes() {
		return this.refComptes;
	}

	public void setRefComptes(Set<RefCompte> refComptes) {
		this.refComptes = refComptes;
	}

}