package dz.gov.mesrs.sii.commons.data.model.referentiel;

// Generated 21 janv. 2014 17:45:57 by Hibernate Tools 3.6.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RefIndividu generated by hbm2java
 */
@Entity
@Table(name = "ref_individu", schema = "ppm")
public class RefIndividu implements java.io.Serializable {

	/**
	 * serialVersionUID
	 * 
	 * @author BELBRIK Oualid on : 22 janv. 2014 18:25:18
	 */
	private static final long serialVersionUID = 1L;
	
	//FIXME must be long
	private int id;
	private String identifiant;
	private Nomenclature nomenclatureBySituationServiceNational;
	private Nomenclature nomenclatureByGroupeSanguin;
	private Nomenclature nomenclatureBySituationFamiliale;
	private Nomenclature nomenclatureByCivilite;
	private Nomenclature nomenclatureByNationalite;
	private Nomenclature nomenclatureByTypeIndividu;
	private Date dateNaissance;
	private String nomArabe;
	private String nomJeuneFilleArabe;
	private String nomJeuneFilleLatin;
	private String nomLatin;
	private String nomMereArabe;
	private String nomMereLatin;
	private String prenomArabe;
	private String prenomLatin;
	private String prenomMereArabe;
	private String prenomMereLatin;
	private String prenomPereArabe;
	private String prenomPereLatin;
	private Boolean presume;
	private String qualite;
	private String lieuNaissance;
	private Set<RefAffectation> refAffectations = new HashSet<RefAffectation>(0);
	private Set<RefPartenaire> refPartenaires = new HashSet<RefPartenaire>(0);
	private Set<RefOccupationLieu> refOccupations = new HashSet<RefOccupationLieu>(
			0);
	private Set<RefCoordonnee> refCoordonnees = new HashSet<RefCoordonnee>(0);

	public RefIndividu() {
	}
	public RefIndividu(String identifiant, String nomArabe, String nomLatin,
			String prenomArabe, String prenomLatin) {
		this.identifiant = identifiant;
		this.nomArabe = nomArabe;
		this.nomLatin = nomLatin;
		this.prenomArabe = prenomArabe;
		this.prenomLatin = prenomLatin;
	}

	public RefIndividu(String identifiant,
			Nomenclature nomenclatureBySituationServiceNational,
			Nomenclature nomenclatureByGroupeSanguin,
			Nomenclature nomenclatureBySituationFamiliale,
			Nomenclature nomenclatureByCivilite,
			Nomenclature nomenclatureByNationalite,
			Nomenclature nomenclatureByTypeIndividu, Date dateNaissance,
			String nomArabe, String nomJeuneFilleArabe,
			String nomJeuneFilleLatin, String nomLatin, String nomMereArabe,
			String nomMereLatin, String prenomArabe, String prenomLatin,
			String prenomMereArabe, String prenomMereLatin,
			String prenomPereArabe, String prenomPereLatin, Boolean presume,
			Short typeIndividu, Set<RefPartenaire> refPartenaires,
			Set<RefOccupationLieu> refOccupations,
			Set<RefCoordonnee> refCoordonnees,
			Set<RefAffectation> refAffectations) {

		this.identifiant = identifiant;
		this.nomenclatureBySituationServiceNational = nomenclatureBySituationServiceNational;
		this.nomenclatureByGroupeSanguin = nomenclatureByGroupeSanguin;
		this.nomenclatureBySituationFamiliale = nomenclatureBySituationFamiliale;
		this.nomenclatureByCivilite = nomenclatureByCivilite;
		this.nomenclatureByNationalite = nomenclatureByNationalite;
		this.dateNaissance = dateNaissance;
		this.nomArabe = nomArabe;
		this.nomJeuneFilleArabe = nomJeuneFilleArabe;
		this.nomJeuneFilleLatin = nomJeuneFilleLatin;
		this.nomLatin = nomLatin;
		this.nomMereArabe = nomMereArabe;
		this.nomMereLatin = nomMereLatin;
		this.prenomArabe = prenomArabe;
		this.prenomLatin = prenomLatin;
		this.prenomMereArabe = prenomMereArabe;
		this.prenomMereLatin = prenomMereLatin;
		this.prenomPereArabe = prenomPereArabe;
		this.prenomPereLatin = prenomPereLatin;
		this.presume = presume;
		this.nomenclatureByTypeIndividu = nomenclatureByTypeIndividu;
		this.refAffectations = refAffectations;
		this.refPartenaires = refPartenaires;
		this.refOccupations = refOccupations;
		this.refCoordonnees = refCoordonnees;
	}
	
	@Id
	@SequenceGenerator(name = "seq_individu", initialValue = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq_individu")
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}
	public void setId(int id) {
		this.id = id;
	}


	@Column(name = "identifiant", nullable = false, length = 18)
	public String getIdentifiant() {
		return this.identifiant;
	}

	public void setIdentifiant(String identifiant) {
		this.identifiant = identifiant;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "situation_service_national")
	public Nomenclature getNomenclatureBySituationServiceNational() {
		return this.nomenclatureBySituationServiceNational;
	}

	public void setNomenclatureBySituationServiceNational(
			Nomenclature nomenclatureBySituationServiceNational) {
		this.nomenclatureBySituationServiceNational = nomenclatureBySituationServiceNational;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "groupe_sanguin")
	public Nomenclature getNomenclatureByGroupeSanguin() {
		return this.nomenclatureByGroupeSanguin;
	}

	public void setNomenclatureByGroupeSanguin(
			Nomenclature nomenclatureByGroupeSanguin) {
		this.nomenclatureByGroupeSanguin = nomenclatureByGroupeSanguin;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "situation_familiale")
	public Nomenclature getNomenclatureBySituationFamiliale() {
		return this.nomenclatureBySituationFamiliale;
	}

	public void setNomenclatureBySituationFamiliale(
			Nomenclature nomenclatureBySituationFamiliale) {
		this.nomenclatureBySituationFamiliale = nomenclatureBySituationFamiliale;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "civilite")
	public Nomenclature getNomenclatureByCivilite() {
		return this.nomenclatureByCivilite;
	}

	public void setNomenclatureByCivilite(Nomenclature nomenclatureByCivilite) {
		this.nomenclatureByCivilite = nomenclatureByCivilite;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "nationalite")
	public Nomenclature getNomenclatureByNationalite() {
		return this.nomenclatureByNationalite;
	}

	public void setNomenclatureByNationalite(
			Nomenclature nomenclatureByNationalite) {
		this.nomenclatureByNationalite = nomenclatureByNationalite;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "type_individu")
	public Nomenclature getNomenclatureByTypeIndividu() {
		return this.nomenclatureByTypeIndividu;
	}

	public void setNomenclatureByTypeIndividu(
			Nomenclature nomenclatureByTypeIndividu) {
		this.nomenclatureByTypeIndividu = nomenclatureByTypeIndividu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_naissance", length = 13)
	public Date getDateNaissance() {
		return this.dateNaissance;
	}

	public void setDateNaissance(Date dateNaissance) {
		this.dateNaissance = dateNaissance;
	}

	@Column(name = "nom_arabe", nullable = false, length = 50)
	public String getNomArabe() {
		return this.nomArabe;
	}

	public void setNomArabe(String nomArabe) {
		this.nomArabe = nomArabe;
	}

	@Column(name = "nom_jeune_fille_arabe", length = 50)
	public String getNomJeuneFilleArabe() {
		return this.nomJeuneFilleArabe;
	}

	public void setNomJeuneFilleArabe(String nomJeuneFilleArabe) {
		this.nomJeuneFilleArabe = nomJeuneFilleArabe;
	}

	@Column(name = "nom_jeune_fille_latin", length = 50)
	public String getNomJeuneFilleLatin() {
		return this.nomJeuneFilleLatin;
	}

	public void setNomJeuneFilleLatin(String nomJeuneFilleLatin) {
		this.nomJeuneFilleLatin = nomJeuneFilleLatin;
	}

	@Column(name = "nom_latin", nullable = false, length = 50)
	public String getNomLatin() {
		return this.nomLatin;
	}

	public void setNomLatin(String nomLatin) {
		this.nomLatin = nomLatin;
	}

	@Column(name = "nom_mere_arabe", length = 50)
	public String getNomMereArabe() {
		return this.nomMereArabe;
	}

	public void setNomMereArabe(String nomMereArabe) {
		this.nomMereArabe = nomMereArabe;
	}

	@Column(name = "nom_mere_latin", length = 50)
	public String getNomMereLatin() {
		return this.nomMereLatin;
	}

	public void setNomMereLatin(String nomMereLatin) {
		this.nomMereLatin = nomMereLatin;
	}

	@Column(name = "prenom_arabe", nullable = false, length = 50)
	public String getPrenomArabe() {
		return this.prenomArabe;
	}

	public void setPrenomArabe(String prenomArabe) {
		this.prenomArabe = prenomArabe;
	}

	@Column(name = "prenom_latin", nullable = false, length = 50)
	public String getPrenomLatin() {
		return this.prenomLatin;
	}

	public void setPrenomLatin(String prenomLatin) {
		this.prenomLatin = prenomLatin;
	}

	@Column(name = "prenom_mere_arabe", length = 50)
	public String getPrenomMereArabe() {
		return this.prenomMereArabe;
	}

	public void setPrenomMereArabe(String prenomMereArabe) {
		this.prenomMereArabe = prenomMereArabe;
	}

	@Column(name = "prenom_mere_latin", length = 50)
	public String getPrenomMereLatin() {
		return this.prenomMereLatin;
	}

	public void setPrenomMereLatin(String prenomMereLatin) {
		this.prenomMereLatin = prenomMereLatin;
	}

	@Column(name = "prenom_pere_arabe", length = 50)
	public String getPrenomPereArabe() {
		return this.prenomPereArabe;
	}

	public void setPrenomPereArabe(String prenomPereArabe) {
		this.prenomPereArabe = prenomPereArabe;
	}

	@Column(name = "prenom_pere_latin", length = 50)
	public String getPrenomPereLatin() {
		return this.prenomPereLatin;
	}

	public void setPrenomPereLatin(String prenomPereLatin) {
		this.prenomPereLatin = prenomPereLatin;
	}

	@Column(name = "presume")
	public Boolean getPresume() {
		return this.presume;
	}

	public void setPresume(Boolean presume) {
		this.presume = presume;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refIndividu")
	public Set<RefAffectation> getRefAffectations() {
		return this.refAffectations;
	}

	public void setRefAffectations(Set<RefAffectation> refAffectations) {
		this.refAffectations = refAffectations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refIndividu")
	public Set<RefPartenaire> getRefPartenaires() {
		return this.refPartenaires;
	}

	public void setRefPartenaires(Set<RefPartenaire> refPartenaires) {
		this.refPartenaires = refPartenaires;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refIndividu")
	public Set<RefOccupationLieu> getRefOccupations() {
		return this.refOccupations;
	}

	public void setRefOccupations(Set<RefOccupationLieu> refOccupations) {
		this.refOccupations = refOccupations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refIndividu")
	public Set<RefCoordonnee> getRefCoordonnees() {
		return this.refCoordonnees;
	}

	public void setRefCoordonnees(Set<RefCoordonnee> refCoordonnees) {
		this.refCoordonnees = refCoordonnees;
	}

	@Column(name = "qualite", length = 200)
	public String getQualite() {
		return qualite;
	}

	public void setQualite(String qualite) {
		this.qualite = qualite;
	}

	/**
	 * [RefIndividu.lieuNaissance] Getter 
	 * @author BELDI Jamel on : 22 juin 2014  15:34:14
	 * @return the lieuNaissance
	 */
	@Column(name = "lieu_naissance")
	public String getLieuNaissance() {
		return lieuNaissance;
	}

	/**
	 * [RefIndividu.lieuNaissance] Setter 
	 * @author BELDI Jamel on : 22 juin 2014  15:34:14
	 * @param lieuNaissance the lieuNaissance to set
	 */
	public void setLieuNaissance(String lieuNaissance) {
		this.lieuNaissance = lieuNaissance;
	}

	
}
