package dz.gov.mesrs.sii.commons.data.model.referentiel;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * RefLieu generated by obelbrik
 */
@Entity
@Table(name = "ref_lieu", schema = "ppm")
public class RefLieu implements java.io.Serializable {

	/**
	 * serialVersionUID
	 * 
	 * @author obelbrik on : 06 02. 2014 17:20:38
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private String identifiant;
	private String designation;
	private String designationArabe;
	private String description;
	private String descriptionArabe;
	private Boolean acceshandicape;
	private Boolean reservable;
	private String codePorte;
	private Short superficie;
	private Short capacite;
	private Short etage;
	private String adresse;
	private String adresseAr;
	private Integer telephone;

	private Nomenclature nomenclatureByTypeLieu;
	private Nomenclature nomenclatureByTypeImplantation;
	private Nomenclature nomenclatureByTypeacces;
	private Nomenclature nomenclatureByTypesalle;

	private Nomenclature nomenclatureByDaira;
	private Nomenclature nomenclatureByCommune;
	private Nomenclature nomenclatureByWilaya;

	private Set<RefCoordonnee> refCoordonnees = new HashSet<RefCoordonnee>(0);
	private RefLieu refLieu;
	private RefStructure refStructure;
	private Set<RefAffectation> refAffectations = new HashSet<RefAffectation>(0);
	private Set<RefLieu> refLieux = new HashSet<RefLieu>(0);
	private Set<RefOccupationLieu> refOccupations = new HashSet<RefOccupationLieu>(
			0);
	private RefEtablissement refEtablissement;

	public RefLieu() {
	}

	public RefLieu(String identifiant, String designation) {
		this.identifiant = identifiant;
		this.designation = designation;
	}

	public RefLieu(String identifiant, String designation,
			String designationArabe, String description,
			String descriptionArabe, String codePorte, Short superficie,
			Boolean acceshandicape, Boolean reservable, Short capacite,
			String etage, String adresse, String adresseAr,
			Set<RefOccupationLieu> refOccupations, Integer telephone,
			RefEtablissement refEtablissement) {
		this.identifiant = identifiant;
		this.designation = designation;
		this.designationArabe = designationArabe;
		this.description = description;
		this.descriptionArabe = descriptionArabe;
		this.acceshandicape = acceshandicape;
		this.reservable = reservable;
		this.codePorte = codePorte;
		this.superficie = superficie;
		this.capacite = capacite;
		this.adresse = adresse;
		this.adresseAr = adresseAr;
		this.telephone = telephone;
		this.refOccupations = refOccupations;
		this.refEtablissement = refEtablissement;

	}

	@Id
	@SequenceGenerator(name = "seq_lieu", initialValue = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq_lieu")
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}
	
	@Column(name = "identifiant", unique = true, nullable = false, length = 50)
	public String getIdentifiant() {
		return this.identifiant;
	}

	public void setIdentifiant(String identifiant) {
		this.identifiant = identifiant;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "etablissement")
	public RefEtablissement getRefEtablissement() {
		return this.refEtablissement;
	}

	public void setRefEtablissement(RefEtablissement refEtablissement) {
		this.refEtablissement = refEtablissement;
	}

	@Column(name = "description_arabe", length = 500)
	public String getDescriptionArabe() {
		return descriptionArabe;
	}

	public void setDescriptionArabe(String descriptionArabe) {
		this.descriptionArabe = descriptionArabe;
	}

	@Column(name = "description_Fr", nullable = false, length = 500)
	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * [RefLieu.designation] Getter
	 * 
	 * @author BELBRIK Oualid on : 10 f�vr. 2014 17:56:53
	 * @return the designation
	 */
	@Column(name = "designation_Fr", nullable = false, length = 100)
	public String getDesignation() {
		return designation;
	}

	/**
	 * [RefLieu.designation] Setter
	 * 
	 * @author BELBRIK Oualid on : 10 f�vr. 2014 17:56:53
	 * @param designation
	 *            the designation to set
	 */
	public void setDesignation(String designation) {
		this.designation = designation;
	}

	/**
	 * [RefLieu.designationArabe] Getter
	 * 
	 * @author BELBRIK Oualid on : 10 f�vr. 2014 17:56:53
	 * @return the designationArabe
	 */
	@Column(name = "designation_Arabe", length = 100)
	public String getDesignationArabe() {
		return designationArabe;
	}

	/**
	 * [RefLieu.designationArabe] Setter
	 * 
	 * @author BELBRIK Oualid on : 10 f�vr. 2014 17:56:53
	 * @param designationArabe
	 *            the designationArabe to set
	 */
	public void setDesignationArabe(String designationArabe) {
		this.designationArabe = designationArabe;
	}

	/**
	 * [RefLieu.acceshandicape] Getter
	 * 
	 * @author BELBRIK Oualid on : 10 f�vr. 2014 17:56:53
	 * @return the acceshandicape
	 */
	@Column(name = "acces_handicape")
	public Boolean getAcceshandicape() {
		return acceshandicape;
	}

	/**
	 * [RefLieu.acceshandicape] Setter
	 * 
	 * @author BELBRIK Oualid on : 10 f�vr. 2014 17:56:53
	 * @param acceshandicape
	 *            the acceshandicape to set
	 */
	public void setAcceshandicape(Boolean acceshandicape) {
		this.acceshandicape = acceshandicape;
	}

	/**
	 * [RefLieu.reservable] Getter
	 * 
	 * @author BELBRIK Oualid on : 10 f�vr. 2014 17:56:53
	 * @return the reservable
	 */
	@Column(name = "lieu_reservable")
	public Boolean getReservable() {
		return reservable;
	}

	/**
	 * [RefLieu.reservable] Setter
	 * 
	 * @author BELBRIK Oualid on : 10 f�vr. 2014 17:56:53
	 * @param reservable
	 *            the reservable to set
	 */
	public void setReservable(Boolean reservable) {
		this.reservable = reservable;
	}

	/**
	 * [RefLieu.codePorte] Getter
	 * 
	 * @author BELBRIK Oualid on : 10 f�vr. 2014 17:56:53
	 * @return the codePorte
	 */
	@Column(name = "code_porte", length = 20)
	public String getCodePorte() {
		return codePorte;
	}

	/**
	 * [RefLieu.codePorte] Setter
	 * 
	 * @author BELBRIK Oualid on : 10 f�vr. 2014 17:56:53
	 * @param codePorte
	 *            the codePorte to set
	 */
	public void setCodePorte(String codePorte) {
		this.codePorte = codePorte;
	}

	/**
	 * [RefLieu.superficie] Getter
	 * 
	 * @author BELBRIK Oualid on : 10 f�vr. 2014 17:56:53
	 * @return the superficie
	 */
	@Column(name = "lieu_supperficie", length = 10)
	public Short getSuperficie() {
		return superficie;
	}

	/**
	 * [RefLieu.superficie] Setter
	 * 
	 * @author BELBRIK Oualid on : 10 f�vr. 2014 17:56:53
	 * @param superficie
	 *            the superficie to set
	 */
	public void setSuperficie(Short superficie) {
		this.superficie = superficie;
	}

	/**
	 * [RefLieu.capacite] Getter
	 * 
	 * @author BELBRIK Oualid on : 10 f�vr. 2014 17:56:53
	 * @return the capacite
	 */
	@Column(name = "lieu_capacite", length = 10)
	public Short getCapacite() {
		return capacite;
	}

	/**
	 * [RefLieu.capacite] Setter
	 * 
	 * @author BELBRIK Oualid on : 10 f�vr. 2014 17:56:53
	 * @param capacite
	 *            the capacite to set
	 */
	public void setCapacite(Short capacite) {
		this.capacite = capacite;
	}

	/**
	 * [RefLieu.etage] Getter
	 * 
	 * @author BELBRIK Oualid on : 10 f�vr. 2014 17:56:54
	 * @return the etage
	 */
	@Column(name = "lieu_etage", length = 2)
	public Short getEtage() {
		return etage;
	}

	/**
	 * [RefLieu.etage] Setter
	 * 
	 * @author BELBRIK Oualid on : 10 f�vr. 2014 17:56:54
	 * @param etage
	 *            the etage to set
	 */
	public void setEtage(Short etage) {
		this.etage = etage;
	}

	/**
	 * [RefLieu.nomenclatureByTypeLieu] Getter
	 * 
	 * @author BELBRIK Oualid on : 10 f�vr. 2014 17:56:54
	 * @return the nomenclatureByTypeLieu
	 */

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "lieu_type")
	public Nomenclature getNomenclatureByTypeLieu() {
		return nomenclatureByTypeLieu;
	}

	/**
	 * [RefLieu.nomenclatureByTypeLieu] Setter
	 * 
	 * @author BELBRIK Oualid on : 10 f�vr. 2014 17:56:54
	 * @param nomenclatureByTypeLieu
	 *            the nomenclatureByTypeLieu to set
	 */
	public void setNomenclatureByTypeLieu(Nomenclature nomenclatureByTypeLieu) {
		this.nomenclatureByTypeLieu = nomenclatureByTypeLieu;
	}

	/**
	 * [RefLieu.nomenclatureByTypeImplantation] Getter
	 * 
	 * @author BELBRIK Oualid on : 10 f�vr. 2014 17:56:54
	 * @return the nomenclatureByTypeImplantation
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "lieu_type_implantation")
	public Nomenclature getNomenclatureByTypeImplantation() {
		return nomenclatureByTypeImplantation;
	}

	/**
	 * [RefLieu.nomenclatureByTypeImplantation] Setter
	 * 
	 * @author BELBRIK Oualid on : 10 f�vr. 2014 17:56:54
	 * @param nomenclatureByTypeImplantation
	 *            the nomenclatureByTypeImplantation to set
	 */
	public void setNomenclatureByTypeImplantation(
			Nomenclature nomenclatureByTypeImplantation) {
		this.nomenclatureByTypeImplantation = nomenclatureByTypeImplantation;
	}

	/**
	 * [RefLieu.nomenclatureByTypeacces] Getter
	 * 
	 * @author BELBRIK Oualid on : 10 f�vr. 2014 17:56:54
	 * @return the nomenclatureByTypeacces
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "lieu_type_acces")
	public Nomenclature getNomenclatureByTypeacces() {
		return nomenclatureByTypeacces;
	}

	/**
	 * [RefLieu.nomenclatureByTypeacces] Setter
	 * 
	 * @author BELBRIK Oualid on : 10 f�vr. 2014 17:56:54
	 * @param nomenclatureByTypeacces
	 *            the nomenclatureByTypeacces to set
	 */
	public void setNomenclatureByTypeacces(Nomenclature nomenclatureByTypeacces) {
		this.nomenclatureByTypeacces = nomenclatureByTypeacces;
	}

	/**
	 * [RefLieu.nomenclatureByTypesalle] Getter
	 * 
	 * @author BELBRIK Oualid on : 10 f�vr. 2014 17:56:54
	 * @return the nomenclatureByTypesalle
	 */

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "lieu_type_salle")
	public Nomenclature getNomenclatureByTypesalle() {
		return nomenclatureByTypesalle;
	}

	/**
	 * [RefLieu.nomenclatureByTypesalle] Setter
	 * 
	 * @author BELBRIK Oualid on : 10 f�vr. 2014 17:56:54
	 * @param nomenclatureByTypesalle
	 *            the nomenclatureByTypesalle to set
	 */
	public void setNomenclatureByTypesalle(Nomenclature nomenclatureByTypesalle) {
		this.nomenclatureByTypesalle = nomenclatureByTypesalle;
	}

	/**
	 * [RefLieu.refCoordonnees] Getter
	 * 
	 * @author BELBRIK Oualid on : 10 f�vr. 2014 17:56:54
	 * @return the refCoordonnees
	 */

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refLieu")
	public Set<RefCoordonnee> getRefCoordonnees() {
		return refCoordonnees;
	}

	/**
	 * [RefLieu.refCoordonnees] Setter
	 * 
	 * @author BELBRIK Oualid on : 10 f�vr. 2014 17:56:54
	 * @param refCoordonnees
	 *            the refCoordonnees to set
	 */
	public void setRefCoordonnees(Set<RefCoordonnee> refCoordonnees) {
		this.refCoordonnees = refCoordonnees;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "lieu_apatenance")
	public RefLieu getRefLieu() {
		return this.refLieu;
	}

	public void setRefLieu(RefLieu refLieu) {
		this.refLieu = refLieu;
	}

	/**
	 * [RefLieu.refAffectations] Getter
	 * 
	 * @author BELBRIK Oualid on : 11 f�vr. 2014 11:36:47
	 * @return the refAffectations
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refLieu")
	public Set<RefAffectation> getRefAffectations() {
		return refAffectations;
	}

	/**
	 * [RefLieu.refAffectations] Setter
	 * 
	 * @author BELBRIK Oualid on : 11 f�vr. 2014 11:36:47
	 * @param refAffectations
	 *            the refAffectations to set
	 */
	public void setRefAffectations(Set<RefAffectation> refAffectations) {
		this.refAffectations = refAffectations;
	}

	/**
	 * [RefLieu.refLieux] Getter
	 * 
	 * @author BELBRIK Oualid on : 11 f�vr. 2014 11:36:47
	 * @return the refLieux
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refLieu")
	public Set<RefLieu> getRefLieux() {
		return refLieux;
	}

	/**
	 * [RefLieu.refLieux] Setter
	 * 
	 * @author BELBRIK Oualid on : 11 f�vr. 2014 11:36:47
	 * @param refLieux
	 *            the refLieux to set
	 */
	public void setRefLieux(Set<RefLieu> refLieux) {
		this.refLieux = refLieux;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "structure")
	public RefStructure getRefStructure() {
		return this.refStructure;
	}

	public void setRefStructure(RefStructure refStructure) {
		this.refStructure = refStructure;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "daira")
	public Nomenclature getNomenclatureByDaira() {
		return this.nomenclatureByDaira;
	}

	public void setNomenclatureByDaira(Nomenclature nomenclatureByDaira) {
		this.nomenclatureByDaira = nomenclatureByDaira;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "commune")
	public Nomenclature getNomenclatureByCommune() {
		return this.nomenclatureByCommune;
	}

	public void setNomenclatureByCommune(Nomenclature nomenclatureByCommune) {
		this.nomenclatureByCommune = nomenclatureByCommune;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "wilaya")
	public Nomenclature getNomenclatureByWilaya() {
		return this.nomenclatureByWilaya;
	}

	public void setNomenclatureByWilaya(Nomenclature nomenclatureByWilaya) {
		this.nomenclatureByWilaya = nomenclatureByWilaya;
	}

	/**
	 * [RefLieu.adresse] Getter
	 * 
	 * @author BELBRIK Oualid on : 17 f�vr. 2014 15:07:28
	 * @return the adresse
	 */
	@Column(name = "adresse")
	public String getAdresse() {
		return adresse;
	}

	/**
	 * [RefLieu.adresse] Setter
	 * 
	 * @author BELBRIK Oualid on : 17 f�vr. 2014 15:07:28
	 * @param adresse
	 *            the adresse to set
	 */
	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	/**
	 * [RefLieu.adresseAr] Getter
	 * 
	 * @author BELBRIK Oualid on : 17 f�vr. 2014 15:07:28
	 * @return the adresseAr
	 */
	@Column(name = "adresse_ar")
	public String getAdresseAr() {
		return adresseAr;
	}

	/**
	 * [RefLieu.adresseAr] Setter
	 * 
	 * @author BELBRIK Oualid on : 17 f�vr. 2014 15:07:28
	 * @param adresseAr
	 *            the adresseAr to set
	 */
	public void setAdresseAr(String adresseAr) {
		this.adresseAr = adresseAr;
	}

	/**
	 * [RefLieu.telephone] Getter
	 * 
	 * @author BELBRIK Oualid on : 17 f�vr. 2014 15:07:28
	 * @return the telephone
	 */
	@Column(name = "telephone")
	public Integer getTelephone() {
		return telephone;
	}

	/**
	 * [RefLieu.telephone] Setter
	 * 
	 * @author BELBRIK Oualid on : 17 f�vr. 2014 15:07:28
	 * @param telephone
	 *            the telephone to set
	 */
	public void setTelephone(Integer telephone) {
		this.telephone = telephone;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refLieu")
	public Set<RefOccupationLieu> getRefOccupations() {
		return this.refOccupations;
	}

	public void setRefOccupations(Set<RefOccupationLieu> refOccupations) {
		this.refOccupations = refOccupations;
	}

}
