package dz.gov.mesrs.sii.commons.data.model.referentiel;

// Generated 19 f�vr. 2014 14:18:43 by Hibernate Tools 3.6.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RefOccupationLieu generated by hbm2java
 */
@Entity
@Table(name = "ref_occupation_lieu", schema = "ppm")
public class RefOccupationLieu implements java.io.Serializable {

	/**
	 * serialVersionUID
	 * 
	 * @author BELBRIK Oualid on : 19 f�vr. 2014 15:03:40
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private RefIndividu refIndividu;
	private RefGroupe refGroupe;
	private Nomenclature nomenclature;
	private RefLieu refLieu;
	private RefEquipement refEquipement;
	private RefStructure refStructure;
	private Date dateDebut;
	private Date dateFin;
	private Boolean provisoire;

	public RefOccupationLieu() {
	}

	public RefOccupationLieu(int id, RefLieu refLieu) {
		this.id = id;
		this.refLieu = refLieu;
	}

	public RefOccupationLieu(int id, RefIndividu refIndividu,
			RefEquipement refEquipement, RefEtablissement refEtablissement,
			RefGroupe refGroupe, Nomenclature nomenclature, RefLieu refLieu,
			RefStructure refStructure, Date dateDebut, Date dateFin,
			Boolean provisoire) {
		this.id = id;
		this.refIndividu = refIndividu;
		this.refGroupe = refGroupe;
		this.nomenclature = nomenclature;
		this.refLieu = refLieu;
		this.refEquipement = refEquipement;
		this.refStructure = refStructure;
		this.dateDebut = dateDebut;
		this.dateFin = dateFin;
		this.provisoire = provisoire;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@SequenceGenerator(name = "seq_occupationLieu", initialValue = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq_occupationLieu")
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "individu")
	public RefIndividu getRefIndividu() {
		return this.refIndividu;
	}

	public void setRefIndividu(RefIndividu refIndividu) {
		this.refIndividu = refIndividu;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "groupe")
	public RefGroupe getRefGroupe() {
		return this.refGroupe;
	}

	public void setRefGroupe(RefGroupe refGroupe) {
		this.refGroupe = refGroupe;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "type_occupation", nullable = false)
	public Nomenclature getNomenclature() {
		return this.nomenclature;
	}

	public void setNomenclature(Nomenclature nomenclature) {
		this.nomenclature = nomenclature;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "lieu", nullable = false)
	public RefLieu getRefLieu() {
		return this.refLieu;
	}

	public void setRefLieu(RefLieu refLieu) {
		this.refLieu = refLieu;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "structure")
	public RefStructure getRefStructure() {
		return this.refStructure;
	}

	public void setRefStructure(RefStructure refStructure) {
		this.refStructure = refStructure;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_debut", length = 29, nullable = false)
	public Date getDateDebut() {
		return this.dateDebut;
	}

	public void setDateDebut(Date dateDebut) {
		this.dateDebut = dateDebut;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_fin", length = 29)
	public Date getDateFin() {
		return this.dateFin;
	}

	public void setDateFin(Date dateFin) {
		this.dateFin = dateFin;
	}

	/**
	 * [RefOccupationLieu.refEquipement] Getter
	 * 
	 * @author BELBRIK Oualid on : 11 mars 2014 17:52:11
	 * @return the refEquipement
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "equipement")
	public RefEquipement getRefEquipement() {
		return this.refEquipement;
	}

	/**
	 * [RefOccupationLieu.refEquipement] Setter
	 * 
	 * @author BELBRIK Oualid on : 11 mars 2014 17:52:11
	 * @param refEquipement
	 *            the refEquipement to set
	 */
	public void setRefEquipement(RefEquipement refEquipement) {
		this.refEquipement = refEquipement;
	}

	@Column(name = "provisoir", columnDefinition = "boolean default true")
	public Boolean getProvisoire() {
		return provisoire;
	}

	public void setProvisoire(Boolean provisoire) {
		this.provisoire = provisoire;
	}

}
