package dz.gov.mesrs.sii.commons.data.model.referentiel;

// Generated 21 janv. 2014 17:45:57 by Hibernate Tools 3.6.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RefPartenaire generated by hbm2java
 */
@Entity
@Table(name = "ref_partenaire", schema = "ppm")
public class RefPartenaire implements java.io.Serializable {

	/**
	 * serialVersionUID
	 * 
	 * @author BELDI Jamel on : 23 janv. 2014 11:21:05
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private Nomenclature nomenclature;
	private RefIndividu refIndividu;
	private RefGroupe refGroupe;
	private RefContrat refContrat;

	private RefStructure refStructure;
	private boolean contractant;
	private Date dateSignature;
	private String observation;
	private String reference;

	public RefPartenaire() {
	}

	public RefPartenaire(int id, RefContrat refContrat, boolean contractant) {
		this.id = id;
		this.refContrat = refContrat;
		this.contractant = contractant;
	}

	public RefPartenaire(int id, Nomenclature nomenclature,
			RefIndividu refIndividu, RefGroupe refGroupe,
			RefContrat refContrat,
			RefStructure refStructure, boolean contractant, Date dateSignature,
			String observation, String reference) {
		this.id = id;
		this.nomenclature = nomenclature;
		this.refIndividu = refIndividu;
		this.refGroupe = refGroupe;
		this.refContrat = refContrat;
		this.refStructure = refStructure;
		this.contractant = contractant;
		this.dateSignature = dateSignature;
		this.observation = observation;
		this.reference = reference;
	}

	@Id
	@SequenceGenerator(name = "seq_partenaire", initialValue = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq_partenaire")
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "role")
	public Nomenclature getNomenclature() {
		return this.nomenclature;
	}

	public void setNomenclature(Nomenclature nomenclature) {
		this.nomenclature = nomenclature;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "individu")
	public RefIndividu getRefIndividu() {
		return this.refIndividu;
	}

	public void setRefIndividu(RefIndividu refIndividu) {
		this.refIndividu = refIndividu;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "groupe")
	public RefGroupe getRefGroupe() {
		return this.refGroupe;
	}

	public void setRefGroupe(RefGroupe refGroupe) {
		this.refGroupe = refGroupe;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "contrat", nullable = false)
	public RefContrat getRefContrat() {
		return this.refContrat;
	}

	public void setRefContrat(RefContrat refContrat) {
		this.refContrat = refContrat;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "structure")
	public RefStructure getRefStructure() {
		return this.refStructure;
	}

	public void setRefStructure(RefStructure refStructure) {
		this.refStructure = refStructure;
	}

	@Column(name = "contractant", nullable = false)
	public boolean isContractant() {
		return this.contractant;
	}

	public void setContractant(boolean contractant) {
		this.contractant = contractant;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_signature", length = 13)
	public Date getDateSignature() {
		return this.dateSignature;
	}

	public void setDateSignature(Date dateSignature) {
		this.dateSignature = dateSignature;
	}

	@Column(name = "observation")
	public String getObservation() {
		return this.observation;
	}

	public void setObservation(String observation) {
		this.observation = observation;
	}

	@Column(name = "reference")
	public String getReference() {
		return this.reference;
	}

	public void setReference(String reference) {
		this.reference = reference;
	}

}
