package dz.gov.mesrs.sii.commons.data.model.referentiel;

// Generated 17 f�vr. 2014 18:36:28 by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * RefPermission generated by hbm2java
 */
@Entity
@Table(name = "ref_permission", schema = "ppm")
public class RefPermission implements java.io.Serializable {

	private int id;
	private RefFonction refFonction;
	private Nomenclature role;
	private boolean creer;
	private boolean modifier;
	private boolean supprimer;
	private boolean consulter;

	public RefPermission() {
	}

	public RefPermission(int id, boolean creer, boolean modifier,
			boolean supprimer) {
		this.id = id;
		this.creer = creer;
		this.modifier = modifier;
		this.supprimer = supprimer;
	}

	public RefPermission(int id, RefFonction refFonction,
			Nomenclature role, boolean creer, boolean modifier,
			boolean supprimer, boolean consulter) {
		this.id = id;
		this.refFonction = refFonction;
		this.role = role;
		this.creer = creer;
		this.modifier = modifier;
		this.supprimer = supprimer;
		this.consulter = consulter;
	}

	@Id
	@SequenceGenerator(name="seq_permission", initialValue = 1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator = "seq_permission")
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fonction")
	public RefFonction getRefFonction() {
		return this.refFonction;
	}

	public void setRefFonction(RefFonction refFonction) {
		this.refFonction = refFonction;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "role")
	public Nomenclature getRole() {
		return this.role;
	}

	public void setRole(Nomenclature role) {
		this.role = role;
	}

	@Column(name = "creer", nullable = false)
	public boolean isCreer() {
		return this.creer;
	}

	public void setCreer(boolean creer) {
		this.creer = creer;
	}

	@Column(name = "modifier", nullable = false)
	public boolean isModifier() {
		return this.modifier;
	}

	public void setModifier(boolean modifier) {
		this.modifier = modifier;
	}

	@Column(name = "supprimer", nullable = false)
	public boolean isSupprimer() {
		return this.supprimer;
	}

	public void setSupprimer(boolean supprimer) {
		this.supprimer = supprimer;
	}

	@Column(name = "consulter")
	public boolean isConsulter() {
		return this.consulter;
	}

	public void setConsulter(boolean consulter) {
		this.consulter = consulter;
	}

}
