package dz.gov.mesrs.sii.commons.data.model.referentiel;

// Generated 17 f�vr. 2014 18:36:28 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * RefPlageAdresse generated by hbm2java
 */
@Entity
@Table(name = "ref_plage_adresse", schema = "ppm")
public class RefPlageAdresse implements java.io.Serializable {

	/**
	 * serialVersionUID
	 * 
	 * @author BELBRIK Oualid on : 26 f�vr. 2014 18:10:30
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private RefEtablissement refEtablissement;
	private String identifiant;
	private String nom;
	private String adresseDebut;
	private String adresseFin;
	private Set<RefCompte> refComptes = new HashSet<RefCompte>(0);

	public RefPlageAdresse() {
	}

	public RefPlageAdresse(int id, String identifiant, String adresseDebut,
			String adresseFin) {
		this.id = id;
		this.identifiant = identifiant;
		this.adresseDebut = adresseDebut;
		this.adresseFin = adresseFin;
	}

	public RefPlageAdresse(int id, String identifiant, String nom,
			RefEtablissement refEtablissement, String adresseDebut,
			String adresseFin, Set<RefCompte> refComptes) {
		this.id = id;
		this.refEtablissement = refEtablissement;
		this.identifiant = identifiant;
		this.nom = nom;
		this.adresseDebut = adresseDebut;
		this.adresseFin = adresseFin;
		this.refComptes = refComptes;
	}

	@Id
	@SequenceGenerator(name = "seq", initialValue = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq")
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "etablissement")
	public RefEtablissement getRefEtablissement() {
		return this.refEtablissement;
	}

	public void setRefEtablissement(RefEtablissement refEtablissement) {
		this.refEtablissement = refEtablissement;
	}

	@Column(name = "identifiant", nullable = false, length = 25)
	public String getIdentifiant() {
		return this.identifiant;
	}

	public void setIdentifiant(String identifiant) {
		this.identifiant = identifiant;
	}

	@Column(name = "nom", length = 25)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "adresse_debut", nullable = false, length = 15)
	public String getAdresseDebut() {
		return this.adresseDebut;
	}

	public void setAdresseDebut(String adresseDebut) {
		this.adresseDebut = adresseDebut;
	}

	@Column(name = "adresse_fin", nullable = false, length = 15)
	public String getAdresseFin() {
		return this.adresseFin;
	}

	public void setAdresseFin(String adresseFin) {
		this.adresseFin = adresseFin;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refPlageAdresse")
	public Set<RefCompte> getRefComptes() {
		return this.refComptes;
	}

	public void setRefComptes(Set<RefCompte> refComptes) {
		this.refComptes = refComptes;
	}

}
