package dz.gov.mesrs.sii.commons.data.model.referentiel;

// Generated 21 janv. 2014 17:45:57 by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RefRelationGroupe generated by hbm2java
 */
@Entity
@Table(name = "ref_relation_groupe", schema = "ppm")
public class RefRelationGroupe implements java.io.Serializable {

	/**
	 * serialVersionUID 
	 * @author BELDI Jamel  on : 23 janv. 2014  11:20:59
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private RefGroupe refGroupeByIdGroupePere;
	private RefGroupe refGroupeByIdGroupeFils;

	public RefRelationGroupe() {
	}

	public RefRelationGroupe(int id) {
		this.id = id;
	}

	public RefRelationGroupe(int id, RefGroupe refGroupeByIdGroupePere,
			RefGroupe refGroupeByIdGroupeFils) {
		this.id = id;
		this.refGroupeByIdGroupePere = refGroupeByIdGroupePere;
		this.refGroupeByIdGroupeFils = refGroupeByIdGroupeFils;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_groupe_pere")
	public RefGroupe getRefGroupeByIdGroupePere() {
		return this.refGroupeByIdGroupePere;
	}

	public void setRefGroupeByIdGroupePere(RefGroupe refGroupeByIdGroupePere) {
		this.refGroupeByIdGroupePere = refGroupeByIdGroupePere;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_groupe_fils")
	public RefGroupe getRefGroupeByIdGroupeFils() {
		return this.refGroupeByIdGroupeFils;
	}

	public void setRefGroupeByIdGroupeFils(RefGroupe refGroupeByIdGroupeFils) {
		this.refGroupeByIdGroupeFils = refGroupeByIdGroupeFils;
	}

}
