package dz.gov.mesrs.sii.commons.data.model.referentiel;

// Generated 17 mars 2014 11:15:54 by Hibernate Tools 3.6.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RefReservation generated by hbm2java
 */
@Entity
@Table(name = "ref_reservation", schema = "ppm")
public class RefReservation implements java.io.Serializable {

	/**
	 * serialVersionUID
	 * 
	 * @author BELBRIK Oualid on : 17 mars 2014 14:24:30
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private RefIndividu refIndividu;
	private RefIndividu refIndividuByResponsable;
	private RefGroupe refGroupe;
	private RefLieu refLieu;
	private RefEquipement refEquipement;
	private RefStructure refStructure;
	private Date dateDebut;
	private Date dateFin;
	private Date heureDebut;
	private Date heureFin;
	private Integer typeRsrv;
	private String objet;
	private String observation;

	public RefReservation() {
	}

	public RefReservation(int id, RefIndividu refIndividu,
			RefIndividu refIndividuByResponsable, RefGroupe refGroupe,
			RefLieu refLieu, RefEquipement refEquipement,
			RefStructure refStructure, Date dateDebut,
			Date dateFin, Date heureDebut,
			Date heureFin, Integer typeRsrv, String objet, String observation) {
		this.id = id;
		this.refIndividu = refIndividu;
		this.refIndividuByResponsable = refIndividuByResponsable;
		this.refGroupe = refGroupe;
		this.refLieu = refLieu;
		this.setRefEquipement(refEquipement);
		this.refStructure = refStructure;
		this.dateDebut = dateDebut;
		this.dateFin = dateFin;
		this.heureDebut = heureDebut;
		this.heureFin = heureFin;
		this.typeRsrv = typeRsrv;
		this.objet = objet;
		this.objet = observation;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@SequenceGenerator(name = "seq_reservation", initialValue = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq_reservation")
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "individu")
	public RefIndividu getrefIndividu() {
		return this.refIndividu;
	}

	public void setrefIndividu(RefIndividu refIndividu) {
		this.refIndividu = refIndividu;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "responsable")
	public RefIndividu getRefIndividuByResponsable() {
		return this.refIndividuByResponsable;
	}

	public void setRefIndividuByResponsable(RefIndividu refIndividuByResponsable) {
		this.refIndividuByResponsable = refIndividuByResponsable;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "groupe")
	public RefGroupe getRefGroupe() {
		return this.refGroupe;
	}

	public void setRefGroupe(RefGroupe refGroupe) {
		this.refGroupe = refGroupe;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "lieu")
	public RefLieu getRefLieu() {
		return this.refLieu;
	}

	public void setRefLieu(RefLieu refLieu) {
		this.refLieu = refLieu;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "structure")
	public RefStructure getRefStructure() {
		return this.refStructure;
	}

	public void setRefStructure(RefStructure refStructure) {
		this.refStructure = refStructure;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_debut", nullable = false, length = 29)
	public Date getDateDebut() {
		return this.dateDebut;
	}

	public void setDateDebut(Date dateDebut) {
		this.dateDebut = dateDebut;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_fin", nullable = false, length = 29)
	public Date getDateFin() {
		return this.dateFin;
	}

	public void setDateFin(Date dateFin) {
		this.dateFin = dateFin;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "heure_debut", nullable = false, length = 15)
	public Date getHeureDebut() {
		return this.heureDebut;
	}

	public void setHeureDebut(Date heureDebut) {
		this.heureDebut = heureDebut;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "heure_fin", nullable = false, length = 15)
	public Date getHeureFin() {
		return this.heureFin;
	}

	public void setHeureFin(Date heureFin) {
		this.heureFin = heureFin;
	}

	@Column(name = "type_rsrv")
	public Integer getTypeRsrv() {
		return this.typeRsrv;
	}

	public void setTypeRsrv(Integer typeRsrv) {
		this.typeRsrv = typeRsrv;
	}

	@Column(name = "objet", nullable = false, length = 250)
	public String getObjet() {
		return this.objet;
	}

	public void setObjet(String objet) {
		this.objet = objet;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "equipement")
	public RefEquipement getRefEquipement() {
		return refEquipement;
	}

	public void setRefEquipement(RefEquipement refEquipement) {
		this.refEquipement = refEquipement;
	}

	@Column(name = "observation", length = 500)
	public String getObservation() {
		return this.observation;
	}

	public void setObservation(String observation) {
		this.observation = observation;
	}

}
