package dz.gov.mesrs.sii.commons.data.model.referentiel;

// Generated 21 janv. 2014 17:45:57 by Hibernate Tools 3.6.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RefStructure generated by hbm2java
 */
@Entity
@Table(name = "ref_structure", schema = "ppm")
public class RefStructure implements java.io.Serializable {

	/**
	 * serialVersionUID
	 * 
	 * @author BELDI Jamel on : 23 janv. 2014 11:21:21
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private String identifiant;
	private RefEtablissement refEtablissement;
	private Nomenclature nomenclatureByNcstatutstructureid;
	private Nomenclature nomenclatureByNcformejuridiqueid;
	private RefStructure refStructure;
	private Date dateCreation;
	private String decret;
	private String lcStructureArabe;
	private String lcStructureLatin;
	private String llStructureArabe;
	private String llStructureLatin;
	private String nif;
	private String nis;
	private String nrc;
	private String nss;
	private Nomenclature nomenclatureByTypeStructure;
	private Set<RefLieu> refLieu = new HashSet<RefLieu>(0);
	private Set<RefPartenaire> refPartenaires = new HashSet<RefPartenaire>(0);
	private Set<RefAffectation> refAffectations = new HashSet<RefAffectation>(0);
	private Set<RefStructure> refStructures = new HashSet<RefStructure>(0);
	private Set<RefCoordonnee> refCoordonnees = new HashSet<RefCoordonnee>(0);
	private Set<RefContrat> refContratsForService = new HashSet<RefContrat>(0);
	private Set<RefOccupationLieu> refOccupations = new HashSet<RefOccupationLieu>(
			0);

	public RefStructure() {
	}

	public RefStructure(String identifiant, Date dateCreation,
			String lcStructureLatin, String llStructureLatin) {
		this.identifiant = identifiant;
		this.dateCreation = dateCreation;
		this.lcStructureLatin = lcStructureLatin;
		this.llStructureLatin = llStructureLatin;
		// this.typeStructure = typeStructure;
	}

	public RefStructure(String identifiant, RefEtablissement refEtablissement,
			Nomenclature nomenclatureByNcstatutstructureid,
			Nomenclature nomenclatureByNcformejuridiqueid,
			Nomenclature nomenclatureByTypeStructure,
			RefStructure refStructure, Date dateCreation, String decret,
			String lcStructureArabe, String lcStructureLatin,
			String llStructureArabe, String llStructureLatin, String nif,
			String nis, String nrc, String nss, String siteWeb,
			Set<RefContrat> refContratsForEtablissement,
			Set<RefPartenaire> refPartenaires,
			Set<RefOccupationLieu> refOccupations,
			Set<RefAffectation> refAffectations,
			Set<RefStructure> refStructures, Set<RefCoordonnee> refCoordonnees,
			Set<RefContrat> refContratsForService, Set<RefLieu> refLieu) {
		this.identifiant = identifiant;
		this.nomenclatureByNcstatutstructureid = nomenclatureByNcstatutstructureid;
		this.nomenclatureByNcformejuridiqueid = nomenclatureByNcformejuridiqueid;
		this.refStructure = refStructure;
		this.dateCreation = dateCreation;
		this.decret = decret;
		this.lcStructureArabe = lcStructureArabe;
		this.lcStructureLatin = lcStructureLatin;
		this.llStructureArabe = llStructureArabe;
		this.llStructureLatin = llStructureLatin;
		this.nif = nif;
		this.nis = nis;
		this.nrc = nrc;
		this.nss = nss;
		this.refEtablissement = refEtablissement;
		this.nomenclatureByTypeStructure = nomenclatureByTypeStructure;
		this.refLieu = refLieu;
		this.refPartenaires = refPartenaires;
		this.refOccupations = refOccupations;
		this.refAffectations = refAffectations;
		this.refStructures = refStructures;
		this.refCoordonnees = refCoordonnees;
		this.refContratsForService = refContratsForService;
	}

	@Id
	@SequenceGenerator(name = "seq_structure", initialValue = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq_structure")
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}
	
	@Column(name = "identifiant", unique = true, nullable = false, length = 12)
	public String getIdentifiant() {
		return this.identifiant;
	}

	public void setIdentifiant(String identifiant) {
		this.identifiant = identifiant;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ncstatutstructureid")
	public Nomenclature getNomenclatureByNcstatutstructureid() {
		return this.nomenclatureByNcstatutstructureid;
	}

	public void setNomenclatureByNcstatutstructureid(
			Nomenclature nomenclatureByNcstatutstructureid) {
		this.nomenclatureByNcstatutstructureid = nomenclatureByNcstatutstructureid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "etablissement")
	public RefEtablissement getRefEtablissement() {
		return this.refEtablissement;
	}

	public void setRefEtablissement(RefEtablissement refEtablissement) {
		this.refEtablissement = refEtablissement;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ncformejuridiqueid")
	public Nomenclature getNomenclatureByNcformejuridiqueid() {
		return this.nomenclatureByNcformejuridiqueid;
	}

	public void setNomenclatureByNcformejuridiqueid(
			Nomenclature nomenclatureByNcformejuridiqueid) {
		this.nomenclatureByNcformejuridiqueid = nomenclatureByNcformejuridiqueid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ratachee_a")
	public RefStructure getRefStructure() {
		return this.refStructure;
	}

	public void setRefStructure(RefStructure refStructure) {
		this.refStructure = refStructure;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_creation", nullable = false, length = 13)
	public Date getDateCreation() {
		return this.dateCreation;
	}

	public void setDateCreation(Date dateCreation) {
		this.dateCreation = dateCreation;
	}

	@Column(name = "decret", length = 250)
	public String getDecret() {
		return this.decret;
	}

	public void setDecret(String decret) {
		this.decret = decret;
	}

	@Column(name = "lc_structure_arabe", length = 100)
	public String getLcStructureArabe() {
		return this.lcStructureArabe;
	}

	public void setLcStructureArabe(String lcStructureArabe) {
		this.lcStructureArabe = lcStructureArabe;
	}

	@Column(name = "lc_structure_latin", nullable = false, length = 100)
	public String getLcStructureLatin() {
		return this.lcStructureLatin;
	}

	public void setLcStructureLatin(String lcStructureLatin) {
		this.lcStructureLatin = lcStructureLatin;
	}

	@Column(name = "ll_structure_arabe", length = 200)
	public String getLlStructureArabe() {
		return this.llStructureArabe;
	}

	public void setLlStructureArabe(String llStructureArabe) {
		this.llStructureArabe = llStructureArabe;
	}

	@Column(name = "ll_structure_latin", nullable = false, length = 200)
	public String getLlStructureLatin() {
		return this.llStructureLatin;
	}

	public void setLlStructureLatin(String llStructureLatin) {
		this.llStructureLatin = llStructureLatin;
	}

	@Column(name = "nif", length = 50)
	public String getNif() {
		return this.nif;
	}

	public void setNif(String nif) {
		this.nif = nif;
	}

	@Column(name = "nis", length = 50)
	public String getNis() {
		return this.nis;
	}

	public void setNis(String nis) {
		this.nis = nis;
	}

	@Column(name = "nrc", length = 50)
	public String getNrc() {
		return this.nrc;
	}

	public void setNrc(String nrc) {
		this.nrc = nrc;
	}

	@Column(name = "nss", length = 50)
	public String getNss() {
		return this.nss;
	}

	public void setNss(String nss) {
		this.nss = nss;
	}


	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refLieu")
	public Set<RefLieu> getRefLieu() {
		return this.refLieu;
	}

	public void setRefLieu(Set<RefLieu> refLieu) {
		this.refLieu = refLieu;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refStructure")
	public Set<RefPartenaire> getRefPartenaires() {
		return this.refPartenaires;
	}

	public void setRefPartenaires(Set<RefPartenaire> refPartenaires) {
		this.refPartenaires = refPartenaires;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refStructure")
	public Set<RefOccupationLieu> getRefOccupations() {
		return this.refOccupations;
	}

	public void setRefOccupations(Set<RefOccupationLieu> refOccupations) {
		this.refOccupations = refOccupations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refStructure")
	public Set<RefAffectation> getRefAffectations() {
		return this.refAffectations;
	}

	public void setRefAffectations(Set<RefAffectation> refAffectations) {
		this.refAffectations = refAffectations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refStructure")
	public Set<RefStructure> getRefStructures() {
		return this.refStructures;
	}

	public void setRefStructures(Set<RefStructure> refStructures) {
		this.refStructures = refStructures;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refStructure")
	public Set<RefCoordonnee> getRefCoordonnees() {
		return this.refCoordonnees;
	}

	public void setRefCoordonnees(Set<RefCoordonnee> refCoordonnees) {
		this.refCoordonnees = refCoordonnees;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "refStructureByService")
	public Set<RefContrat> getRefContratsForService() {
		return this.refContratsForService;
	}

	public void setRefContratsForService(Set<RefContrat> refContratsForService) {
		this.refContratsForService = refContratsForService;
	}

	/**
	 * [RefStructure.nomenclatureByTypeStructure] Getter
	 * 
	 * @author BELDI Jamel on : 29 janv. 2014 11:07:58
	 * @return the nomenclatureByTypeStructure
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "type_structure")
	public Nomenclature getNomenclatureByTypeStructure() {
		return nomenclatureByTypeStructure;
	}

	/**
	 * [RefStructure.nomenclatureByTypeStructure] Setter
	 * 
	 * @author BELDI Jamel on : 29 janv. 2014 11:07:58
	 * @param nomenclatureByTypeStructure
	 *            the nomenclatureByTypeStructure to set
	 */
	public void setNomenclatureByTypeStructure(
			Nomenclature nomenclatureByTypeStructure) {
		this.nomenclatureByTypeStructure = nomenclatureByTypeStructure;
	}

}
