package dz.gov.mesrs.sii.commons.data.model.referentiel;

// Generated 21 janv. 2014 17:45:57 by Hibernate Tools 3.6.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RefSituation generated by hbm2java
 */
@Entity
@Table(name = "ref_situation", schema = "ppm")
public class RefSituation implements java.io.Serializable {

	/**
	 * serialVersionUID 
	 * @author BELDI Jamel  on : 23 janv. 2014  11:21:13
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private RefEntiteSituation refEntiteSituation;
	private Date dateSituation;
	private Integer idEntite;
	private String nomEntite;
	private String observation;

	public RefSituation() {
	}

	public RefSituation(int id) {
		this.id = id;
	}

	public RefSituation(int id, RefEntiteSituation refEntiteSituation,
			Date dateSituation, Integer idEntite, String nomEntite,
			String observation) {
		this.id = id;
		this.refEntiteSituation = refEntiteSituation;
		this.dateSituation = dateSituation;
		this.idEntite = idEntite;
		this.nomEntite = nomEntite;
		this.observation = observation;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "refentitesituationid")
	public RefEntiteSituation getRefEntiteSituation() {
		return this.refEntiteSituation;
	}

	public void setRefEntiteSituation(RefEntiteSituation refEntiteSituation) {
		this.refEntiteSituation = refEntiteSituation;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_situation", length = 29)
	public Date getDateSituation() {
		return this.dateSituation;
	}

	public void setDateSituation(Date dateSituation) {
		this.dateSituation = dateSituation;
	}

	@Column(name = "id_entite", length = 50)
	public Integer getIdEntite() {
		return this.idEntite;
	}

	public void setIdEntite(Integer idEntite) {
		this.idEntite = idEntite;
	}

	@Column(name = "nom_entite", length = 50)
	public String getNomEntite() {
		return this.nomEntite;
	}

	public void setNomEntite(String nomEntite) {
		this.nomEntite = nomEntite;
	}

	@Column(name = "observation")
	public String getObservation() {
		return this.observation;
	}

	public void setObservation(String observation) {
		this.observation = observation;
	}

}
