package dz.gov.mesrs.sii.commons.data.model.referentiel;

// Generated 21 janv. 2014 17:45:57 by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * RefTelephone generated by hbm2java
 */
@Entity
@Table(name = "ref_telephone", schema = "ppm")
public class RefTelephone implements java.io.Serializable {

	/**
	 * serialVersionUID 
	 * @author BELDI Jamel  on : 23 janv. 2014  11:21:26
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private Nomenclature nomenclatureByNatureTelephone;
	private RefCoordonnee refCoordonnee;
	private Nomenclature nomenclatureByTypeTelephone;
	private String numeroTelephone;

	public RefTelephone() {
	}

	public RefTelephone(RefCoordonnee refCoordonnee) {
		this.refCoordonnee = refCoordonnee;
	}

	public RefTelephone(Nomenclature nomenclatureByNatureTelephone,
			RefCoordonnee refCoordonnee,
			Nomenclature nomenclatureByTypeTelephone, String numeroTelephone) {
		this.nomenclatureByNatureTelephone = nomenclatureByNatureTelephone;
		this.refCoordonnee = refCoordonnee;
		this.nomenclatureByTypeTelephone = nomenclatureByTypeTelephone;
		this.numeroTelephone = numeroTelephone;
	}

	//@GenericGenerator(name = "generator_telephone", strategy = "foreign", parameters = @Parameter(name = "property", value = "refCoordonnee"))
	@Id
	//@GeneratedValue(generator = "generator_telephone")
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "nature_telephone")
	public Nomenclature getNomenclatureByNatureTelephone() {
		return this.nomenclatureByNatureTelephone;
	}

	public void setNomenclatureByNatureTelephone(
			Nomenclature nomenclatureByNatureTelephone) {
		this.nomenclatureByNatureTelephone = nomenclatureByNatureTelephone;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public RefCoordonnee getRefCoordonnee() {
		return this.refCoordonnee;
	}

	public void setRefCoordonnee(RefCoordonnee refCoordonnee) {
		this.refCoordonnee = refCoordonnee;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "type_telephone")
	public Nomenclature getNomenclatureByTypeTelephone() {
		return this.nomenclatureByTypeTelephone;
	}

	public void setNomenclatureByTypeTelephone(
			Nomenclature nomenclatureByTypeTelephone) {
		this.nomenclatureByTypeTelephone = nomenclatureByTypeTelephone;
	}

	@Column(name = "numero_telephone", nullable = false, length = 20)
	public String getNumeroTelephone() {
		return this.numeroTelephone;
	}

	public void setNumeroTelephone(String numeroTelephone) {
		this.numeroTelephone = numeroTelephone;
	}

}
