package dz.gov.mesrs.sii.commons.data.model.referentiel;

// Generated 12 f�vr. 2014 15:08:55 by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * RefTache generated by hbm2java
 */
@Entity
@Table(name = "ref_tache", schema = "ppm")
public class RefTache implements java.io.Serializable {

	/**
	 * serialVersionUID
	 * 
	 * @author BELDI Jamel on : 13 f�vr. 2014 10:47:59
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private RefEvenement evenement;
	private Nomenclature nomenclatureByType;
	private String titre;
	private String description;
	private Boolean active;

	public RefTache() {
	}

	public RefTache(int id, RefEvenement evenement, String titre) {
		this.id = id;
		this.evenement = evenement;
		this.titre = titre;
	}

	public RefTache(int id, RefEvenement evenement,
			Nomenclature nomenclatureByType, String titre, String description,
			Boolean active) {
		this.id = id;
		this.evenement = evenement;
		this.nomenclatureByType = nomenclatureByType;
		this.titre = titre;
		this.description = description;
		this.active = active;
	}

	@Id
	@SequenceGenerator(name = "seq_tache", initialValue = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq_tache")
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "evenement", nullable = false)
	public RefEvenement getEvenement() {
		return this.evenement;
	}

	public void setEvenement(RefEvenement evenement) {
		this.evenement = evenement;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "type")
	public Nomenclature getNomenclatureByType() {
		return this.nomenclatureByType;
	}

	public void setNomenclatureByType(Nomenclature nomenclatureByType) {
		this.nomenclatureByType = nomenclatureByType;
	}

	@Column(name = "titre", nullable = false, length = 200)
	public String getTitre() {
		return this.titre;
	}

	public void setTitre(String titre) {
		this.titre = titre;
	}

	@Column(name = "description", length = 400)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "active")
	public Boolean getActive() {
		return this.active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

}
