package dz.gov.mesrs.sii.commons.data.model.referentiel;

// Generated 17 f�vr. 2014 11:25:00 by Hibernate Tools 3.6.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RefVersionDocument generated by hbm2java
 */
@Entity
@Table(name = "ref_version_document", schema = "ppm")
public class RefVersionDocument implements java.io.Serializable {

	/**
	 * serialVersionUID
	 * 
	 * @author MAKERRI Sofiane on : 10 avr. 2014 11:21:18
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private RefIndividu refIndividu;
	private RefDocument refDocument;
	private String numVersion;
	private Date dateVersion;
	private String url;
	private String observation;
	private Integer etab;

	public RefVersionDocument() {
	}

	public RefVersionDocument(int id) {
		this.id = id;
	}

	public RefVersionDocument(int id, RefIndividu refIndividu,
			RefDocument refDocument,
			String numVersion, Date dateVersion, String url,
			String observation, Integer etab) {
		this.id = id;
		this.refIndividu = refIndividu;
		this.refDocument = refDocument;
		this.numVersion = numVersion;
		this.dateVersion = dateVersion;
		this.url = url;
		this.observation = observation;
		this.etab = etab;
	}

	@Id
	@SequenceGenerator(name = "seq_version_document", initialValue = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq_version_document")
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "individu")
	public RefIndividu getRefIndividu() {
		return this.refIndividu;
	}

	public void setRefIndividu(RefIndividu refIndividu) {
		this.refIndividu = refIndividu;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_document")
	public RefDocument getRefDocument() {
		return this.refDocument;
	}

	public void setRefDocument(RefDocument refDocument) {
		this.refDocument = refDocument;
	}

	@Column(name = "num_version", length = 15)
	public String getNumVersion() {
		return this.numVersion;
	}

	public void setNumVersion(String numVersion) {
		this.numVersion = numVersion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_version", length = 29)
	public Date getDateVersion() {
		return this.dateVersion;
	}

	public void setDateVersion(Date dateVersion) {
		this.dateVersion = dateVersion;
	}

	@Column(name = "url", length = 100)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "observation", length = 200)
	public String getObservation() {
		return this.observation;
	}

	public void setObservation(String observation) {
		this.observation = observation;
	}

	@Column(name = "etab")
	public Integer getEtab() {
		return this.etab;
	}

	public void setEtab(Integer etab) {
		this.etab = etab;
	}

}
