package dz.gov.mesrs.sii.commons.data.model.fve.cursus;

// Generated 8 juin 2014 12:21:31 by Hibernate Tools 3.6.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import dz.gov.mesrs.sii.commons.data.model.fve.offreformation.AnneeAcademique;
import dz.gov.mesrs.sii.commons.data.model.fve.offreformation.AtomePedagogique;
import dz.gov.mesrs.sii.commons.data.model.fve.offreformation.MatiereConstitutive;
import dz.gov.mesrs.sii.commons.data.model.fve.offreformation.UniteEnseignement;
/**
 * AbsenceMatiere generated by hbm2java
 */
@Entity
@Table(name = "absence_matiere", schema = "cursus")
public class AbsenceMatiere implements java.io.Serializable {

	/**
	 * serialVersionUID 
	 * @author BELBRIK Oualid  on : 8 juin 2014  13:32:41
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private MatiereConstitutive mc;
	private AtomePedagogique ap;
	private String refCodeTypeAbsence;
	private String refCodeModeEnvoi;
	private Boolean justf;
	private Date dateJustif;
	private Date dateAbsence;
	private String dure;
	private String motif;
	private DossierInscriptionAdministrative dossierInscriptionAdministrative;
	private AnneeAcademique anneeAcademique;

	public AbsenceMatiere() {
	}

	public AbsenceMatiere(int id) {
		this.id = id;
	}

	public AbsenceMatiere(int id, DossierInscriptionAdministrative dossierInscriptionAdministrative,
			Dossier dossier, AnneeAcademique anneeAcademique,MatiereConstitutive mc, AtomePedagogique ap,
			UniteEnseignement ue,String refCodeTypeAbsence, String motif,String refCodeModeEnvoi, Boolean justf, Date dateJustif,
			Date dateAbsence, String dure) {
		this.id = id;
		this.mc = mc;
		this.ap = ap;
		this.dossierInscriptionAdministrative = dossierInscriptionAdministrative;
		this.anneeAcademique = anneeAcademique;
		this.refCodeTypeAbsence = refCodeTypeAbsence;
		this.refCodeModeEnvoi = refCodeModeEnvoi;
		this.justf = justf;
		this.dateJustif = dateJustif;
		this.dateAbsence = dateAbsence;
		this.dure = dure;
		this.motif = motif;
	}
	
	@SequenceGenerator(name = "absencematiere_id_seq_gen", sequenceName = "cursus.absence_matiere_id_seq")
	@Id
	@GeneratedValue(generator = "absencematiere_id_seq_gen")
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_mc")
	public MatiereConstitutive getMc() {
		return this.mc;
	}

	public void setMc(MatiereConstitutive mc) {
		this.mc = mc;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_ap")
	public AtomePedagogique getAp() {
		return this.ap;
	}

	public void setAp(AtomePedagogique ap) {
		this.ap = ap;
	}

			
	@Column(name = "ref_code_type_absence", length = 30)
	public String getRefCodeTypeAbsence() {
		return this.refCodeTypeAbsence;
	}

	public void setRefCodeTypeAbsence(String refCodeTypeAbsence) {
		this.refCodeTypeAbsence = refCodeTypeAbsence;
	}
	
	@Column(name = "motif")
	public String getMotif() {
		return this.motif;
	}

	public void setMotif(String motif) {
		this.motif = motif;
	}


	@Column(name = "ref_code_mode_envoi", length = 30)
	public String getRefCodeModeEnvoi() {
		return this.refCodeModeEnvoi;
	}

	public void setRefCodeModeEnvoi(String refCodeModeEnvoi) {
		this.refCodeModeEnvoi = refCodeModeEnvoi;
	}

	@Column(name = "justf")
	public Boolean getJustf() {
		return this.justf;
	}

	public void setJustf(Boolean justf) {
		this.justf = justf;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_justif", length = 13)
	public Date getDateJustif() {
		return this.dateJustif;
	}

	public void setDateJustif(Date dateJustif) {
		this.dateJustif = dateJustif;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_absence", length = 13)
	public Date getDateAbsence() {
		return this.dateAbsence;
	}

	public void setDateAbsence(Date dateAbsence) {
		this.dateAbsence = dateAbsence;
	}

	@Column(name = "dure")
	public String getDure() {
		return this.dure;
	}

	public void setDure(String dure) {
		this.dure = dure;
	}

		@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_inscription_administrative", nullable = false)
	public DossierInscriptionAdministrative getDossierInscriptionAdministrative() {
		return this.dossierInscriptionAdministrative;
	}

	public void setDossierInscriptionAdministrative(
			DossierInscriptionAdministrative dossierInscriptionAdministrative) {
		this.dossierInscriptionAdministrative = dossierInscriptionAdministrative;
	}
	

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_annee_academique", nullable = false)
	public AnneeAcademique getAnneeAcademique() {
		return this.anneeAcademique;
	}

	public void setAnneeAcademique(AnneeAcademique anneeAcademique) {
		this.anneeAcademique = anneeAcademique;
	}


	
}
