package dz.gov.mesrs.sii.commons.data.model.fve.cursus;

// Generated 15 juil. 2014 16:41:51 by Hibernate Tools 3.6.0

import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import dz.gov.mesrs.sii.commons.data.model.fve.examen.BilanControleContinu;

/**
 * AffectationGroupePedagogique generated by hbm2java
 */
@Entity
@Table(name = "affectation_groupe_pedagogique", schema = "cursus", uniqueConstraints = @UniqueConstraint(columnNames = {
		"groupe_pedagogique", "dossier_inscription"}))
public class AffectationGroupePedagogique implements java.io.Serializable {

	/**
	 * serialVersionUID 
	 * @author MAKERRI Sofiane  on : 22 juil. 2014  13:04:06
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private DossierInscriptionAdministrative dossierInscriptionAdministrative;
	private GroupePedagogique groupePedagogique;
	private Date dateAffectation;
	private List<BilanControleContinu> bilanControleContinus;

	public AffectationGroupePedagogique() {
	}

	public AffectationGroupePedagogique(int id,
			DossierInscriptionAdministrative dossierInscriptionAdministrative,
			GroupePedagogique groupePedagogique) {
		this.id = id;
		this.dossierInscriptionAdministrative = dossierInscriptionAdministrative;
		this.groupePedagogique = groupePedagogique;
	}

	public AffectationGroupePedagogique(int id,
			DossierInscriptionAdministrative dossierInscriptionAdministrative,
			GroupePedagogique groupePedagogique, Date dateAffectation) {
		this.id = id;
		this.dossierInscriptionAdministrative = dossierInscriptionAdministrative;
		this.groupePedagogique = groupePedagogique;
		this.dateAffectation = dateAffectation;
	}

	@SequenceGenerator(name = "affectation_groupe_pedagogique_id_seq", sequenceName = "cursus.affectation_groupe_pedagogique_id_seq")
	@Id
	@GeneratedValue(generator = "affectation_groupe_pedagogique_id_seq")
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dossier_inscription", nullable = false)
	public DossierInscriptionAdministrative getDossierInscriptionAdministrative() {
		return this.dossierInscriptionAdministrative;
	}

	public void setDossierInscriptionAdministrative(
			DossierInscriptionAdministrative dossierInscriptionAdministrative) {
		this.dossierInscriptionAdministrative = dossierInscriptionAdministrative;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "groupe_pedagogique", nullable = false)
	public GroupePedagogique getGroupePedagogique() {
		return this.groupePedagogique;
	}

	public void setGroupePedagogique(GroupePedagogique groupePedagogique) {
		this.groupePedagogique = groupePedagogique;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_affectation", length = 13)
	public Date getDateAffectation() {
		return this.dateAffectation;
	}

	public void setDateAffectation(Date dateAffectation) {
		this.dateAffectation = dateAffectation;
	}

	/**
	 * [AffectationGroupePedagogique.bilanControleContinus] Getter 
	 * @author MAKERRI Sofiane on : 5 janv. 2015  08:34:16
	 * @return the bilanControleContinus
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "affectationGroupePedagogique")
	public List<BilanControleContinu> getBilanControleContinus() {
		return bilanControleContinus;
	}

	/**
	 * [AffectationGroupePedagogique.bilanControleContinus] Setter 
	 * @author MAKERRI Sofiane on : 5 janv. 2015  08:34:16
	 * @param bilanControleContinus the bilanControleContinus to set
	 */
	public void setBilanControleContinus(
			List<BilanControleContinu> bilanControleContinus) {
		this.bilanControleContinus = bilanControleContinus;
	}
	
	

}
