/**
 * [dz.gov.mesrs.sii.fve.business.model.bo.cursus.AssociationGroupePedagogique.java] 
 * @author MAKERRI Sofiane on : 2 oct. 2014  09:46:00
 */
package dz.gov.mesrs.sii.commons.data.model.fve.cursus;

//Generated 12 juin 2014 15:36:03 by Hibernate Tools 3.6.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import dz.gov.mesrs.sii.commons.data.model.fve.offreformation.AtomePedagogique;
import dz.gov.mesrs.sii.commons.data.model.fve.offreformation.RattachementMc;

/**
 * GroupePedagogiqueAp generated by hbm2java
 */
@Entity
@Table(name = "association_groupe_pedagogique", schema = "cursus", uniqueConstraints = @UniqueConstraint(columnNames = {
		"id_groupe_pedagogique", "id_rattachement_mc", "id_ap" }))
public class AssociationGroupePedagogique implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int id;
	private GroupePedagogique groupePedagogique;
	private AtomePedagogique ap;
	private String obervation;
	private Date dateAttachement;
	private RattachementMc rattachementMc;

	public AssociationGroupePedagogique() {
	}

	public AssociationGroupePedagogique(int id,
			GroupePedagogique groupePedagogique, AtomePedagogique ap,
			RattachementMc rattachementMc) {
		this.id = id;
		this.groupePedagogique = groupePedagogique;
		this.ap = ap;
		this.rattachementMc = rattachementMc;
	}

	public AssociationGroupePedagogique(int id,
			GroupePedagogique groupePedagogique, AtomePedagogique ap,
			String obervation) {
		this.id = id;
		this.groupePedagogique = groupePedagogique;
		this.ap = ap;
		this.obervation = obervation;
	}

	@SequenceGenerator(name = "association_groupe_pedagogique_id_seq", sequenceName = "cursus.association_groupe_pedagogique_id_seq")
	@Id
	@GeneratedValue(generator = "association_groupe_pedagogique_id_seq")
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_groupe_pedagogique", nullable = false)
	public GroupePedagogique getGroupePedagogique() {
		return this.groupePedagogique;
	}

	public void setGroupePedagogique(GroupePedagogique groupePedagogique) {
		this.groupePedagogique = groupePedagogique;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_ap", nullable = false)
	public AtomePedagogique getAp() {
		return this.ap;
	}

	public void setAp(AtomePedagogique ap) {
		this.ap = ap;
	}

	@Column(name = "obervation", length = 500)
	public String getObervation() {
		return this.obervation;
	}

	public void setObervation(String obervation) {
		this.obervation = obervation;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_attachement", length = 29)
	public Date getDateAttachement() {
		return dateAttachement;
	}

	public void setDateAttachement(Date dateAttachement) {
		this.dateAttachement = dateAttachement;
	}
	
	/**
	 * [GroupePedagogique.rattachementMc] Getter 
	 * @author MAKERRI Sofiane on : 6 oct. 2014  10:14:57
	 * @return the rattachementMc
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_rattachement_mc", nullable = false)
	public RattachementMc getRattachementMc() {
		return rattachementMc;
	}

	/**
	 * [GroupePedagogique.rattachementMc] Setter 
	 * @author MAKERRI Sofiane on : 6 oct. 2014  10:14:57
	 * @param rattachementMc the rattachementMc to set
	 */
	public void setRattachementMc(RattachementMc rattachementMc) {
		this.rattachementMc = rattachementMc;
	}

}
