package dz.gov.mesrs.sii.commons.data.model.fve.cursus;

// Generated 28 sept. 2014 09:52:08 by Hibernate Tools 3.6.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AttestationFinEtudeEdition generated by hbm2java
 */
@Entity
@Table(name = "attestation_fin_etude_edition", schema = "cursus")
public class AttestationFinEtudeEdition implements java.io.Serializable {

	/**
	 * serialVersionUID 
	 * @author BELBRIK Oualid  on : 28 sept. 2014  11:35:37
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private AttestationFinEtude attestationFinEtude;
	private Boolean estValide;
	private Date dateEdition;
	private String refTypeImpression;
	private String service;
	private String observation;
	private String agent;

	public AttestationFinEtudeEdition() {
	}

	public AttestationFinEtudeEdition(int id, AttestationFinEtude attestationFinEtude) {
		this.id = id;
		this.attestationFinEtude = attestationFinEtude;
	}

	public AttestationFinEtudeEdition(int id, AttestationFinEtude attestationFinEtude,
			Boolean estValide, Date dateEdition,
			String refTypeImpression, String service, String observation, String agent) {
		this.id = id;
		this.attestationFinEtude = attestationFinEtude;
		this.estValide = estValide;
		this.dateEdition = dateEdition;
		this.refTypeImpression = refTypeImpression;
		this.service = service;
		this.observation = observation;
		this.agent = agent;
	}

	@SequenceGenerator(name = "attestation_fin_etude_edition_id_seq", sequenceName = "cursus.attestation_fin_etude_edition_id_seq")
	@Id
	@GeneratedValue(generator = "attestation_fin_etude_edition_id_seq")
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_attestation_fin_etude", nullable = false)
	public AttestationFinEtude getAttestationFinEtude() {
		return this.attestationFinEtude;
	}

	public void setAttestationFinEtude(AttestationFinEtude attestationFinEtude) {
		this.attestationFinEtude = attestationFinEtude;
	}

	
	@Column(name = "est_valide")
	public Boolean getEstValide() {
		return this.estValide;
	}

	public void setEstValide(Boolean estValide) {
		this.estValide = estValide;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_edition", length = 13)
	public Date getDateEdition() {
		return this.dateEdition;
	}

	public void setDateEdition(Date dateEdition) {
		this.dateEdition = dateEdition;
	}

	@Column(name = "ref_type_impression", length = 30)
	public String getRefTypeImpression() {
		return this.refTypeImpression;
	}

	public void setRefTypeImpression(String refTypeImpression) {
		this.refTypeImpression = refTypeImpression;
	}

	@Column(name = "service", length = 50)
	public String getService() {
		return this.service;
	}

	public void setService(String service) {
		this.service = service;
	}

	@Column(name = "observation")
	public String getObservation() {
		return this.observation;
	}

	public void setObservation(String observation) {
		this.observation = observation;
	}
	
	@Column(name = "agent")
	public String getAgent() {
		return this.agent;
	}

	public void setAgent(String agent) {
		this.agent = agent;
	}

}
