package dz.gov.mesrs.sii.commons.data.model.fve.cursus;

// Generated 8 juin 2014 14:16:38 by Hibernate Tools 3.6.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import dz.gov.mesrs.sii.commons.data.model.fve.offreformation.AnneeAcademique;

/**
 * CongeAcademique generated by hbm2java
 */
@Entity
@Table(name = "conge_academique", schema = "cursus")
public class CongeAcademique implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int id;
	private Dossier dossier;
	private DossierEtudiant dossierEtudiant;
	private DossierInscriptionAdministrative dossierInscriptionAdministrative;
	private AnneeAcademique anneeAcademique;
	private AnneeAcademique anneeAcademiqueReintegration;

	private Date dateDemande;
	private String refCodeTypeConge;
	private Date dateDebutDemande;
	private Date dateFinDemande;
	private Boolean resultat;
	private Date dateResultat;
	private Date dateDebutAccordee;
	private Date dateFinAccordee;
	private String motifRefus;
	private Date dateReintegration;
	private String raison;

	private Boolean demandeValidee;
	private Boolean resultatValide;
	private Boolean reintegrationValidee;

	private Date dateValidationDemande;
	private Date dateValidationResultat;
	private Date dateValidationReintegration;

	public CongeAcademique() {
	}

	public CongeAcademique(Dossier dossier) {
		this.dossier = dossier;
	}

	public CongeAcademique(Dossier dossier, DossierEtudiant dossierEtudiant,
			Date dateDemande, String refCodeTypeConge, Date dateDebutDemande,
			Date dateFinDemande, Boolean resultat, Date dateResultat,
			Date dateDebutAccordee, Date dateFinAccordee, String motifRefus,
			Date dateReintegration, String raison) {
		this.dossier = dossier;
		this.dossierEtudiant = dossierEtudiant;
		this.dateDemande = dateDemande;
		this.refCodeTypeConge = refCodeTypeConge;
		this.dateDebutDemande = dateDebutDemande;
		this.dateFinDemande = dateFinDemande;
		this.resultat = resultat;
		this.dateResultat = dateResultat;
		this.dateDebutAccordee = dateDebutAccordee;
		this.dateFinAccordee = dateFinAccordee;
		this.motifRefus = motifRefus;
		this.dateReintegration = dateReintegration;
		this.raison = raison;
	}

	// @GenericGenerator(name = "generator", strategy = "foreign", parameters =
	// @Parameter(name = "property", value = "dossier"))
	// @GeneratedValue(generator = "generator")
	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Dossier getDossier() {
		return this.dossier;
	}

	public void setDossier(Dossier dossier) {
		this.dossier = dossier;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_dossier_etudiant")
	public DossierEtudiant getDossierEtudiant() {
		return this.dossierEtudiant;
	}

	public void setDossierEtudiant(DossierEtudiant dossierEtudiant) {
		this.dossierEtudiant = dossierEtudiant;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_demande", length = 13)
	public Date getDateDemande() {
		return this.dateDemande;
	}

	public void setDateDemande(Date dateDemande) {
		this.dateDemande = dateDemande;
	}

	@Column(name = "ref_code_type_conge", length = 30)
	public String getRefCodeTypeConge() {
		return this.refCodeTypeConge;
	}

	public void setRefCodeTypeConge(String refCodeTypeConge) {
		this.refCodeTypeConge = refCodeTypeConge;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_debut_demande", length = 13)
	public Date getDateDebutDemande() {
		return this.dateDebutDemande;
	}

	public void setDateDebutDemande(Date dateDebutDemande) {
		this.dateDebutDemande = dateDebutDemande;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_fin_demande", length = 13)
	public Date getDateFinDemande() {
		return this.dateFinDemande;
	}

	public void setDateFinDemande(Date dateFinDemande) {
		this.dateFinDemande = dateFinDemande;
	}

	@Column(name = "resultat")
	public Boolean getResultat() {
		return this.resultat;
	}

	public void setResultat(Boolean resultat) {
		this.resultat = resultat;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_resultat", length = 13)
	public Date getDateResultat() {
		return this.dateResultat;
	}

	public void setDateResultat(Date dateResultat) {
		this.dateResultat = dateResultat;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_debut_accordee", length = 13)
	public Date getDateDebutAccordee() {
		return this.dateDebutAccordee;
	}

	public void setDateDebutAccordee(Date dateDebutAccordee) {
		this.dateDebutAccordee = dateDebutAccordee;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_fin_accordee", length = 13)
	public Date getDateFinAccordee() {
		return this.dateFinAccordee;
	}

	public void setDateFinAccordee(Date dateFinAccordee) {
		this.dateFinAccordee = dateFinAccordee;
	}

	@Column(name = "motif_refus")
	public String getMotifRefus() {
		return this.motifRefus;
	}

	public void setMotifRefus(String motifRefus) {
		this.motifRefus = motifRefus;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_reintegration", length = 13)
	public Date getDateReintegration() {
		return this.dateReintegration;
	}

	public void setDateReintegration(Date dateReintegration) {
		this.dateReintegration = dateReintegration;
	}

	@Column(name = "raison")
	public String getRaison() {
		return this.raison;
	}

	public void setRaison(String raison) {
		this.raison = raison;
	}

	@Column(name = "demande_validee")
	public Boolean getDemandeValidee() {
		return demandeValidee;
	}

	public void setDemandeValidee(Boolean demandeValidee) {
		this.demandeValidee = demandeValidee;
	}

	@Column(name = "resultat_valide")
	public Boolean getResultatValide() {
		return resultatValide;
	}

	public void setResultatValide(Boolean resultatValide) {
		this.resultatValide = resultatValide;
	}

	@Column(name = "reintegration_validee")
	public Boolean getReintegrationValidee() {
		return reintegrationValidee;
	}

	public void setReintegrationValidee(Boolean reintegrationValidee) {
		this.reintegrationValidee = reintegrationValidee;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_validation_demande", length = 29)
	public Date getDateValidationDemande() {
		return dateValidationDemande;
	}

	public void setDateValidationDemande(Date dateValidationDemande) {
		this.dateValidationDemande = dateValidationDemande;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_validation_resultat", length = 29)
	public Date getDateValidationResultat() {
		return dateValidationResultat;
	}

	public void setDateValidationResultat(Date dateValidationResultat) {
		this.dateValidationResultat = dateValidationResultat;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_validation_reintegration", length = 29)
	public Date getDateValidationReintegration() {
		return dateValidationReintegration;
	}

	public void setDateValidationReintegration(Date dateValidationReintegration) {
		this.dateValidationReintegration = dateValidationReintegration;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_dossier_inscription")
	public DossierInscriptionAdministrative getDossierInscriptionAdministrative() {
		return dossierInscriptionAdministrative;
	}

	public void setDossierInscriptionAdministrative(
			DossierInscriptionAdministrative dossierInscriptionAdministrative) {
		this.dossierInscriptionAdministrative = dossierInscriptionAdministrative;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_annee_academique")
	public AnneeAcademique getAnneeAcademique() {
		return anneeAcademique;
	}

	public void setAnneeAcademique(AnneeAcademique anneeAcademique) {
		this.anneeAcademique = anneeAcademique;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_annee_academique_reintegration")
	public AnneeAcademique getAnneeAcademiqueReintegration() {
		return anneeAcademiqueReintegration;
	}

	public void setAnneeAcademiqueReintegration(
			AnneeAcademique anneeAcademiqueReintegration) {
		this.anneeAcademiqueReintegration = anneeAcademiqueReintegration;
	}

}
