package dz.gov.mesrs.sii.commons.data.model.fve.cursus;

// Generated 20 mai 2014 17:49:05 by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Diplome generated by hbm2java
 */
@Entity
@Table(name = "diplome", schema = "cursus")
public class Diplome implements java.io.Serializable {

	/**
	 * serialVersionUID
	 * 
	 * @author BELDI Jamel on : 21 mai 2014 09:00:31
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private ReleveDeNotes releveDeNotes;
	private DossierEtudiant dossierEtudiant;
	private String code;
	private Short anneeObtention;
	private String refCodeDiplome;
	private String equivalence;
	private String refCodeSpecialite;
	private String refCodeMention;
	private String etablissement;
	private String observation;

	public Diplome() {
	}

	public Diplome(int id) {
		this.id = id;
	}

	public Diplome(int id, ReleveDeNotes releveDeNotes,
			DossierEtudiant dossierEtudiant, String code, Short anneeObtention,
			String refCodeDiplome, String equivalence,
			String refCodeSpecialite, String refCodeMention,
			String etablissement, String observation) {
		this.id = id;
		this.releveDeNotes = releveDeNotes;
		this.dossierEtudiant = dossierEtudiant;
		this.code = code;
		this.anneeObtention = anneeObtention;
		this.refCodeDiplome = refCodeDiplome;
		this.equivalence = equivalence;
		this.refCodeSpecialite = refCodeSpecialite;
		this.refCodeMention = refCodeMention;
		this.etablissement = etablissement;
		this.observation = observation;
	}

	@SequenceGenerator(name = "diplome_id_seq_gen", sequenceName = "cursus.diplome_id_seq")
	@Id
	@GeneratedValue(generator = "diplome_id_seq_gen")
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_releve_de_notes")
	public ReleveDeNotes getReleveDeNotes() {
		return this.releveDeNotes;
	}

	public void setReleveDeNotes(ReleveDeNotes releveDeNotes) {
		this.releveDeNotes = releveDeNotes;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_dossier_etudiant")
	public DossierEtudiant getDossierEtudiant() {
		return this.dossierEtudiant;
	}

	public void setDossierEtudiant(DossierEtudiant dossierEtudiant) {
		this.dossierEtudiant = dossierEtudiant;
	}

	@Column(name = "code", length = 30)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "annee_obtention")
	public Short getAnneeObtention() {
		return this.anneeObtention;
	}

	public void setAnneeObtention(Short anneeObtention) {
		this.anneeObtention = anneeObtention;
	}

	@Column(name = "ref_code_diplome", length = 30)
	public String getRefCodeDiplome() {
		return this.refCodeDiplome;
	}

	public void setRefCodeDiplome(String refCodeDiplome) {
		this.refCodeDiplome = refCodeDiplome;
	}

	@Column(name = "equivalence")
	public String getEquivalence() {
		return this.equivalence;
	}

	public void setEquivalence(String equivalence) {
		this.equivalence = equivalence;
	}

	@Column(name = "ref_code_specialite", length = 30)
	public String getRefCodeSpecialite() {
		return this.refCodeSpecialite;
	}

	public void setRefCodeSpecialite(String refCodeSpecialite) {
		this.refCodeSpecialite = refCodeSpecialite;
	}

	@Column(name = "ref_code_mention", length = 30)
	public String getRefCodeMention() {
		return this.refCodeMention;
	}

	public void setRefCodeMention(String refCodeMention) {
		this.refCodeMention = refCodeMention;
	}

	@Column(name = "etablissement")
	public String getEtablissement() {
		return this.etablissement;
	}

	public void setEtablissement(String etablissement) {
		this.etablissement = etablissement;
	}

	@Column(name = "observation")
	public String getObservation() {
		return this.observation;
	}

	public void setObservation(String observation) {
		this.observation = observation;
	}

}
