package dz.gov.mesrs.sii.commons.data.model.fve.cursus;

// Generated 28 sept. 2014 09:52:08 by Hibernate Tools 3.6.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import dz.gov.mesrs.sii.commons.data.model.fve.examen.BilanSession;
import dz.gov.mesrs.sii.commons.data.model.fve.offreformation.AnneeAcademique;
import dz.gov.mesrs.sii.commons.data.model.fve.offreformation.Cycle;

/**
 * DiplomeFinEtude generated by hbm2java
 */
@Entity
@Table(name = "diplome_fin_etude", schema = "cursus")
public class DiplomeFinEtude implements java.io.Serializable {

	/**
	 * serialVersionUID 
	 * @author BELBRIK Oualid  on : 28 sept. 2014  11:36:13
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private String identifiant;
	private AnneeAcademique anneeAcademique;
	private Integer idEtablissement;
	private Date dateObtention;
	private boolean estValide;
	private boolean estValideEtab;
	private boolean estValideFac;
	private boolean estDelivre;
	private Date dateDerniereEdition;
	private Integer idCompteAgent;
	private String refTypeImpression;
	private String observation;
	private String observationEtab;
	private String refMinistere;
	private Date dateSignatureMinistere;
	private Date dateSignatureEtablissement;
	private Date dateSignatureFaculte;
	private String autoriteMinistere;
	private String autoriteEtablissement;
	private Date dateCreation;
	private BilanSession bilanSession;
	private boolean generationValide;
	private String refEtab;
	private String refFac;
	private String autoriteFac;
	private String observationFac;
	private Cycle cycle;


	public DiplomeFinEtude(){
		super();
	}

	@SequenceGenerator(name = "diplome_fin_etude_id_seq", sequenceName = "cursus.diplome_fin_etude_id_seq")
	@Id
	@GeneratedValue(generator = "diplome_fin_etude_id_seq")
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}
	
	public void setId(int id) {
		this.id = id;
	}



	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_annee_academique", nullable = false)
	public AnneeAcademique getAnneeAcademique() {
		return this.anneeAcademique;
	}

	public void setAnneeAcademique(AnneeAcademique anneeAcademique) {
		this.anneeAcademique = anneeAcademique;
	}

	@Column(name = "id_etablissement", nullable = true, length = 15)
	public Integer getIdEtablissement() {
		return this.idEtablissement;
	}

	public void setIdEtablissement(Integer idEtablissement) {
		this.idEtablissement = idEtablissement;
	}
	
	@Temporal(TemporalType.DATE)
	@Column(name = "date_obtention", length = 13)
	public Date getDateObtention() {
		return this.dateObtention;
	}

	public void setDateObtention(Date dateObtention) {
		this.dateObtention = dateObtention;
	}

	@Column(name = "est_valide")
	public boolean getEstValide() {
		return this.estValide;
	}

	public void setEstValide(boolean estValide) {
		this.estValide = estValide;
	}

	@Column(name = "est_delivre")
	public boolean getEstDelivre() {
		return this.estDelivre;
	}

	public void setEstDelivre(boolean estDelivre) {
		this.estDelivre = estDelivre;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_derniere_edition", length = 13)
	public Date getDateDerniereEdition() {
		return this.dateDerniereEdition;
	}

	public void setDateDerniereEdition(Date dateDerniereEdition) {
		this.dateDerniereEdition = dateDerniereEdition;
	}

	
	@Column(name = "id_compte_agent")
	public Integer getIdCompteAgent() {
		return this.idCompteAgent;
	}

	public void setIdCompteAgent(Integer idCompteAgent) {
		this.idCompteAgent = idCompteAgent;
	}

	@Column(name = "ref_type_impression", length = 30)
	public String getRefTypeImpression() {
		return this.refTypeImpression;
	}

	public void setRefTypeImpression(String refTypeImpression) {
		this.refTypeImpression = refTypeImpression;
	}

	@Column(name = "observation")
	public String getObservation() {
		return this.observation;
	}

	public void setObservation(String observation) {
		this.observation = observation;
	}

	@Column(name = "observation_etab")
	public String getObservationEtab() {
		return this.observationEtab;
	}

	public void setObservationEtab(String observationEtab) {
		this.observationEtab = observationEtab;
	}

	/**
	 * [DiplomeFinEtude.refMinistere] Getter 
	 * @author BELBRIK Oualid on : 11 oct. 2014  16:28:01
	 * @return the refMinistere
	 */
	@Column(name = "ref_ministere")
	public String getRefMinistere() {
		return refMinistere;
	}

	/**
	 * [DiplomeFinEtude.refMinistere] Setter 
	 * @author BELBRIK Oualid on : 11 oct. 2014  16:28:01
	 * @param refMinistere the refMinistere to set
	 */
	public void setRefMinistere(String refMinistere) {
		this.refMinistere = refMinistere;
	}


	/**
	 * [DiplomeFinEtude.dateSignatureMinistere] Getter 
	 * @author BELBRIK Oualid on : 11 oct. 2014  16:28:01
	 * @return the dateSignatureMinistere
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "date_signature_ministere", length = 13)
	public Date getDateSignatureMinistere() {
		return dateSignatureMinistere;
	}

	/**
	 * [DiplomeFinEtude.dateSignatureMinistere] Setter 
	 * @author BELBRIK Oualid on : 11 oct. 2014  16:28:01
	 * @param dateSignatureMinistere the dateSignatureMinistere to set
	 */
	public void setDateSignatureMinistere(Date dateSignatureMinistere) {
		this.dateSignatureMinistere = dateSignatureMinistere;
	}

	/**
	 * [DiplomeFinEtude.dateSignatureEtablissement] Getter 
	 * @author BELBRIK Oualid on : 11 oct. 2014  16:28:01
	 * @return the dateSignatureEtablissement
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "date_signature_etablissement", length = 13)
	public Date getDateSignatureEtablissement() {
		return dateSignatureEtablissement;
	}

	/**
	 * [DiplomeFinEtude.dateSignatureEtablissement] Setter 
	 * @author BELBRIK Oualid on : 11 oct. 2014  16:28:01
	 * @param dateSignatureEtablissement the dateSignatureEtablissement to set
	 */
	public void setDateSignatureEtablissement(Date dateSignatureEtablissement) {
		this.dateSignatureEtablissement = dateSignatureEtablissement;
	}

	/**
	 * [DiplomeFinEtude.autoriteMinistere] Getter 
	 * @author BELBRIK Oualid on : 11 oct. 2014  16:28:01
	 * @return the autoriteMinistere
	 */
	@Column(name = "autorite_ministere")
	public String getAutoriteMinistere() {
		return autoriteMinistere;
	}

	/**
	 * [DiplomeFinEtude.autoriteMinistere] Setter 
	 * @author BELBRIK Oualid on : 11 oct. 2014  16:28:01
	 * @param autoriteMinistere the autoriteMinistere to set
	 */
	public void setAutoriteMinistere(String autoriteMinistere) {
		this.autoriteMinistere = autoriteMinistere;
	}

	/**
	 * [DiplomeFinEtude.autoriteEtablissement] Getter 
	 * @author BELBRIK Oualid on : 11 oct. 2014  16:28:01
	 * @return the autoriteEtablissement
	 */
	@Column(name = "autorite_etablissement")
	public String getAutoriteEtablissement() {
		return autoriteEtablissement;
	}

	/**
	 * [DiplomeFinEtude.autoriteEtablissement] Setter 
	 * @author BELBRIK Oualid on : 11 oct. 2014  16:28:01
	 * @param autoriteEtablissement the autoriteEtablissement to set
	 */
	public void setAutoriteEtablissement(String autoriteEtablissement) {
		this.autoriteEtablissement = autoriteEtablissement;
	}
	
	@Column(name = "est_signe_etab")
	public boolean getEstValideEtab() {
		return this.estValideEtab;
	}

	public void setEstValideEtab(boolean estValideEtab) {
		this.estValideEtab = estValideEtab;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_creation", length = 13)
	public Date getDateCreation() {
		return this.dateCreation;
	}

	public void setDateCreation(Date dateCreation) {
		this.dateCreation = dateCreation;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_bilan_session")
	public BilanSession getBilanSession() {
		return this.bilanSession;
	}

	public void setBilanSession(BilanSession bilanSession) {
		this.bilanSession = bilanSession;
	}

	/**
	 * [DiplomeFinEtude.estValideFac] Getter 
	 * @author BELBRIK Oualid on : 2 nov. 2014  17:33:39
	 * @return the estValideFac
	 */
	@Column(name = "est_signe_fac")
	public boolean getEstValideFac() {
		return estValideFac;
	}

	/**
	 * [DiplomeFinEtude.estValideFac] Setter 
	 * @author BELBRIK Oualid on : 2 nov. 2014  17:33:39
	 * @param estValideFac the estValideFac to set
	 */
	public void setEstValideFac(boolean estValideFac) {
		this.estValideFac = estValideFac;
	}

	/**
	 * [DiplomeFinEtude.dateSignatureFaculte] Getter 
	 * @author BELBRIK Oualid on : 2 nov. 2014  17:33:39
	 * @return the dateSignatureFaculte
	 */
	@Temporal(TemporalType.DATE)
	@Column(name = "date_signature_faculte", length = 13)
	public Date getDateSignatureFaculte() {
		return dateSignatureFaculte;
	}

	/**
	 * [DiplomeFinEtude.dateSignatureFaculte] Setter 
	 * @author BELBRIK Oualid on : 2 nov. 2014  17:33:39
	 * @param dateSignatureFaculte the dateSignatureFaculte to set
	 */
	public void setDateSignatureFaculte(Date dateSignatureFaculte) {
		this.dateSignatureFaculte = dateSignatureFaculte;
	}

	/**
	 * [DiplomeFinEtude.generationValide] Getter 
	 * @author BELBRIK Oualid on : 3 nov. 2014  11:53:27
	 * @return the generationValide
	 */
	@Column(name = "generation_valide")
	public boolean getGenerationValide() {
		return generationValide;
	}

	/**
	 * [DiplomeFinEtude.generationValide] Setter 
	 * @author BELBRIK Oualid on : 3 nov. 2014  11:53:27
	 * @param generationValide the generationValide to set
	 */
	public void setGenerationValide(boolean generationValide) {
		this.generationValide = generationValide;
	}

	/**
	 * [DiplomeFinEtude.refEtab] Getter 
	 * @author BELBRIK Oualid on : 3 nov. 2014  16:33:43
	 * @return the refEtab
	 */
	@Column(name = "ref_etab")
	public String getRefEtab() {
		return refEtab;
	}

	/**
	 * [DiplomeFinEtude.refEtab] Setter 
	 * @author BELBRIK Oualid on : 3 nov. 2014  16:33:43
	 * @param refEtab the refEtab to set
	 */
	public void setRefEtab(String refEtab) {
		this.refEtab = refEtab;
	}

	/**
	 * [DiplomeFinEtude.refFac] Getter 
	 * @author BELBRIK Oualid on : 3 nov. 2014  16:33:43
	 * @return the refFac
	 */
	@Column(name = "ref_fac")
	public String getRefFac() {
		return refFac;
	}

	/**
	 * [DiplomeFinEtude.refFac] Setter 
	 * @author BELBRIK Oualid on : 3 nov. 2014  16:33:43
	 * @param refFac the refFac to set
	 */
	public void setRefFac(String refFac) {
		this.refFac = refFac;
	}

	/**
	 * [DiplomeFinEtude.autoriteFac] Getter 
	 * @author BELBRIK Oualid on : 3 nov. 2014  16:33:43
	 * @return the autoriteFac
	 */
	@Column(name = "autorite_fac")
	public String getAutoriteFac() {
		return autoriteFac;
	}

	/**
	 * [DiplomeFinEtude.autoriteFac] Setter 
	 * @author BELBRIK Oualid on : 3 nov. 2014  16:33:43
	 * @param autoriteFac the autoriteFac to set
	 */
	public void setAutoriteFac(String autoriteFac) {
		this.autoriteFac = autoriteFac;
	}

	/**
	 * [DiplomeFinEtude.observationFac] Getter 
	 * @author BELBRIK Oualid on : 3 nov. 2014  16:33:43
	 * @return the observationFac
	 */
	@Column(name = "observation_fac")
	public String getObservationFac() {
		return observationFac;
	}

	/**
	 * [DiplomeFinEtude.observationFac] Setter 
	 * @author BELBRIK Oualid on : 3 nov. 2014  16:33:43
	 * @param observationFac the observationFac to set
	 */
	public void setObservationFac(String observationFac) {
		this.observationFac = observationFac;
	}

	/**
	 * [DiplomeFinEtude.identifiant] Getter 
	 * @author BELBRIK Oualid on : 10 nov. 2014  12:21:50
	 * @return the identifiant
	 */
	@Column(name = "identifiant")
	public String getIdentifiant() {
		return identifiant;
	}

	/**
	 * [DiplomeFinEtude.identifiant] Setter 
	 * @author BELBRIK Oualid on : 10 nov. 2014  12:21:50
	 * @param identifiant the identifiant to set
	 */
	public void setIdentifiant(String identifiant) {
		this.identifiant = identifiant;
	}

	/**
	 * [DiplomeFinEtude.cycle] Getter 
	 * @author MAKERRI Sofiane on : 17 févr. 2015  12:33:05
	 * @return the cycle
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_cycle", nullable = false)
	public Cycle getCycle() {
		return cycle;
	}

	/**
	 * [DiplomeFinEtude.cycle] Setter 
	 * @author MAKERRI Sofiane on : 17 févr. 2015  12:33:05
	 * @param cycle the cycle to set
	 */
	public void setCycle(Cycle cycle) {
		this.cycle = cycle;
	}
	
	
	
	
}
