package dz.gov.mesrs.sii.commons.data.model.fve.cursus;

// Generated 8 juin 2014 09:47:18 by Hibernate Tools 3.6.0

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import dz.gov.mesrs.sii.commons.data.model.fve.offreformation.AnneeAcademique;
import dz.gov.mesrs.sii.commons.data.model.fve.offreformation.OuvertureOffreFormation;
import dz.gov.mesrs.sii.commons.data.model.fve.offreformation.Periode;
import dz.gov.mesrs.sii.commons.data.model.referentiel.Nomenclature;
import dz.gov.mesrs.sii.commons.data.model.referentiel.RefEtablissement;
import dz.gov.mesrs.sii.commons.data.model.referentiel.RefGroupe;
/**
 * GroupePedagogique generated by hbm2java
 */
@Entity
@Table(name = "groupe_pedagogique", schema = "cursus")
public class GroupePedagogique implements java.io.Serializable {

	/**
	 * serialVersionUID
	 * 
	 * @author MAKERRI Sofiane on : 8 juin 2014 09:59:14
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private OuvertureOffreFormation oof;
	private Periode periode;
	private Nomenclature ncTypeGroupe;
	private RefGroupe refGroupe;
	private Integer capaciteMin;
	private Integer capaciteMax;
	private RefEtablissement refEtablissement;
	private AnneeAcademique anneeAcademique;
	private String nomAffichage;
	private String nomAffichageArabe;
	private Boolean mcOptionnelle;
	private GroupePedagogique section;
	private Set<GroupePedagogique> sections = new HashSet<GroupePedagogique>(0);
	private List<AffectationGroupePedagogique> affectationGroupePedagogiques = new ArrayList<AffectationGroupePedagogique>();

	public GroupePedagogique() {
	}

	public GroupePedagogique(int id) {
		this.id = id;
	}

	public GroupePedagogique(int id, 
			Integer capaciteMin, Integer capaciteMax
			) {
		this.id = id;
		this.capaciteMin = capaciteMin;
		this.capaciteMax = capaciteMax;
	}

	@SequenceGenerator(name = "groupe_pedagogique_id_seq", sequenceName = "cursus.groupe_pedagogique_id_seq")
	@Id
	@GeneratedValue(generator = "groupe_pedagogique_id_seq")
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}
	
	

	/**
	 * [GroupePedagogique.periode] Getter 
	 * @author MAKERRI Sofiane on : 8 sept. 2014  09:44:18
	 * @return the periode
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_periode")
	public Periode getPeriode() {
		return periode;
	}

	/**
	 * [GroupePedagogique.periode] Setter 
	 * @author MAKERRI Sofiane on : 8 sept. 2014  09:44:18
	 * @param periode the periode to set
	 */
	public void setPeriode(Periode periode) {
		this.periode = periode;
	}

	@Column(name = "capacite_min")
	public Integer getCapaciteMin() {
		return this.capaciteMin;
	}

	public void setCapaciteMin(Integer capaciteMin) {
		this.capaciteMin = capaciteMin;
	}

	@Column(name = "capacite_max")
	public Integer getCapaciteMax() {
		return this.capaciteMax;
	}

	public void setCapaciteMax(Integer capaciteMax) {
		this.capaciteMax = capaciteMax;
	}

//	@Column(name = "ref_code_etablissement", length = 20, nullable = false)
//	public String getRefCodeEtablissement() {
//		return refCodeEtablissement;
//	}
//
//	public void setRefCodeEtablissement(String refCodeEtablissement) {
//		this.refCodeEtablissement = refCodeEtablissement;
//	}
	
	

	/**
	 * [GroupePedagogique.of] Getter
	 * 
	 * @author MAKERRI Sofiane on : 9 juin 2014 08:17:15
	 * @return the of
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_oof")
	public OuvertureOffreFormation getOof() {
		return oof;
	}

	/**
	 * [GroupePedagogique.refEtablissement] Getter 
	 * @author MAKERRI Sofiane on : 2 oct. 2014  13:36:26
	 * @return the refEtablissement
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_ref_etablissement")
	public RefEtablissement getRefEtablissement() {
		return refEtablissement;
	}

	/**
	 * [GroupePedagogique.refEtablissement] Setter 
	 * @author MAKERRI Sofiane on : 2 oct. 2014  13:36:26
	 * @param refEtablissement the refEtablissement to set
	 */
	public void setRefEtablissement(RefEtablissement refEtablissement) {
		this.refEtablissement = refEtablissement;
	}

	/**
	 * [GroupePedagogique.of] Setter
	 * 
	 * @author MAKERRI Sofiane on : 9 juin 2014 08:17:15
	 * @param of
	 *            the of to set
	 */
	public void setOof(OuvertureOffreFormation oof) {
		this.oof = oof;
	}



	/**
	 * [GroupePedagogique.typeGroupe] Getter 
	 * @author MAKERRI Sofiane on : 2 oct. 2014  11:01:16
	 * @return the typeGroupe
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "nc_type_groupe")
	public Nomenclature getNcTypeGroupe() {
		return ncTypeGroupe;
	}

	/**
	 * [GroupePedagogique.typeGroupe] Setter 
	 * @author MAKERRI Sofiane on : 2 oct. 2014  11:01:16
	 * @param typeGroupe the typeGroupe to set
	 */
	public void setNcTypeGroupe(Nomenclature ncTypeGroupe) {
		this.ncTypeGroupe = ncTypeGroupe;
	}

	
	/**
	 * [GroupePedagogique.anneeAcademique] Getter 
	 * @author MAKERRI Sofiane on : 24 déc. 2014  10:54:26
	 * @return the anneeAcademique
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "annee_academique", nullable = false)
	public AnneeAcademique getAnneeAcademique() {
		return anneeAcademique;
	}

	/**
	 * [GroupePedagogique.anneeAcademique] Setter 
	 * @author MAKERRI Sofiane on : 24 déc. 2014  10:54:26
	 * @param anneeAcademique the anneeAcademique to set
	 */
	public void setAnneeAcademique(AnneeAcademique anneeAcademique) {
		this.anneeAcademique = anneeAcademique;
	}

	/**
	 * [GroupePedagogique.nomAffichage] Getter 
	 * @author MAKERRI Sofiane on : 16 juin 2014  08:15:01
	 * @return the nomAffichage
	 */
	@Column(name = "nom_affichage", length = 30, nullable = false)
	public String getNomAffichage() {
		return nomAffichage;
	}

	/**
	 * [GroupePedagogique.nomAffichage] Setter 
	 * @author MAKERRI Sofiane on : 16 juin 2014  08:15:01
	 * @param nomAffichage the nomAffichage to set
	 */
	public void setNomAffichage(String nomAffichage) {
		this.nomAffichage = nomAffichage;
	}
	
	

	/**
	 * [GroupePedagogique.nomAffichageArabe] Getter 
	 * @author MAKERRI Sofiane on : 16 sept. 2014  11:08:34
	 * @return the nomAffichageArabe
	 */
	@Column(name = "nom_affichage_arabe", length = 30, nullable = false)
	public String getNomAffichageArabe() {
		return nomAffichageArabe;
	}

	/**
	 * [GroupePedagogique.nomAffichageArabe] Setter 
	 * @author MAKERRI Sofiane on : 16 sept. 2014  11:08:34
	 * @param nomAffichageArabe the nomAffichageArabe to set
	 */
	public void setNomAffichageArabe(String nomAffichageArabe) {
		this.nomAffichageArabe = nomAffichageArabe;
	}

	/**
	 * [GroupePedagogique.section] Getter 
	 * @author MAKERRI Sofiane on : 16 juin 2014  08:55:02
	 * @return the section
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "section")
	public GroupePedagogique getSection() {
		return section;
	}

	/**
	 * [GroupePedagogique.section] Setter 
	 * @author MAKERRI Sofiane on : 16 juin 2014  08:55:02
	 * @param section the section to set
	 */
	public void setSection(GroupePedagogique section) {
		this.section = section;
	}

	/**
	 * [GroupePedagogique.sections] Getter 
	 * @author MAKERRI Sofiane on : 16 juin 2014  08:56:04
	 * @return the sections
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "section")
	public Set<GroupePedagogique> getSections() {
		return sections;
	}

	/**
	 * [GroupePedagogique.sections] Setter 
	 * @author MAKERRI Sofiane on : 16 juin 2014  08:56:04
	 * @param sections the sections to set
	 */
	public void setSections(Set<GroupePedagogique> sections) {
		this.sections = sections;
	}

	/**
	 * [GroupePedagogique.refGroupe] Getter 
	 * @author MAKERRI Sofiane on : 2 oct. 2014  11:02:13
	 * @return the refGroupe
	 */
	@ManyToOne(fetch = FetchType.LAZY, cascade=CascadeType.ALL)
	@JoinColumn(name = "id_ref_groupe", nullable = false)
	public RefGroupe getRefGroupe() {
		return refGroupe;
	}

	/**
	 * [GroupePedagogique.refGroupe] Setter 
	 * @author MAKERRI Sofiane on : 2 oct. 2014  11:02:13
	 * @param refGroupe the refGroupe to set
	 */
	public void setRefGroupe(RefGroupe refGroupe) {
		this.refGroupe = refGroupe;
	}

	/**
	 * [GroupePedagogique.mcOptionnelle] Getter 
	 * @author MAKERRI Sofiane on : 6 oct. 2014  15:54:55
	 * @return the mcOptionnelle
	 */
	@Column(name = "mc_optionnelle")
	public Boolean getMcOptionnelle() {
		return mcOptionnelle;
	}

	/**
	 * [GroupePedagogique.mcOptionnelle] Setter 
	 * @author MAKERRI Sofiane on : 6 oct. 2014  15:54:55
	 * @param mcOptionnelle the mcOptionnelle to set
	 */
	public void setMcOptionnelle(Boolean mcOptionnelle) {
		this.mcOptionnelle = mcOptionnelle;
	}

	/**
	 * [GroupePedagogique.affectationGroupePedagogiques] Getter 
	 * @author MAKERRI Sofiane on : 27 janv. 2015  08:04:19
	 * @return the affectationGroupePedagogiques
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "groupePedagogique", cascade = CascadeType.ALL, orphanRemoval = true)
	public List<AffectationGroupePedagogique> getAffectationGroupePedagogiques() {
		return affectationGroupePedagogiques;
	}

	/**
	 * [GroupePedagogique.affectationGroupePedagogiques] Setter 
	 * @author MAKERRI Sofiane on : 27 janv. 2015  08:04:19
	 * @param affectationGroupePedagogiques the affectationGroupePedagogiques to set
	 */
	public void setAffectationGroupePedagogiques(
			List<AffectationGroupePedagogique> affectationGroupePedagogiques) {
		this.affectationGroupePedagogiques = affectationGroupePedagogiques;
	}
	
	


}
