package dz.gov.mesrs.sii.commons.data.model.fve.cursus;

// Generated 20 mai 2014 17:49:05 by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * LigneReleveDeNotes generated by hbm2java
 */
@Entity
@Table(name = "ligne_releve_de_notes", schema = "cursus")
public class LigneReleveDeNotes implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int id;
	private ReleveDeNotes releveDeNotes;
	private String libelleMatiereFr;
	private String libelleMatiereAr;
	private Double note;
	private Double noteBase;
	private Short rang;

	public LigneReleveDeNotes() {
	}

	public LigneReleveDeNotes(int id) {
		this.id = id;
	}

	public LigneReleveDeNotes(int id, ReleveDeNotes releveDeNotes,
			String libelleMatiereFr, String libelleMatiereAr, Double note,
			Double noteBase, Short rang) {
		this.id = id;
		this.releveDeNotes = releveDeNotes;
		this.libelleMatiereFr = libelleMatiereFr;
		this.libelleMatiereAr = libelleMatiereAr;
		this.note = note;
		this.noteBase = noteBase;
		this.rang = rang;
	}

	@SequenceGenerator(name="ligneReleveDeNotes_id_seq_gen", sequenceName="cursus.ligne_releve_de_notes_id_seq")
	@Id @GeneratedValue(generator="ligneReleveDeNotes_id_seq_gen")
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_releve_notes")
	public ReleveDeNotes getReleveDeNotes() {
		return this.releveDeNotes;
	}

	public void setReleveDeNotes(ReleveDeNotes releveDeNotes) {
		this.releveDeNotes = releveDeNotes;
	}

	@Column(name = "libelle_matiere_fr")
	public String getLibelleMatiereFr() {
		return this.libelleMatiereFr;
	}

	public void setLibelleMatiereFr(String libelleMatiereFr) {
		this.libelleMatiereFr = libelleMatiereFr;
	}

	@Column(name = "libelle_matiere_ar")
	public String getLibelleMatiereAr() {
		return this.libelleMatiereAr;
	}

	public void setLibelleMatiereAr(String libelleMatiereAr) {
		this.libelleMatiereAr = libelleMatiereAr;
	}

	@Column(name = "note", precision = 17, scale = 17)
	public Double getNote() {
		return this.note;
	}

	public void setNote(Double note) {
		this.note = note;
	}

	@Column(name = "note_base", precision = 17, scale = 17)
	public Double getNoteBase() {
		return this.noteBase;
	}

	public void setNoteBase(Double noteBase) {
		this.noteBase = noteBase;
	}

	@Column(name = "rang")
	public Short getRang() {
		return this.rang;
	}

	public void setRang(Short rang) {
		this.rang = rang;
	}

}
