package dz.gov.mesrs.sii.commons.data.model.fve.cursus;

// Generated 8 juin 2014 12:21:31 by Hibernate Tools 3.6.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AbsenceMatiere generated by hbm2java
 */
@Entity
@Table(name = "reintegration", schema = "cursus")
public class Reintegration implements java.io.Serializable {

	/**
	 * serialVersionUID
	 * 
	 * @author BELBRIK Oualid on : 9 juillet 2014 13:32:41
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private Exclusion exclusion;
	private Date dateDemande;
	private Boolean resultat;
	private String objet;
	private Date dateResultat;
	private Date dateAutorisation;
	private Date dateReintegration;
	private String motif;

	private Boolean reintegrationValidee;
	private Date dateValidation;

	public Reintegration() {
	}

	public Reintegration(int id) {
		this.id = id;
	}

	public Reintegration(int id, Exclusion exclusion, Date dateDemande,
			Boolean resultat, String objet, String motif, Date dateResultat,
			Date dateAutorisation, Date dateReintegration) {
		this.id = id;
		this.exclusion = exclusion;
		this.dateDemande = dateDemande;
		this.resultat = resultat;
		this.objet = objet;
		this.dateResultat = dateResultat;
		this.dateAutorisation = dateAutorisation;
		this.dateReintegration = dateReintegration;
		this.motif = motif;
	}

	@SequenceGenerator(name = "reintegration_id_seq_gen", sequenceName = "cursus.reintegration_id_seq")
	@Id
	@GeneratedValue(generator = "reintegration_id_seq_gen")
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_exclusion")
	public Exclusion getExclusion() {
		return this.exclusion;
	}

	public void setExclusion(Exclusion exclusion) {
		this.exclusion = exclusion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_demande")
	public Date getDateDemande() {
		return this.dateDemande;
	}

	public void setDateDemande(Date dateDemande) {
		this.dateDemande = dateDemande;
	}

	@Column(name = "objet")
	public String getObjet() {
		return this.objet;
	}

	public void setObjet(String objet) {
		this.objet = objet;
	}

	@Column(name = "motif")
	public String getMotif() {
		return this.motif;
	}

	public void setMotif(String motif) {
		this.motif = motif;
	}

	@Column(name = "resultat")
	public Boolean getResultat() {
		return this.resultat;
	}

	public void setResultat(Boolean resultat) {
		this.resultat = resultat;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_resultat")
	public Date getDateResultat() {
		return this.dateResultat;
	}

	public void setDateResultat(Date dateResultat) {
		this.dateResultat = dateResultat;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_autorisation")
	public Date getDateAutorisation() {
		return this.dateAutorisation;
	}

	public void setDateAutorisation(Date dateAutorisation) {
		this.dateAutorisation = dateAutorisation;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_reintegration")
	public Date getDateReintegration() {
		return this.dateReintegration;
	}

	public void setDateReintegration(Date dateReintegration) {
		this.dateReintegration = dateReintegration;
	}

	@Column(name = "reintegration_validee")
	public Boolean getReintegrationValidee() {
		return reintegrationValidee;
	}

	public void setReintegrationValidee(Boolean reintegrationValidee) {
		this.reintegrationValidee = reintegrationValidee;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_validation_reintegration")
	public Date getDateValidation() {
		return dateValidation;
	}

	public void setDateValidation(Date dateValidation) {
		this.dateValidation = dateValidation;
	}

}
