package dz.gov.mesrs.sii.commons.data.model.fve.cursus;

// Generated 20 mai 2014 17:49:05 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * ReleveDeNotes generated by hbm2java
 */
@Entity
@Table(name = "releve_de_notes", schema = "cursus")
public class ReleveDeNotes implements java.io.Serializable {

	/**
	 * serialVersionUID
	 * 
	 * @author BELDI Jamel on : 21 mai 2014 09:05:24
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private Set<Formation> formations = new HashSet<Formation>(0);
	private Set<Diplome> diplomes = new HashSet<Diplome>(0);
	private Set<TitreAcces> titreAcceses = new HashSet<TitreAcces>(0);
	private Set<LigneReleveDeNotes> ligneReleveDeNoteses = new HashSet<LigneReleveDeNotes>(
			0);

	public ReleveDeNotes() {
	}

	public ReleveDeNotes(int id) {
		this.id = id;
	}

	public ReleveDeNotes(int id, Set<Formation> formations,
			Set<Diplome> diplomes, Set<TitreAcces> titreAcceses,
			Set<LigneReleveDeNotes> ligneReleveDeNoteses) {
		this.id = id;
		this.formations = formations;
		this.diplomes = diplomes;
		this.titreAcceses = titreAcceses;
		this.ligneReleveDeNoteses = ligneReleveDeNoteses;
	}

	@SequenceGenerator(name = "releveDeNotes_id_seq_gen", sequenceName = "cursus.releve_de_notes_id_seq")
	@Id
	@GeneratedValue(generator = "releveDeNotes_id_seq_gen")
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "releveDeNotes")
	public Set<Formation> getFormations() {
		return this.formations;
	}

	public void setFormations(Set<Formation> formations) {
		this.formations = formations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "releveDeNotes")
	public Set<Diplome> getDiplomes() {
		return this.diplomes;
	}

	public void setDiplomes(Set<Diplome> diplomes) {
		this.diplomes = diplomes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "releveDeNotes")
	public Set<TitreAcces> getTitreAcceses() {
		return this.titreAcceses;
	}

	public void setTitreAcceses(Set<TitreAcces> titreAcceses) {
		this.titreAcceses = titreAcceses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "releveDeNotes")
	public Set<LigneReleveDeNotes> getLigneReleveDeNoteses() {
		return this.ligneReleveDeNoteses;
	}

	public void setLigneReleveDeNoteses(
			Set<LigneReleveDeNotes> ligneReleveDeNoteses) {
		this.ligneReleveDeNoteses = ligneReleveDeNoteses;
	}

}
